### ISSUE TITLE
Allow Registration calls to be extended with fluent API

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#1]
All RegisterXXX methods return void. If those methods instead would return some object that would describe the made registration(s), it would allow the library or its users to extend these objects with extension methods. This would result in more fluent APIs.

Note that changing the return type is a breaking change and this means that this can't be implemented in the v2.x branch.

Examples:

``` c#
container.Register<ISomeService, MyService>()
    .OnActivation(service => service.TempDirectory = "c:\\temp")
    .DisposeOnEndOf(scopedLifestyle);

container.Register(typeof(ICommandHandler<>), applicationAssemblies)
    .WithPropertiesInjectedImplicitly()
    .WithConstructorOverloadResolution(new MostParametersConstructorResolutionBehavior());

container.Register(typeof(IRepository<>), typeof(Repository<>))
    .WithConstructorArgument("connectionString",  AppSettings["AppConString"]);
```

**Comment by qujck** [comment]
I spent some time looking at this a few months ago. I found that returning `Tuple<IService, IEnumerable<IImplementation>>` was usually more than adequate.

**Comment by dotnetjunkie** [comment]
Yes, returning an object that contains a ServiceType property and an ImplementationTypes property seems a good starting point.

**Comment by qujck** [comment]
One suggestion is `WithDelegate()`.

Something that may prove problematic is `DecoratedBy`: it's fine with normal registrations but adding a decorator with a `predicate` makes it unclear whether the returned list of types is filtered by the predicate or not.

**Comment by dotnetjunkie** [comment]
What we'll need to do is define a bunch of use cases (and implement them in the CodeSamples project) to prove that this fluent API is usable. I think what it comes down to is returning some type hierarchy, for instance:

``` c#
public class FluentResult {
    public Type ServiceType { get; }
    public Container Container { get; }
}
public class FluentImplementationResult : FluentResult {
    public Type ImplementationType { get; }
}
public class FluentResult<TService> : FluentResult {
    public override Type ServiceType { get { return typeof(TService); } }
}

public class FluentImplementationResult<TService, TImplementation> : FluentImplementationResult {
    public override Type ServiceType { get { return typeof(TService); } }
    public override Type ImplementationType { get { return typeof(TImplementation); } }  
}

public class FluentCollectionResult : FluentResult {
    public ReadOnlyCollection<Type> CollectionTypes { get; }
}

public class FluentCollectionResult<TService> : FluentResult<TService> {
    public ReadOnlyCollection<Type> CollectionTypes { get; }
}
```
Such hierarchy would anyone to create extension methods for one or multiple of those FluentResult types. For instance:

``` c#
public static void WithDelegate<TService>(this FluentResult<TService> result, Action<TService> a) {
    result.Container.RegisterInitializer(a);
}
```

The trick of course would be to come up with a class hierarchy or set of interfaces that would make it easy to allow extension using extension methods.

**Comment by dotnetjunkie** [comment]
I'm starting to doubt whether this change is worth it. I've been looking at this today, but it it's actually quite difficult to return enough information from all the existing RegisterXXX overloads so extension methods can be added in a way that they can safely target that particular registration. Take this example for instance:

``` c#
container.Register(typeof(IRepository<>), typeof(Repository<>), 
    c => c.Consumer.ImplementationType.Namespace.Contains("Admin"))
    .WithConstructorArgument("connectionString",  AppSettings["AdminConString"]);
container.Register(typeof(IRepository<>), typeof(Repository<>), c => !c.Handled)
    .WithConstructorArgument("connectionString",  AppSettings["DefaultConString"]);
```

Here we register two conditional registrations for IRepository<T> where both get their own connection string. But for a `WithConstructorArgument` extension method (written by a third party; we will don't include such thing OOTB) to be able to determine which registration is actually targeted, it should have some piece of information that uniquely identifies it and the extension method implementation must be able to use this piece of information to match the registration later on in the process. This typically means that when on of the behavior classes are overridden, this information must be passed along to this behavior classes. A `WithConstructorArgument` extension method would typically override `IDependencyInjectionBehavior` to intercept calls to `BuildExpression`. Normally, this uniquely identifiable information would mean something like a `Registration` object, but in the case of the open generic registration, there can be many `Registration` instances, and they are not created during the registration process. Another option would be to generate a unique id for a registration, but this would mean quite a big change in the code base and this information must be past on to all interception points to make sure an extender can make use of this information. Not only is this quite an undertaking to achieve internally, it is (again) a big breaking change.

So I'm in doubt whether this is worth it. Especially considering that this use case is something that doesn't come up often as a feature request.

**Comment by qujck** [comment]
I have tried to define a fluent API for SI myself and it is very easy to introduce ambiguity. Having worked with the new API and I think it may well be simple enough to not require any fluent extension methods. 

IMO the convention based approach that we currently use for application settings (`IConstructorInjectionBehavior` etc) is much neater than any extension method.

**Comment by dotnetjunkie** [comment]
I'll close this issue for now; we will not implement this feature in v3.
