### ISSUE TITLE
Error in v3 when registering a two parameters constructor class

### ISSUE THREAD

**Issue by tribet84** [simpleinjector/SimpleInjector#101]
Everything is detailed in this error

http://stackoverflow.com/questions/32155491/simpleinjector-cant-inject-string-after-update

Please let me know if you need more information to reproduce the issue.

**Comment by dotnetjunkie** [comment]
Pleass post a minimal reproducible example that shows this behavior difference between 2.8 and 3.0.

**Comment by dotnetjunkie** [comment]
I'll close this as 'not reproducible' for now. Without a reproducible example, we unfortunately can't help you.
