### ISSUE TITLE
.NET Native support not works

### ISSUE THREAD

**Issue by cprkv** [simpleinjector/SimpleInjector#1013]
## Describe the bug

I try to make very simple container:

```cs
container = new SimpleInjector.Container();
container.RegisterSingleton<Platform>();
container.Verify();
platform = container.GetInstance<Platform>();
```

But it doesn't work when I publish AOT with trimming. Reason is it doesn't understand that `Platform` constructor is being used. So I tried to make container like this:

```cs
container = new SimpleInjector.Container();
register_singleton<Platform>();
container.Verify();
platform = container.GetInstance<Platform>();

  private static void register_singleton<
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods |
                                DynamicallyAccessedMemberTypes.PublicConstructors)]
    T>() where T : class
  {
    container.RegisterSingleton<T>();
  }
```

This is dirty fix for that, but it doesn't work, because `container.Verify();` fails with message:

> System.NotSupportedException: 'SimpleInjector.VerificationOption[]' is missing native code or metadata. This can happen for code that is not compatible with trimming or AOT. Inspect and fix trimming and AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility

There is also dirty fix for that - `DynamicDependencyAttribute`, but even Microsoft does not recommend to use it. So I didn't.

I searched issues and found that .net native ticket in your repository already exists, so I make another one as feature still not available.

## Expected behavior

Everything works fine with AOT out of box.

## Actual behavior

Fails with exception.

## To Reproduce

Code:

```cs
container = new SimpleInjector.Container();
container.RegisterSingleton<Platform>();
container.Verify();
platform = container.GetInstance<Platform>();
```

csproj settings:

```xml
<PublishAot>true</PublishAot>
```

Publishing command used:

```
dotnet publish
```

Because it works with any type, it doesn't matter what implementation of `Platform` class is. It could be even empty I guess.

## Additional context

* Library version: 5.5.0
* .NET version: 8.0.400
* Used libraries or frameworks (with version) that are required: none

**Comment by dotnetjunkie** [comment]
As you noticed, Simple Injector does not support .NET Native. But it will not support .NET Native in the future as I stated [here](https://github.com/simpleinjector/SimpleInjector/issues/264) in 2019:

> .NET Native applications are better off using [Pure DI](https://blog.ploeh.dk/2014/06/10/pure-di/).
