### ISSUE TITLE
Add RegisterConditional(Type, Registration, Predicate<PredicateContext>) overload.

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#102]
See [this question](https://stackoverflow.com/questions/32186022/injecting-different-implementations-and-configurations-of-same-interface-into-di) for a valid use case.

**Comment by azzlack** [comment]
The RegisterWithContext extension does not work with v3 when using WebAPI and classes have `WebApiRequestLifestyle`, because the extensions uses the `Transient` lifestyle. 

```csharp
container.RegisterWithContext<ILog>(
    dependencyContext =>
    {
        if (dependencyContext.ImplementationType != null)
        {
            return LogManager.GetLogger(dependencyContext.ImplementationType);
        }

        return LogManager.GetCurrentClassLogger();
});
```

Is there any way to solve this?

I've tried to disable warnings by writing

```csharp
var registration = container.GetRegistration(typeof(ILog)).Registration;
registration.SuppressDiagnosticWarning(DiagnosticType.LifestyleMismatch, "The logger must be new every time");
```

but I still get the warnings/errors

**Comment by dotnetjunkie** [comment]
@azzlack I moved your question to #103.
