### ISSUE TITLE
Using SimpleInjector 3 with Nancy

### ISSUE THREAD

**Issue by jmojiwat** [simpleinjector/SimpleInjector#110]
Hi Steven,

I wanted to use SimpleInjector 3 as my container in Nancy. I've read the discussions over at Nancy and felt that although Nancy looks like a great framework (I'm just starting out to learn Nancy), their team perhaps could be a little bit more accommodating in making Nancy more DI friendlier as espoused by yourself and Mark Seemann.

I used the sample code you provided here: 

https://simpleinjector.codeplex.com/discussions/541398

but it doesn't complie under SimpleInjector 3. The 

```c#
private bool CanBuildParameterExpression(ParameterInfo parameter) 
```
function in the sample code broke, specifically the 

```c#
container.Options.ConstructorInjectionBehavior.BuildParameterExpression(parameter). 
```

Error returned was "In v3, the IConstructorVerificationBehavior and IConstructorInjectionBehavior interfaces have been replaced with the single IDependencyInjectionBehavior interface. Please use the DependencyInjectionBehavior property to override Simple Injector's constructor injection behavior." 

I tried: 

container.Options.DependencyInjectionBehavior.BuildExpression but not sure how to build InjectionConsumerInfo from ParameterInfo. 

Could you help point me in the right direction? 

Thanks! 

Jacob

**Comment by dotnetjunkie** [comment]
You  can replace the method with the following:

``` c#
private bool CanBuildParameterExpression(ParameterInfo parameter)
{
    return this.container.GetRegistration(parameter.ParameterType) != null;
}
```

**Comment by jmojiwat** [comment]
Ah, thank you very much! I was actually half expecting a more complicated solution of passing the serviceType and implementationType parameters from the GetConstructor method all the way down. :)

**Comment by dotnetjunkie** [comment]
I'm not sure why the old code actually calls back into the `Options.ConstructorInjectionBehavior` anyway. The use of `GetRegistration` is simpler and works in both v2.x and v3.x.

**Comment by AnderssonPeter** [comment]
It would be nice if there was a nuget package for this, currently we have some code in https://simpleinjector.codeplex.com/discussions/541398 and some code in https://github.com/NancyFx/Nancy/issues/1227. do i need to use both or just the code from CodePlex?

**Comment by dotnetjunkie** [comment]
The guidance in the codeplex discussion is outdated and the [integration page](https://simpleinjector.readthedocs.io/en/latest/integration.html) in the documentation points at [this thread](https://github.com/NancyFx/Nancy/issues/1227#issuecomment-163279040) on the Nancy forum for some time now. The given code sample on that thread is how we advice approaching integration with Nancy, since it's much simpler and much more stable.

**Comment by AnderssonPeter** [comment]
Thanks @dotnetjunkie i managed to get it up and running with that solution!
