### ISSUE TITLE
AllowOverridingRegistrations in v3 does not allow overriding with same implementation

### ISSUE THREAD

**Issue by MichaelLogutov** [simpleinjector/SimpleInjector#114]
This code:

    public class Program
    {
        public interface IMyService
        {
        }

    	private class MyService : IMyService
    	{
    	}

    	public static void Main ()
    	{
    		try
    		{
    			var container = new Container { Options = { AllowOverridingRegistrations = true } };
    			var lifestyle = new ExecutionContextScopeLifestyle ();

    			container.Register (typeof (IMyService), typeof (MyService), lifestyle);
                container.Register (typeof (IMyService), typeof (MyService), lifestyle);

    			container.Verify ();
    		}
    		catch (Exception ex)
    		{
    			Console.Write ("\n\n{0}\n\n", ex);
    		}
    	}
    }

Generates exception:

    System.InvalidOperationException: There is already a registration for Program.IMyService (with implementation Program.MyService) that overlaps with the registration for Program.MyService that you are trying to make. This new registration would cause ambiguity, because both registrations would be used for the same closed service types. Either remove one of the registrations or make them both conditional.
       at SimpleInjector.Internals.NonGenericRegistrationEntry.ThrowWhenProviderToRegisterOverlapsWithExistingProvider(InstanceProducer producerToRegister)
       at SimpleInjector.Internals.NonGenericRegistrationEntry.Add(InstanceProducer producer)
       at SimpleInjector.Container.AddInstanceProducer(InstanceProducer producer)
       at SimpleInjector.Container.AddRegistration(Type serviceType, Registration registration)
       at SimpleInjector.Container.Register(Type serviceType, Type implementationType, Lifestyle lifestyle, String serviceTypeParamName, String implementationTypeParamName)
       at SimpleInjector.Container.Register(Type serviceType, Type implementationType, Lifestyle lifestyle)
       at Bug.Program.Main() in c:\My\Bug\Bug\Program.cs:line 26

**Comment by dotnetjunkie** [comment]
Thanks for reporting this. This is a bug and should be fixed. v2.x didn't even allow this. In v2.x, open-generic registrations were done with the `RegisterOpenGeneric` extension method, and this used the `ResolveUnregisteredType` event in the background. This made it completely impossible to check for overriding registrations.

In the meantime the work around is to not make the duplicate registration (yes, I know, quite painful).

**Comment by MichaelLogutov** [comment]
Well, it was possible in v2 - our libraries registering their services in their own "Setup Library" static class and that "Setup" code could be called multiple times because some core libraries used in multiple other libraries - so you get multiple Register call for the same core interfaces (in which case they were replacing their own registration). It should be definately the case in v3 too because it's very needed functionality.

**Comment by dotnetjunkie** [comment]
I'm sorry. I misread the question. I thought you were registering open-generic types. I'm able to reproduce the issue. The problem only happens if you try to override a registration with the same implementation. The following will work correctly:

``` c#
container.Register (typeof(IMyService), typeof(MyService), lifestyle);
container.Register (typeof(IMyService), typeof(AnotherService), lifestyle);
```

**Comment by MichaelLogutov** [comment]
No, not open generic. The code works correctly on v2 and now it's broken. Like I've said - we have library (for example Core) that have static class CoreLibrary with the method CoreLibrary.Setup which is configure the passed container with it's services registrations. Because of this library called from other libraries and those libraries called from App the CoreLibrary.Setup could be called couple of times for the same container. Prior to v3 it was working perfectly - AllowOverridingRegistrations allowed to override the registration with the same implementation and it was as expected. Now suddenly all libraries not working because of that and I see no obvious way to fix this.

**Comment by dotnetjunkie** [comment]
We pushed patch release v3.0.4 to NuGet. That release fixes your issue.

**Comment by MichaelLogutov** [comment]
Awesome! Thanks

**Comment by theonlylawislove** [comment]
It seems that after this bug fix, I can't register an open-generic type at all with ```AllowOverridingRegistrations```. I created another issue #116.
