### ISSUE TITLE
Can Simple Injector detect which scoped lifestyle it should use?

### ISSUE THREAD

**Issue by AlthalusDGr8** [simpleinjector/SimpleInjector#123]
I have a stack of business logic which is currently accessed from different applications using different technologies (mainly WCF, Web API and MVC).  I have some elements which need to be scoped for example for the entire request.  From the documentation I saw that there are different life styles for different type of services.
Is simple injector knowledgeable enough to detect on its own the current application type and determine the type of life style to use automatically?

Thanks in advance

**Comment by dotnetjunkie** [comment]
Nope. You will have to tell Simple Injector explicitly which scoped lifestyle dhould be used. You can do this in the start up path of the application:

``` c#
var container = new Comtainer();
container.Options.DefaultScopedLifestyle =
    new WebRequestLifestyle();

// register a 'per request' type:
container.Register<MyContext>(Lifestyle.Scoped);
```

**Comment by amantur** [comment]
I have application mixing MVC and Web API (.Net 4.6.1) and I got an exception with calling a repository from MVC controller which was registered as `Scoped`. I have currently switched to `Transient` registration, but will come back later with more details.

**Comment by dotnetjunkie** [comment]
Hi @amantur, please open a new question/issue with the appropriate details. We'll take it from there.
