### ISSUE TITLE
Re-entrant calls and nested scopes

### ISSUE THREAD

**Issue by derhally** [simpleinjector/SimpleInjector#125]
We have some legacy code that uses ThreadStatic data and I'm looking at a way to change the code to use SimpleInjector scopes.   

The service can be hosted either in a WCF service or as part of a regular application.   In both runtime modes the service is re-entrant and I was wondering how to implement the resolution so that a nested scope returns the same instance of an object until the initial scope is disposed of.   I've looked at the documentation for LifetimeScoping, but each call of container.BeginLifetimeScope seems to return a new instance.

**Comment by dotnetjunkie** [comment]
What is the reason you are using nested scopes?

**Comment by derhally** [comment]
I'm not using them now, but I was trying to determine the best way to handle moving thread static data to using scopes with SimpleInjector.   Looks like the best thing to do is to spend more time refactoring the code to avoid the nested scopes instead of trying to use SimpleInjector with the code as is.   Pain of legacy code!  :)
