### ISSUE TITLE
RegisterCollection with abstract base class failing now?

### ISSUE THREAD

**Issue by bcraun** [simpleinjector/SimpleInjector#127]
Has the behavior of collection registration of an interface with multiple concrete implementations which inherit from an abstract base class changed from in 3.0.5 from 2.8.3? The code that's failing now simply registers the various concrete state machine states of the Solid State state machine. Here's the code that used to work and for some reason is failing now...
```
container.RegisterCollection(typeof(ISolidState), 
AppDomain.CurrentDomain.GetAssemblies()
.First(a => a.GetName().Name.Contains("MyAssemblyName"))
.GetExportedTypes()
.Where(x => typeof(ISolidState).IsAssignableFrom(x)));
```
Upon verifying the container, I receive the exception "The configuration is invalid. Creating the instance for type ```ISolidState``` failed. No registration for type ```ParserStateBase``` could be found."

All of the state classes inherit from the abstract ```ParserStateBase```, and ```ParserStateBase``` inherits from ```ISolidState```. Again, this worked before upgrading from v2.8.3 to v3.0.5 of SimpleInjector.

Any thoughts?

**Comment by dotnetjunkie** [comment]
Can you supply me with a complete reproducible example?

**Comment by bcraun** [comment]
Steven, I'm working on it now. To where should I send it?

**Comment by bcraun** [comment]
I have a reproducible sample. Where should I send it?

**Comment by qujck** [comment]
You should be able to drag and drop the files in the comments box ....

**Comment by dotnetjunkie** [comment]
But if it's not too much code, you can simply copy-paste the code here.

**Comment by bcraun** [comment]
Sure. Solid.State v1.2.0 and SimpleInjector v3.0.5

Project 1:

```
        static void Main()
        {
            // For this example, use an arbitrary type to ensure the
            // TelemetryParser assembly is not optimized away
            var state = new IdleState();

            var container = new Container();

            container.RegisterCollection(typeof(ISolidState),
                AppDomain
                .CurrentDomain
                .GetAssemblies()
                .First(a => a.GetName().Name.Contains("TelemetryParsers"))
                .GetExportedTypes()
                .Where(x => typeof(ISolidState).IsAssignableFrom(x)));

            container.Verify();
        }
```

Project 2:

```
    public class IdleState : ParserStateBase
    {
        protected override void DoEntering(SolidMachine<ParserTriggerTypes> machine)
        {
        }
    }

    public abstract class ParserStateBase : ISolidState
    {
        protected static object Context { get; private set; }

        protected virtual void DoEntering(SolidMachine<ParserTriggerTypes> machine)
        {
            // Unimplemented
        }

        protected virtual void DoExiting(SolidMachine<ParserTriggerTypes> machine)
        {
            // Unimplemented
        }

        // Methods

        public void Entering(object context)
        {
            Context = context;

            // Redirect to protected methods and cast context
            DoEntering(context as SolidMachine<ParserTriggerTypes>);
        }

        public void Exiting(object context)
        {
            // Redirect to protected methods and cast context
            DoExiting(context as SolidMachine<ParserTriggerTypes>);
        }
    }

    public enum ParserTriggerTypes
    {
        GatewaySymbolFound,
        NodeSymbolFound,
        PointSymbolFound,
        PointDataFound,
        InvalidSymbolFound,
        EofFound
    }
```

**Comment by dotnetjunkie** [comment]
Can you post the full exception + stack trace you get?

**Comment by bcraun** [comment]
```
Unhandled Exception: System.InvalidOperationException: The configuration is invalid. Creating the instance for type ISolidState failed. No registration for type ParserStateBase could be found. ---> SimpleInjector.ActivationException: No registration for type ParserStateBase could be found.
   at SimpleInjector.Container.ThrowMissingInstanceProducerException(Type serviceType)
   at SimpleInjector.Container.GetRegistration(Type serviceType, InjectionConsumerInfo consumer, Boolean throwOnFailure)
   at SimpleInjector.Internals.ContainerControlledCollection`1.CreateNewExternalProducer(Type implementationType)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SimpleInjector.Internals.ContainerControlledCollection`1.VerifyCreatingProducer(Lazy`1 lazy)
   --- End of inner exception stack trace ---
   at SimpleInjector.Internals.ContainerControlledCollection`1.VerifyCreatingProducer(Lazy`1 lazy)
   at SimpleInjector.Internals.ContainerControlledCollection`1.VerifyCreatingProducers()
   at SimpleInjector.Container.VerifyInstanceProducersOfContainerControlledCollection(Expression expression)
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt(InstanceProducer[] producersToVerify)
   at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt()
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify()
   at SimpleInjectorExample.Program.Main() in C:\projects\SimpleInjectorExample\SimpleInjectorExample\Program.cs:line 27
Press any key to continue . . .
```

**Comment by bcraun** [comment]
Explicitly registering the base type / concrete type prior to registering the collection appears to produce correct behavior, but defeats the purpose of the single-step collection registration. Does this sound right?

```
            // For this example, use an arbitrary type to ensure the
            // TelemetryParser assembly is not optimized away
            var state = new IdleState();

            var container = new Container();

            container.Register<ParserStateBase, IdleState>();

            container.RegisterCollection(typeof(ISolidState),
                AppDomain
                .CurrentDomain
                .GetAssemblies()
                .First(a => a.GetName().Name.Contains("TelemetryParsers"))
                .GetExportedTypes()
                .Where(x => typeof(ISolidState).IsAssignableFrom(x)));

            container.Verify();

            var instances = container.GetAllInstances(typeof (ISolidState));

            Debug.Assert(instances.Any());
```

**Comment by bcraun** [comment]
Disregard that last comment. In the actual app code, registering the state types explicitly before the collection causes this exception to be thrown so I'm reluctant to make any more changes until I understand if the original issue is a regression in 3.0.5:

```
Type ParserStateBase has already been registered. If your intention is to resolve a collection of ParserStateBase implementations, use the RegisterCollection overloads. More info: https://simpleinjector.org/coll1. If your intention is to replace the existing registration with this new registration, you can allow overriding the current registration by setting Container.Options.AllowOverridingRegistrations to true. More info: https://simpleinjector.org/ovrrd.
```

**Comment by bcraun** [comment]
For what it's worth, registering the collection this way does not cause an exception to be thrown when the container is verified.

```
container.RegisterCollection(typeof(ISolidState),
                AppDomain
                .CurrentDomain
                .GetAssemblies())
```

**Comment by dotnetjunkie** [comment]
Although lots has changed in v3, I'm not sure that what you're doing actually would have worked in v2.8, because as far as I can see, the problem is simply in the following code:

``` c#
container.RegisterCollection(typeof(ISolidState),
    AppDomain
        .CurrentDomain
        .GetAssemblies()
        .First(a => a.GetName().Name.Contains("TelemetryParsers"))
        .GetExportedTypes()
        .Where(x => typeof(ISolidState).IsAssignableFrom(x)));
```

What this code does is to load every type from the given assembly that either implements `ISolidState`, or IS `ISolidState` itself. What this means is that the list will include both the `ISolidState` interface and the abstract class `ParserStateBase`. This is obviously incorrect, because you just want to have a list of the contrete implementations of `ISolidState` and register them as a collection. This same code wouldn't have worked in v2.8 either.

So, the solution is to filter out the invalid types, for instance:

``` c#
container.RegisterCollection(typeof(ISolidState),
    AppDomain
        .CurrentDomain
        .GetAssemblies()
        .First(a => a.GetName().Name.Contains("TelemetryParsers"))
        .GetExportedTypes()
        .Where(x => !x.IsAbstract) -- added this line
        .Where(x => typeof(ISolidState).IsAssignableFrom(x)));
```

But it's much cleaner to call `Container.GetTypesToRegister` instead, because it takes care of this filtering for you:

``` c#
var assembly = AppDomain
    .CurrentDomain
    .GetAssemblies()
     .First(a => a.GetName().Name.Contains("TelemetryParsers"));

var types = container.GetTypesToRegister(typeof(ISolidState), new[] { assembly });

container.RegisterCollection(typeof(ISolidState), types);
```

But, as you already noticed, there is a convenient shortcut available for the previous code:

``` c#
container.RegisterCollection<ISolidState>(new[] { assembly });
```

This `RegisterCollection` overload calls `Container.GetTypesToRegister` for you in the background.

The reason you get the rather confusing "No registration for type ParserStateBase could be found" exception message is because types that are registered as part of a collection, are delegated. This means that Simple Injector will look for a one-to-one registration (as in `Register<ISolidState, Something>()`) for you. If such registration does not exist, Simple Injector will try to implicitly try to create a registration for you, but this only works when the type is actually constructable (but neither interfaces nor abstract types are constructable). And that's why Simple Injector tells you that "No registration for type ParserStateBase could be found". The message is technically correct, and by design, but confusing in your case.

**Comment by bcraun** [comment]
Okay thanks for the prompt and thorough explanation. I'll simply use the following version.

```container.RegisterCollection<ISolidState>(new[] { assembly });```
