### ISSUE TITLE
Register types in different layers

### ISSUE THREAD

**Issue by qreftan** [simpleinjector/SimpleInjector#130]
Hi!

I've been using Ninject for all my previous projects and I was thinking about using something faster, like simple injector. 

In my current project I have a three layer architecture, application => service => data, and what I like about Ninject is that I can override the load function and register my types wherever I want. For example I register service types in the application, and data types in my service project. That way, I dont have to reference data project in my application. Is this possible with Simple Injector? I could only see examples where you register types in the App_Start, (application layer).

You can see a more detailed explanation about this in my latest question on Stackoverflow. Thanks!:)
http://stackoverflow.com/questions/32932034/unity-di-n-tier-architecture-register-types-business-data

**Comment by dotnetjunkie** [comment]
Yacoub Massad's answer to your question is fine. Please also read [my answer](https://stackoverflow.com/a/9505530/264697) to a related question.

Good luck.
