### ISSUE TITLE
Strange Torn Lifestyle warning for singleton decorators

### ISSUE THREAD

**Issue by MichaelLogutov** [simpleinjector/SimpleInjector#131]
This started to come up with 3.0.6 (was fine on 3.0.5):

    public class Test
    {
        public interface IMyService
        {
        }

        private class MyService : IMyService
        {
        }

        public class MyDecorator : IMyService
        {
            public MyDecorator (Func<IMyService> decorated)
            {
            }
        }

        public class MyDecorator2 : IMyService
        {
            public MyDecorator2 (Func<IMyService> decorated)
            {
            }
        }

        [Fact]
        public void Main ()
        {
            // arrange
            var container = new Container { Options = { AllowOverridingRegistrations = true } };

            container.Register (typeof (IMyService), typeof (MyService), Lifestyle.Transient);
            container.RegisterDecorator (typeof (IMyService), typeof (MyDecorator), Lifestyle.Singleton);
            container.RegisterDecorator (typeof (IMyService), typeof (MyDecorator2), Lifestyle.Singleton);

            // act
            Action act = () => container.Verify ();

            // assert
            act.ShouldNotThrow ();
        }
    }

The error:

    The configuration is invalid. The following diagnostic warnings were reported:
    -[Torn Lifestyle] The registration for Func<Test.IMyService> maps to the same implementation and lifestyle as the registration for Func<Test.IMyService> does. They both map to Func<Test.IMyService> (Singleton). This will cause each registration to resolve to a different instance: each registration will have its own instance.
    See the Error property for detailed information about the warnings. Please see https://simpleinjector.org/diagnostics how to fix problems and how to suppress individual warnings.

**Comment by dotnetjunkie** [comment]
Ouch. Thanks for reporting this. That's an unfortunate bug that we introduced in v3.0.6. My advice is to revert to v3.0.5 for now. We will publish a patch release a.s.a.p. I'll keep you updated through this thread.

**Comment by MichaelLogutov** [comment]
Will do. Thanks.

**Comment by dotnetjunkie** [comment]
Fixed with change set 1ca439620bb85e8541daf0d721b35eb112fcfa33.

**Comment by dotnetjunkie** [comment]
We just released [patch release v3.0.7](https://github.com/simpleinjector/SimpleInjector/releases/tag/v3.0.7) to Github and NuGet. This patch release contains the fix for the bug you reported.

**Comment by MichaelLogutov** [comment]
Thanks!

2015-10-10 21:42 GMT+03:00 Steven <notifications@github.com>:
