### ISSUE TITLE
Make ActivationException and other exceptions serializable

### ISSUE THREAD

**Issue by tompazourek** [simpleinjector/SimpleInjector#132]
I'm using Simple Injector together with Entity Framework Code First Migrations.

When using the Code First Migrations command-line tools in the Package Manage Exporer (like `Add-Migration Foo`), I use a small Simple Injector config to setup the dependencies for my DbContext (initializers, seed data, entity mappings, that kind of stuff...).

If there is a problem with my Simple Injector dependency config for the migration tool, the migration tool fails with:

```
System.Runtime.Serialization.SerializationException: Type is not resolved for member 'SimpleInjector.ActivationException,SimpleInjector, Version=3.0.6.0, Culture=neutral, PublicKeyToken=984cb50dea722e99'.
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Scaffold(String migrationName, String language, String rootNamespace, Boolean ignoreChanges)
   at System.Data.Entity.Migrations.AddMigrationCommand.Execute(String name, Boolean force, Boolean ignoreChanges)
   at System.Data.Entity.Migrations.AddMigrationCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Type is not resolved for member 'SimpleInjector.ActivationException,SimpleInjector, Version=3.0.6.0, Culture=neutral, PublicKeyToken=984cb50dea722e99'.
```

This makes it really hard to debug the problem, since I will not get the exception that caused the failure.

I think this could all be solved if the ActivationException and other exceptions would be made `[Serializable]`.

See: http://stackoverflow.com/questions/1066701/why-should-i-always-make-my-exceptions-serializable-net

**Comment by dotnetjunkie** [comment]
The `ActivationException` is marked with the `[Serializable]` attribute, but only in the full (.NET 4.0 and .NET 4.5) version of Simple Injector. You are using the PCL version of Simple Injector where the `System.SerializableAttribute` does not exist.

If you switch to the full version the problem goes away.

**Comment by tompazourek** [comment]
Thanks you, you're right that the `ActivationException` is marked with the `[Serializable]` attribute. I missed that. I am actually using the right `net45` version.

However, the problem still occurs. I couldn't find out why the `SerializationException` keeps throwing. I tried to implement my own custom exception with all the serialization stuff correct and just throw it, but I get the same problem.

```csharp
    [Serializable]
    public class CustomException : DataException
    {
        public CustomException() { }
        public CustomException(string message) : base(message) { }
        public CustomException(string message, Exception innerException) : base(message, innerException) { }
        protected CustomException(SerializationInfo info, StreamingContext context) : base(info, context) { }
    }
```

Not sure what to do. I think that your code is correct, but I don't know what causes the serialization exceptions.

My current workaround to get the actual error message is:

```
catch (ActivationException ex)
{
    throw new Exception(ex.Message);
}
```

**Comment by dotnetjunkie** [comment]
Is it possible that the `ActivationException` wraps a different exception (from your code or some other framework) that isn't decorated with the `[Serializable]` attribute or the special protected ctor?

**Comment by tompazourek** [comment]
I thought about that, but I tried throwing plain `ActivationException` or even my `CustomException` (without any inner exception, etc.) and still the same problem.

Probably there's something wrong with the migrate tool.
