### ISSUE TITLE
Containers get rooted when decorators are applied

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#135]
For more information, see [this SO question](https://stackoverflow.com/questions/33156432/simple-injector-decorators-causing-container-to-not-be-garbage-collected).

Here's a test to prove this bug:

``` c#

[TestMethod]
public void GCCollect_OnUnreferencedVerifiedContainersWithDecorators_CollectsThoseContainers()
{
    // Arrange
    Func<Container> buildContainer = () =>
    {
        var container = new Container();
        container.Options.EnableDynamicAssemblyCompilation = false;
        container.Register<INonGenericService, RealNonGenericService>();

        container.RegisterDecorator<INonGenericService, NonGenericServiceDecorator>();

        container.GetInstance<INonGenericService>();

        return container;
    };

    var containers =
        Enumerable.Range(0, 10).Select(_ => new WeakReference(buildContainer())).ToArray();

    // Act
    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();

    // Assert
    Assert.AreEqual(0, containers.Count(c => c.IsAlive), "We've got a memory leak.");
}
```

**Comment by dotnetjunkie** [comment]
There seems to be a weird problem in combination with `ThreadLocal<T>` values that are stored in the container's internal `Dictionary<object, object> items` by the decorator sub system. The memory leak goes away in case:

 - The `items` dictionary is cleared when the container is disposed (even though the `items` dictionary is only referenced by the `Container` and not referenced by some static field), or
 - When instead of using the `ThreadLocal<T>` from the BCL, a custom `ThreadLocal<T>` implementation is used (as is already done by the PCL version of Simple Injector, because `ThreadLocal<T>` is not available in PCL).

It seems that for some weird reason, the GC gets confused by the cyclic dependency between the container, the items, and BCL's the `ThreadLocal<T>`.

Since users are only expected to call `Container.Dispose` in case they are interested in deterministic disposal of singletons (since v2 didn't have a `Dispose` method), the best solution would be to refrain from using the BCL's `ThreadLocal<T>` and solely use the -already existing- custom `ThreadLocal<T>` implementation.

This bug is ironic, because `ThreadLocal<T>` was used in Simple Injector v2 with the specific reason to prevent memory leaks (in Simple Injector v1.x, `[ThreadStatic]` was used, which causes the same memory leaks as we see in this issue).

**Comment by dotnetjunkie** [comment]
After some investigation, there seems to be [a bug](https://stackoverflow.com/questions/33172615/memory-leak-when-threadlocalt-is-used-in-cyclic-graph) in the .NET framework that causes this.

**Comment by Steve-O-Cassels** [comment]
@dotnetjunkie - we've really enjoyed your library.  We're also experiencing a memory leak with decorators, do you have an eta for releasing 3.1.1?  Thanks Stephen.

**Comment by dotnetjunkie** [comment]
Hi @Steve-O-Cassels, you can expect 3.1.1 to be released within a couple of weeks.

**Comment by bapti** [comment]
Hi @dotnetjunkie - Can you think of any workarounds for this as a temporary mitigation before 3.1.1 is released?  Thanks for any help!

**Comment by dotnetjunkie** [comment]
Ansolutely, but you will need some reflection to get that working. There is a private readonly field `items` in the `Container` of type `Dictionary<object, object>`. You should call `Clear()` on that instance after you're done using a container instance. After doing that, and the instance goes out of scope, it will be garbage collected.

**Comment by dotnetjunkie** [comment]
We just pushed patch release v3.1.1 to Github and Nuget. This patch release contains a fix for this issue. Calling `Dispose` on the container will prevent the memory leak.
