### ISSUE TITLE
Simple Injector and vNext

### ISSUE THREAD

**Issue by Gillardo** [simpleinjector/SimpleInjector#137]
This is a not a bug but a few questions with regard to vNext/.NET 5.

Following issue #41 I have implemented this in my vNext project, using an extension method.  Like this

```
public static void UseSimpleInjector(this IApplicationBuilder app, Container container)
{
    container.Options.DefaultScopedLifestyle = new ExecutionContextScopeLifestyle();

    RegisterServices(container);
    RegisterControllers(app, container);

    // Wrap requests in a execution context scope. This allows
    // scoped instances to be resolved from the container.
    app.Use(async (context, next) => {
        using (container.BeginExecutionContextScope())
        {
            await next();
        }
    });
}
```

This keeps my startup.cs file nice and clean, so i can use an extension method like this

```
app.UseSimpleInjector(container);
```

Now in my RegisterServices method, i need to register my entity framework DbContext, but my context requires a connection string as the parameter.  To get this connectionString, i need to be able to get an instance of my IConfiguration.  This is currently being injected via .NET.  Is there a way i can get hold of the .NET DI so i can get the IConfiguration dependency and construct my connection string.  

This is what my Register method currently looks like
```
// 1 context per web request
container.Register<IDataContext>(() =>
{
    return new DataContext("THIS IS WHERE I NEED MY CONNECTION STRING");
}, Lifestyle.Scoped);
```
Also, does the code in #41 cope with an instance per request, like you could configure using the WebApi extension in MVC5?  Or this is the same as the LifeStyle.Scoped option if you setup the DI like in #41 ???

Thanks in advance!

**Comment by dotnetjunkie** [comment]
Can you describe how this IConfiguration abstraction looks like and why you need it

**Comment by Gillardo** [comment]
In my startup.cs file, i create the configuration object like so.

```
public IConfiguration Configuration { get; set; }

        public Startup(IHostingEnvironment env)
        {
            // configuration is in the folder above the wwwroot
            var builder = new ConfigurationBuilder(env.MapPath("..\\"))
                .AddJsonFile("config.json")
                .AddEnvironmentVariables();

            Configuration = builder.Build();
        }
```

This then holds all my configuration settings from my config.json file.

In my startup.cs ConfigureServices(IServiceCollection services) method, i then have this, which can be added to the SimpleInjector container instead, but currently is using the native DI container.

```
// Add IConfiguration to DI
services.AddSingleton(e => Configuration);
```

Then my question is, whether this object is stored using the native DI framework or SimpleInjector, how can i get the object from this method

// 1 context per web request
container.Register<IDataContext>(() =>
{
    return new DataContext("THIS IS WHERE I NEED MY CONNECTION STRING");
}, Lifestyle.Scoped);
```

**Comment by dotnetjunkie** [comment]
Although you can register the `Configuration` class in Simple Injector as follows:

``` c#
container.RegisterSingleton(this.Configuration);
```

I would advice against this, because injecting a `Configuration` class into consumers, makes those consumers hard to test, and makes your application fail at runtime (instead during startup) when a configuration value is missing from the config file.

So instead, request the configuration value from the `Configuration` property just before you register your `IDataContext` in Simple Injector. For instance:

``` c#
string connectionString = this.Configuration.Get("connectionString");
container.Register<IDataContext>(() => new DataContext(connectionString), Lifestyle.Scoped);
```

Preferably even add an extra check to ensure that the value exists:

``` c#
string connectionString = ThrowWhenNullOrEmpty(this.Configuration.Get("connectionString"));
container.Register<IDataContext>(() => new DataContext(connectionString), Lifestyle.Scoped);
```

This ensures your application will break at startup, which is always better than very late at runtime. The sooner you find the problem, the better.

**Comment by Gillardo** [comment]
Looks like my extension method may have to take an extra parameter then lol
but this is fine. Thnaks for this. Good advice!

Do you have any advice on my instancePerRequest question?

**Comment by dotnetjunkie** [comment]
Ow, I'm sorry; I forgot about your lifestyle question.

> Also, does the code in #41 cope with an instance per request

Yes it does. All you need to do is configure a scoped lifestyle (which for ASP.NET 5 is the `ExecutionContextScopeLifestyle`) and use `Lifestyle.Scoped` for per-request registrations.

> like you could configure using the WebApi extension in MVC5?

The extension methods such as `RegisterPerWebRequest` and `RegisterWebApiRequest` have been abandoned in Simple Injector 3, and have been superseded by `Lifestyle.Scoped`. So for a future integration package for ASP.NET 5, we will not create extension methods for registration. You should simply use the `Container.Options.DefaultScopedLifestyle` in combination with `Lifestyle.Scoped`.

> Or this is the same as the LifeStyle.Scoped option if you setup the DI like in #41 ???

Exactly.

**Comment by Gillardo** [comment]
This all seems to work great, but I seem to have 1 last problem, which is kinda another question.  Since i have asked simple injector to now take care of creating controllers etc, but .NET DI resolves system dependencies, how can i inject a system dependency that the .NET is taking care of, into my controllers?

The example i have is that in order for my controllers to be unit testable, the POST method needs to use IHttpContextAccessor, which before was injected automatically by the .NET DI.

How can I now inject this interface into my controller?

**Comment by dotnetjunkie** [comment]
In general I would advice against letting your code directly depend on framework abstractions, as explained [here](https://stackoverflow.com/a/33118861/264697). ASP.NET controllers however, should typically contain very little code, and that code is  typically not much more than some wiring and a forward of the call to the business layer. In that case it can make sense to inject some framework abstractions in controllers. In such case, cross-wiring a specific framework dependency in Simple Injector is just a simple one-liner:

``` c#
container.Register(app.ApplicationServices.GetRequiredService<IHttpContextAccessor>);
```

**Comment by Gillardo** [comment]
Thank you, i found this about a minute after i posted.  But thanks again for all the help and advice!
