### ISSUE TITLE
Simple Injector + Fluent Nhibernate + UnitOfWork

### ISSUE THREAD

**Issue by monteiro2107** [simpleinjector/SimpleInjector#145]
I'm using the Simple Injector with Fluent Nhibernate. I recorded the "Session" in SimpleInjectorInitializer file with the following code:

var container = Bootstrapper.
// Registra sessão do NHibernate
 container.Register(() => Core.Core.Dados.NH.NhSessionFactory.Current.OpenSession(), new SimpleInjector.Integration.Web.WebRequestLifestyle());

However, the session is through the builder in my "UnitOfWork," that she was registered, there is always a single instance of "Session" active, caused some errors when handling objects, as "a different object with the same identifier value was already associated with the session ".
How can I work the "Session" with the Nhiberante UnitOfWork to avoid this problem?

**Comment by dotnetjunkie** [comment]
This is a duplicate: https://stackoverflow.com/questions/33692085/simple-injector-fluent-nhibernate-wiith-unitofwork
