### ISSUE TITLE
DBContext Not Being Disposed

### ISSUE THREAD

**Issue by ziongh** [simpleinjector/SimpleInjector#147]
I have the following Registration:

    container.RegisterForWeb<AppContext>(() => new EFAppContext(@"DefaultConnection", new PetaPocoDispatcher(@"DefaultConnection")));

Inside this RegisterForWeb method i have:

    var hybridLifestyle = Lifestyle.CreateHybrid(
						() => HttpContext.Current != null,
						new WebRequestLifestyle(),
						new LifetimeScopeLifestyle());

    container.Register<TService>(instance, hybridLifestyle);

My EFAppContext Class is an extensions of IdentityDbContext

    public class EFAppContext : IdentityDbContext<ApplicationUser, CustomRole,
	int, CustomUserLogin, CustomUserRole, CustomUserClaim>, AppContext;

And i Followed the tutorial to find Leaking Connections on EF6 [codeproject](http://www.codeproject.com/Tips/823951/Finding-Non-disposed-Contexts-in-Entity-Framework). And Extended this tutorial to be able to see which Query was being executed by this leaked connection. And I found that every time i made a request to the Server, a new connection was being open and never closed. And the only query it did was:

    IF db_id(N'DB_MySystem_TEST') IS NOT NULL SELECT 1 ELSE SELECT Count(*) FROM sys.databases WHERE [name]=N'DB_MySystem_TEST'

Is this a problem with my code, or with SimpleInjector? I had never had this problem with SimpleInjector 2.8.0.

**Comment by dotnetjunkie** [comment]
This is [a duplicate](https://stackoverflow.com/questions/33708992/dbcontext-not-being-disposed-on-simpleinjector). Let's continue the discussion on Stackoverflow.
