### ISSUE TITLE
Read the Docs window title says "Simple Injector 2"

### ISSUE THREAD

**Issue by janhartmann** [simpleinjector/SimpleInjector#149]
It's a very, very minor thing and just a heads up. :-)

On the Read the Docs page for Simple Injector the window title says its "Simple Injector 2 documentation".  When I end on the site from Google I sometimes get confused that the title says it's for Simple Injector 2. :-)

**Comment by dotnetjunkie** [comment]
@qujck, is this something we can configure in readthedocs? This information doesn't seem to be part of our RST files, but I can't findd a RTDS setting either.

**Comment by dotnetjunkie** [comment]
Thanks for reporting this @janhartmann. btw, next bug on the docs can be reported [here](https://github.com/simpleinjector/Documentation/issues) ;-).

**Comment by qujck** [comment]
Fixed this, the setting is in [conf.py](https://github.com/simpleinjector/Documentation/blob/master/source/conf.py) for the relevant branch.

**Comment by janhartmann** [comment]
Ah, sorry did not see that :-)
