### ISSUE TITLE
Injecting parameters does not re-read the values, making the feature invalid

### ISSUE THREAD

**Issue by godrose** [simpleinjector/SimpleInjector#171]
Hi guys.
I'm trying to add the "injection with parameters" functionality to the container. This is useful in the specific scenario so let's just assume that this is a valid request.
I implemented the **IDependencyInjectionBehavior**. 
This worked for single resolution but then I tried to resolve collection of dependencies and they all got the same value for the injected parameter. 
After some investigation I discovered that the **BuildExpression** method of the aforementioned interface was called only **once** and not for each resolution as I had hoped.
The dependency itself is registered in the transient lifetime style.
Is this behavior by design? Can it be altered somehow? Thanks in advance.

**Comment by qujck** [comment]
The current behaviour is by design. Can you provide specific examples of the values you are trying to inject so we can understand how/why they change over time?

**Comment by godrose** [comment]
Thanks for the quick response.
Imagine a client app that displays items. These items both display data and allow user to perform simple operations like deleting an item from within the containing grid. The items are created dynamically and are merely object view models. Their type is registered transiently as a new instance needs to be created each time. Additonally these view models have dependencies. Some of the dependencies can be accessed via an Ambient Context while some can not. Hence to avoid cluttering the constructor with lots of parameters and delegate the lifetime management to the container, the view models are resolved dynamically. Moreover, their dependencies(models) are new at each resolution and they are never registered into the container(anti-pattern). I can switch to another IoC container but I would love to stay with the SimpleInjector.
Thanks in advance.

**Comment by qujck** [comment]
Simple Injector dropped support for Property Injection in [2.6](https://simpleinjector.readthedocs.org/en/2.6/injectproperties-is-deprecated.html) because it makes it difficult to verify the configuration. 

I think by hiding the fact you have a lot of (optional?) dependencies by keeping the constructor small is going to lead to trouble down the road. 

Your description does make sense but it does not give me a feel for what the code actually looks like, without which it's very difficult to give any useful feedback or advice.

**Comment by godrose** [comment]
I'm not talking about the PropertyInjection. By the way, sometimes the Property Injection is the only possible way without resorting to the Service Location but that is out of scope of this discussion.
The dependencies are not optional. I add the code below so that you can get a better understanding of the scenario (sorry for lack of formatting):

[UsedImplicitly]
    public class WarehouseItemsViewModel : PropertyChangedBase
    {
        private readonly IDataService _dataService;
        private readonly IViewModelCreatorService _viewModelCreatorService;

        public WarehouseItemsViewModel(
            IDataService dataService,
            IViewModelCreatorService viewModelCreatorService)
        {
            _dataService = dataService;
            _viewModelCreatorService = viewModelCreatorService;
        }

        private WrappingCollection _warehouseItems;
        public IEnumerable WarehouseItems
        {
            get { return _warehouseItems ?? (_warehouseItems = CreateWarehouseItems()); }
        }

        private WrappingCollection CreateWarehouseItems()
        {
            var wc = new WrappingCollection
            {
                FactoryMethod =
                    o =>
                        _viewModelCreatorService.CreateViewModel<IWarehouseItem, WarehouseItemViewModel>(
                            (IWarehouseItem) o)
            }.WithSource(_dataService.WarehouseItems);

            return wc;
        }
    }

The **WarehouseItems** property of the **IDataService** is a **ObservableCollection** and therefore the changes in the collection of the models are reflected in the collection of view models.

You may find the whole sample at the following location:
https://github.com/LogoFX/Samples.Specifications

**Comment by godrose** [comment]
Any reply to this? qujck? Maybe, others?

**Comment by TheBigRic** [comment]
If I can make time tonight, I will reply

**Comment by qujck** [comment]
@godrose once I'd realised it was WPF I asked @TheBigRic to take a look. You can fit what I know about WPF on the back of a postage stamp.

**Comment by godrose** [comment]
@qujck @TheBigRic  Thanks a lot. 
In my humble opinion it has very little to do with the WPF itself as this scenario of dynamic feeding can pop up in every other client framework when one uses the MVVM approach; maybe even in the server scenarios of which I know less.

**Comment by TheBigRic** [comment]
I'm having trouble to understand your setup. I looked at your sample. As far as I understand:
`WarehouseItemsViewModel` is a viewmodel from the mvVM pattern and thus acts as `DataContext` for the `WarehouseItemsView`

In this viewmodel you have a `WrappingCollection` which basically is an extended ObservableCollection<WarehousItemViewModel>. These viewmodels could have, as you say, have dependencies of their own. I think this the point where I must say, I don't understand.I would normally say this `List<>` or `ObservableCollection<>` would contain poco objects at most. Because this is runtime data and [injecting runtime data is an anti-pattern](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99).

Does this second layer of wrapped `ViewModels` have views of their own? I think not and if yes, they could still be POCO and use a `ItemControl` or something to create a complex view per item.

So could please explain why you have a God viewmodel which wraps a list of viewmodels, which at their turn just wrap a poco object (`IWarehouseItem`).

**Comment by godrose** [comment]
@TheBigRic  Thanks a lot for the response. Below is my reply.
The real-world models are never POCOs, they have another responsibilities such as error information and validation, managing editable object lifecycle. They almost never are POCOs, otherwise I'd use DTO without introducing another layer.
The ViewModel has another concerns to address. In this case they are no POCOs either , they are merely object view models which wrap their models. They can never be POCOs because they implement **INotifyPropertyChanged** .
The data source update could occur on any thread and yet the collection of the view models must be updated on the UI thread (at least this was the initial constraint when the WPF came out) hence the **WrappingCollection**.
I didn't wan't to overwhelm the readers with details and this is why I decided to omit complex logic from the view models. In the other sample I demonstrate how to use view models which have commands of their own. These commands may have dependencies that will be injected (different services such as **IDataService** etc.)
The link you provided also has commentaries below. Have a look at the last one.

**Comment by TheBigRic** [comment]
> The real-world models are never POCOs, they have another responsibilities such as error information and validation, managing editable object lifecycle.

I guess I disagree with this statement. I build several real-world and quite big wpf applications and I never moved from the MVVM patter to the as I would call your design VMVVM pattern. Injecting dependencies into models is a big no-no for me. So IMHO this boils down to a design problem in your setup, which is probably why you can't this to work with Simple Injector as [Simple Injector pushes developers into best practices](http://simpleinjector.readthedocs.org/en/latest/principles.html#push-developers-into-best-practices).

I guess you should read [this](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91) and [this](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=92). The architecture described in these two blogposts are using as I normally like to call it a message based design. All data in the application flows through the system as a message.

Consumers of these messages can do all the stuff you need like validation, error handling etc. And these messages could still implement `INotifyPropertyChanged`. And you're correct on this point, from that angle they are no real POCO's, but they still don't need dependencies!

So I suggest to really thing about this design, a piece of data is just a piece of data and it shouldn't be able to determine itself if it is valid, has errors or whatever. It is the responsibility of the business logic which determines these states.

As a last resort I think you still could use the setup as you have now. The `VewModelCreatorService` could still ask the container for a new transient wrapperviewmodel with all dependencies needed. But don't see the model, the data, the POCO, the DTO or whatever you would like to call it as a dependency! Just set the property of the `IModelWrapper` interface by hand.

Based on your code, I would imagine some smal changes:
``` c#
public interface IModelWrapper<T> : IModelWrapper 
{ 
       new T Model { get; set; } 
} 

// in LogoFX.Client.Mvvm.ViewModelFactory.SimpleInjector.ViewModelFactory
public TViewModel CreateModelWrapper<TModel, TViewModel>(TModel model) where TViewModel : IModelWrapper<TModel> 
{ 
    using (new ObjectResolver(model)) 
    { 
        lock (_syncObject) 
        { 
            var viewModel = _container.GetInstance<TViewModel>();
            viewModel.Model = model;
            return viewModel;
        } 
    } 
} 
```

**Comment by godrose** [comment]
@TheBigRic  Thanks a lot for the response.
Basically you're suggesting to use Property Setter over Constructor Injection for the View Model Wrappers. This will work but I don't think it's the best solution.
Please pay attention that I never mentioned injecting dependencies into models.
I think that we might have different understanding as to the role of the Model and View Model in the MVVM. 
I believe that Model has certain scope and responsibilities, among them validation and editing state. These responsibilities have nothing to do with the Presentation (View) of this Model. After all it doesn't matter how I present the data. If my model is a battleship , would it matter if I present it as a rich shape or a block of text? Would it influence the operations that are defined over it? Not at all. 
So in my design the Model is the central layer of the Client App. Still I'm not talking about injecting dependencies into the models. 
As to validation there are two kinds of error sources: client-side validation and server-side validation.
The latter would be yielded, if any, by server responses, but the former are pure client responsibilities and do not require any server response.
The View Models are merely abstractions of Views. Nothing more nothing less. This means that they expose Properties and Commands. Nothing more nothing less.
This approach has proven to work for me in several large real-world apps , with great results as well.
I would love to see piece of code with different approach and how it addresses all the aforementioned issues. 

Anyway, any such abstract factory would still be some sort of Service Locator, with or without parameters.
So it's either creating the View Models explicitly (just assume there is a need in the View Model) or resolving them in the run-time, with or without parameters.

**Comment by TheBigRic** [comment]
I'm still confused about your terminology. You talk about the Model, but inject this in a View Model which is his turn wrapped. This View Model is a different View Model as you mean here:
> The View Models are merely abstractions of Views

Referring to our first sample code, the `WarehouseItemsViewModel` is the datacontext for the view, or 'merely abstraction of Views' as you described, where as `WarehouseItemViewModel` is not a ViewModel as meant in the MVVM pattern. It is more or less the Model from this pattern, but as you use the name ViewModel I'm confused.

Could you elaborate and explain why you use the name ViewModel in different layers of your application?

**Comment by godrose** [comment]
Of course.
**WarehouseItemViewModel** is a Model Wrapper or an Object View Model. 
I could use another ItemsControl with some rich view for each item, including commands, etc. In this case I would create a WarehouseItemView and use it as the ItemTemplate for each item. In the simpler case which is illustrated in the sample I could omit the **WarehouseItemViewModel** and use the Model directly. 
Both approaches are equal to me and I prefer using ViewModel because there's almost always a need in one.
So there is no  usage of View Model in different layers. 
Model uses Models , View Model uses View Models.
For instance if I would put the TotalCost property into the View Model and calculate it there (which might be more suitable here as no one but the Presentation requires this value) it would make more sense to you?

I understand that we have somewhat different approaches. I would like to see the sample code of another approach to see what are the pros and the cons.

**Comment by TheBigRic** [comment]
I use the referenced blogposts about CommandHandlers and QueryHandlers in pretty much all of my applications. I would still advice you to read those as they describe as no other what the benefis of a message based architecture are. I can promise you, once you get the hang of it, you never want anything else.

I have used these patterns to come up with a design for my MVVM applications. And even than the message based architecture just rocks. 

I wrote several answers on stackoverfow and here on GitHub which describes this setup. Your can read them:
[here](http://stackoverflow.com/a/32339958/3294832) and
[here](http://stackoverflow.com/a/28310234/3294832) and
[here](http://stackoverflow.com/a/34385305/3294832) and
[here](http://stackoverflow.com/a/27159863/3294832) and

on GitHub [here](https://github.com/simpleinjector/SimpleInjector/issues/151)
