### ISSUE TITLE
Publish debug symbols to MyGet

### ISSUE THREAD

**Issue by abatishchev** [simpleinjector/SimpleInjector#175]
Hi,
I talk to @dotnetjunkie from time to time regarding publishing the debug symbols to a symbol server such as SymbolSource, MyGet, or something else.
All my attempts to learn how to integrate with SymbolSource failed, since it doesn't perform well. Maybe just a coincidence or they're hosted somewhere on the opposite from Redmond side of Earth :)

So instead I would propose to use MyGet. See [the docs](http://docs.myget.org/docs/reference/symbols), should be quite simple: upload a package, include the pdbs, they'll scan and publish.
Also it will be co-published to SymbolSource, at least [the docs](http://docs.myget.org/docs/reference/symbolsource) says so.

From the implementation standpoint, I think we could just adjust [publish2nuget.bat](https://github.com/simpleinjector/SimpleInjector/blob/2be5be6bad412ddd526f0a9f8a547d99361c8dc5/src/publish2nuget.bat#L31).

**Comment by abatishchev** [comment]
Folks, any thoughts on this, please?

**Comment by dotnetjunkie** [comment]
Does this require any changes to the NuGet packages? How do developers know where to get the sources from? How does this integrate with Visual Studio?

**Comment by abatishchev** [comment]
No, you just push packages to the 2nd source. Which scans and publishes symbols as a separate feature.
Developer just configures VS which now days is smart enough to try to match dll<>pdb on each of given servers.
Perfect instruction is here: https://www.symbolsource.org/Public/Wiki/Using
Also here: http://docs.myget.org/docs/reference/symbols
We just provide the exact url to add in the documentation

**Comment by dotnetjunkie** [comment]
Okay. Sounds good. Can you send a PR? But be careful not to send any secrets (API keys and such) with the PR.

**Comment by abatishchev** [comment]
Sure, will do.
But first I think we need to register on MyGet, an org if possible. I'll look into this.
