### ISSUE TITLE
Injecting dependencies into custom OwinMiddleware

### ISSUE THREAD

**Issue by tynor88** [simpleinjector/SimpleInjector#176]
I'm aware of the [SimpleInjector Owin integration documentation](http://simpleinjector.readthedocs.org/en/latest/owinintegration.html)

I would like a feature to make it possible to let SimpleInjector inject dependencies into my custom Middleware classes eg: 

```C#
public class FirstMiddleware : OwinMiddleware
    {
        private readonly ILogger _logger;

        public FirstMiddleware(OwinMiddleware next, ILogger logger) : base(next)
        {
            _logger = logger;
        }

        public override async Task Invoke(IOwinContext context)
        {
            _logger.Write("Inside the 'Invoke' method of the '{0}' middleware.", GetType().Name);

            await Next.Invoke(context);
        }
    }
```

It's possible in Autofac by registering the Middleware in your container as [shown here](http://docs.autofac.org/en/latest/integration/owin.html#dependency-injection-in-middleware). Is it possible to do with SimpleInjector?

**Comment by dotnetjunkie** [comment]
Yes, this is possible. Just remove the `next` delegate from the ctor, to keep the ctor clean with purely dependencies, and pass `next` in with the rest of the funtime data into the `Invoke` method. This way SI can resolve your middleware class without any problems.

**Comment by dotnetjunkie** [comment]
For more information and a code example, please see here: https://stackoverflow.com/questions/33002340/replace-activator-for-middleware-in-asp-net-5
