### ISSUE TITLE
Resolving Array not stream of types

### ISSUE THREAD

**Issue by guy-lud** [simpleinjector/SimpleInjector#179]
Hello all,

I am working on a legacy code (very large solution) and i've been wanting to replace our IoC,
a lot of our code uses ```IFoo[]``` c'tor parameters.

using the code below i was able to support array as parameters on a new project.

``` c#
public static void AllowToResolveArraysAndLists(this Container container)
{
	container.ResolveUnregisteredType += (sender, e) =>
	{
		var serviceType = e.UnregisteredServiceType;

		if (serviceType.IsArray)
		{
			RegisterArrayResolver(e, container,
				serviceType.GetElementType());
		}
		else if (serviceType.IsGenericType &&
			serviceType.GetGenericTypeDefinition() == typeof(IList<>))
		{
			RegisterArrayResolver(e, container,
				serviceType.GetGenericArguments()[0]);
		}
	};
}

private static void RegisterArrayResolver(UnregisteredTypeEventArgs e,
	Container container, Type elementType)
{
	var producer = container.GetRegistration(typeof(IEnumerable<>)
		.MakeGenericType(elementType));
	var enumerableExpression = producer.BuildExpression();
	var arrayMethod = typeof(Enumerable).GetMethod("ToArray")
		.MakeGenericMethod(elementType);
	var arrayExpression = Expression.Call(arrayMethod, enumerableExpression);

	e.Register(arrayExpression);
}
```

Yet on my main solution i get a diagnostic warning as written below

> The configuration is invalid. The following diagnostic warnings were reported: -[Lifestyle Mismatch] Test (Singleton) depends on IFoo[] (Unknown). See the Error property for detailed information about the warnings. Please see https://simpleinjector.org/diagnostics how to fix problems and how to suppress individual warnings.

any ideas why ?

Thanks

**Comment by dotnetjunkie** [comment]
Simple Injector has out of the box support for arrays since I believe  v2.7 or v2.8. This means that your custom ResolveUnregisteredType delegate is not required anymore: Remove it.

But removing the custom extension will not solve your problem; it will only change the exception. The RegisterInreigsteredType tries to detect the lifestyle of your made array registration, but because it can't determine it, it flags it as 'unknown', which is practically the same as having the transient lifestyle in the diagnostic subsystem. When you remove the custom code, Simple Injector will register the array as transient, which has the same effect; the diagnostics will warn about this. Simple Injector v3 warns you that this configuration is incorrect when you call `Verify()`.

It is incorrect because array is a mutable type that can be changed and the elements in that array can have all sorts of lifestyles, such as transient. That's why Simple Injector always registers arrays as transient. This means that injecting an array into any other component with another lifestyle than transient (such as your singleton `Test`) can cause problems, as the [documentation about lifestylr mismatches](https://simpleinjector.org/dialm) describes.

The solution is to either make `Test` transient, or change the dependency in the `Test` ctor from an array to an `IList<T>`, or `IEnumerable<T>`. The error will disappear because enumerable and ILists are streams in Simple Injector, which means that 1. the are immutable and 2. Simple Injector will request a proper instance according to its lifestyle each time you iterate the collection. So if the elements in the collection are transients foreaching over them will get you a fresh set of instances. This means that enumerables can safely be injected into singletons and the error will go away.

**Comment by guy-lud** [comment]
Thank you for that quick response,
While I agree with simple injector singleton grasp on the matter, we chose to use singleton lifestyle to force our services to stateless and changing all array to immutable collection is Hugh  amount of work, is there a away to suppress the warning?

Another question if you may regarding using the IOC in integration tests, while other frameworks allow cloning the IOC I could not find this feature on simple.  Creating and registering in each fixture can be quite expensive, any suggestions?


Thanks

**Comment by qujck** [comment]
You can supress the warning but can you register the `IFoo`'s as singletons?

**Comment by qujck** [comment]
Regarding integration tests, the container is thread safe so you could configure the container once and reuse the same instance across all tests in parallel

**Comment by dotnetjunkie** [comment]
And if you want to clone the container, just call a method that creates a new container; there's nothing special needed in Simple Injector to get this working in an integration test.

What I don't understand though is, it seems like you have a legacy project and migrate from a different container to Simple Injector, is that right? This might not be the best thing to do, if making other changes to your design are hard.

**Comment by guy-lud** [comment]
Again thanks for the quick response,

All our services are singleton except for the controllers which never get dependencies on arrays.

Regarding integration tests if we run them in parallel and need to override some services for example is this thread safe also? Meaning two tests need to use IFoo and one of the tests override the service, does simple knows to override only in the scope ( my guess is no. When you wrote call a method to create new container did you mean new Container(); or some api from existing one, because creating a new container is cheap register all types is expensive. Today using Windsor it takes 17 seconds to do that after much optimizations.

**Comment by dotnetjunkie** [comment]
You can't change anything in the container after use. For safety and thread-safety. This means you are required to create a new Container instance for each test. 

Registering types in the container isn't that expensive, just prevent to call Verify() for each integration test; that would kill performance. Have you measured the time it takes to make all registrations a second time (don't measure the first time; that will always be much slower).

**Comment by guy-lud** [comment]
Thank you, i'll give it a try

**Comment by guy-lud** [comment]
@dotnetjunkie, 
can you pleas prvoide an example how to supress the warning with arrays?

i've tried 
````
_container.RegisterCollection(col.Key, col);
					var reg = Lifestyle.Singleton.CreateRegistration(col.Key.MakeArrayType(), _container);
					reg.SuppressDiagnosticWarning(DiagnosticType.LifestyleMismatch, "arrays");
					_container.AddRegistration(col.Key.MakeArrayType(), reg);
```` 

and get The given type IArray[] is not a concrete type. Please use one of the other overloads to register this type.

**Comment by dotnetjunkie** [comment]
I think there are multiple options here. You can do this just before calling Verify:

``` C#
var p = container.GetRegistration(col.Key.MakeArrayType());
p.Registration.SuppressDiagnosticWarning(
    DiagnosticType.LifestyleMismatch, "arrays");
```

or you register the array explicitly as singleton:

``` c#
container.RegisterSingleton<MyType[]>(() => container.GetAllInstances<MyType>().ToArray());
```

**Comment by guy-lud** [comment]
@dotnetjunkie Sorry to bother you about this but now it's personal between my and simple..

regarding your first suggestion it does not work.. still getting mismatch warnings.

the second suggestion only work when i use generics as written above yet i use types to register

````
c.RegisterCollection<IFoo>(new Foo1(), new Foo2());

c.RegisterSingleton(typeof(IFoo).MakeArrayType(),() => c.GetAllInstances(typeof(IFoo)).ToArray());
````
````
The configuration is invalid. Creating the instance for type IT failed. The registered delegate for type IFoo[] threw an exception. Unable to cast object of type 'System.Object[]' to type 'SimpleinjectorSandBox.IFoo[]'.
````

Any suggestion please?

(already tried to use Convert class does not work)

**Comment by dotnetjunkie** [comment]
Try this:

``` C#
c.RegisterSingleton<IFoo[]>(new IFoo[] { new Foo1(), new Foo2() });
```

**Comment by guy-lud** [comment]
I can't i don't use generics only Type (batch registration from  assemblies)

**Comment by dotnetjunkie** [comment]
In that case you can use the non-generic overload of `RegisterSingleton`.

**Comment by guy-lud** [comment]
````
c.RegisterSingleton(typeof (IFoo[]), new[] {typeof (Foo1), typeof (Foo2)});
````
this won't work because the type is Type[] and not IFoo[] ..

i can't see a solution even with somekind of middleware like

````
var r = Lifestyle.Singleton.CreateRegistration(typeof(IFoo).MakeArrayType(), () =>
			{
				var array = c.GetAllInstances(typeof (IFoo)).Select(x => Convert.ChangeType(x, typeof (IFoo))).ToArray();

				var con = Array.CreateInstance(typeof (IFoo).MakeArrayType(), array.Length);

				for (int i = 0; i < array.Length; i++)
				{
					con.SetValue(array[i], i);
				}


				return con;
			}, c);
````

my guess that i was beaten

**Comment by guy-lud** [comment]
HI @dotnetjunkie ,

so i found a way to do it, get array and not IEnumerable while registering all services as Singlton

````C#
c.RegisterSingleton(typeof(IFoo).MakeArrayType(), () =>
   {
    var array = c.GetAllInstances(typeof (IFoo)).ToArray();

    var x = Array.CreateInstance(typeof (IFoo), array.Length);


    array.CopyTo(x,0);

    return x;

   });

````
 
do you have a better way?

**Comment by dotnetjunkie** [comment]
Why not just do:

``` C#
c.RegisterSingleton<IFoo[]>(() =>
    c.GetAllInstances<IFoo>().ToArray());
```

**Comment by guy-lud** [comment]
I can't use generics, it's full service registration thus i  have only `Type` after getting it from `Assembly.GetTypes();`
