### ISSUE TITLE
Q: What is the best practice to inject connection string

### ISSUE THREAD

**Issue by YehudahA** [simpleinjector/SimpleInjector#184]
Common use with data context [like EF] is with injection the connection string.
Or if I use WebApi/Wcf clients and I want inject the url string into it.

What is the best practice to do it using SimpleInjector?

A similar question is In EF Core which uses DbContextOptions injection.
Thanks.

**Comment by YehudahA** [comment]
The option that I know: Configuring the services manually or using delegate.
The disadvantage with this option is in large and modular application, when I want to use Batch / Automatic registration

**Comment by qujck** [comment]
A complete solution can be found [here](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=94)

**Comment by dotnetjunkie** [comment]
If you find yourself injecting the same configuration value into many components,  it is safe to assume you are missing an abstraction. So you will typically have one or a few components that depend upon a certain configuration value. Those components can typically be registered using a delegate.

**Comment by YehudahA** [comment]
@qujck Thanks a lot! your answer was a great help.

After some work I see some difficulties with conventions:
- Naming parameters with names like myServiceUrlAppSetting is not nice.
- If we put a coupling between our code and the configuration file, it's better to do it explicit and declare it with attribute.
So, I created an ```ImportFromConfiguration``` attribute, with ```ConfiurationKey``` property, and I put it on the primitive parameters.

Thanks again!

[My English is not well. Sorry ):]

**Comment by YehudahA** [comment]
@dotnetjunkie, What are you mean?

for example, I have 5 contexts depend on productionDb, and 4 context depend on AccountingDb.
I can do 2 base contexts, but still every context have to get the connection string in using his constructor.

**Comment by qujck** [comment]
> Naming parameters with names like myServiceUrlAppSetting is not nice.

You use

```xml
<configuration>
  <appSettings>   
    <add key="myServiceUrl" value="<whatever>"/>
```

and 

``csharp
pub
```

**Comment by YehudahA** [comment]
Because myServiceUrlAppSetting is not an appropriate name. The 'AppSetting' suffix doesn't describe the functionality of the parameter. 
Actually that suffix is a kind of attribute... So, if we have an attribute, why not declare it explicitly?

**Comment by TheBigRic** [comment]
> I have 5 contexts depend on productionDb, and 4 context depend on AccountingDb

In that case you're just missing an abstraction:

``` c#
public interface IConnectionstring<TContext>
{
    public string ConnectionString { get; }
}

public class ProductionDbContextConnectionString : IConnectionstring<ProductionDbContext>
{
    public ProductionDbContextConnectionString(string connectionString)
    {
        this.Connectionstring = connectionString;
    }
    public string Connectionstring { get; }
}

public class DbContextProductionDb1 : DbContext
{
    public DbContextProductionDb1(connectionString IConnectionstring<ProductionDbContext>)
        : base(connectionString.Connectionstring)
    {}
}
```

And register as:
``` c#
     var connectionString = ConfigurationManager.ConnectionStrings["productionDbString"];
    container.RegisterSingleton<IConnectionstring<ProductionDbContext>(
                new ProductionDbContextConnectionString(connectionString);

    /// batch register your DbContext's and other services here...
```

**Comment by YehudahA** [comment]
@TheBigRic, Very nice! Thanks!
