### ISSUE TITLE
Mix WebApi and WCF injection

### ISSUE THREAD

**Issue by cosmo0** [simpleinjector/SimpleInjector#185]
I have created a WebApi application, which uses SimpleInjector.  
Now a user of the API wants a WCF endpoint to consume it (for whatever reason).

To make things simple for me, I want to just call the WebApi controller from inside the WCF service:

````csharp
public class MyService : IMyService
{
	private MyApiController controller;

	public MyService(IMyInjection inject)
	{
		controller = new MyApiController(inject);
	}

	public int GetResult(string data)
	{
		return controller.GetResult(data);
	}
}
````

To make it work in WebApi, my controller currently uses an injection with a `WebApiRequestLifeStyle` lifestyle, and I have tried to "just add" SimpleInjector WCF Integration:

````csharp
public static void LoadDependencyInjection()
{
	var container = new Container();
	container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
	container.RegisterWebApiControllers(GlobalConfiguration.Configuration);

	// some more registration

	// configure WCF to use SimpleInjector
	container.RegisterWcfServices(Assembly.GetExecutingAssembly());

	// verify
	container.Verify();

	// configure the global WebApi to use SimpleInjector
	GlobalConfiguration.Configuration.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(container);

	// configure WCF to use SimpleInjector
	SimpleInjectorServiceHostFactory.SetContainer(container);
}
````

But obviously, my WCF service does not like this lifestyle, and throws an error when I try to call a method:

> The IMyInjection is registered as 'Web API Request' lifestyle, but the instance is requested outside the context of a Web API Request.

So I have tried to create a second container with a different lifestyle:

````csharp
public static void LoadDependencyInjection()
{
	// WebApi container
	var webApiContainer = CreateContainer(new WebApiRequestLifestyle(true));
	webApiContainer.RegisterWebApiControllers(GlobalConfiguration.Configuration);
	webApiContainer.EnableHttpRequestMessageTracking(GlobalConfiguration.Configuration);
	
	// WCF container
	var wcfContainer = CreateContainer(new WcfOperationLifestyle(true));
	wcfContainer.RegisterWcfServices(Assembly.GetExecutingAssembly());

	// verify
	webApiContainer.Verify();
	wcfContainer.Verify();

	// configure the global WebApi to use SimpleInjector
	GlobalConfiguration.Configuration.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(webApiContainer);

	// configure WCF to use SimpleInjector
	SimpleInjectorServiceHostFactory.SetContainer(wcfContainer);
}

private static Container CreateContainer(ScopedLifestyle lifestyle)
{
	var container = new Container();

	// set the default lifestyle
	container.Options.DefaultScopedLifestyle = lifestyle;

	// here I register a bunch of interfaces/instances using the Scoped lifestyle

	return container;
}
````

But the second call to `container.Options.DefaultScopedLifestyle = lifestyle;` (using `WcfOperationLifestyle`) also changes the the default lifestyle of the first container! In this case, when I call my WebApi service I get the same kind of error, but in reverse:

> IMyStuff is registered as WCF operation lifestyle.

I have seen that there is a `Hybrid` lifestyle, but I have no idea how to detect whether it's currently a WCF or WebApi request...

I am using SimpleInjector 3.1.0.

Thanks for your help !

**Comment by dotnetjunkie** [comment]
Please nite that we are watching both Github and Stackoverflow. Double posting you question doesn't make us answer it more quickly. 

This is a double post of:  https://stackoverflow.com/q/35318382/264697

**Comment by cosmo0** [comment]
Yes sorry, but here, I thought I would have an answer on the part where setting the default lifestyle on one container changes the default lifestyle on the other.

**Comment by qujck** [comment]
Hi @cosmo0,  I can't reproduce a problem with a shared scope ...

```csharp
[Test]
public void DefaultScopedLifestyle_BetweenTwoNewContainers_IsNotShared()
{
    var container1 = new Container();
    container1.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
    var container2 = new Container();
    container2.Options.DefaultScopedLifestyle = new WcfOperationLifestyle();

    Assert.AreEqual(
        typeof(WebApiRequestLifestyle),
        container1.Options.DefaultScopedLifestyle.GetType());
    Assert.AreEqual(
        typeof(WcfOperationLifestyle),
        container2.Options.DefaultScopedLifestyle.GetType());
}

[Test]
public void DefaultScopedLifestyle_BetweenTwoConfiguredContainers_IsNotShared()
{
    var container1 = new Container();
    container1.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
    var container2 = new Container();
    container2.Options.DefaultScopedLifestyle = new WcfOperationLifestyle();

    container1.Register<WebApiClass>(Lifestyle.Scoped);
    container1.Register<CommonClass>(Lifestyle.Scoped);
    container2.Register<WcfClass>(Lifestyle.Scoped);
    container2.Register<CommonClass>(Lifestyle.Scoped);

    Assert.AreEqual(
        typeof(WebApiRequestLifestyle),
        container1.Options.DefaultScopedLifestyle.GetType());
    Assert.AreEqual(
        typeof(WcfOperationLifestyle),
        container2.Options.DefaultScopedLifestyle.GetType());
}

[Test]
public void DefaultScopedLifestyle_BetweenTwoVerifiedConfiguredContainers_IsNotShared()
{
    var container1 = new Container();
    container1.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
    var container2 = new Container();
    container2.Options.DefaultScopedLifestyle = new WcfOperationLifestyle();

    container1.Register<WebApiClass>(Lifestyle.Scoped);
    container1.Register<CommonClass>(Lifestyle.Scoped);
    container2.Register<WcfClass>(Lifestyle.Scoped);
    container2.Register<CommonClass>(Lifestyle.Scoped);
    container1.Verify();
    container2.Verify();

    Assert.AreEqual(
        typeof(WebApiRequestLifestyle),
        container1.Options.DefaultScopedLifestyle.GetType());
    Assert.AreEqual(
        typeof(WcfOperationLifestyle),
        container2.Options.DefaultScopedLifestyle.GetType());
}
```

**Comment by cosmo0** [comment]
Yes, I'm starting to wonder if it's not the fact that I call a WebApi service from a WCF service... I'd have to create a sample solution, but I'm not sure I have the time.

Thanks for taking the time to look into it ! :)

**Comment by dotnetjunkie** [comment]
Besides the whole Simple Injector discussion, in general I would always advice to run WCF and Web API in two complete separate applications; two different application instances with their own application projects. They can of course share the same code base, but both are usually comletely different in design and need different configurations. Separating them simplifies everything.

Another note is that you should question whether you should do the extra work of creating a SOAP service AT ALL. This calll might not be up to you, but as I see it, you provided your services in a good and industry-standard way. Why should you be forced to increase your maintenance without increasing the amount of functionality you provide?

**Comment by cosmo0** [comment]
Well, as I said, the REST webservice already existed, and a team just wanted a WCF access point (maybe it's much easier to use for them? I'm not sure. Maybe they're just lazy).

I didn't want to go through creating a new project, setting up a new website etc, just to provide the same features in a different format.
