### ISSUE TITLE
Conditional registration predicates are called extraneously

### ISSUE THREAD

**Issue by onyxmaster** [simpleinjector/SimpleInjector#187]
This is more of a question, than an issue, although it might be worth checking out for some subtle problem in predicate checking code.
When conditional registration is used and then, the depending type is resolved, the predicate checks are run twice, see https://github.com/onyxmaster/sitest (the non-generic part of it), for two GetInstanceCalls, the two predicates get called eight times, that's one extra call per predicate.

**Comment by qujck** [comment]
If you explicitly call `container.Verify()` and do a `Console.WriteLine()` before the calls to `GetInstanceCall` you'll see that all those calls are part of the verification process.

**Comment by onyxmaster** [comment]
Thank you for the explanation.

**Comment by dotnetjunkie** [comment]
And note that the predicates will be called for each consumer, since the information of the consumer will change on each predicate call. The predicate will usually be called once per consumer.
