### ISSUE TITLE
Combining abstract factories with dependencies

### ISSUE THREAD

**Issue by zedr0n** [simpleinjector/SimpleInjector#188]
I'm trying to figure out a way to handle creating class instances with dependencies which can only be resolved at runtime and are also transient registrations. An example I have is 

``` c#
interface ILoginService {
    IDocument DoLogin();
}

interface ILoginServiceFactory {
    ILoginService Create(IDocument document);
}

public class LoginServiceFactory : ILoginServiceFactory {
    ILoginService Create(IDocument document) {
        return new LoginService(document);
    }  
}

interface IConnectionService {
    IDocument GetDocument(string url);
}

public class AuthenticatedConnectionService : ConnectionService {
    private readonly IConnectionService _connectionService;
    private readonly ILoginServiceFactory _factory;

    public IDocument GetDocument(string url) {
        var document = _connectionService.GetDocument(url);
        var loginService = _factory.Create(document);
        return loginService.DoLogin();
    }

    AuthenticatedConnectionService(IConnectionService connectionService, 
        ILoginServiceFactory factory) {
        _factory = factory;
        _connectionService = connectionService;
    }
}
```

Here I am using an abstract factory registration to create the object with a runtime dependency. The problem with this approach is that I have explicit dependency on a constructor of ILoginService. For simple cases I could move the parameter to property and initialise explicitly in the factory

``` c#
public class LoginServiceFactory : ILoginServiceFactory {
    private readonly Container _container;

    ILoginService Create(IDocument document) {
        var loginService = _container.GetInstance<ILoginService>();
        loginService.Document = document;
    }

    LoginServiceFactory(Container container) {
        _container = container;
    }
}
```

But in my case ILoginService has properties injected which depend on IDocument so what I really need is to register the IDocument instance in the container so it can resolve all dependencies correctly. The reason I need to do this is that ILoginService has properties which depend on both IDocument instance plus primitives which are resolved from attributes implementing an aspect driven design:

``` c#
public class LoginService : ILoginService {
    [Selector(".ul")]
    private IPageItem _list { get; set; } 
}

public class PageItem : IPageItem {
    PageItem(IDocument document, string selector) { }
}
```

The only way I could figure out how to do it is by using a temporary container for each resolution of the type:

``` c#
public class LoginServiceFactory : ILoginServiceFactory {
    private readonly Container _innerContainer;

    ILoginService Create(IDocument document) {
        _innerContainer.Register(() => document);
        var loginService = _innerContainer.GetInstance<ILoginService>();
        return loginService;
    }

    LoginServiceFactory(Container container) {
        _innerContainer = new Container();
        foreach(var producer in container.GetAllRegistrations()) {
            _innerContainer.AddRegistration(producer.ServiceType, producer.Registration);
        }
    }
}
```

But that really seems quite ugly. I've read through all the docs and especially the design concepts/guidelines but I still can't figure out what would be a valid way to combine runtime dependencies with static dependencies. Any hints?

**Comment by dotnetjunkie** [comment]
The root of your problems is that you wish to inject runtime data (the document) into your components. This is an anti-pattern, as described [here](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99).

**Comment by zedr0n** [comment]
I see, if I move the runtime data to a method then I won't be able to inject properties which means I will have to manually initialise IPageItem avoiding which was the primary goal of using dependency injection. Now if I move the runtime behind an abstraction ( e.g. IDocumentProvider ) I will still have to somehow configure the IDocumentProvider to give me an instance I want so now we are back to square one where IDocumentProvider itself will depend on some runtime data which defines which document to create. 

	interface IDocumentProvider
	{
          IDocument Document { get; }
	}

    public class DocumentProvider : IDocumentProvider
    {
        IConnectionStack _connectionStack;
        private string _url;

        IDocument Document => _connectionStack[url];
    }

That doesn't really help much as while in your examples the runtime data is in a sense a singleton here we cannot abstract runtime data here by a service.

**Comment by qujck** [comment]
What sort of app is it Mvc/WebApi/?

**Comment by zedr0n** [comment]
UWP app which is basically a wrapper around a website but I use https://github.com/AngleSharp/AngleSharp for connecting and parsing html elements. That's why I'm using dependency injection, I want the app classes to be descriptive of web pages, e.g. I have something like

    [Url("http://")]
    public class Profile
    {
        [Selector("div.page-title")]
        public readonly IWebString Name;
        [Selector("div.page__lede")]
        public readonly IWebNumber Age;

SimpleInjector is used to process the attributes and inject them as primitives to the actual parameters of underlying constructors. This should allow for very quick scaffolding and is primarily a framework I'm creating.

**Comment by zedr0n** [comment]
Now that I think about it there might be another way to handle this abstracting out IDocument

    public interface IDocumentProvider
    {
        IDocument Document { get; set; }
    }

    public class AuthenticatedConnectionService : IConnectionService
    {
        private readonly IHttpConnectionService _connectionService;
        private readonly Func<ILoginService> _loginServiceFactory;
        private readonly Container _container;

        public async Task<IDocument> GetDocument(string url, bool alwaysReload = false)
        {
            var document = await _connectionService.GetDocument(url, alwaysReload);

            if (document == null)
                return null;

            using (_container.BeginExecutionContextScope())
            {
                var documentProvider = _container.GetInstance<IDocumentProvider>();
                documentProvider.Document = document;

                var loginService = _loginServiceFactory();

**Comment by dotnetjunkie** [comment]
Why can't the `IDocumentProvider` implementation itself call `_connectionService.GetDocument`? By setting the document after the provider is constructed, you cause temporal coupling and make it mutable. Perhaps it's my unfamiliarity with the technology, but what is this document a d why must it be get/set using a property. Why can't you pass it along with method calls? What is so special about this document object?

**Comment by zedr0n** [comment]
IDocument is just a parsed html page, I can have IDocumentProvider get it again but that would require passing somehow the url string to the document provider. The problem with passing along with method calls is that I need an IDocument instance at login service construction to inject properties:

    public class DocumentLogin : DocumentLoginService
    {
        [Selector("input#email")]
        protected override IPageInputElement Username { get; }
        [Selector("input#password")]
        protected override IPageInputElement Password { get; }
        [Selector("button.btn")]
        protected override IPageButtonElement Button { get; }
    }

Here IPageInputElement is constructed by IoC by using IDocumentProvider instance and the attribute selector string using primitives injection as in your article

**Comment by zedr0n** [comment]
So in the end I've subverted scoping for something generic like this

    public class Provider<T>
    {
        public T Value { get; set; }
    }

    public class ScopeFactory<TInput,TService> : IScopeFactory<TInput,TService> where TService : class
    {
        public IDisposable BeginScope() => _container.BeginExecutionContextScope();
        private readonly Container _container;

        public TService Create(TInput input)
        {
            if(_container.GetCurrentExecutionContextScope() == null)
                throw new ActivationException();

            var provider = _container.GetInstance<Provider<TInput>>();
            provider.Value = input;

            return _container.GetInstance<TService>();
        }

        public ScopeFactory(Container container)
        {
            _container = container;
        } 
    }

which can then be used using scope

        public async Task<IDocument> GetDocument(string url, bool alwaysReload = false)
        {
            var document = await _connectionService.GetDocument(url, alwaysReload);

            if (document == null)
                return null;

            using (_loginServiceFactory.BeginScope())
            {
                var loginService = _loginServiceFactory.Create(document);

                // replace the result in the connection stack with the authentication result
                return await _connectionService.ConnectionStack.GetConnection(url, loginService.DoLogin(), true);
            }
        }
