### ISSUE TITLE
Use LogicalSetData in LifetimeScopeManager for scope tracking

### ISSUE THREAD

**Issue by ejsmith** [simpleinjector/SimpleInjector#190]
Why not use LogicalSetData in the LifetimeScopeManager so that scopes can flow through async calls?  This seems like a big limitation currently of the lifetime scopes.

http://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html

**Comment by qujck** [comment]
What are the limitations of [Per Execution Context Scope](http://simpleinjector.readthedocs.org/en/latest/lifetimes.html#perexecutioncontextscope)?

**Comment by ejsmith** [comment]
Uhh... so yeah, guess I missed that. :-)

So if I am using this in a Web API app and set WebApiRequestLifestyle to be the DefaultScopedLifestyle, can I have a nested scope that uses ExecutionContextScopeLifestyle?

**Comment by qujck** [comment]
`WebApiRequestLifestyle` is a `ExecutionContextScopeLifestyle`[https://github.com/simpleinjector/SimpleInjector/blob/master/src/SimpleInjector.Integration.WebApi/WebApiRequestLifestyle.cs#L42]!

**Comment by dotnetjunkie** [comment]
RTM :-D

**Comment by ejsmith** [comment]
Yep. :-) Thought I did, but missed a section.
