### ISSUE TITLE
About Lifestyle.Transient

### ISSUE THREAD

**Issue by zhshqzyc** [simpleinjector/SimpleInjector#198]
I have a telephony application. During the operation, many lines run simultaneously. Each line uses its own channel resource or voice resource. 

```csharp
public class VoiceElementsLine : ILine
{
    public IVoiceResource IncomingChannelResource { get; set; }
    public VoiceElementsLine(IVoiceResource channelElementsResource = null)
    {
        IncomingChannelResource = channelElementsResource;
    }
```

And

```csharp
public class VoiceElementsResource : IVoiceResource
{
    private readonly ChannelResource _channelResource;
    private readonly VoiceResource _voiceResource;

    public VoiceElementsResource()
    {
    }

    public VoiceElementsResource(ChannelResource channelResource)
    {
        _channelResource = channelResource;
        _voiceResource = _channelResource.VoiceResource;
    }
```

I register it as

```csharp
Container.Register<ILine, VoiceElementsLine>();

Container.Register<IVoiceResource>(() =>
    new VoiceElementsResource()
);
```

My question is can I use Lifestyle.Transient rather than new up VoiceElementsResource?

So the code will be:
```csharp
Container.Register<IVoiceResource,VoiceElementsResource>(Lifestyle.Transient);
```

Is there any difference?

**Comment by qujck** [comment]
It will be the same for your example. 

```csharp
container.Register<IVoiceResource>(() => new VoiceElementsResource());
```
is the same as
```csharp
container.Register<IVoiceResource, VoiceElementsResource>(Lifestyle.Transient);
```
is the same as 
```csharp
container.Register<IVoiceResource, VoiceElementsResource>();
```

**Comment by dotnetjunkie** [comment]
The `VoiceElementsResource` contains two constructors. You should ditch the default constructor, because [this is an anti-pattern](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=97).

**Comment by TheBigRic** [comment]
Small addition to @qujck answer:

``` c#
container.Register<TService,TImplementation>()
```
creates a registration for `TService` using the default configured lifestyle, which is `Transient` by default.

You could however override the `LifestyleSelectionBehaviour` of the `ContainerOptions` as you can read here: [Overriding Lifestyle Selection Behavior](https://simpleinjector.readthedocs.org/en/latest/extensibility.html#overriding-lifestyle-selection-behavior)

So using 
``` c#
container.Register<TService, TImplementation>(Lifestyle.Transient);
```
explicitely creates a transient registration where as the former creates an registration which uses the `LifestyleSelectionBehaviour` for determining the correct lifestyle.

**Comment by zhshqzyc** [comment]
@dotnetjunkie 
I want to ditch the second constructor. So do I have to  create a 'wrapper' interface around ChannelResource? And how?

**Comment by dotnetjunkie** [comment]
Why do you think you need a wrapper around that class?

**Comment by zhshqzyc** [comment]
Because in the constructor

     public VoiceElementsResource(ChannelResource channelResource)
     {
         _channelResource = channelResource;
         _voiceResource = _channelResource.VoiceResource;
     }
I guess that I have to inject an interface? Right now it is a class.

**Comment by TheBigRic** [comment]
Simple injector can just as easily inject a class. On that case TService is the same as TImplementation. There are also overloads available which take just the TImplementation.
