### ISSUE TITLE
Conflict with Microsoft.AspNet.WebApi.Core v5.2.3

### ISSUE THREAD

**Issue by johnsmith9264** [simpleinjector/SimpleInjector#202]
SimpleInjector.Integration.WebApi v3.1.2 conflicts with Microsoft.AspNet.WebApi.Core v5.2.3 when used in dnx project. Sample [here](https://github.com/johnsmith9264/Stuff/tree/master/WebApiSImpleInjectorBug). Removing line "Microsoft.AspNet.WebApi.Core": "5.2.3", from project.json fixes bug.

This "bug" was really obscure and hard to find. Maybe issue with Microsoft.AspNet.WebApi.Core library itself. Any ideas whi this is happening?

**Comment by dotnetjunkie** [comment]
The Web API integration package is designed for Web API, not for ASP.NET Core. You should use the new ASP.NET Core integration package.

**Comment by johnsmith9264** [comment]
Thing is, I use packge Microsoft.AspNet.Odata which depends on WebApi2. This whole thing is inside OWIN "container". Now I want to use new features of xproj such as gulp. Btw I used standard dnx46 - NET Framework 4.6, not .NET Core. 
So far so good, but when trying to run this whole thing from xproj(dnx), I get inability to load SimpleInjector.Integration.WebApi when "Microsoft.AspNet.WebApi.Core" "v5.2.3" is loaded

**Comment by waynebloss** [comment]
So, I just want to confirm - since I'm not using DNX, this isn't a problem if I'm not using dnx right?

I am about to integrate SimpleInjector with my *ASP.NET 4*, Web API 2 project that uses `package id="Microsoft.AspNet.WebApi.Core" version="5.2.3"`.

I see that the SimpleInjector WebApi Integration project has `package id="Microsoft.AspNet.WebApi.Core" version="4.0.20710.0"`.

**Comment by johnsmith9264** [comment]
No, it's not a problem

**Comment by johnsmith9264** [comment]
Since .NET Core and ASP.NET Core are released (RC2), it's good idea check if it's reproduced there. I may do it in spare time

**Comment by dotnetjunkie** [comment]
The Simple Injector packages are not compatible with RC2 a.t.m. Microsoft changed (again) everything which causes Visual Studio to produce a compile error (while Simple Injector itself is binary compatible). The horror.

This is work in progress.

**Comment by dotnetjunkie** [comment]
An RC2 compatible version of Simple Injector has just been released (v3.1.5).

**Comment by johnsmith9264** [comment]
It works. Thanks!
