### ISSUE TITLE
Simple Injector with basic asp.net 5 MVC site.

### ISSUE THREAD

**Issue by menkari** [simpleinjector/SimpleInjector#205]
I've just gotten started with the latest version of MVC and I've been using Simple Injector now for some time so its my go to for DI. I've followed the getting started guide published [here](https://simpleinjector.readthedocs.org/en/latest/aspnetintegration.html) and added in AutoMapper for my VM > Model conversions. My models are all contained in a class library and besides that, its almost a File > New Project.

The issue I've come across is when I try and register and/or login, I'm presented with the following error message:

> InvalidOperationException: No authentication handler is configured to handle the scheme: Microsoft.AspNet.Identity.Application`

Specifically this occurs on the `_signInManager.PasswordSignInAsync` method. I've not changed anything inside the `AccountController` and have also created a project from scratch which duplicates the behaviour.

My `Startup.cs` can be found here: [http://pastebin.com/PmQvu9qh](https://pastebin.com/PmQvu9qh). I'm really at a loss as to why this isn't working properly...

Any help would be greatly appreciated.

**Comment by dotnetjunkie** [comment]
Does [this answer](https://stackoverflow.com/q/34657983/264697) answer your question?

**Comment by menkari** [comment]
Thanks for sending this through, I don't know if I'm making the proper sense of it though. I think my issue with the `SignInManager` not having the ability to set authentication information?(HttpContext not being available). Again, I'm not sure as the example in the SO question was around a custom SignInManager whereas I'm trying to use the SignInManager with the functionality already available (two factor, external login, etc).

Your answer [here](http://stackoverflow.com/questions/34657983/using-simple-injector-in-mvc6-with-cookie-auth) mentions that the simplest thing to do is register `SignInManager` as `transient` but doesn't using `CrossWire` do this already? Again, I'm relatively new to the asp.net 5 so I'm not entirely sure I understand it fully. I'll create the project from scratch and post it below

**Comment by menkari** [comment]
Repository here https://github.com/menkari/SimpleInjectorHelloWorld
