### ISSUE TITLE
RegisterCollection Conditionally

### ISSUE THREAD

**Issue by gregbty** [simpleinjector/SimpleInjector#207]
Is it possible to register a collection based on a condition that resides in another instance in the container?

```csharp
container.RegisterSingleton<Settings>(/* Resolved using some complex method */);

container.RegisterCollection<IConfigChangeSubscriber>(
  AppDomain.CurrentDomain.GetAssemblies()
   .SelectMany(t => t.GetTypes())
   .Where(t => typeof (IConfigChangeSubscriber).IsAssignableFrom(t))
   .Select(t => Lifestyle.Singleton.CreateRegistration(t, container))
 , c => container.GetInstance<Settings>().EnableConfigChangeEvents); //Need the ability to conditionally register this collection
```

**Comment by dotnetjunkie** [comment]
The short answer is: no, there's no support for such feature.

In general, you should prevent having to resolve services to get configuration values (your `Settings` class for instance). Instead, make sure the configuration values are available before configuring the container. In my experience this is always possible, and always desirable. When you do this, you can simply make the follwoing registration:

``` c#
if (settings.EnableConfigChangeEvents) {
container.RegisterCollection<IConfigChangeSubscriber>(...); 
} else {
container.RegisterCollection<IConfigChangeSubscriber>(Type.EmptyTypes);
}
```

**Comment by gregbty** [comment]
Fair enough. I'll re-think the design. Thanks for the quick reply.

**Comment by dotnetjunkie** [comment]
You're welcome. If you're in doubt about how to change, feel free to show some code that we can discuss.
