### ISSUE TITLE
Can't install ExecutionContextScoping extension with .NET 4.0

### ISSUE THREAD

**Issue by flcdrg** [simpleinjector/SimpleInjector#210]
In a WebApi project that is using Web API 4.0 and targets .NET 4.0

1. Add NuGet package SimpleInjector
2. Succeeds
3. Add NuGet package SimpleInjector.Extensions.ExecutionContextScoping
4. Fails with error:

```
Attempting to gather dependency information for package 'SimpleInjector.Extensions.ExecutionContextScoping.3.1.2' with respect to project 'Source\WebApi', targeting '.NETFramework,Version=v4.0'
Attempting to resolve dependencies for package 'SimpleInjector.Extensions.ExecutionContextScoping.3.1.2' with DependencyBehavior 'HighestMinor'
Resolving actions to install package 'SimpleInjector.Extensions.ExecutionContextScoping.3.1.2'
Resolved actions to install package 'SimpleInjector.Extensions.ExecutionContextScoping.3.1.2'
Install failed. Rolling back...
Package 'SimpleInjector.Extensions.ExecutionContextScoping.3.1.2 : SimpleInjector [3.1.2, )' does not exist in project 'WebApi'
Package 'SimpleInjector.Extensions.ExecutionContextScoping.3.1.2 : SimpleInjector [3.1.2, )' does not exist in folder 'C:\Dev\git\MySolution\packages'
Could not install package 'SimpleInjector.Extensions.ExecutionContextScoping 3.1.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by flcdrg** [comment]
Examining the SimpleInjector.Extensions.ExecutionContextScoping.3.1.2.nupkg file reveals that indeed there is no lib\net40 folder

**Comment by flcdrg** [comment]
Stumbled across http://stackoverflow.com/questions/22392032/are-there-any-technical-reasons-simple-injector-cannot-support-web-api-on-net-4/22404267#22404267

I think in that case the README.md needs to be updated to clarify that not all components support .NET 4.0

**Comment by dotnetjunkie** [comment]
The [Web API integration page](https://simpleinjector.org/webapi) does state that the package only support .NET 4.5, but it does make sense to make this more explicit, for instance by describing this in the README.md.

Thanks for your suggestion.
