### ISSUE TITLE
How to Use Property and Method Injection with Simple Injector

### ISSUE THREAD

**Issue by saineshwar** [simpleinjector/SimpleInjector#212]
There is no Proper Documentation on this topic [Property and Method Injection with SimpleInjector] can one guide me in this

**Comment by TheBigRic** [comment]
Property injection is described [here](http://simpleinjector.readthedocs.org/en/latest/advanced.html#property-injection).

For method injection You dont need the container, just put the dependency in the Method signature and supply the dependency on each Call to the Method.

Notice that the preferred method of injection is constructor injection and property injection is almost never really needed, except for frameworks as ASP.net webforms

**Comment by dotnetjunkie** [comment]
@saineshwar, can you explain your scenario concerning method injection? What is it you want to achieve?

**Comment by vladimir-kovalyuk** [comment]
I can imagine that method injection might come in handy in cases where the hierarchy of classes has base class with N dependencies and all these common dependencies can be extracted into method of base class attributed with [Inject]. This would allow to omit necessity of listing all these N dependencies in every derived class' constructors. I'm not saying that this approach is good.

```
public abstract class ClassBase
{
   protected ClassBase(explicit dependencies) { ... }
   [Inject] 
   protected/public void InjectDependencies(implicit dependencies) { ... }
}
```

**Comment by dotnetjunkie** [comment]
[Dependency Injection in .NET, second edition](http://manning.com/seemann2/) goes into quite a lot of details about Method Injection, how to use it, and how _not_ to use it. Here are a few excerpts from chapter 4:

> *Method Injection* is unsuited to be used _within_ the [Composition Root](http://freecontent.manning.com/dependency-injection-in-net-2nd-edition-understanding-the-composition-root/). Within a *Composition Root*, *Method Injection* can be used to _initialize_ a previously constructed class with its *Dependencies*. Doing so, however, leads to [Temporal Coupling](http://blog.ploeh.dk/2011/05/24/DesignSmellTemporalCoupling/) and for that reason it is highly discouraged. (paragraph 4.3.2)

> **WARNING**: Do not store injected method *Dependencies*. This leads to *Temporal Coupling*, [Captive Dependencies](http://blog.ploeh.dk/2014/06/02/captive-dependency/) or hidden side effects. A method should use the *Dependency* or pass it on, but should refrain from storing such *Dependency*.  (paragraph 4.3.2)

Besides the warnings about Temporal Coupling and Captive Dependencies, the use of base classes in general is a design smell. Chapter 3 that book warns about base classes:

> Base classes can easily turn into ever-changing ever growing [God Objects](https://en.wikipedia.org/wiki/God_object). Base classes can cause _tight coupling_. Interfaces on the other hand force us into the [Composition over Inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) mantra.

Base classes _with dependencies_ in general are problematic, because the the base class is strongly coupled with the derivatives, which complicates testing. Often base classes are abused for handling cross-cutting concerns (e.g. logging, audit trailing, transaction handling, etc), but this causes derivates to be strongly-coupled to the cross-cutting concerns, which is problematic for testability and maintainability. There are more effective alternatives, such as the use of Decorators or Interceptors.

**Comment by jurajvt** [comment]
> @saineshwar, can you explain your scenario concerning method injection? What is it you want to achieve?

For example this:

[https://simpleinjector.readthedocs.io/en/latest/windowsformsintegration.html](url)

On the end of guide there is a note:

> It is not possible to use Constructor Injection in User Controls. User Controls are required to have a default constructor. Instead, pass on dependencies to your User Controls using Method Injection.

**Comment by SkunkGuru** [comment]
> > @saineshwar, can you explain your scenario concerning method injection? What is it you want to achieve?
> 
> For example this:
> 
> [https://simpleinjector.readthedocs.io/en/latest/windowsformsintegration.html](url)
> 
> On the end of the guide there is a note:
> 
> > It is not possible to use Constructor Injection in User Controls. User Controls are required to have a default constructor. Instead, pass on dependencies to your User Controls using Method Injection.

Agree with this.
Guide says to use Method Injection, but dont explain how

**Comment by dotnetjunkie** [comment]
I updated that note in the documentation. Using Method Injection is not helpful in that case, which makes the note confusing. The new note suggests Property Injection and points to the documentation section about Property Injection.
