### ISSUE TITLE
Let Integration.Web.Mvc reference MVC NuGet instead of GAC version

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#218]
The SimpleInjector.Integration.Web.Mvc.dll currently depends on the specific GAC version 3.0.0.1 of System.Web.Mvc. This complicates building MVC and can cause trouble for developers who didn't apply the MS security patch for MVC that replaces the GAC version 3.0.0.0 of MVC.

Pull request #211 supplies us with the necessary changes to the SimpleInjector.Integration.Web.Mvc.csproj, but we also need to update the NuGet package template as well.

Since there is a small risk of causing trouble to developers who use this package, it's wise to not fix this in a patch release.

**Comment by malylemire1** [comment]
The also a mismatch if someone use MVC nuget package.

I'm using CheckAsm to verify assembly version mismatch and I get the following error.
Assembly was found with version 5.2.3.0 but parent references 3.0.0.1.
