### ISSUE TITLE
Separate Crosswire functionality from ASP.NET core extensions, like RegisterAspNetControllers

### ISSUE THREAD

**Issue by apawsey** [simpleinjector/SimpleInjector#222]
.net core dependency injection is available outside of ASP.NET and I'm sure will sooner or later appear in use in the real world.  The Crosswire behaviour for forwarding requests for services owned by the platform, would be useful to separate out from the functionality that is specific to handling ASP.NET's particular dependencies.

**Comment by dotnetjunkie** [comment]
I don't like extracting this sole extension method into its own package for a framework that does not exist. That would be a form of over generalizing. We'll wait until the day arrives that other frameworks start making use of the abstraction, before we start to generalize.

**Comment by apawsey** [comment]
Oh I definitely wouldn't have wanted to extract just the one method.  I guess it was more to raise the specific point regarding the separation of .net core and ASP.NET core.  I've seen with many other libraries that the focus is purely on providing support for ASP.NET core, but then having to backtrack and unwind to separate .net core functionality out.  I also raised it because I'm busy working exactly that use case... (as a side note, the current project is being greatly enhanced by your articles on command handlers etc, so despite a few raised voices getting the rest of the team to buy in, many many thanks for that!!)

**Comment by dotnetjunkie** [comment]
Microsoft created an abstraction on top of its DI container and promotes DI container maintainers to create adapters for this adapter. This however something we are strongly against, and we expressed are objections in (among other places) the following discussions: https://github.com/simpleinjector/SimpleInjector/issues/41 and https://github.com/simpleinjector/SimpleInjector/issues/156.

Since you won't see an official adapter from the Simple Injector contributors, there is IMO little need for a reusable library for the core DI bits.

**Comment by apawsey** [comment]
While I completely agree with your assessment of the Microsoft DI infrastructure (I've actually read many of your discussions on this topic, including when you've been discussing directly with the Microsoft guys), my point is not to adapt SI to conform with Microsoft's DI abstractions, but rather to provide enough "cross wiring" to not need the Microsoft layer (or rather to not have to interact with it any further after SI's registrations :))  My intention is that all my dependencies should come from SI (as I would have constructed my app before core), with a few (where I have no choice) being cross-wired to come from Microsoft's underlying stuff.  This way, even if Microsoft changes the behaviour in future, it will just be a case of me fixing my cross-wiring.

Anyway, I don't want to drag you into rehashing all the different discussions... that's my (probably flawed) plan.

**Comment by dotnetjunkie** [comment]
As long as you're not suggesting an adapter, your plan isn't flawed ;) So we might want to extract functionality in a shared library in the future, but let's wait a bit to see how the world around us evolves. Currently, cross-wiring is not much nore than a three lines big extension method. But let's keep a close I on what will happen in the near future.
