### ISSUE TITLE
Separate assembly for container in N-Layer application

### ISSUE THREAD

**Issue by osobica** [simpleinjector/SimpleInjector#225]
Hi,

I have a question.
I am coming from Unity environment and am exploring Simple Injector as an IoC container, especially its Automatic registration. So far I've managed to get a grip of things, but am stuck at certain problems.

First, in Unity I usually had a separate assembly for container and this assembly was referenced from MVC, WCF, etc. Of course, these technologies were unaware that there is an IoC container that controlled the instantations and there was no reference of Unity inside these assemblies.
I'd like to do the same with Simple Injector. I'd like to set it as a container that is in a separate assembly (I managed to do that) and when I want to bind MVC with this assembly, I have to explicitly reference SimpleInjector.Integration.Web.Mvc. That's something that I don't want to do as I'd like to have my MVC clean and independent of any IoC so that I can change that as I want without disrupting the MVC assembly (SOLID, strategy pattern).

Unity container in its own assembly:

``` c#
namespace Obi.Mdm.Security.Bootstrap.Unity
{
    public abstract class UnityBootstrapper : IBootstrapper
    {
        private readonly string _bootstrapperName;
        protected readonly Type BootstrapperType;
        protected readonly IUnityContainer Container;

        protected UnityBootstrapper(IUnityContainer unityContainer)
        {
            if (unityContainer == null)
                throw new ArgumentNullException("unityContainer");

            Container = unityContainer;
            BootstrapperType = typeof(IBootstrapper);
            _bootstrapperName = BootstrapperType.Assembly.GetName()
                .Name.Split(".".ToCharArray(), StringSplitOptions.RemoveEmptyEntries).Last();
        }

        public object Initialize(Type type)
        {
            return Container.Resolve(type);
        }

        public abstract void RegisterComponents();

        protected IEnumerable<Type> ApplicationAssemblies()
        {
            //if (HostingEnvironment.IsHosted) 
			// determines whether the application is web hosted or not
            return AllClasses.FromAssemblies(
				BuildManager.GetReferencedAssemblies().Cast<Assembly>())
				.Where(TypeIsFromApplication).ToList();
        }

        protected IUnityContainer RegisterBaseComponents()
        {
            return Container.RegisterTypes(ApplicationAssemblies(), ApplicationTypes);
        }

        protected IEnumerable<Type> ApplicationTypes(Type assembly)
        {
            return WithMappings.FromAllInterfaces(assembly).Where(TypeIsFromApplication).ToList();
        }

        protected virtual bool TypeIsFromApplication(Type type)
        {
            // ReSharper disable once PossibleNullReferenceException
            return type != BootstrapperType
                && type.Namespace.StartsWith(GetApplicationNamespace(), 
				StringComparison.InvariantCultureIgnoreCase);
        }

        protected virtual string GetApplicationNamespace()
        {
            var name = Assembly.GetExecutingAssembly().GetName().Name;
            return name.Substring(0, name.IndexOf(_bootstrapperName, 
			StringComparison.InvariantCultureIgnoreCase));
        }
    }
}
```

Bootstrapper "Factory":

``` c#
namespace Bootstrap
{
    public static class BootstrapperFactory
    {
        public static IBootstrapper Create(Context context)
        {
            switch (context)
            {
                case Context.SecurityWebSite:
                    return new SimpleInjectorBootstrapper();
                //return new SecurityWebSiteBootstrapper(new UnityContainer());
                case Context.SecurityWebService:
                    return new SecurityBootstrapper(new UnityContainer());
                default:
                    throw new InvalidEnumArgumentException("context");
            }
        }
    }

    public enum Context
    {
        SecurityWebSite,
        SecurityWebService
    }
}
```

MVC call:

``` c#
namespace Web.CentralAdministration.ControllerActivators
{
    public class BootstrapperHttpControllerActivator : IHttpControllerActivator
    {
        private readonly IBootstrapper _bootstrapper;

        public BootstrapperHttpControllerActivator(IBootstrapper bootstrapper)
        {
            if (bootstrapper == null)
                throw new ArgumentNullException("bootstrapper");

            _bootstrapper = bootstrapper;
        }

        public IHttpController Create(HttpRequestMessage request, 
			HttpControllerDescriptor controllerDescriptor, Type controllerType)
        {
            if (controllerType == null)
                throw new HttpException(404, string.Format(
					"The controller for path '{0}' could not be found or it " + 
					"does not implement IController",
                    request.RequestUri));
            if (!typeof(IHttpController).IsAssignableFrom(controllerType))
                throw new ArgumentException(string.Format(
					"Type requested is not a controller: {0}", controllerType.Name));

            IHttpController controller;

            try
            {
                controller = _bootstrapper.Initialize(controllerType) as IHttpController;
            }
            catch (Exception exception)
            {
                throw new InvalidOperationException(string.Format(
					"Error resolving controller {0}", controllerType.Name), exception);
            }

            return controller;
        }
    }
}
```

If that's not possible due to a faulty pattern, can somebody explain me why and what can I do to improve it? I (am trying to) use Domain Driven Design and SOLID as much as possible.

Thanks!

**Comment by dotnetjunkie** [comment]
> in Unity I usually had a separate assembly for container and this assembly was referenced from MVC, WCF, etc.

If you refence this 'bootstrap' assembly from your MVC project at compile time, it still means that the MVC assembly depends on the DI library, since assembly dependencies are transitive.

Also take a look at this [Stackoverflow question](https://stackoverflow.com/questions/9501604/ioc-di-why-do-i-have-to-reference-all-layers-assemblies-in-entry-application) and both the answers from me and Mark Seemann. I describe that it isn't really useful to prevent your startup project from having a reference to the DI library. In my answer I explain the difference between deployment and logical artifacts:

> Don't forget that assemblies are a deployment artifact; you split code into multiple assemblies to allow code to be deployed separately. An architectural layer on the other hand is a logical artifact. It's very well possible (and common) to have multiple layers in the same assembly. In this case we'll end up having the Composition Root (layer) and the Presentation Layer [MVC] in the same web application project (thus in the same assembly). And even though that assembly references the assembly containing the DAL, the Presentation Layer still does not reference the Data Access Layer. This is a big distinction.

> I'd like to set it as a container that is in a separate assembly (I managed to do that) and when I want to bind MVC with this assembly, I have to explicitly reference SimpleInjector.Integration.Web.Mvc.

The `SimpleInjector.Integration.Web.Mvc` library contains extension points for adding Simple Injector to an MVC project. For instance, it allows registering controllers using `RegisterMvcControllers`. You don't have to add it as reference to your MVC project, if you wish, you only have to add it as reference to your IoC project. You will still have to make a call from your MVC startup path into that bootstrap assembly.

I'm a bit confused though, since you're talking about MVC but have an Web API `IHttpControllerActivator`. But either way, with the Simple Injector MVC integration package you don't have to create your own custom IControllerFactory / IHttpControllerActivator. You can just use the `SimpleInjectorDependencyResolver` (for MVC) or `SimpleInjectorWebApiDependencyResolver` (for Web API).

**Comment by osobica** [comment]
> If you refence this 'bootstrap' assembly from your MVC project at compile time, it still means that the MVC assembly depends on the DI library, since assembly dependencies are transitive.

Definitely! But, the main point is that I can switch IoC container without MVC knowing it and I can reuse it with other technologies, like WCF and WPF within a single solution, especially when automating the registrations. Perhaps I didn't elaborate well :P.

Thanks for pointing those SO articles! Nice read.

I probably c/p-ed the wrong Activator, since I have one for MVC and one for API.
