### ISSUE TITLE
Torn Lifestyle errors are thrown when the same closed type is registered more than once and more than one decorator is registered

### ISSUE THREAD

**Issue by jasonmcboyd** [simpleinjector/SimpleInjector#228]
The following code (from LinqPad) can reproduce the issue:

``` c#
void Main()
{
	Container container = new Container();
	
	var fooA = Lifestyle.Singleton.CreateProducer<IFoo<int>, FooA>(container);
	var fooB = Lifestyle.Singleton.CreateProducer<IFoo<int>, FooB>(container);
		
	container.RegisterDecorator(typeof(IFoo<>), typeof(Decorator1<>), Lifestyle.Singleton);
	container.RegisterDecorator(typeof(IFoo<>), typeof(Decorator2<>), Lifestyle.Singleton);

	container.Verify();
}

public interface IFoo<T> { }
public class FooA : IFoo<int> { }
public class FooB : IFoo<int> { }

public class Decorator1<T> : IFoo<T> {
	public Decorator1(IFoo<T> inner) {
		this._Inner = inner;
	}
	
	private readonly IFoo<T> _Inner;
}

public class Decorator2<T> : IFoo<T> {
	public Decorator2(IFoo<T> inner) {
		this._Inner = inner;
	}

	private readonly IFoo<T> _Inner;
}
```

> The configuration is invalid. The following diagnostic warnings were reported:
> -[Torn Lifestyle] The registration for UserQuery.IFoo<Int32> maps to the same implementation and lifestyle as the registration for UserQuery.IFoo<Int32> does. They both map to UserQuery.Decorator1<Int32> (Singleton). This will cause each registration to resolve to a different instance: each registration will have its own instance.
> See the Error property for detailed information about the warnings. Please see https://simpleinjector.org/diagnostics how to fix problems and how to suppress individual warnings. 

If you remove one of the decorator registrations or one of the `IFoo<>` registrations the error goes away.

**Comment by dotnetjunkie** [comment]
Thanks for reporting this. I've been able to reproduce this bug.

**Comment by dotnetjunkie** [comment]
Path release v3.1.4 has been published that fixes this issue.
