### ISSUE TITLE
How to resolve to a specific concrete type, with decorators, while there are multiple implementations of the same interface?

### ISSUE THREAD

**Issue by jvdvleuten** [simpleinjector/SimpleInjector#234]
In short, the problem is:

- I have multiple interfaces of `IEventHandler<TEvent>`
- I have multiple concrete EventHandlers using the same `IEventHandler<ConcreteEventType>`s
- I want to `GetInstance` to a specific concrete EventHandler, while decorating it (so the type visible or return type would be of `IEventHandler<ConcreteEventType>`

I am using the following IEventHandler interface:

``` c#
public interface IEventHandler<in TEvent> where TEvent : class, IEvent
{
    Task HandleAsync(TEvent @event);
}
```

The following ProjectionHandlers implement the same `UserSignedUpEvent` and `UseChangedEmailAddressEvent`

``` c#
public class FirstProjectionHandler : 
   IEventHandler<UserCreatedEvent>, 
   IEventHandler<UserChangedEmailAddressEvent> 
{ /* implementation */ }

public class SecondProjectionHandler : 
   IEventHandler<UserCreatedEvent>, 
   IEventHandler<UserChangedEmailAddressEvent> 
{ /* implementation */ }
```

Both Projection handlers have their own queue, where Events are coming in. In an `EventHandlerService`, the Event is handled and should eventually be called like this:

``` c#
 private async Task HandleAsync<TEvent, TEventHandler>(TEvent @event) 
    where TEvent : class, IEvent, new() 
    where TEventHandler : IEventHandler<TEvent>
{
    using (_container.BeginExecutionContextScope())
    {
        // *Here lies to problem*
        var eventHandler = _container.GetInstance<TEventHandler>();

        await eventHandler.HandleAsync(@event).ConfigureAwait(false);
    }
}
```

I would like to resolve the concrete event handler (e.g. `FirstProjectionHandler` or `SecondProjectionHandler`, based on TEventHandler and also decorate the IEventHandler<TEvent>. 

To setup decoration, I tried this:

``` c#
container.RegisterCollection(typeof(IEventHandler<>), commandHandlerAssemblies);

container.RegisterDecorator(typeof(IEventHandler<>), typeof(DecoratedEventHandler<>), 
   Lifestyle.Transient);
```

This breaks `_container.GetInstance<TEventHandler>();` because now I need to use `_container.GetAllInstances(eventHandlerType)`

I tried implementing a factory, to do get back a decorated `IEventHandler<TEvent>` based on the concrete EventHandler type and type of Event being handled:

``` c#
var eventHandler = _eventHandlerFactory.CreateNew<TEventHandler, TEvent>();
```

Implementing and registering the factory, brings me back to the basis of the problem. That I cannot get a correct single instance of the correct concrete type which is decorated...

Maybe doing something fundamentally wrong? How would you do something like this? 

All examples provided on the website and stackoverflow, only use one concrete implementation of the `ICommandHandler` or `IEventHandler` interface, while I need a little tiny bit more...

**Comment by dotnetjunkie** [comment]
I understand what you are trying to do. Not only do you have a queue for each event, you have a separate queue per event handler to allow them to be atomic and independent of failures of other handlers. This is a very sane approach and you need to know about the existence of the concrete handler type to be able to pull this off.

You can do this as follows:

``` c#
Type[] handlerTypes = container.GetTypesToRegister(typeof(IEventHandler<>),
    commandHandlerAssemblies);

Dictionary<Type, Dictionary<Type, InstanceProducer>>> eventHandlerProducers =
    from handlerType in handlerTypes
    from eventType in GetEventsForHandler(handlerType)
	group handlerType by eventType into g
	select new { eventType = g.Key, handlerTypes = g.ToArray() })
	.ToDictionary(
		i => i.eventType,
		i => i.handlerTypes.ToDictionary(
			t => t,
			t => Lifestyle.Transient.CreateProducer(
				typeof(IEventHandler<>).MakeGenericType(i.eventType),
				t, container)));

private static Type[] GetEventsForHandler(Type handlerType) => (
    from iface in handlerType.GetInterfaces()
    where iface.IsGenericType
    where iface.GetGenericTypeDefinition() == typeof(IEventHandler<>)
    select iface.GetGenericArguments().Single())
    .ToArray();

// Usage
var handlersForEvent = eventHandlerProducers[typeof(UserCreatedEvent)];
InstanceProducer producer = handlersForEvent[typeof(SecondProjectionHandler)];
dynamic handler = producer.GetInstance();
handler.Handle((dynamic)(new UserCreatedEvent()));
```

What this does is create a dictionary with the `event type` as key and the value is again a dictionary with the `event handler type` as key and an `InstanceProducer` as value. This instance producer can create the handler with its decorators applied.

This might come close to what you need. You might need to tweak this code a bit to get it to work in your specific case. There might be other (or even easier) ways to do this in Simple Injector, but this is the first thing that came to my mind.

**Comment by jvdvleuten** [comment]
I didn't know that you could create your own producer. I have now the following factory interface for my event handlers:

```
public interface IEventHandlerFactory
{
    IEventHandler<TEvent> CreateNew<TEvent, TEventHandler>() where TEvent : class, IEvent, new() where TEventHandler : IEventHandler<TEvent>;
    IEnumerable<Type> GetEventHandlers();
}
```

I use GetEventHandlers() to help subscribe all event handlers and their events to the queue.

When an event comes in, I use:

```
private async Task HandleAsync<TEvent, TEventHandler>(TEvent @event) where TEvent : class, IEvent, new() where TEventHandler : IEventHandler<TEvent>
{
    using (_container.BeginExecutionContextScope())
    {
        var eventHandler = _eventHandlerFactory.CreateNew<TEvent, TEventHandler>();

        await eventHandler.HandleAsync(@event).ConfigureAwait(false);
    }
}
```

And the concrete implementation of the factory is:

```
public class SimpleInjectorEventHandlerFactory : Dictionary<Type, Dictionary<Type, InstanceProducer>>, IEventHandlerFactory
{
    IEventHandler<TEvent> IEventHandlerFactory.CreateNew<TEvent, TEventHandler>()
    {
        var handlersForEvent = this[typeof(TEvent)];

        InstanceProducer producer = handlersForEvent[typeof(TEventHandler)];

        var handler = (IEventHandler<TEvent>)producer.GetInstance();

        return handler;
    }

    public IEnumerable<Type> GetEventHandlers()
    {
        return this.SelectMany(x => x.Value).Select(x => x.Key);
    }
}
```

Which gets populated when building the container like this:

```
container.RegisterCollection(typeof(IEventHandler<>), commandHandlerAssemblies);
container.RegisterDecorator(typeof(IEventHandler<>), typeof(EventHandlerDecorator<>), Lifestyle.Transient);

var eventHandlerTypes = container.GetTypesToRegister(typeof(IEventHandler<>), commandHandlerAssemblies);

var eventHandlerFactory = new SimpleInjectorEventHandlerFactory();

foreach (var eventHandlerType in eventHandlerTypes)
{
    foreach (var eventType in GetEventsForHandler(eventHandlerType))
    {
        Dictionary<Type, InstanceProducer> producerDictionary;

        if (!eventHandlerFactory.TryGetValue(eventType, out producerDictionary))
        {
            producerDictionary = new Dictionary<Type, InstanceProducer>();
            eventHandlerFactory.Add(eventType, producerDictionary);
        }

        producerDictionary.Add(eventHandlerType,
            Lifestyle.Transient.CreateProducer(
                typeof(IEventHandler<>).MakeGenericType(eventType),
                eventHandlerType,
                container));
    }
}

container.Register<IEventHandlerFactory>(() => eventHandlerFactory, Lifestyle.Singleton);
```

```
private static Type[] GetEventsForHandler(Type handlerType)
{
    return handlerType
        .GetInterfaces()
        .Where(i => i.IsGenericType)
        .Where(i => i.GetGenericTypeDefinition() == typeof(IEventHandler<>))
        .Select(i => i.GetGenericArguments().Single())
        .ToArray();
}
```

Works beautifully! 

Big thanks for your help!
