### ISSUE TITLE
update installs "DotNET 5.0" dependencies on target 4.6.1

### ISSUE THREAD

**Issue by vitidev** [simpleinjector/SimpleInjector#235]
Why update from 3.1.2 to 3.1.4 installs all this packages

    DotNET 5.0
    System.Collections (>= 4.0.10)
    System.Collections.Concurrent (>= 4.0.10)
    System.Diagnostics.Debug (>= 4.0.10)
    System.Globalization (>= 4.0.10)
    System.IO (>= 4.0.10)
    System.Linq (>= 4.0.0)
    System.Linq.Expressions (>= 4.0.10)
    System.Reflection (>= 4.0.10)
    System.Reflection.Extensions (>= 4.0.0)
    System.Reflection.TypeExtensions (>= 4.0.0)
    System.Runtime (>= 4.0.20)
    System.Runtime.Extensions (>= 4.0.10)
    System.Threading (>= 4.0.10)
    System.Threading.Tasks (>= 4.0.10)

on platform .NETFramework,Version=v4.6.1 if they are not used?

**Comment by dotnetjunkie** [comment]
Can you be more precise? What version of Visual Studio are you using, what kind of project do you use? Are you using the new DNX project structure with project.json?

**Comment by vitidev** [comment]
Visual Studio 2015 update 2
Project type: WPF Application (begin with .NET 3.5 and migrate 3.5->4->4.5->4.61)
simple injector used from 2.x and migrated to 3.x. version is 3.1.2
Current target framework: 4.6.1
DNX not used.

**Comment by dotnetjunkie** [comment]
I tried to reproduce your issue by creating a WPF application with Visual Studio 2015 update 2, with .NET 4.6.1, but I can't reproduce this. Can you provide me with screen shots that show what you are experiencing?

**Comment by vitidev** [comment]
https://i.imgsafe.org/28eb2cf.png

**Comment by vitidev** [comment]
On new test project the same. 
Attempting to gather dependency information for package 'SimpleInjector.3.1.4' with respect to project 'SimpleInjectionTest', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'SimpleInjector.3.1.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'SimpleInjector.3.1.4'
Resolved actions to install package 'SimpleInjector.3.1.4'
Adding package 'System.Collections.4.0.10' to folder 'E:\dev\test\SimpleInjectionTest\packages'
Added package 'System.Collections.4.0.10' to folder 'E:\dev\test\SimpleInjectionTest\packages'
Added package 'System.Collections.4.0.10' to 'packages.config'
Successfully installed 'System.Collections 4.0.10' to SimpleInjectionTest
Adding package 'System.Collections.Concurrent.4.0.10' to folder 'E:\dev\test\SimpleInjectionTest\packages'
Added package 'System.Collections.Concurrent.4.0.10' to folder 'E:\dev\test\SimpleInjectionTest\packages'
Added package 'System.Collections.Concurrent.4.0.10' to 'packages.config'
Successfully installed 'System.Collections.Concurrent 4.0.10' to SimpleInjectionTest
Adding package 'System.Diagnostics.Debug.4.0.10' to folder 'E:\dev\test\SimpleInjectionTest\packages'
Added package 'System.Diagnostics.Debug.4.0.10' to folder 'E:\dev\test\SimpleInjectionTest\packages'
Added package 'System.Diagnostics.Debug.4.0.10' to 'packages.config'
....

**Comment by dotnetjunkie** [comment]
I'm still unable to reproduce this, but I think you can safely ignore this message. These references exist for .NET core projects  and you would typically only see those packages being referenced by your application if you're running a Core (DNX) project. In the new .NET ecosystem, the whole BCL is split up in thousand little packages and every library will have to state which parts of the BCL it whishes to use. If you look inside those NuGet packages however, you will see that their corresponding /net46 directory is empty, which means that no .DLL reference will be added to your project.

**Comment by vitidev** [comment]
May be...except System.Reflection.TypeExtensions.dll, who also added to references with SimpleInjector.dll. 
For other libs /net46 not contains /net46 directory or contains /net46 directory with file "_._ 0 bytes"

**Comment by vitidev** [comment]
It seems repaired
After installing the studio I had one url in nuget:https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/ (as "Machine-wide package sources").
I found on stackoverflow https://www.nuget.org/api/v2/ (as "Available package sources") and work with him.
Now I found another url https://api.nuget.org/v3/index.json, where simple injector installs and update without dnx dependies.
