### ISSUE TITLE
Update SimpleInjector.Integration.AspNet

### ISSUE THREAD

**Issue by Asshiah** [simpleinjector/SimpleInjector#236]
With the new RC2 of the the ASP.NET Core 1.0 framework, it is no longer possible to use this integration package to resolve dependencies for ViewComponents and Controllers as

- The **SimpleInjectorViewComponentInvokerFactory** class does not implement the new **Microsoft.AspNetCore.Mvc.IViewComponentInvokerFactory** interface.

- The **RegisterAspNetControllers** and **RegisterAspNetViewComponents** extension method do not use the new **Microsoft.AspNetCore.Builder.IApplicationBuilder** interface.

Is it possible to update the package?

Thanks in advance.

**Comment by dotnetjunkie** [comment]
Dude, Microsoft just published RC2 yesterday. How fast do you think we are? :) 

There are breaking changes in RC2 that affect the integration package. It will take us some time to publish a RC2 compatible version.

**Comment by Asshiah** [comment]
I know. I was not asking for it today but I thought this could be a reminder for you in your TODO list^^

No pressure.

**Comment by dotnetjunkie** [comment]
Don't worry. It's on my a.s.a.p. list.

**Comment by Asshiah** [comment]
Thank you for this.^^ I'll try it out.

**Comment by dotnetjunkie** [comment]
I pushed v3.1.5-rc2 of the ASP.NET Core integration library to NuGet. You can use that.

**Comment by Asshiah** [comment]
I don't know why but it seems the nuget packages is still referencing old versions (**6.0.0-rc1-final** instead of **1.0.0-rc2-final**) of its dependency packages. (**Microsoft.AspNet.Mvc.Core** and **Microsoft.AspNet.Mvc.ViewFeatures**)

This is creating problems as there can be 2 methods with the exact same signature in two different packages due to package renaming in RC2 (**Microsoft.Extensions.OptionsModel** -> **Microsoft.Extensions.Options** for instance.)

**Comment by dotnetjunkie** [comment]
Ouch! You are right. Thanks for reporting this.

**Comment by dotnetjunkie** [comment]
Can you try again with [this version](https://www.nuget.org/packages/SimpleInjector.Integration.AspNet/3.1.5-rc2-02)?

**Comment by Asshiah** [comment]
Very strange...

Even thought the requested version seems right for the dependencies, I get versions **6.0.0-beta1** and **6.0.0-beta6**  for **Microsoft.AspNet.Mvc.Core** and **Microsoft.AspNet.Mvc.ViewFeatures** respectively for a project and **6.0.0-rc1-final** for another.

Maybe this is do the the indexing of nuget still beeing in progress.

I'll try again tomorrow.

**Comment by tim-elvidge** [comment]
Hi I tried this and got the same result. On investigation it seems like the name space for  Microsoft.AspNet.Mvc.ViewFeatures has changed in RC2 it is now :-
Microsoft.AspNetCore.Mvc.ViewFeatures 
same issue for Microsoft.AspNet.Mvc.Core goes to:-
Microsoft.AspNetCore.Mvc.Core
hope this helps

**Comment by dotnetjunkie** [comment]
Oh boy! I'm really making a mess out of it. I thought I fixed the NuGet package dependencies in the rc2-02 version, but still screwed up. I just pushed v3.1.5-rc2-03. That package references the Microsoft.AspNetCore packages for rc2.

**Comment by tim-elvidge** [comment]
v3.1.5-rc2-03 looking good - thanks for all the hard work

**Comment by Asshiah** [comment]
Same here looking all good!^^  Thanks for the hard work!
