### ISSUE TITLE
How to log every time an object gets created or disposed by SimpleInjector?

### ISSUE THREAD

**Issue by waynebloss** [simpleinjector/SimpleInjector#239]
During development, I want to basically `Debug.Print` every time any object gets created or disposed by SimpleInjector. What are some ways to do it?

Both [Interception](http://simpleinjector.readthedocs.io/en/latest/advanced.html#interception) and [Decorators](http://simpleinjector.readthedocs.io/en/latest/advanced.html#decorators) seem a little heavy handed for this task.

Is there anything else that I can do, short of adding logging code to every constructor and dispose method?

**Comment by dotnetjunkie** [comment]
You can use the `RegisterInitializer` hook to get notified every time an object gets created. You can use the same hook to register a delegate that gets called when a Scope gets disposed:

``` c#
// This registration has a performance penalty. Only add during debugging
#if DEBUG
container.RegisterInitializer(data => {
        Debug.Print($"Created {data.Context.Registration.ImplementationType}");
    }, 
    c => true);

container.RegisterInitializer(data => {
        Lifestyle.Scoped.GetCurrentScope(container).WhenScopeEnds(() => {
            Debug.Print($"Disposed {data.Context.Registration.ImplementationType}");
        });
    }, 
    c => c.Registration.Lifestyle is ScopedLifestyle &&
        typeof(IDisposable).IsAssignableFrom(c.Registration.ImplementationType));
#endif
```

**Comment by waynebloss** [comment]
Thank you!
