### ISSUE TITLE
Self hosted WCF no docs

### ISSUE THREAD

**Issue by aleha84** [simpleinjector/SimpleInjector#241]
There is no description how to use SimpleInjector with WCF self-hosted as Windows Service.
Page: https://simpleinjector.readthedocs.io/en/latest/wcfintegration.html only illustrate how to use it with IIS and WAS and without any usage examples. Can you provide some best practices how to do it correctly? Thanx.

**Comment by dotnetjunkie** [comment]
Are there any particular problems you are running into while creating a self-hosted WCF service?

**Comment by aleha84** [comment]
Then i'm using some framework i prefer to use it's documentation with examples. If there are no solution provided i'm starting to google it. It spends too much time
WCF self hosted in Windows service is a common practice, and i expected to find solution in SimpleInjector documentation, to use it, because it offered by developer of this framework.

**Comment by dotnetjunkie** [comment]
We do accept pull requests on our documentation. If you have got a working solution, please consider sending us a pull request.
