### ISSUE TITLE
Add adapter implementation for ITagHelperActivator in ASP.NET Core MVC integration package

### ISSUE THREAD

**Issue by Reonekot** [simpleinjector/SimpleInjector#247]
I have an issue getting our ASP.NET Core RC2 application to work correctly. From the sample we add the IControllerActivator and IViewComponentActivator registrations, and call container.RegisterMvcControllers(app); and container.RegisterMvcViewComponents(app);.

But it seems like taghelpers are still resolved from the buildin container, so if we use any application services in taghelpers* they will be resolved by the buildin container and we need to crosswire those graphs used by the taghelpers. :(

Are there any good/known solutions for this currently with SimpleInjector? We had a very quick look at what is in the Microsoft.AspNetCore.Razor.TagHelpers.TagHelper namespace, but couldn't see an easy solution for this.

* (ie. we could have a validated-email, which injects validation rules to the taghelper to name one example, but I know another team has quite a few taghelpers injecting application services.)

**Comment by dotnetjunkie** [comment]
What kind of services do you have in your tag helpers? It feels kinda weird to me to have them depend on your application services, just as you shouldn't inject any dependencies into your views.

**Comment by dotnetjunkie** [comment]
But to be able to let Simple Injector create your tag helpers, there must be an abstraction that allows intercepting the creation of tag helpers, just as there are `IControllerActivator` and `IViewComponentActivator` abstractions. I might be missing something, but this abstraction seems to be missing.

**Comment by Reonekot** [comment]
From my limited research and knowledge it looks like your are right and there seems to missing an abstraction here. I'm not sure if it's because it's in the Razor engine and not per see in MVC itself. I guess it's a feature request for the MVC team, but that will probably not be implemented for RTM.

About the why, I personally do not have the issue yet on our project, but I know another teams has, as their taghelper know about users I think. Fx. they can insert a taghelper which only shows itself if the user has certain permissions or the taghelper knows about tenancy/site segmentation. Unfortunately I'm not in a position to "ban" such usage, as well as I can't ban the @inject keyword in views (as much I want to) company wide - my primary goal though is to get as much as possible to fail on Verify() and make it harder to shoot your self in the foot with captured lifetime dependencies, which is why SimpleInjector is must for our "template" project IMO.

**Comment by dotnetjunkie** [comment]
> I guess it's a feature request for the MVC team

Have you got a link?

> they can insert a taghelper which only shows itself if the user has certain permissions or the taghelper knows about tenancy/site segmentation.

This seems more like a View Component to me.

> @inject keyword in views (as much I want to) 

Yuck! That's an awful practice. I'm not sure why the ASP.NET decided to implement such feature.

For now, I think it is best to use your tag helpers as [Humble Object](http://xunitpatterns.com/Humble%20Object.html) and move all logic that concerns dependencies out of the tag helper, and at most resolve one single service directly from the container (Service Locator).

**Comment by Reonekot** [comment]
I meant that as I think I/we need to make a feature request for it to the MVC team. There is not an issue created I'm aware of, though I haven't looked. It seems like an omission to me that the abstraction is missing it, as the taghelpers do use DI.

About taghelper vs. ViewComponent I'm not sure why the taghelpers are use instead of a ViewComponent - my guess is that there is no real reason except taghelpers are new and cool. ;) I'll have a talk again with the other team and see if there is a good use case for it or it's just an arbitrary decision.

Again thanks for the guidance on this !

**Comment by dotnetjunkie** [comment]
> It seems like an omission to me that the abstraction is missing it, as the taghelpers do use DI.

Absolutely. This is an omission. Since the ASP.NET team was so focussed on their abstraction, that they forgot to add a lot of abstractions. I've already seen this with the `IViewComponentActivator` that was only added in RC2 (after I reported this issue myself) and we will see this again in the future.

Feel free to create that issue on the MVC project and post a link here.

> taghelpers are new and cool.

Yes, I think they are cool actually. They are a real improvement and will make our views much cleaner.

> Again thanks for the guidance on this!

You're welcome.

**Comment by Reonekot** [comment]
Another thing, not complete related - is this still the way to do middleware integration?
https://stackoverflow.com/questions/33002340/replace-activator-for-middleware-in-asp-net-5

**Comment by dotnetjunkie** [comment]
@Reonekot, yes little has changed since I wrote that answer. Difference is that the ASP.NET Core Integration package for MVC now contains a `CrossWire` extension method that makes it easier to cross-wire dependencies from the ASP.NET configuration system.

**Comment by dotnetjunkie** [comment]
I added an issue here: https://github.com/aspnet/Mvc/issues/4869

**Comment by dotnetjunkie** [comment]
There already seems to be an [ITagHelperActivator](https://github.com/aspnet/Mvc/blob/1.0.0-rc2/src/Microsoft.AspNetCore.Mvc.Razor/ITagHelperActivator.cs) abstraction. Problem solved.

**Comment by dotnetjunkie** [comment]
`SimpleInjectorTagHelperActivator` class added to SimpleInjector.Integration.AspNetCore.Mvc NuGet package.
