### ISSUE TITLE
Let Verify fail when a decorator exists for a short circuited dependency

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#248]
The [short circuited dependency](hhttps://simpleinjector.readthedocs.io/en/latest/ShortCircuitedDependencies.html) check will only go off in case the short-circuited dependency has a different lifestyle as the explicit abstraction-based registration. But this doesn't cover the case where a decorator (or other expression replacing mechanism) is applied to the explicit abstraction-based registration.

Example:

``` c#
container.Register<ILogger, MyLogger>();
container.RegisterDecorator<ILogger, LoggerDecorator>();
container.Register<HomeController>();

class HomeController { public HomeController(MyLogger logger) { ... } }
```

Here, the use of `MyLogger` in `HomeController` will cause problems, because we can expect users to expect the `LoggerDecorator` to be applied, while it won't, since it can't be applied to the concrete `MyLogger` type.

**Comment by dotnetjunkie** [comment]
Alternatively to trying to detect whether a given registration got intercepted, the Short Circuited Dependencies warning could also be made more strict, so that it fails whenever there is an explicit registration, instead of only when the lifestyle of the concrete unregistered type (typically `transient`) doesn't match with the explicit registration.

Such change is much easier to make and safer to do (less chance of getting false-positives), but is on the other hand a bigger breaking change, since it can cause more configurations to fail, while there is no real problem.

**Comment by qujck** [comment]
In the past I have relied on the ability to retrieve the undecorated instance (I can't recall the exact purpose at the time but it was related to database activity and the underlying implementation had an *extra*/*hidden* method that was available to an event that was triggered elsewhere in the transaction. Any change to the container would break that solution.

**Comment by dotnetjunkie** [comment]
> A change to the container could break that solution.

Yes, a change to this diagnostic rule would case the container to throw more often, and might cause an exception in your particular case as well, but you can suppress this by making the registration explicitly.

**Comment by TheBigRic** [comment]
> The short circuited dependency check will only go off in case the short-circuited dependency has a different lifestyle than the explicit abstraction-based registration

Correct me if I'm wrong but is this (existing) behavior useful at all? I guess if the short circuited dependency diagnostic result is only thrown in this case, it doesn't add anything except a useful message, because this should also throw a ambigious lifestyle mismatch? Is there a scenario where the short circuited dependency diagnostic result is thrown in its own?

That being said I think the diagnostic result should throw in case of an applied decorator and ofcourse @qujck is correct, this is a breaking change. But as you explained to me when v3 went live, every change in the diagnostic subsystem has become a breaking change since we throw these when verifying the container. 

Nevertheless this is a bug IMO and thus should be fixed.

**Comment by dotnetjunkie** [comment]
> it doesn't add anything except a useful message, because this should also throw a ambigious lifestyle mismatch?

Correct. This lifestyle is a mix of an Ambiguous Lifestyle and a Container-Registered Component. I think the Ambiguous Lifestyle warning has been added at a later point in time, and is a superset o the Short Circuited Dependency (I'm not sure I ever realized this). This does make the Short Circuited Dependency warning itself ambiguous :-). It could be removed without breaking any applications (although the warning message could be useful).

So in its current form, this warning isn't useful. So it should either be removed or fixed. There are two possible fixes: we make sure that it warns when decorators get applied, or we also warn in the case of equal lifestyles. Both options are breaking changes. The latter might possibly affect more users than the former does; it could cause more false-positives.

**Comment by TheBigRic** [comment]
> we also warn in the case of equal lifestyles

Does this really add something, because isn't this the same as Torn Lifestyle?

So the question is does the Ambiguous and Torn lifestyle warnings incorporate decorators? And if not, is it possible to add this? That would make the Short Circuited dependency obsolete.

**Comment by dotnetjunkie** [comment]
> So the question is does the Ambiguous and Torn lifestyle warnings incorporate decorators?

The following configuration will cause an Ambiguous Lifestyles error:
``` c#
container.Register<ILogger, MyLogger>(Lifestyle.Scoped);
container.RegisterDecorator<ILogger, LoggerDecorator>(Lifestyle.Transient);
container.Register<MyLogger>(Lifestyle.Transient);
container.Verify();
```
The following will cause a Torn Lifestyle warning:
``` c#
container.Register<ILogger, MyLogger>(Lifestyle.Scoped);
container.RegisterDecorator<ILogger, LoggerDecorator>(Lifestyle.Transient);
container.Register<MyLogger>(Lifestyle.Scoped);
container.Verify();
```
So to answer your question: yes, they work independently of whether decorators are applied or not.

> Does this really add something, because isn't this the same as Torn Lifestyle?

What this adds is that the error will pop up more often, because typically you don't want to have short-circuited dependencies, even if both the registration for the abstraction and the unregistered concrete type are transient. So adding this prevents that possible misconfigurations stay unnoticed, because of any transformations or interception that might take place. For instance, we might explicitly check for decorators, but any type of transformation (using ExpressionBuilt) could have taken place. It might be tricky to detect them and it might be hard to communicate proper error messages.

**Comment by TheBigRic** [comment]
> What this adds is that the error will pop up more often

In that case it seems valuable.

> yes, they work independently of whether decorators are applied or not

Yes independently, but what I meant was: Does the check take the decorator into account including it's lifestyle. But it doesn't, because otherwise this config should throw an Ambigious Lifestyle and not a Torn Lifestyle.

``` c#
container.Register<ILogger, MyLogger>(Lifestyle.Scoped);
container.RegisterDecorator<ILogger, LoggerDecorator>(Lifestyle.Transient);
container.Register<MyLogger>(Lifestyle.Scoped);
container.Verify();
```

I think however, especially with the possible changes in ExpressionBuilt, catching 100% is impossible.

**Comment by dotnetjunkie** [comment]
I decided to implement the strict behaviour, i.e. a short circuited dependency is always reported, even though both the unregistered and the registered type have the same lifestyle. This will cause the warning to go off when with Transient registrations and decorators, which gives the user a very clear description of what is going on.
