### ISSUE TITLE
v3.1.5 not playing well with Code Analysis in Visual Studio

### ISSUE THREAD

**Issue by wbokkers** [simpleinjector/SimpleInjector#249]
When performing a code analysis in Visual Studio 2015 update 2, I get some obscure CA0001 error in the registration code of my UWP (!) project.

I mainly register singletons and do Verify (in debug builds). Nothing fancy. For one singleton registration I use an instance creator as argument.

Reverting back to v3.1.4 solves this problem.

**Comment by dotnetjunkie** [comment]
Can you show the code that causes the error?

**Comment by wbokkers** [comment]
`  private void ConfigureContainer()
        {
            _container.RegisterSingleton<IViewService>(
                () => // created on demand
                {
                    var nav = new ViewService(RootFrame);
                    nav.Configure(Constants.MainPageKey, typeof(MainPage));
                    nav.Configure(Constants.UserStatusPageKey, typeof(UserStatusPage));
                    nav.Configure(Constants.StartPageKey, typeof(StartPage));
                    return nav;
                });

            _container.RegisterSingleton<IDialogService, DialogService>();
            _container.RegisterSingleton<IDeviceService, DeviceService>();
            _container.RegisterSingleton<IUserSessionSettings, UserSessionSettings>();
            _container.RegisterSingleton<IPushRegistration, PushRegistration>();
            _container.RegisterSingleton<IUserSession, UserSession>();
            _container.RegisterSingleton<IRestHttp, RestHttp>();
            _container.RegisterSingleton<IRestClient, RestClient>();
            _container.RegisterSingleton<IInternetConnection, InternetConnection>();
            _container.RegisterSingleton<IAddressableIconProvider, AddressableIconProvider>();
            _container.RegisterSingleton<XelionAppContext>();

            // No need to register concrete types (except for singleton instances!)
        
#if DEBUG
            _container.Verify();
#endif
        }`

**Comment by dotnetjunkie** [comment]
The CA0001 error [seems to be](https://msdn.microsoft.com/en-us/library/ms245246.aspx) the default code analysis error when there is an internal error (a bug) in the code analysis engine itself:

> An exception was raised within managed code analysis tool that does not indicate an expected error condition.

Nothing much has changed between 3.1.4 and 3.1.5 concerning the API, so I have no idea why this happens, but if you Google, you'll see that others experiencing these issues as well. [This issue](https://stackoverflow.com/questions/13893570/visual-studio-code-analysis-ca0001-error-running-code-analysis-object-referen) seems to indicate that it might be possible to rewrite the code that CA is tripping over.

I'm afraid that there's not much we can do from perspective of Simple Injector; we can't work around bugs in Code Analysis tools.

**Comment by wbokkers** [comment]
I submitted this issue using the feedback option in Visual Studio. Hopefully it will be sorted out at MS some day. Thanks for looking into this problem!

**Comment by wbokkers** [comment]
FYI, the issue is 'caused' by using RegisterSingleton with an instance creator. I tried rewriting the code by using a function instead of a lambda and by using a local variable of type Func<IViewService>. To no avail, unfortunately.
The complete error message is:
Error CA0001 : An error was encountered while parsing IL for method: '....ConfigureContainer', instruction at offset '0x2D' with opcode 'Callvirt'.
