### ISSUE TITLE
Looking for hook using SqlFileStream

### ISSUE THREAD

**Issue by mpaul31** [simpleinjector/SimpleInjector#250]
i've been racking my brain on this and i'm hoping someone can help me here. i am trying to use the SqlFileStream within a web api method and one of the requirements is a database transaction must be open and commited in order for this to work. i am trying to figure out where i can hook into this with simple injector. i am already using a ef dbcontext as a web api request lifestyle, so i need a hook to begin the transaction and commit the transaction or rollback the transaction if an error occurs. since this is streaming content i need to commit or rollback this at the last possible moment of the response since this is using a StreamConent.

any help would be great!

**Comment by dotnetjunkie** [comment]
The solution is to leave such behavior completely out of your composition root. Place.this logic behind an abstraction and implement an adapter or decorator that adds transactional logic.

**Comment by mpaul31** [comment]
i tried a custom action filter and this was to early in the game to commit the transaction since the streaming is still going on after the action completes.

**Comment by dotnetjunkie** [comment]
If you're more specific and post the relevant code, we m8ght be able to comment on your current design to help to improve it.

**Comment by TheBigRic** [comment]
Can you share some code with us? Using the current information it is quite hard to give some good advice. I guess you use something like:

``` c#
using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
     var uploadTask = await someStreamContentInstance.CopyToAsync(someSqlFileStreamInstance);
    
     scope.Complete();
}
```

And if you do it like this, what is the problem you're running into?
