### ISSUE TITLE
How to inject a configuration section?

### ISSUE THREAD

**Issue by uchinago** [simpleinjector/SimpleInjector#252]
I am trying to inject a complete configuration setting custom section but can't seem to get it just right.

Registering and calling the configuration from inside the class works just fine however, we want to inject and not have that dependency on the app.config file.

``` c#
_container.Register<IKyuTransport, ActiveMQTransport>();

public class ActiveMQTransport : IKyuTransport
{
    public ActiveMQTransport() // ...     works
}

_container.RegisterInitializer<ActiveMQTransport>(mq => { mq.Address = config.queue.Server });
public class ActiveMQTransport : IKyuTransport
{
   public ActiveMQTransport(Inbound config) // ..  <-- how do we inject this concrete object?
   {
           // Create connection using connectionFactory
    }
}
```

The `Inbound` is configuration data that is constant during the application lifecycle.  I would expect that the application be restarted if this information was to change. Basically it is a POCO that has information in its simplest form as Queue Server, Queue Name which the transport layer then uses to make a connection and subscription to the queue system to process. No application behavior as this is in the business interface that is called.

Sure it is possible, but can't see it right now.

**Comment by dotnetjunkie** [comment]
What is this `Inbound` object? Is this runtime data (that might change on a per-request basis), is it some configuration data that stays constant during the lifetime of the AppDomain, or is this some component with contains application behavior?

**Comment by uchinago** [comment]
It is configuration data that is constant during the application lifecycle.  I would expect that the application be restarted if this information was to change.   Basically it is a POCO that has information in its simplest form as Queue Server, Queue Name which the transport layer then uses to make a connection and subscription to the queue system to process.    No application behavior as this is in the business interface that is called.

**Comment by dotnetjunkie** [comment]
In that case, you should register a simple delegate for the construction of your `ActiveMQTransport` class:

``` c#
Inbound config = new Inbound { ... };
_container.Register<IKyuTransport>(() => new ActiveMQTransport(config));
```

And if the `ActiveMQTransport` class is thread-safe, consider registering it as singleton:


``` c#
Inbound config = new Inbound { ... };
_container.RegisterSingleton<IKyuTransport>(new ActiveMQTransport(config));
```

**Comment by uchinago** [comment]
Thanks.   I new I was just missing something.   Still trying to make DI more of a standard practice for my coding and SimpleInjector is outstanding.
