### ISSUE TITLE
SimpleInjector and Rebus

### ISSUE THREAD

**Issue by stevengopmo** [simpleinjector/SimpleInjector#253]
Hi,

I feel like I've had this discussion with you guys many times before, but can not find the evidence so here it is again.

We use Rebus and SimpleInjector in our projects quite extensively but because of some oddities for previous versions of both components (probably just oddities in me), we've never used Rebus & SimpleInjector together in our Windows Service projects.  I am trying to fix that now.  The problem that I am having is getting my head around Scoping.

When Rebus messages come in, I want to inject a RavenDB Session object.  The session object should be per incoming message as I use some details in the header to determine which database to connect to.  To make this work I've tried the following

``` c#
_container = new Container();
_container.Options.DefaultScopedLifestyle = new ExecutionContextScopeLifestyle();

_container.Register<SomeDisposableClass>(Lifestyle.Scoped);

_container.RegisterCollection(typeof(IHandleMessages<>), Assembly.GetExecutingAssembly());
_container.RegisterDecorator(typeof(IHandleMessages<>), typeof(LifetimeScopeDecorator<>));

```

`LifetimeScopeDecorator` is just a class to start the scope

``` c#
    public class LifetimeScopeDecorator<TMessage> : IHandleMessages<TMessage>
    {
        private readonly Container _container;
        private readonly IHandleMessages<TMessage> _decorated;
        public LifetimeScopeDecorator(Container container, IHandleMessages<TMessage> decorated)
        {
            _container = container;
            _decorated = decorated;
        }

        public async Task Handle(TMessage message)
        {
            using (_container.BeginExecutionContextScope())
            {
                await _decorated.Handle(message);
            }
        }
    }
```

The error I get is 
`The SomeDisposableClass is registered as 'Execution Context Scope' lifestyle, but the instance is requested outside the context of a Execution Context Scope.`

I'm sure this is something really obvious, but can't for the life of me get my head around it.

**Comment by dotnetjunkie** [comment]
You should change your `IHandleMessages<TMessage>` dependency in your decorator to a 
`Func<IHandleMessages<TMessage>>` dependency. That would solve your problem, because the Func will ensure that SI will resolve the decoratee when you call that Func (which should be inside the scope).

**Comment by stevengopmo** [comment]
D'OH!  Of course that was it.  I guess I didn't fully understand it what I was doing.  Let's see if I do now.

The error was occurring because in order to correctly create the LifetimeScopeDecorator it was resolving the message handler even though I had not started the execution scope yet.  By changing it to a Func<>, SI is smart enough to pass the delegate instead of the resolved handler and I can resolve as needed inside the scope.

Is that correct?

**Comment by dotnetjunkie** [comment]
Yes, that's correct.

**Comment by stevengopmo** [comment]
Thanks!

**Comment by stevengopmo** [comment]
@dotnetjunkie sorry to revisit this, but I realized that my decorators are not getting applied using this technique.  My registration looks like the first post in this issue, and I'm using the updated LifetimeScopeDecorator.  Here's the updated registrations code

````
            var container = new Container();
            container.Options.DefaultScopedLifestyle = new ExecutionContextScopeLifestyle();

            //regsiter all the query handlers
            container.Register(typeof(IHandleQueryAsync<,>),
                assembliesToScan);

            //Register decorators - order is important.
            container.RegisterDecorator(
                typeof(IHandleQueryAsync<,>),
                typeof(ValidationQueryHandlerDecorator<,>));

            //regsiter the decorator that logs total time
            container.RegisterDecorator(
                typeof(IHandleQueryAsync<,>),
                typeof(TotalTimeQueryHandlerDecorator<,>));

            container.RegisterCollection(typeof(IHandleMessages<>), Assembly.GetExecutingAssembly());
            container.RegisterDecorator(typeof(IHandleMessages<>), typeof(LifetimeScopeDecorator<>));

````

the `var decoratee = _decorateeFactory.Invoke();` resolves to the actual queryhandler with no decorators.

**Comment by dotnetjunkie** [comment]
Using the following program:

``` c#
public interface IHandleMessages<M> { }

internal class Program
{
    private static void Main(string[] args)
    {
        var container = new Container();
        container.Options.DefaultScopedLifestyle = new ExecutionContextScopeLifestyle();

        Assembly[] assembliesToScan = new[] { typeof(Program).Assembly };

        container.RegisterCollection(typeof(IHandleMessages<>), Assembly.GetExecutingAssembly());
        container.RegisterDecorator(typeof(IHandleMessages<>), typeof(DecoratorA<>));
        container.RegisterDecorator(typeof(IHandleMessages<>), typeof(DecoratorB<>));
        container.RegisterDecorator(typeof(IHandleMessages<>), typeof(LifetimeScopeDecorator<>));

        dynamic h1 = container.GetAllInstances<IHandleMessages<object>>().First();

        Console.WriteLine(h1.GetType().Name);

        dynamic h2 = h1.DecorateeFactory();

        Console.WriteLine(h2.GetType().Name);

        Console.WriteLine(h2.Decoratee.GetType().Name);
        Console.WriteLine(h2.Decoratee.Decoratee.GetType().Name);

        Console.ReadLine();
    }
}

public class ObjectHandler : IHandleMessages<object> { }

public class DecoratorA<M> : IHandleMessages<M>
{
    public DecoratorA(IHandleMessages<M> decoratee) { Decoratee = decoratee; }
    public IHandleMessages<M> Decoratee { get; }
}
    
public class DecoratorB<M> : IHandleMessages<M>
{
    public DecoratorB(IHandleMessages<M> decoratee) { Decoratee = decoratee; }

    public IHandleMessages<M> Decoratee { get; }
}

public class LifetimeScopeDecorator<M> : IHandleMessages<M>
{
    public LifetimeScopeDecorator(Func<IHandleMessages<M>> decorateeFactory) { DecorateeFactory = decorateeFactory; }

    public Func<IHandleMessages<M>> DecorateeFactory { get; }
}
```

I get the following output:

```
LifetimeScopeDecorator`1
DecoratorB`1
DecoratorA`1
ObjectHandler
```

Might it be that you're doing something wrong? Do note that the `ValidationQueryHandlerDecorator<,>` will not be wrapped around an `IHandleMessages<T>` because it is registered for an `IHandleQueryAsync<,>`.

**Comment by stevengopmo** [comment]
> Might it be that you're doing something wrong?

HAHA!  yes of course, that's why I'm here. :)

> Do note that the ValidationQueryHandlerDecorator<,> will not be wrapped around an IHandleMessages<T>

Arghhh!  I KNEW that, and usually I am injecting `IHandleQueryAsync<,>` into my message handler, but didn't in this case.  You are the MAN!
