### ISSUE TITLE
Issue with parameterless constructor in Umbraco

### ISSUE THREAD

**Issue by simoazzo** [simpleinjector/SimpleInjector#258]
Hi Guys,

I am facing an issue similar to this: http://www.devtrends.co.uk/blog/using-unity.mvc5-and-unity.webapi-in-umbraco

For such controllers in umbraco, related to the CMS, the resolving such controllers, it is preferring the paramterfilled constructors, causing the below error:

Failed to retrieve data for child nodes undefined

`An error occurred when trying to create a controller of type 'ContentController'. Make sure that the controller has a parameterless public constructor.`

Using Unity, as described in the above reference link, doing the following, will save such issue:

`container.RegisterType<LegacyTreeController>(new InjectionConstructor());`

So in order to solve my issue, when using SimpleInjectorMVC In Umbraco, what is the quivalent of the above code for SimpleInjector?

Thank you in advance.

Kind Regards

**Comment by dotnetjunkie** [comment]
I think the problem is different in your case. Typically you will have either replace the `IDependencyResolver` abstraction. I'm unfamiliar with Umbraco, but if it's built on top of ASP.NET MVC, you'll need to use the Simple Injector MVC integration package as described [here](https://simpleinjector.readthedocs.io/en/latest/mvcintegration.html).

If this doesn't work, please let me know and show your complete configuration.

**Comment by simoazzo** [comment]
Hi,

Thank you for your reply.

I am using it, the Simple Injector MVC integration package.

This is my code:

```
// This is an extension method from the integration package.
            container.RegisterMvcControllers(Assembly.GetExecutingAssembly());

            container.RegisterWebApiControllers(configuration, assemblies);


            // This is an extension method from the integration package as well.
            container.RegisterMvcIntegratedFilterProvider();


            container.Verify();
            DependencyResolver.SetResolver(new SimpleInjectorDependencyResolver(container));
           
            configuration.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(container);
```

I have custom classes extending the ApiController, which is working fine, but when going to the Umbraco Administration (CMS) since it has back office apis, they are giving me errors because such api controllers (I know from the source code of Umbraco) has multiple constructors, and like Unity, I think it is preferring the parameters constructor.

**Comment by simoazzo** [comment]
And the Constructors for ContactController (extending eventaully the ApiController) has the following constructors:

```
/// <summary>
        /// Constructor
        /// </summary>
        public ContentController()
            : this(UmbracoContext.Current)
        {            
        }

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="umbracoContext"></param>
        public ContentController(UmbracoContext umbracoContext)
            : base(umbracoContext)
        {            
        }
```

**Comment by dotnetjunkie** [comment]
This `ContentController` is this your code, or code from Umbraco that you can't change?

**Comment by simoazzo** [comment]
The ContentController is not my code, it is code from Umbraco that I cannot change.

**Comment by dotnetjunkie** [comment]
In that case you will have to override Simple Injector's constructor resolution behavior, as described [here](https://simpleinjector.readthedocs.io/en/latest/extensibility.html#overriding-constructor-resolution-behavior).

Example:

``` c#
public class UmbracoConstructorBehavior : IConstructorResolutionBehavior {
    public IConstructorResolutionBehavior DefaultBehavior { get; set; }
    public ConstructorInfo GetConstructor(Type serviceType, Type implementationType) {
        return implementationType.Assembly.FullName.Contains("Umbraco")
            ? GetUmbracoConstructor(serviceType, implementationType)
            : DefaultBehavior.GetConstructor(serviceType, implementationType);
    }

    private static ConstructorInfo GetUmbracoConstructor(Type s, Type i) => (
        from ctor in i.GetConstructors() orderby ctor.GetParameters().Length select ctor)
        .FirstOrDefault() ?? DefaultBehavior.GetConstructor(s, i);
}

// Usage
var container = new Container();
container.Options.ConstructorResolutionBehavior = new UmbracoConstructorBehavior {
    DefaultBehavior = container.Options.ConstructorResolutionBehavior
};
```

**Comment by simoazzo** [comment]
Hi dotnetjunkie,

I have tested it out but for the `ContentController`, which has two constructors, it is still giving me an error:

![image](https://cloud.githubusercontent.com/assets/19478530/16303186/bcef73d8-394f-11e6-9b44-c353a5c110b4.png)

**Comment by dotnetjunkie** [comment]
I bet that the assembly that the `ContentController` contains is does not contain the name "Umbraco". This was just a wild guess of mine. Instead of using the following predicate:

``` c#
implementationType.Assembly.FullName.Contains("Umbraco")
```

You could try something like this:


``` c#
implementationType.Namespace.Contains("Umbraco")
```

But please do check how you can distinquish Umbraco controllers from your application components (that [always should have a single constructor](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=97)). If you found the right solution, please post it here; this might help others with the same problem.

**Comment by aclave1** [comment]
Steven's latest answer did the trick for me. I had to modify it slightly to work with the newest version of simpleinjector:

```
public class UmbracoConstructorBehavior : IConstructorResolutionBehavior
    {
        public IConstructorResolutionBehavior DefaultBehavior { get; set; }
        public ConstructorInfo GetConstructor(Type implementationType)
        {
            return implementationType.Namespace.Contains("Umbraco")
                ? GetUmbracoConstructor(implementationType)
                : DefaultBehavior.GetConstructor(implementationType);
        }

        private ConstructorInfo GetUmbracoConstructor(Type i) => (
            from ctor in i.GetConstructors() orderby ctor.GetParameters().Length select ctor)
            .FirstOrDefault() ?? DefaultBehavior.GetConstructor(i);
    }
```
