### ISSUE TITLE
Split SimpleInjector.Integration.AspNet into two separate packages.

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#259]
The current `SimpleInjector.Integration.AspNet` integration package contains both general ASP.NET Core integration points and ASP.NET Core MVC specific integration points. Splitting the package into two seperate packages SimpleInjector.Integration.AspNetCore and SimpleInjector.Integration.AspNetCore.Mvc makes sense (where MVC depends on Core), because ASP.NET Core is much larger than just MVC. Not splitting this, while the application itself doesn't use MVC, will cause the application footprint to increase, since many more DLLs will be included (the complete MVC stack).

With this change, we can also rename the package from `AspNet` to `AspNetCore`, which seems to be the final name of the name framework.

**Comment by Asshiah** [comment]
This would make sense^^

**Comment by Asshiah** [comment]
In the new packages, there does not seem to have a `SimpleInjectorControllerActivator` or a `SimpleInjectorControllerActivator` class anymore.

Is it gone? Is there any replacement or is there no need for it anymore?

**Comment by dotnetjunkie** [comment]
Please update your packages to 3.2.3.

**Comment by Asshiah** [comment]
Perfect!^^

**Comment by dotnetjunkie** [comment]
Packages are named:
 * SimpleInjector.Integration.AspNetCore
 * SimpleInjector.Integration.AspNetCore.Mvc
