### ISSUE TITLE
'IServiceCollection' does not contain a definition for 'AddInstance'  with "3.1.5-rc2-07"

### ISSUE THREAD

**Issue by zhshqzyc** [simpleinjector/SimpleInjector#260]
Basically I created a asp.net core web api. Then installed the framework from [here.](https://www.nuget.org/packages/SimpleInjector.Integration.AspNet).

But there is an error in the service configuration.

``` c#
public void ConfigureServices(IServiceCollection services)
{
    // Add framework services

    services.AddMvc();

    services.AddInstance<IControllerActivator>(
        new SimpleInjectorControllerActivator(container));

    services.AddInstance<IViewComponentInvokerFactory>(
        new SimpleInjectorViewComponentInvokerFactory(container));
}
```

I post the zipped project at [one drive](https://onedrive.live.com/?id=3A8BB9EAEEFF1DB%215366&cid=03A8BB9EAEEFF1DB).

What I missed?
Thanks for help.

**Comment by dotnetjunkie** [comment]
That's an error in the documentation. Replace `AddInstance` with `AddSingleton`.

**Comment by dotnetjunkie** [comment]
You are using the extension method naming as it was in RC1. In .NET Core RC2 this name has been changed to `AddSingleton`. [The documentation](https://simpleinjector.org/aspnetcore) shows the right methods.

**Comment by zhshqzyc** [comment]
Hi, I made the change again by the documentation. But I still have the error SimpleInjectorViewComponentActivatory can't be found.

**Comment by dotnetjunkie** [comment]
Did you make a typo somewhere? The class is named `SimpleInjectorViewComponentActivator`, not `SimpleInjectorViewComponentActivatory`. You might also miss the namespace and make sure that you actually included the NuGet package that contains this file.
