### ISSUE TITLE
NuGet Version 3.2.0 cannot be added to MonoAndroid,Version=v6.0

### ISSUE THREAD

**Issue by ghost** [simpleinjector/SimpleInjector#262]
Starting with 3.2.0-beta1 I cannot add SimpleInjector via NuGet to my Xamarin.Android application.

**Comment by dotnetjunkie** [comment]
What is the error you get from the NuGet package manager?

**Comment by af-mvo** [comment]
> Could not install package 'SimpleInjector 3.2.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by dotnetjunkie** [comment]
Did this work before in older versions? I'm unsure whether we ever supported MonoAndroid.
