### ISSUE TITLE
Create a version with a stripped down API with only .NET Native compatible features

### ISSUE THREAD

**Issue by FatJohn** [simpleinjector/SimpleInjector#264]
after compileing. I see these compile warning
1. ILTransform_0017: Assembly 'SimpleInjector' requests the address of the virtual method 'Type.IsAssignableFrom(Type)' which is not available in the targeted .NET platform. Please ask the author of 'SimpleInjector' to provide an implementation that can be used in the currently targeted .NET platform.
2. ILTransform_0027: Invalid IL detected in method 'System.Void System.Progress.InvokeHandlers(System.Object)' at IL offset 0x1
3. ILTransform_0027: Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not be found.

although it seems working fine in my project.

**Comment by dotnetjunkie** [comment]
.NET Native only supports a subset of .NET and especially a lot of redlection based features are not supported, which is what DI libraries do under the covers.

To prevent these warnings we need to create a special stripped down version of Simple Injector for .NET Native that contains a subset of the complete Simple Injecto API. This would also prevent you from calling unsupported methods (like batch registration).

But for now, as long as you only call methods that work under Native, you'll be fine.

**Comment by FatJohn** [comment]
got it~ thanks~

**Comment by MattWhilden** [comment]
I work on the .NET Native runtime and compiler team. If you get around to this and notice anything "odd" or "painful" we'd love to get your feedback. Feel free to mail us at dotnetnative@microsoft.com. Happy to help.

I have a feeling I've posted this in another issue here but it doesn't hurt to repeat myself :-)

**Comment by dotnetjunkie** [comment]
This issue is related to https://github.com/simpleinjector/SimpleInjector/issues/162

**Comment by dotnetjunkie** [comment]
We won't be creating a stripped-down version of Simple Injector for .NET Native. .NET Native is too limited for any DI Container to run. .NET Native applications are better off using [Pure DI](https://blog.ploeh.dk/2014/06/10/pure-di/).
