### ISSUE TITLE
SimpleInjector.Integration.Web.Mvc NuGet package missing net40 libraries

### ISSUE THREAD

**Issue by eddiepaz** [simpleinjector/SimpleInjector#267]
Seems this package only has net45 libraries. An oversight or no longer supporting MVC4?

**Comment by dotnetjunkie** [comment]
This is an oversight. The NuGet package references ASP.NET MVC 3 3.0.20105.1,  which is compatible with .NET 4.0. Our integration package should be compatible with .NET 4.0 as well.

**Comment by dotnetjunkie** [comment]
We just pushed [version 3.2.1](https://www.nuget.org/packages/SimpleInjector.Integration.Web.Mvc/3.2.1) of the SimpleInjector.Integration.Web.Mvc NuGet package. This version re-adds net40 support.
