### ISSUE TITLE
Register Container with multiple interfaces

### ISSUE THREAD

**Issue by benjaminadrom** [simpleinjector/SimpleInjector#269]
Is it possible with "Simple Injector" to register a container with multiple Interfaces?
somehow like this:

```
var container = new Container();
container.Register<List<?>{ITemplateTest , IEmailAnalyzerProvider }, TestController>(Lifestyle.Scoped);
```
and the controller would look like this:

```
public class TestController: ApiController
{
        private readonly ITemplateTest _TemplateTestClient;
        private readonly IEmailAnalyzerProvider _EmailAnalyzerProvider;

        public TestController(ITemplateTest TemplateTestClient, IEmailAnalyzerProvider EmailAnalyzerProvider)
        {
            this._TemplateTestClient = TemplateTestClient;
            this._EmailAnalyzerProvider = EmailAnalyzerProvider;
        }
}
```

OR:

How to use "SimpleInjector" with a static class, they don't have constructor with parameters...

**Comment by dotnetjunkie** [comment]
I'm sorry, I don't understand your question. Could you show how you would construct your

**Comment by benjaminadrom** [comment]
The "TestController" (which is non-static like in the example above ) is not actively called.
But the "TestController" does have a Method which uses another class (static).

But i would like to use the "Simple Injector" with this static class.

**Comment by dotnetjunkie** [comment]
> But i would like to use the "Simple Injector" with this static class.

You can't. Dependency Injection does not work with static classes, and DI library require the creation of types; a static type can't be created.

**Comment by benjaminadrom** [comment]
Hmm okay this means the static class has to be a non-static class in order to use it?
When i change it to non-static, how do i instantiate this class, 
i ask this because i dont know what to use as parameter (this would be  Interface)

```
public class EmailAnalyzerHelper
    {
        private readonly IEmailAnalyzerHelper _EmailAnalyzerHelper;

        public EmailAnalyzerHelper(IEmailAnalyzerHelper EmailAnalyzerHelper)
        {
            this._EmailAnalyzerHelper = EmailAnalyzerHelper;
        }

        public RequestResult<AnalyzeReport> Analyze(AnalyzeRequest request)
        {
            return this._EmailAnalyzerHelper.Analyze(request);
        }
    }
```

How would i call this class? referencing to the constructor

**Comment by dotnetjunkie** [comment]
You might want to take a step back and explain what it is you are trying to do. This is unclear to me. For instance, why do you have a class with the name `EmailAnalyzerHelper` that does nothing more than forward the call to an abstraction with seemingly the same contract? What code you wish to call in your controller?

**Comment by benjaminadrom** [comment]
Sorry for the unintelligibilities :)

Global.asax

```
var container = new Container();
container.Register<ITemplateTest, TemplateTestMock>(Lifestyle.Scoped);
container.Register<MyInterface, MailHelper>(Lifestyle.Scoped);
```
_____________

Class **MailHelper**
```
public class MailHelper
{
     private readonly IMyInterface _MyInterface;
     public MailHelper(IMyInterface MyInterface)
     {
        this._MyInterface = MyInterface;
     }

     public GetMails()
     {
          return new List<string>{"A", "B"};
     }

}
```
_________
Class **Mail**
```
public class TemplateTestController : ApiController
{
public IHttpActionResult GetMails()
        {
           var _mailHelper = new MailHelper(); // <--- WHAT AM I SUPOSED TO USE HERE AS A PARAM?
            var result = _mailHelper .GetMails();            
            return Ok(result);
        }
}
```
_________

In the Mail-Class i call "new MailHelper()" but it supposed to have a parameter,
so how would i instantiate this Helper class?

**Comment by dotnetjunkie** [comment]
Ahh I see. You should let your controller have a constructor argument of type `MailHelper`, just like the mailhelper ctor has its dependencies. This allows you to build 'object graphs' of many levels deep.

**Comment by benjaminadrom** [comment]
Sorry but i can't follow your Answer, would you be so kind to serve a tiny example please?

**Comment by dotnetjunkie** [comment]
Change your `TemplateTestController` to the following:

``` c#
public class TemplateTestController : ApiController {
    private readonly ITemplateTest _TemplateTestClient;
    private readonly MyInterface _MailHelper;

    public TemplateTestController(ITemplateTest TemplateTestClient, MyInterface MailHelper) {
        this._TemplateTestClient = TemplateTestClient;
        this._MailHelper = MailHelper;
    }

    public IHttpActionResult GetMails() {
        var result = _MailHelper.GetMails();            
        return Ok(result);
    }
}
```

**Comment by benjaminadrom** [comment]
Thank you!
I see, so this is way the same as my example code above, but what should go inside the "Global.asax"

```
var container = new Container();
container.Register<ITemplateTest, TemplateTestMock>(Lifestyle.Scoped);
```
Does not work because the "MailHelper" is missing, so i dont know how to achive this

**Comment by dotnetjunkie** [comment]
Your `MailHelper` doesn't seem to implement an interface, this means you'll need to register it as follows:

``` c#
container.Register<MailHelper>(Lifestyle.Scoped);
```

Or perhaps even simply:

``` c#
container.Register<MailHelper>();
```

**Comment by benjaminadrom** [comment]
But so doesn't my "TemplateTestController"?

Could not compile:

The constructor of type TemplateTestController contains the parameter with name 'MailHelper' and type MyInterface  that is not registered. Please ensure MyInterface  is registered, or change the constructor of TemplateTestController.

I guess this  is because in Global.asax i am calling

```
container.Register<ITemplateTest, TemplateTestMock>(Lifestyle.Scoped);
container.Register<MailHelper>(Lifestyle.Scoped);
```

Is it missing in the first "container.Register" the "MyInterface" ?

**Comment by dotnetjunkie** [comment]
It completely depends on what you need. What is this `MyInterface` interface. It seems to exist, but is this interface meant to be the abstraction for `MailHelper` or not? If it is meant to be, you should:

 - Let `MailHelper` implement `MyInterface`.
 - Register `MailHelper` in Simple Injector by its interface, i.e. `container.Register<MyInterface, MailHelper>();`
 - Let `TemplateTestController` depend on `MyInterface` in its constructor (as it does now).

In case `MyInterface` is unrelated to `MailHelper`, you should:

 - Let `TemplateTestController` depend on `MailHelper` in its constructor (instead of `MyInterface`).

**Comment by benjaminadrom** [comment]
Hm, let me redraft my question :)

When i hav inside my Global.asax this
```
container.Register<ITemplateTest, TemplateTestMock>(Lifestyle.Scoped);
container.Register<MyInterface, MailHelper>(Lifestyle.Scoped);
```

I am never going to call "TemplateTestMock"-Controller manually (only via url:  ".../api/TemplateTestMock/FooBar").
BUT
I want to call INSIDE the "TemplateTestMock", in a method, the "MailHelper"-Class to call a method of "MailHelper"

```
public IHttpActionResult GetMails() {
        var mailhelper = new MailHelper(????);
        var result = mailhelper .GetMails();
        return Ok(result);
    }
```

What is here the right way to call "new MailHelper(??)", what is supposed to be inside the parenthesis?

Regards

**Comment by dotnetjunkie** [comment]
It's unclear what it is you are trying to achieve? Why do you want to new up this `MailHelper` instead of letting it be injected by Simple Injector, and what do you want to inject into it? What is stopping you from injecting the `IMyInterface` into the `TemplateTestController`'s constructor and passing it on to the `MailHelper` constructor inside the `GetMails` method?

**Comment by benjaminadrom** [comment]
What i try to achive is that **both** **classes** get **registered** via "container.Register(...)", and i want to be able to use the "**MailHelper**"-Class inside the "**TemplateTest**"-Controller.

To do that i should somehow define it inside of "**Global.asax**".
(these registrations register it with classes which implements separate interfaces, MailHelper <--> MyInterface & TemplateTest <--> ITemplateTest )

But inside of "**MailHelper**"-Class there is a **constructor injection**.

So how would i call this **MailHelper**"-Class inside of **TemplateTest**"-Controller?
