### ISSUE TITLE
Xamarin.Forms.Android Release Mode Binding Warnings

### ISSUE THREAD

**Issue by BCSATX** [simpleinjector/SimpleInjector#27]
Howdy,

I'm getting the following warning when I build.  This just started happening out of no where.  Not sure what would have triggered it.  

Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: 
![simpleinjectorassemblybindings](https://cloud.githubusercontent.com/assets/3741314/7240216/1bce1bf8-e775-11e4-8a32-ea99d271b4e4.PNG)

It wouldn't let me copy XML in here and there doesn't seem to be a way to denote code.  Makes perfect sense for a source code issue tracking system... 

This is a Xamarin.Forms project.  Any ideas?

**Comment by dotnetjunkie** [comment]
Have you got any reason to assume this is related to Simple Injector?

**Comment by BCSATX** [comment]
Howdy, I added an image of the XML warning.  Any ideas?

**Comment by dotnetjunkie** [comment]
Could it be that you have a duplicate assembly binding in your config file?

**Comment by BCSATX** [comment]
Cleaned that up, still no workie...

**Comment by dotnetjunkie** [comment]
Can you create a Github repository and link to it, with a minimal solution that reproduces the issue?
