### ISSUE TITLE
Move Dynamic Assembly Compilation to different assembly

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#275]
Dynamic assembly compilation can be turned on or off by using the `Options.EnableDynamicAssemblyCompilation` flag and it is used in the full (.NET 4.0 and .NET 4.5) version of Simple Injector to optimize performance. When delegates are compiled in a dynamic assembly, it results code that is identical to the code that would get compiled when it is written in C#. Without dynamic assembly compilation, delegates are compiled in-memory using LCG. This results in less optimal IL that uses some reflection in the background. Performance is less optimal.

Both the PCL and .NET Core versions of Simple Injector lack this optimizations and even with those versions, performance of Simple Injector this very high. The performance difference is unnoticeable (probably even not measurable) in any real system. The only practical benefit of this performance optimization is to get a better score during benchmarks.

We should therefore remove this optimization completely, because:
- Reduces the amount of code that needs to be maintained
- Only the .NET 4.x version of Simple Injector contains these optimizations.
- Lowers the complexity of the library
- Reduces the size of the SimpleInjector.dll and its memory footprint.
- Prevents possible bugs caused by this complex code.
- Prevents problems caused by Dynamic Assembly Compilation as described here: https://github.com/simpleinjector/SimpleInjector/issues/274.

I labeled this a 'breaking change', but this actually depends on whether or not the configuration flag is removed or not. Functionally, Simple Injector behaves identically.

**Comment by favill42** [comment]
:+1:

**Comment by dotnetjunkie** [comment]
[feature-275](https://github.com/simpleinjector/SimpleInjector/tree/feature-275) branch created.

**Comment by dotnetjunkie** [comment]
API Changes:

* `ContainerOptions.EnableDynamicAssemblyCompilation` is marked obsolete
* `ContainerOptions.ExpressionCompilationBehavior` property added.
* `IExpressionCompilationBehavior` implementation with the behavior of `EnableDynamicAssemblyCompilation = true` is placed in new `SimpleInjector.DynamicAssemblyCompilation.dll` and is called `DynamicAssemblyExpressionCompilationBehavior`.
