### ISSUE TITLE
Avoid instances creation if HTTP Request is OPTIONS

### ISSUE THREAD

**Issue by Reltik** [simpleinjector/SimpleInjector#28]
Hi everyone! I would like to know if there's a workaround to avoid the unnecesary instance of the registered services if the Http request verb is OPTIONS.
I'm using WebApi with CORS enabled, and the default behavior of Chrome is to send first an http request with verb options to know the list of allowed methods before sending the original request.

As a result my services are instanced twice!

I post here because I see other people asking, so I hope not disturbing someone.

Cheers!

**Comment by dotnetjunkie** [comment]
You should build your container exactly once per app domain, preferably during application start-up. Can you show the related code, so we can see how and where you are building up your container?

**Comment by Reltik** [comment]
Sorry I has some kind of lapsus, i wrote it last night, was late and i was very tired. By container I was meaning the registered services. 

In my case is that SimpleInjector is registering a NHibernate Session per each request.


    container.RegisterSingle(Of ISessionFactory)(Function() NHFactory.Build)

    container.Register(Of ISession)(Function() container.GetInstance(Of ISessionFactory)().OpenSession, registerType)
    container.Register(Of IStatelessSession)(Function() container.GetInstance(Of ISessionFactory)().OpenStatelessSession, registerType)
    container.Register(Of IUnitOfWork, UnitOfWork)(registerType)
    container.Register(Of IDbConnection)(Function() container.GetInstance(Of ISession).Connection, registerType)

The variable registerType is a lifestyle of WebApiRequestLifestyle.

**Comment by dotnetjunkie** [comment]
Registering objects with a 'per request lifestyle' doesn't mean that the container WILL create them during a web request. Objects are created lazily, so if an object graph is resolved that does not contain that session object, it is not created.

**Comment by Reltik** [comment]
Yes, I know that. From the callstack I see that WebAPI is creating the Controller and SimpleInjector resolves the dependencies from the controller constructor. So I figure out a way to get rid of the dumb session.

In Begin_request in Global.asax i check if the request method is OPTIONS, if so it sent allowed methods and end the response to avoid the registration of the objects.

    If Request.HttpMethod = "OPTIONS" Then
        Response.AddHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE")
                    Response.AddHeader("Access-Control-Allow-Headers", "origin, content-type, accept, x-requested-with")

    End if

I feel this as a hacky solution, but at least it works as I intend.

Cheers!
