### ISSUE TITLE
(Web. MVC) How to initialize objects that have per session data?

### ISSUE THREAD

**Issue by MercedeX** [simpleinjector/SimpleInjector#280]
In my web application (MVC based) I need to keep few objects per session. Lets call them S.
In the SimpleInjector documentation objects with per session lifetime are frowned upon. So I changed the design that their creation does not require session based stuff but to use them properly I still need to initialize them with some data that is in the session (consider a key).

Is there a better way to handle this?

**Comment by dotnetjunkie** [comment]
Can you show your code?
