### ISSUE TITLE
Usage with RoleProvider (parameterless constructor)

### ISSUE THREAD

**Issue by benjaminadrom** [simpleinjector/SimpleInjector#284]
What would be the correct way to use the SimpleInjector with a custome role provider?

A custom roleProvider does not accept a constructor with parameters, so it would not possible to use it like that:

**custom roleProvider**
``` c#
private readonly ICentralUnsubscribe _CentralUnsubscribe;
public MyRoleProvider(ICentralUnsubscribe CentralUnsubscribe)
{
    _CentralUnsubscribe = CentralUnsubscribe;
}
```

this would throw an error because it asks for a parameterless constructor.
**Web.config**
``` xml
<roleManager>
...
    <add name="MyRoleProvider" 
        type="MyProvider.RoleProvider" applicationName="/" />
...
</roleManager>
```

**Comment by dotnetjunkie** [comment]
The ASP.NET provider model was not designed with Dependency Injection in mind. Best is to make your custom role provider a [Humble Object](http://xunitpatterns.com/Humble%20Object.html). This means you move all interesting logic out of the provider into a dependency and from within your within the role provider you call the container (probably located in a static field) (a.k.a. service locator) to request the dependency and call it.

There are several paths to walk here. For instance, you can let your role provider depend on more specific interface(s) and resolve it (or them). Trick is to let your role provider to absolutely nothing more than resolve the dependency and call it's method. Doing anything more complicated than this, makes means your provider is not 'humble' anymore.

The other option is to create a role provider that is just meant to dispatch to the real role provider that you can build up with dependency injection. In this case you still use the service locator pattern to resolve the dependency, but in this case the dependency is simply another `RoleProvider`. Your 'humble' dispatching provider simply resolves the registered provider and forwards the calls. The dispatching provider is registered in the xml configuration, the real provider in your container.

Here's an example of something similar with a resource provider: https://stackoverflow.com/questions/10619962/custom-resourceproviderfactory-dependency-injection/10633095.

**Comment by benjaminadrom** [comment]
Thank you for your quick response!
So what i would like to achive is not possible with the "Simple Injector"?

I am not clearly aware what or how a "service locator" works, so with "[service locator](https://msdn.microsoft.com/en-us/library/ff648968.aspx)" did you mean somehow like [this](http://www.asp.net/web-api/overview/advanced/dependency-injection)?

Regards
Ben

**Comment by dotnetjunkie** [comment]
> So what i would like to achive is not possible with the "Simple Injector"?

The limitation is not in Simple Injector. The limitation is in the ASP.NET Provider model that requires providers to be configured in XML and they require a default constructor.

> I am not clearly aware what or how a "service locator" works

Service Locator is a general pattern, which describes an intermediate class (the locator) that allows classes to get their dependency. Any time you call `Container.GetInstance<T>` from within your application code, you are using the Service Locator pattern. Service Locator is the oposite of Dependency Injection where you don't need this intermediate class, but simply inject dependencies into a class from the outside. The Service Locator pattern *IS* an anti-pattern, so you should only use it in cases where you are troubled by bad design. The Provider Model is such bad design.

> I guess i could use this? ;)

Please don't. Service Locator is a pattern; you don't need tools for that. It won't make things better, only adds another library to your application. 

Instead, you can simply expose the `Container` instance in a static field and let your dispatching provider get to it. You can also let this dispatching provider have some public static property that you set while starting the application.

For instance, this is what your `DispatchingRoleProvider` can look like:

``` c#
public sealed class DispatchingRoleProvider : RoleProvider
{
	private static Func<RoleProvider> Factory;

	public static void SetProviderFactory(Func<RoleProvider> factory) {
		Factory = factory;
	}

    private static RoleProvider Provider => Factory();

    public DispatchingRoleProvider() { }
    public override void AddUsersToRoles(string[] usernames, string[] roleNames) => Provider.AddUsersToRoles(usernames, roleNames);
    public override void CreateRole(string roleName) => Provider.CreateRole(roleName);
    public override bool DeleteRole(string roleName, bool throwOnPopulatedRole) => Provider.DeleteRole(roleName, throwOnPopulatedRole);
    public override string[] FindUsersInRole(string roleName, string usernameToMatch) => Provider.FindUsersInRole(roleName, usernameToMatch);
    public override string[] GetAllRoles() =>Provider.GetAllRoles();
    public override string[] GetRolesForUser(string username) => Provider.GetRolesForUser(username);
    public override string[] GetUsersInRole(string roleName) => Provider.GetUsersInRole(roleName);
    public override bool IsUserInRole(string username, string roleName) => Provider.IsUserInRole(username, roleName);
    public override void RemoveUsersFromRoles(string[] usernames, string[] roleNames) => Provider.RemoveUsersFromRoles(usernames, roleNames);
    public override bool RoleExists(string roleName) => Provider.RoleExists(roleName);

    public abstract string ApplicationName { 
        get { return Provider.ApplicationName; }
        set {  Provider.ApplicationName = value; }
    }
}
```

You can make this class a part of your application's [Composition Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/) and refer it through the `<roleProviders>` section in the web config.

With this code you can easily hook up your real role provider as follows:

``` c#
container.Register<RoleProvider, MyFancyRoleProvider>();

DispatchingRoleProvider.SetProviderFactory(() => container.GetInstance<RoleProvider>());
```

Et voila!

**Comment by benjaminadrom** [comment]
Nice, thank you so much!
