### ISSUE TITLE
UserContext is directly or indirectly depending on itself.

### ISSUE THREAD

**Issue by jjwilliams** [simpleinjector/SimpleInjector#29]
But its not ... that I can see!

UserContext registration:

``` c#
container.Register<IUserContext, UserContext>(defaultAppLifeStyle);
```

Database Registration:

``` c#
container.Register(() =>
            {
                var logger = container.GetInstance&lt;ILogger>();
                var userContext = container.GetInstance&lt;IUserContext>();
                return new LENSSContext(nameOrConnectionString, logger, userContext);
            }, defaultAppLifeStyle);
```

Fails on return new LENSSContext

> The configuration is invalid. The type UserContext is directly or indirectly depending on itself.

**Comment by dotnetjunkie** [comment]
I've yet to see that the container is wrong when throwing this message. Please review your object graph closely. How does the `UserContext` look like?
