### ISSUE TITLE
When using MySqlConnection with SimpleInjector strange exception is thrown - doesn't show in for example Autofac

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [simpleinjector/SimpleInjector#293]
Hi,

There is some bug which I cannot narrow due to limited time.
Test case: 
1) simple web api with simple controller - taking data from my sql table by using plain mysql connection - works
2) adding simpleinjector as IoC - excpetion is thrown "The type initializer for 'MySql.Data.MySqlClient.Replication.ReplicationManager' threw an exception."

I added solution with minimum working of project to github
https://github.com/AdaskoTheBeAsT/SimpleInjectorMySqlBugHunt 

When I run all test cases - bug appears in both test cases - when I run test case one by one - case with some "hack" works.

I suspect some race condition in MySQL connector which SimpleInjector only expose anyway it is very strange

**Comment by dotnetjunkie** [comment]
It is possible that you can get race conditions when swapping out Autofac for Simple Injector. AFAIK Autofac always uses locks when building object graphs. Simple Injector on the other hand, is completely lock-free and has a much different performance characteristic. Both differences might cause Autofac to 'accidentally' protected you from the concurrency bugs in the underlying code (the MySQL API in your case). This is of course a very unpredictable 'feature' that you should never rely on.

Unfortunately, I'm unable to reproduce the problem you are seeing and unfortunately my time is limited as well.

What you might try is to provide access to that part of the API that is causing problems in a synchronized way (that means: use a lock statement). Also take a good look at the inner exception of the TypeInitializationException. The inner exception of the TypeInitializationException contains the details of what went wrong.

**Comment by AdaskoTheBeAsT** [comment]
I will use that thread if you don't mind to investigate it further - of course it is not simpleinjector bug - it only exposed problem which exists deeper.

it seems that this line shows an error

MySql.Data.MySqlClient.Replication.ReplicationManager
private static MySqlConfiguration settings
      = ConfigurationManager.GetSection("MySQL") as MySqlConfiguration;

Type 'Microsoft.Owin.OwinContext' in assembly 'Microsoft.Owin, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.

**Comment by AdaskoTheBeAsT** [comment]
So far I found only nasty workaround
you need to have on beginning Startup method something like this

public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            ConfigurationManager.GetSection("MySQL");
             ....
            .......
        }
}

not sure what is more buggy - MySQL lib or ConfigurationManager.GetSection in that case
