### ISSUE TITLE
Does simpleinjector support .net core?

### ISSUE THREAD

**Issue by milla** [simpleinjector/SimpleInjector#298]
If supports, what're the dependencies in project.json, for dnxcore50?

**Comment by dotnetjunkie** [comment]
Yes, Simple Injector v3.2 is compatible with .NET Core. You will need to add the [Simple Injector NuGet package](https://www.nuget.org/packages/SimpleInjector/).

**Comment by milla** [comment]
Yes, now it's ok, but another question, why I got "Package restore failed" error when install SimpleInjector.Integration.Web? Does simpleInjector support WebAPI for .net core?

**Comment by dotnetjunkie** [comment]
ASP.NET Web API is a completely different technology. With ASP.NET Core MVC, the concepts of the old Web API and MVC libraries have merged into one single framework. So both SimpleInjector.Integration.Web and SimpleInjector.Integration.WebApi projects won't work and are not needed when working with ASP.NET Core.
