### ISSUE TITLE
Move ExecutionContextScopingLifestyle and LifetimeScopeLifestyle into the core library.

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#299]
Doing so will cause Simple Injector to become incompatible with .NET 4.0. Since .NET 4.0 is becoming more and more obsolete, this will unlikely be a problem. This might however be a problem for older platforms that don't support AsyncLocal or CallContext; we either need to make version of the core library without an ExecutionContextScopingLifestyle; or we need to drop support for those platforms.

We should also consider renaming the lifestyles. Suggestion:
- AsyncScopingLifestyle
- ThreadScopingLifestyle

**Comment by dotnetjunkie** [comment]
Moving ExecutionContextScopingLifestyle into the core library basically means the core library will be >= .NETStandard1.3 while v3.2 is >= .NETStandard1.0.

**Comment by dotnetjunkie** [comment]
Effect of merging those lifestyles into the Core library is that the `BeginLifetimeScope()` and `BeginExecutionContextScope()` extension methods will always be available. This might be confusing for the user. Which method to call?

So instead, we might think about moving these methods to the `ScopedLifestyle` class instead. For instance, we could force the user to do the following:

``` c#
using (Lifestyle.Scoped.BeginScope(container))
{
    container.GetInstance<X>();
}
```
```

**Comment by dotnetjunkie** [comment]
Here are some possible names for the name lifestyle:

- AsyncScopingLifestyle
- AsyncScopeLifestyle
- AsyncScopedLifestyle

What would be the best name?

**Comment by dotnetjunkie** [comment]
Should we simplify working with the `AsyncScopedLifestyle` and `ThreadScopedLifestyle` (which will be part of the core library in v4) by adding shortcuts to them from the `Lifestyle` class, just as we now do with `Lifestyle.Transient`, `Lifestyle.Scoped` and `Lifestyle.Singleton`?

This would mean typical usage would become:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = Lifestyle.AsyncScoped;

container.Register<MyClass>(Lifestyle.Scoped);
```

Instead of:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new SimpleInjector.Lifestyles.AsyncScopedLifestyle();

container.Register<MyClass>(Lifestyle.Scoped);
```

I can imagine adding `Lifestyle.AsyncScoped` and `Lifestyle.ThreadScoped` would be confusing next to the `Lifestyle.Scoped`:

- Lifestyle.AsyncScoped
- Lifestyle.ThreadScoped
- Lifestyle.Transient
- Lifestyle.Scoped
- Lifestyle.Singleton

**Comment by qujck** [comment]
The confusion is more with Scoped, should it have been DefaultScoped and if so is it worth a breaking change now?

**Comment by dotnetjunkie** [comment]
Although `Lifestyle.DefaultScoped` does make it clearer that there is a relationship between `Lifestyle.Scoped` and `ContainerOptions.DefaultScopedLifestyle`, I do think that the `Default` prefix clutters the registration of developers:

``` c#
container.Register<IRepository<Person>, PersonRepository>(Lifestyle.DefaultScoped);
container.Register<IRepository<Order>, OrderRepository>(Lifestyle.DefaultScoped);
container.Register<IRepository<Item>, ItemRepository>(Lifestyle.DefaultScoped);
container.Register<IRepository<Product>, ProductRepository>(Lifestyle.DefaultScoped);
```

**Comment by dotnetjunkie** [comment]
I don't think it is obvious that the `Lifestyle.Default` would map to `Options.DefaultScopedLifestyle`. I would rather think it would map to `Options.DefaultLifestyle` (which is new in v3.3).

I don't mind making (yet another) breaking change in v4, but since this is a really prominent part of the API, the improvement should be rather significant. I'm currently not sure whether renaming `Lifestyle.Scoped` is a big enough improvement that would justify this. That would probably mean we shouldn't add `Lifestyle.AsyncScoped` and `Lifestyle.ThreadScoped`, since they cause confusion.

**Comment by qujck** [comment]
What about this:

- Lifestyle.AsyncScope
- Lifestyle.ThreadScope
- Lifestyle.Transient
- Lifestyle.Scoped
- Lifestyle.Singleton

I'm not a fan of `Scoped` regardless of the other options, I don't believe it clearly describes what the property holds, whereas `DefaultScope` does. But, as you say, the api is uglier with `container.Register<IRepository<Product>, ProductRepository>(Lifestyle.DefaultScope);`.

I think that `container.RegisterDefaultScope<IRepository<Product>, ProductRepository>();` is neater than both the other options as the full intention of the registration is in the registration method name rather than tucked away as a parameter - but I understand that this suddenly brings a load more `RegisterXXX` methods to the party.

Not the easiest decision to make!

**Comment by qujck** [comment]
why `Options.DefaultScopedLifestyle` and `Options.DefaultLifestyle`?

**Comment by dotnetjunkie** [comment]
> why Options.DefaultScopedLifestyle and Options.DefaultLifestyle?

See: https://github.com/simpleinjector/SimpleInjector/issues/313

**Comment by TheBigRic** [comment]
Maybe this comment is too late in the thread but I think this:
``` c#
container.Options.DefaultScopedLifestyle = Lifestyle.AsyncScoped;
```
is pretty strange. Because this:
``` c#
container.Options.DefaultScopedLifestyle = Lifestyle.Scoped;
```
will throw an exception because it will cause a StackOverflowException otherwise (if I'm not mistaken). 

So this will be confusing. Although Lifestyle.xxx is not an enum it almost acts like one and making 2 out of there behave differently than others is just hard to grasp.

What about:
``` c#
// these options could be default if not set by the user
// the user will in that case have the option to overwrite
// the various integrations packages could override these with
// the integration package specific ones like WebRequestLifestyle
container.Options.DefaultLifestyle = new TransienstLifestyle();
container.Options.DefaultScopedLifestyle = new ThreadScopedLifestyle();
container.Options.DefaultAsyncScopedLifestyle = new AsyncScopedLifestyle();

container.Register<ITransientService, Service1>();
container.Register<ILifetimeScopeService, Service2>(Lifestyle.Scoped);
container.Register<IAsyncScopeService, Service2>(Lifestyle.AsyncScoped);
```
