### ISSUE TITLE
How to register an OpenGeneric in WebApi 2?

### ISSUE THREAD

**Issue by gufigueiredo** [simpleinjector/SimpleInjector#30]
I have the following in my current MVC project:

```
private static void InitializeContainer(Container container)
{
            container.RegisterOpenGeneric(typeof(IUnitOfWork<>), typeof(UnitOfWork<>), 
            new WebRequestLifestyle());          
}
```
Now, we are moving to a project that uses WebAPI 2, in a similar architecture. How to register an open generic type like above? I think WebRequestLifestyle is not the correct way in this case...

I've tried and works:
```
container.RegisterOpenGeneric(typeof(IUnitOfWork<>), typeof(UnitOfWork<>), Lifestyle.Transient);
```

...but I have no idea if it´s correct or no.

**Comment by dotnetjunkie** [comment]
For Web API, there's the [Web API request lifestyle](https://simpleinjector.readthedocs.org/en/latest/lifetimes.html#perwebapirequest):

``` c#
container.RegisterOpenGeneric(typeof(IUnitOfWork<>), typeof(UnitOfWork<>), 
    new WebApiRequestLifestyle());    
```

The Web Request lifestyle might work in Web API, but the Web API lifestyle is [recommended](https://simpleinjector.readthedocs.org/en/latest/lifetimes.html#web-api-request-lifestyle-vs-web-request-lifestyle).

**Comment by gufigueiredo** [comment]
Hi dotnetjunkie.

Thanks for the reply. Unfortunately, the code provided does not compile. I receive the following message:

"Agument type 'SimpleInjector.Integration.WebApi.WebApiRequestLifestyle' is not assignable to parameter type 'SimpleInjector.LifeStyle'

Any ideas?

**Comment by dotnetjunkie** [comment]
Might it be that you accidentally created your own type named `WebApiRequestLifestyle`? The `WebApiRequestLifestyle` that lives in the `SimpleInjector.Integration.WebApi` namespace of the `SimpleInjector.Integration.WebApi.dll` does actually inherit from `SimpleInjector.Lifestyle`. Or could it be that you defined your own `RegisterOpenGeneric` extension method, instead of using the extension method from `SimpleInjector.Extensions`?

**Comment by gufigueiredo** [comment]
No, I don't have any extensions or types.

My container.RegisterOpenGeneric method receives the following (and overloads):
```
void RegisterOpenGeneric(System.Type openGenericType, System.Type openGenericImplementation)
void RegisterOpenGeneric(System.Type openGenericType, System.Type openGenericImplementation, Lifestyle lifestyle)
void RegisterOpenGeneric(System.Type openGenericType, System.Type openGenericImplementation, Lifestyle lifestyle, Predicate<OpenGenericPredicateContext> predicate)
```

I have those DLL´s referenced in my project:

**SimpleInjector - 2.7.3.0**
**SimpleInjector.Diagnostics - 2.7.3.0**
**SimpleInjector.Extensions.ExecutionContextScoping - 2.7.3.0**
**SimpleInjector.Integration.WebApi - 2.7.3.0**

All installed via nuget command:

**Install-package SimpleInjector.Integration.WebApi**

...that resolve all needed dependencies

**Comment by dotnetjunkie** [comment]
I'm sorry man, but I'm unable to reproduce this. It 'works on my machine', as they say. The line `container.RegisterOpenGeneric(typeof(IUnitOfWork<>), typeof(UnitOfWork<>), new WebApiRequestLifestyle());` was copied from a compiling web project. I just installed `SimpleInjector.Integration.WebApi` (version 2.7.3), added the `IUnitOfWork<T>` interface and `UnitOfWork<T>` class, included the following namespaces at the top and it works:

``` c#
using SimpleInjector;
using SimpleInjector.Extensions;
using SimpleInjector.Integration.WebApi;
```

btw. did you copy that compile error? There is no type called 'LifeStyle'. It is called 'Lifestyle'. So if you copy-pasted the error, this `LifeStyle` is a different type.

**Comment by gufigueiredo** [comment]
Man, I really had a problem with my project.
I've made an empty project and the WebApiRequestLifestyle worked fine.

So... I've uninstalled all nuget packages from my main project and re-installed again. Now, worked like a charm.

Sorry for the incovenience.

**Comment by dotnetjunkie** [comment]
Welcome in the wonderful world of NuGet :-)
