### ISSUE TITLE
Batch registration with different lifecycles

### ISSUE THREAD

**Issue by cgreen69** [simpleinjector/SimpleInjector#301]
When registering types that implement an interface that supports generics I can use the `Register` method to batch register and pass in a life style parameter like the example below, this works well.

``` c#
container.Register(typeof (IMyValidator<>), new[] {typeof (IMyValidator<>).Assembly}, lifeStyle);
```

However I have one class that needs a different life cycle. How can i register this and use the batch registration without getting an error that the same class has been registered? In other words how do i say "from my assembly how do i register all of my types that implement a generic interface using a transient lifecycle except one which should be registered as a singleton"

Thanks for any advice.

**Comment by dotnetjunkie** [comment]
There are multiple ways to achieve this.

You can split the batch-registration into multiple calls:

``` c#
var types = container.GetTypesToRegister(typeof(IMyValidator<>), 
    new[] { typeof (IMyValidator<>).Assembly });

var nonTransientTypes =new[] { typeof(SomeType) };
var transientTypes = types.Except(nonTransientTypes);

container.Register(typeof (IMyValidator<>), transientTypes);
container.Register(typeof (IMyValidator<>), nonTransientTypes, Lifestyle.Scoped);
```

Or you can override the particular registration:

``` c#
container.Register(typeof (IMyValidator<>), new[] { typeof (IMyValidator<>).Assembly });

container.Options.AllowOverridingRegistrations = true;
container.Register<IMyValidator<Something>, SomethingValidator>(Lifestyle.Scoped);
container.Options.AllowOverridingRegistrations = false;
```

Or you can use a custom lifestyle selection behavior as described [here](https://simpleinjector.readthedocs.io/en/latest/extensibility.html#overriding-selection-behavior). This allows you to define your custom type with your custom `CreationPolicyAttribute` (as described in the link):

``` c#
[CreationPolicy(CreationPolicy.Scoped)]
public class SomethingValidator : IMyValidator<Something> { ... }
```

You can use the following registration to get this working:

``` c#
var container = new Container();
container.Options.LifestyleSelectionBehavior = new AttributeBasedLifestyleSelectionBehavior();

container.Register(typeof (IMyValidator<>), new[] { typeof (IMyValidator<>).Assembly });
```

Simple Injector's batch-registration calls check the configured `LifestyleSelectionBehavior` to get the correct lifestyle of components to register.

**Comment by cgreen69** [comment]
Thank you for these great suggestions
