### ISSUE TITLE
Drop support for PCL and unify projects

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#306]
Which platforms should be supported by Simple Injector v4? The current v3.2 version supports the following platforms:
- .NETFramework 4.0
- .NETFramework 4.5
- .NETStandard 1.0 (and up)
- Silverlight 5.0 (PCL)
- Windows 8.0 (PCL)
- WindowsPhone 8.0 (PCL)
- Mono (PCL)

I'm considering removing support for:
- .NETFramework 4.0
- Silverlight 5.0 (through PCL)
- Windows 8.0 (through PCL)
- WindowsPhone 8.0 (through PCL)
- Mono (through PCL)

That means supporting:
- .NETFramework 4.5
- .NETStandard 1.0 (and up)

I'm even considering only supporting - .NETStandard 1.3 (and up).

**Comment by TheBigRic** [comment]
I vote for supporting.net 4.5 and up and .net standard 1.0 and up. This keeps the support for most platforms, while having the benefit of removing the removing the PCL package.

**Comment by dotnetjunkie** [comment]
I'll think I'll keep .NET 4.0 but drop support for PCL.

**Comment by dotnetjunkie** [comment]
According to this [pol](https://twitter.com/simpleinjector/status/837224719762010113) we should keep support for .NET 4.0.
