### ISSUE TITLE
Mark lifestyle constructors that allow non-disposable registrations obsolete(false)

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#307]
All built-in Scoped lifestyles in Simple Injector currently allow suppressing disposal:

``` c#
container.Register<SomeService>(new WebRequestLifestyle(disposeWhenLifetimeScopeEnds: false));
```

I however think that this feature is rarely used, and smells like there is something weird going on if this is required. At one hand the developer asks Simple Injector to create the instance, but it isn't allowed to dispose it.

**Comment by TheBigRic** [comment]
What was the primary use case you had in mind when you added this feature in the first place?

**Comment by dotnetjunkie** [comment]
The idea is that users might have components that are 'externally owned'. Provided by the user to the container, but a different entity in the system should be in control over its lifetime.

There are however not many containers that allow you to control whether or not such component should be disposed or not. Most simply dispose components automatically. From what I can see only Simple Injector and [Autofac](http://docs.autofac.org/en/latest/lifetime/disposal.html#disabling-disposal) actually allow this.

It would typically be very weird when you let the container control the creation of such component (auto-wiring) while not letting it dispose it. On the other hand, when the component is registered with a lambda, the component isn't created by Simple Injector, but Simple Injector still assumes ownership and will dispose it for you. This would be a typical case for disabling disposal:

``` c#
container.Register<IService>(() => ExternalLib.CreateService(), new WebRequestLifestyle(false));
```

From a design perspective something weird is going on though here. You will typically only want to disable disposal for components that you have no control over (external library stuf), since application components can be refactored in a way that disposal iss not a problem. External components however should not be injected into application components directly, and since an adapter should be used anyway, such adapter would also solve the problem, because it can prevent disposal.

**Comment by Tornhoof** [comment]
Maybe provide your adapter solution in an upgrade guide for v4, but your reasoning for discontinuing is sound imho.

**Comment by TheBigRic** [comment]
I think the adapter approach is in line with the advice we give on a regular basis. It also adheres to DIP.

With the adapter approach it is still supported and given the fact that are almost no other libraries supporting this feature and thus it is rarely used, I would say: Remove!
