### ISSUE TITLE
The IContext is registered as 'ASP.NET Request' lifestyle, but the instance is requested outside the context of a ASP.NET Request.

### ISSUE THREAD

**Issue by milla** [simpleinjector/SimpleInjector#308]
I got the exception while migrating simpleinjector for wcf to asp.net core mvc.

> The IContext is registered as 'ASP.NET Request' lifestyle, but the instance is requested outside the context of a ASP.NET Request.

`container.Options.DefaultScopedLifestyle = new AspNetRequestLifestyle();

container.Register<IContext>(() => new Context()
{
    version = context.RouteData.Values["version"].ToString()
}, container.Options.DefaultScopedLifestyle);
var controller = container.GetInstance(context.ActionDescriptor.ControllerTypeInfo.AsType());`

The exception is thrown out from the the last line of above code.
When I removed , container.Options.DefaultScopedLifestyle from container.Register<IContext> like below

`container.Register<IContext>(() => new Context()
{
    version = context.RouteData.Values["version"].ToString()
}, container.Options.DefaultScopedLifestyle);`

I got another error:

>A lifestyle mismatch is encountered. OperationContext (ASP.NET Request) depends on IList<Error> (Transient). Lifestyle mismatches can cause concurrency bugs in your application. Please see https://simpleinjector.org/dialm to understand this problem and how to solve it.

Does container.Register<IClassA, ClassA>() default to Transient? What shall I do to clear the errors? Is there any more information about the mvc core integration? 

Thanks,
Elaine

**Comment by dotnetjunkie** [comment]
Please don't [double post](https://stackoverflow.com/questions/39890690/simple-injector-in-asp-net-core-error-the-instance-is-requested-outside-the-con) your question. We are watching both Stackoverflow and Github.
