### ISSUE TITLE
Main page https://simpleinjector.org is down

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [simpleinjector/SimpleInjector#309]
TLDR:
Web site is down.

Explanation:

no css, js, svg is loaded - it returns 500 on request to every css, js,svg - only font file hosted on some external CDN is delivered correctly

**Comment by dotnetjunkie** [comment]
Thanks for reporting this.

**Comment by dotnetjunkie** [comment]
I'll have to contact the hoster in the morning; can't figure out what is going wrong here.

**Comment by AdaskoTheBeAsT** [comment]
No worry. Thanks for head up.

**Comment by dotnetjunkie** [comment]
And we're up again. 

The `mimeMap` entry we had in the `<staticContent>` section of the web.config broke the complete application. We required this config in the past to allow browsers to download .svg files. An update by our hosting provider made the configuration redundant, but at the same time completely broke the application.

I removed the `mimeMap` entry and everything is back to normal.
