### ISSUE TITLE
Action filter logic doesn't seem to work for MVC (works for Web API)

### ISSUE THREAD

**Issue by aabragan** [simpleinjector/SimpleInjector#310]
Any ideas what I am missing. I followed your article for this setup to be able to secure methods with an attribute that had an externally defined security handler.
https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=98

In my MVC DI initializer I register a collection for IUIActionFilter<>
![image](https://cloud.githubusercontent.com/assets/580127/19192558/9b259688-8c74-11e6-89e1-8a8cb1dca4f5.png)
I invoke container.GetAllInstances for the generic type but nothing is returned. 
![image 1](https://cloud.githubusercontent.com/assets/580127/19192592/bde4e908-8c74-11e6-9ed5-d04efc2e8190.png)
Filtertype returns the generic as expected but the Invoke returns nothing. I know the collection registered successfully during setup.
![image 2](https://cloud.githubusercontent.com/assets/580127/19192645/ea3bdef8-8c74-11e6-84d1-c94bb5f85bb7.png)
The actionfilter implementation
![image 3](https://cloud.githubusercontent.com/assets/580127/19192682/0a89eaa6-8c75-11e6-8ec8-d8d90766cbed.png)
The decorated endpoint which should have the hasaccess check run
![image 4](https://cloud.githubusercontent.com/assets/580127/19192695/186080d6-8c75-11e6-941a-c9c680fec3e4.png)

In this case I should be hitting the hasAccess check which returns false but that code never gets called because I don't get the actionFilter back.

**Comment by aabragan** [comment]
A similar setup in the Web API version of this code works perfectly.
![image](https://cloud.githubusercontent.com/assets/580127/19192922/f84b8fba-8c75-11e6-8ebf-52d3e6b9e835.png)

**Comment by dotnetjunkie** [comment]
I bet that the list of assemblies you use, do not contain any `IUIActionFilter<T>` implementations.

**Comment by aabragan** [comment]
Yep. Looks like somehow the dll with the implementation was not in the list of items to process during initialization and consequently didn't get loaded into the container. Thanks for the pointer!
