### ISSUE TITLE
Remove unneeded dependencies in .NETStandard release.

### ISSUE THREAD

**Issue by thomas-goerlich** [simpleinjector/SimpleInjector#312]
Hi, 

if i add the SimpleInjector NuGet Package to my Xamarin iOS/Android Project it wants to install a bunch of stuff like System.Collections, System.Linq, etc which are probably the .netstandard dependencies. I don't think this should happen, right? Do you maybe need to add the Xamarin Nuget Package Identifier like "MonoAndroid10+xamarinios10+MonoTouch10" to the portable Version? We have a few internal nuget packages with identifiers like "portable-net45+win8+MonoAndroid10+xamarinios10+MonoTouch10" and they work just fine.

regards Thomas

**Comment by dotnetjunkie** [comment]
.NETStandard is the new PCL and we will only support MonoAndroid and related platforms through .NETStandard. Simple Injector requires packages like System.Collections and System.Linq.

**Comment by thomas-goerlich** [comment]
Okay, i get that. I'll try installing the .netstandard version in my project. I was cautious because of all the dependencies it wants to install. Dependencies that i would think are not required because Mono already includes them (e.g. System.Linq).

**Comment by dotnetjunkie** [comment]
After some investigation, I have to conclude that most of the dependencies are indeed not required. They are left overs of the time that the `NETStandard.Library` dependency wasn't there. The only required dependency is `System.ComponentModel` (although it might be possible to remove it as well, with some minor code changes).

We will schedule the removal of these dependencies for the next minor release (v3.3).
