### ISSUE TITLE
Could not load SimpleInjector assembly after its update to 3.2.3 in ASP.NET Core MVC

### ISSUE THREAD

**Issue by salixzs** [simpleinjector/SimpleInjector#319]
After updating SimpleInjector to 3.2.3 ASP.NET Core MVC application (targetting full 4.6.x framework) throws exception:

> System.IO.FileLoadException
> Could not load file or assembly 'SimpleInjector, Version=3.2.0.0, Culture=neutral, PublicKeyToken=984cb50dea722e99' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Project also has SimpleInjector.Integration.AspNetCore.Mvc package (v 3.2.3)
I have suspicions on some dependencies versions, as in project.lock.json demands SimpleInjector 3.2.0 as reference for dependency package SimpleInjector.Integration.AspNetCore (which is v3.2.1)

```
"SimpleInjector.Extensions.ExecutionContextScoping/3.2.0": {
        "type": "package",
        "dependencies": {
          "SimpleInjector": "3.2.0"
        },
        "compile": {
          "lib/net45/SimpleInjector.Extensions.ExecutionContextScoping.dll": {}
        },
        "runtime": {
          "lib/net45/SimpleInjector.Extensions.ExecutionContextScoping.dll": {}
        }
      },
      "SimpleInjector.Integration.AspNetCore/3.2.1": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNetCore.Http.Abstractions": "1.0.0",
          "NuSpec.ReferenceGenerator": "2.0.0-beta-bld14",
          "SimpleInjector": "3.2.0",
          "SimpleInjector.Extensions.ExecutionContextScoping": "3.2.0"
        },
        "compile": {
          "lib/net451/SimpleInjector.Integration.AspNetCore.dll": {}
        },
        "runtime": {
          "lib/net451/SimpleInjector.Integration.AspNetCore.dll": {}
        }
      },
      "SimpleInjector.Integration.AspNetCore.Mvc/3.2.3": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNetCore.Mvc.Core": "1.0.0",
          "Microsoft.AspNetCore.Mvc.Razor": "1.0.0",
          "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.0.0",
          "NuSpec.ReferenceGenerator": "2.0.0-beta-bld14",
          "SimpleInjector.Integration.AspNetCore": "3.2.1"
        },
        "compile": {
          "lib/net451/SimpleInjector.Integration.AspNetCore.Mvc.dll": {}
        },
        "runtime": {
          "lib/net451/SimpleInjector.Integration.AspNetCore.Mvc.dll": {}
        }
      },
```

Am I missing something for correct update or this is old-ish package dependencies, which needs to be updated?

**Comment by salixzs** [comment]
Appears it cached somewhere in ```bin``` folders some old references. After clearing out all compiled files, packages and recompiling everything it started to work again without problems.
There were these records in some of compiled DLL config files:
```
<bindingRedirect oldVersion="3.2.0.0" newVersion="3.2.2.0" />
<bindingRedirect oldVersion="3.2.0.0" newVersion="3.2.3.0" />
```
(I was updating SimpleInjector as soon as it released several times during project)

**Comment by dotnetjunkie** [comment]
NuGet is at it again :'(

When updating a NuGet package, the NuGet package manager should manage the binding redirects for you. Without setting the binding redirects, the CLR will go look for an assembly by its exact version number.

Since this often went wrong in the past, we decided to update the version numbers of all packages and republish them to NuGet, even if only the core library was changed. We however stopped doing this with the ASP.NET Core integration packages, because we assumed that by now NuGet would have fixed this problem.

Apparantly NuGet still screws up. We might have to start updating these two integration packages as well in the future.

In the meantime, you can add the following binding redirect to your application's configuration file:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="SimpleInjector" publicKeyToken="984cb50dea722e99" 
            culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.2.2.0" newVersion="3.2.3.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
