### ISSUE TITLE
Should we add the possibility for Transient objects to be disposed on scope boundary?

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#321]
Simple Injector's default lifestyle is the `Transient` lifestyle. This lifestyle does not dispose instances, because by default, Simple Injector has no notion of scoping. This is because not all applications use scoped lifestyles and for others need their specific one. This means scoping has to be enabled explicitly, for instance by using the `container.Options.DefaultScopedLifestyle` property.

When objects implement `IDisposable` the advise is to register them as `Scoped`; Simple Injector will warn about a [Disposable Transient Component](https://simpleinjector.readthedocs.io/en/latest/disposabletransientcomponent.html). This however is troublesome when the component is a root level component, like MVC Controllers (both old MVC and Core MVC). Making those components scoped means that every component in the application should be registered with scoped or singleton, to prevent [Lifestyle Mismatches](https://simpleinjector.readthedocs.io/en/latest/LifestyleMismatches.html). This can be done as follows:

``` c#
var container = new Container();
container.Options.DefaultLifestyle = new ExecutionContextScopeLifestyle();
```

This might solve these problems, but it is questionable whether it is okay to make every component scoped. Developers can run into issues like [this one](https://github.com/simpleinjector/SimpleInjector/issues/219) that we will try to solve in v4.

Another option would be to create a special version of the `Transient` lifestyle that will register that instance for disposal when the active scope ends. The [DisposableTransientLifestyle example](https://github.com/simpleinjector/SimpleInjector/blob/master/src/SimpleInjector.CodeSamples/DisposableTransientLifestyle.cs) in the CodeSamples project shows a possible implementation. Using such construct, the user would be able to do the following:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new ExecutionContextScopeLifestyle();
container.Options.DefaultLifestyle =
    new DisposableTransientLifestyle(container.Options.DefaultScopedLifestyle);
```

Or perhaps more elegantly:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new ExecutionContextScopeLifestyle();
container.Options.DisposeTransientsWhenOnScopeBoundary = true;
```

This would allow transient components to be automatically disposed (in case `IDisposable` is implemented) when the request ends. This will prevent Disposable Transient Component warnings and will prevent problems as described in #219.

On the other hand, when #219 is solved in v4, making everything scoped by default might be a better solution.

What do you think?

**Comment by dotnetjunkie** [comment]
One big downside of making everything Scoped by default, there could be a noticeable performance penalty in resolve time, because every resolved scoped registration will cause a dictionary lookup. If everything is scoped, every instance will cause at least one lookup. Depending on the graph the time it takes to resolve such graph could be in the range from 10% to 2000% of the time it takes to resolve a transient graph (depending on the graph, it could theoretically cause a speed-up, because part of the graph could be pulled from the cache, but this not a very likely scenario).

**Comment by dotnetjunkie** [comment]
A downside of disposing transients on scoped boundaries is that Simple Injector won't (obviously) warn about Disposable Transient Components anymore. This can cause problems, since often disposable components also require a scoped lifestyle.

Take a `DbContext` for instance. When Simple Injector is instructed to register components as *disposable transient* by default, a `DbContext` will still be created multiple times during a request. Although all instances are properly disposed at the end of the request, in most cases [you only want to have one single DbContext per request](https://stackoverflow.com/questions/10585478/one-dbcontext-per-web-request-why) (or per ‘unit of work’). So while Verify() succeeds, the application might break at runtime, because `SaveChanges` is called only on the last DbContext. This leaves the user in the dark, while with Simple Injector’s default configuration, the problem would be noticed right away.

**Comment by TheBigRic** [comment]
I took some time to think about this one a little bit. At first I thought the point was valid.  But after really letting sinking this in:

> a  DbContext  will still be created multiple times during a request
without any warning.

I think this completely is against the design principles of S.I. A user should never be able to do this without getting a warning. 

Making things scoped by default however will increase complexity because a user will need to start a scope (and end it!) and will have to really think when and how the will implement this. In WinForms for example this could be very tricky to get right. I never got it right so all my Forms are 'Transient'. I suppress the warning and dispose the forms myself when they are closed. 

So I think this is not an easy one to decide on.

**Comment by dotnetjunkie** [comment]
Won't fix.
