### ISSUE TITLE
Misleading exception when Container is disposed.

### ISSUE THREAD

**Issue by BrettJaner** [simpleinjector/SimpleInjector#322]
I'm getting the following exception when my tests are ran a 2nd time w/o a restart.

Message:
Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.   

StackTrace:
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstance(Type serviceType)

This is a Web Api project using WebApiRequestLifestyle.  The exception is being thrown from inside my MessageHandlers that reference my container directly.

References:
SimpleInjector.Integration.WebApi v3.2.3
SimpleInjector.Extensions.ExecutionContextScoping v3.2.3
SimpleInjector v3.2.3
.NET 4.5.1

Let me know what other info would be helpful.

Thanks!

**Comment by dotnetjunkie** [comment]
My educated guess is that you disposed the `Container` instance.

**Comment by BrettJaner** [comment]
Thanks Steven.  Looks like you're right.  I added SignalR to my app and then decided to merge start up locations.  I made my container static and was still disposing of it in the Dispose method.  So I'll just go ahead and remove that Dispose override.

    [assembly: OwinStartup(typeof(App.Web.WebApiApplication))]
    namespace App.Web
    {
        public class WebApiApplication : HttpApplication
        {
            static Container container;

            protected void Application_Start()
            {
                container = new Container();

                container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();

                SimpleInjectorConfig.Register(container);

                container.Verify();

                GlobalConfig.Register(GlobalConfiguration.Configuration, container);
                WebApiConfig.Register(GlobalConfiguration.Configuration, container);
            }

            public void Configuration(IAppBuilder app)
            {
                //do something with container
                  
                app.MapSignalR();
            }

            //Deleting this
            public override void Dispose()
            {
                base.Dispose();

                if (container != null)
                    container.Dispose();
            }
        }
    }

If this exception is the one you receive when you access a dispose container, what are your thoughts on throwing a little more descriptive of an exception?

**Comment by dotnetjunkie** [comment]
> what are your thoughts on throwing a little more descriptive of an exception?

Since one of the design principles behind Simple Injector is to [Communicate Errors Clearly](https://simpleinjector.readthedocs.io/en/latest/principles.html#communicate-errors-clearly) I can only agree with you: The exception you were getting is misleading and this should be fixed whenever possible.

Can you supply me with a full stack trace of the exception you got?

**Comment by dotnetjunkie** [comment]
That is: the stack trace including stack traces of all inner exceptions.

**Comment by BrettJaner** [comment]
Message: Cannot access a disposed object.  Object name: 'The ThreadLocal object has been disposed.'.
Source: SimpleInjector
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstanceForRootType(Type serviceType)
   at SimpleInjector.Container.GetInstance(Type serviceType)
   at App.Web.Code.HttpMessageCommandHandler.<SendAsync>d__2.MoveNext() in C:\git\App\App.Web\Code\HttpMessageCommandHandler.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at App.Web.Code.ErrorHandlingDelegatingHandler.<SendAsync>d__2.MoveNext() in C:\git\App\App.Web\Code\ErrorHandlingDelegatingHandler.cs:line 24

--Inner
Message: Cannot access a disposed object.  Object name: 'The ThreadLocal object has been disposed.'.
Source: mscorlib
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at System.Threading.ThreadLocal`1.get_Value()
   at SimpleInjector.Advanced.AdvancedExtensions.IsVerifying(Container container)
   at SimpleInjector.Scope.GetScopelessInstance[TService,TImplementation](ScopedRegistration`2 registration)
   at SimpleInjector.Scope.GetInstance[TService,TImplementation](ScopedRegistration`2 registration, Scope scope)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`2.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.InstanceProducer.GetInstance()

**Comment by dotnetjunkie** [comment]
After some investigation, I noticed there are dozens of places where a check will need to be added to make sure that in all cases the container communicates clearly that the container is disposed. Unfortunately, there is no simple way to do this without impacting performance. I will add the checks to a few obvious places that won't impact performance too much, but I'm afraid we will have to break our "Communicate Errors Clearly" rule here :-(

**Comment by BrettJaner** [comment]
Understandable.  Thanks again for your responsive support.  Feel free to close the issue at your discretion.

**Comment by dotnetjunkie** [comment]
No, thank you for bringing this up. I added the check to `Container.GetInstance` which will be the most common entry point, so this will already reduce the chance significantly of anyone getting in the dark because of this. This will communicate disposal in your particular case as well.

I will push this fix with the next release (either v3.2.4 pr v3.3.0).

**Comment by dotnetjunkie** [comment]
Fixed in [v3.2.4](https://www.nuget.org/packages/SimpleInjector/3.2.4).
