### ISSUE TITLE
[question] Can I use Attribute Routing for MVC 5 and Web API 2 with Simple Injector?

### ISSUE THREAD

**Issue by aabragan** [simpleinjector/SimpleInjector#327]
I am trying to user attribute routing for my api and ui endpoints. I am unable to get it to detect the attribute routes that I have defined, in spite of calling MapMvcAttributeRoutes after setting the controller factory as follows. What am I missing here?

`            
ControllerBuilder.Current.SetControllerFactory(new CustomControllerFactory(container, controllerTypes));
`
`
RouteTable.Routes.MapMvcAttributeRoutes();
`

**Comment by dotnetjunkie** [comment]
This seems to me a question about MVC instead of Simple Injector. You might want to ask this sinewhere else (like Stackoverflow).

**Comment by aabragan** [comment]
Ok thanks.
