### ISSUE TITLE
Hosting OWIN Web Api in IIS

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [simpleinjector/SimpleInjector#332]
Hi,

from some time I used https://github.com/stackia/SimpleInjector.Integration.Owin
Autor wrote:

> The official integration guide recommends using execution context scope. Well, it seems no problem but when you host your OWIN application on IIS (use Microsoft.Owin.Host.SystemWeb), you'll find sometimes your execution context scope disappears and new service instances are created.

Question is - it is still the case?

**Comment by dotnetjunkie** [comment]
I am not familiar of this issue and the author never contacted us about this. We've never got any a bug report sbout this from anyone else about such issue, while many developers are using Simple Injector with OWIN on IIS in production.

I therefore have no reason to believe that such bug exists. In other words, it's safe to use this lifestyle in production.
