### ISSUE TITLE
ConfigureAwait(false) and ExecutionContextScope 

### ISSUE THREAD

**Issue by stevengopmo** [simpleinjector/SimpleInjector#335]
In #334 Steven mentions
> Somewhere during the asynchronous flow of methods, ConfigureAwait(false) is called. ConfigureAwait(false) causes the CLR to ditch its contextual information. The ExecutionContextScope requires this context to be available.

I was under the impression that ConfigureAwait(false) is the preferable approach to async library methods for performance and overall scalability reasons.  Is there a way to make these 2 work in happy unison or no?

**Comment by dotnetjunkie** [comment]
Sorry, that statement is confusing and wrong. I just tested this to make sure I'm correct: Scopes flow across asynchronous calls, even if `ConfigureAwait(false)` is called. I got confused after misreading [this old thread](https://stackoverflow.com/questions/22242239/simpleinjector-registerwebapirequest-vs-registerperwebrequest). @blueling states there the following:

> The scope used by `WebApiRequestLifestyle` is `ExecutionContextScope`. As the name implies an `ExecutionContextScope` registers itself in the logical call context and flows with async operations across threads (e.g. a continuation after await on a different thread still has access to the scope regardless of whether `ConfigureAwait()` was used with `true` or `false`).

**Comment by stevengopmo** [comment]
Whew! That's a relief then. :)
