### ISSUE TITLE
Simple Injector with RemotingService FluorineFx

### ISSUE THREAD

**Issue by lira92** [simpleinjector/SimpleInjector#339]
Hi guys, We have an application that use FluorineFx and I want to use dependency injection with simple injector, she uses the remoting Services that it is called through a web form page Gateway.aspx. can i use dependency injection in a remoting service contructor? What will I put in my Aplication_Start?

**Comment by dotnetjunkie** [comment]
I have no experience with FluorineFx what so ever. Have you tried resolving this removing service using Simple Injector? Can you show some code that demonstrates your problems?

**Comment by lira92** [comment]
I do this implementation: https://gist.github.com/lira92/2e797b8504761bb1ade1fb3240a3358a
according this link: http://simpleinjector.readthedocs.io/en/latest/webformsintegration.html

but when I invoke BancosController I get a error "Constructor in type 'ServiceWeb.Controllers.Financeiro.BancosController' not found."

**Comment by dotnetjunkie** [comment]
Please post the full stack trace.

**Comment by lira92** [comment]
Hi @dotnetjunkie I can't get full stack trace, but I did this implementation:

https://gist.github.com/lira92/09f92315b17a2bb1d692cbb6b685822f

it Works, but is uggly.
