### ISSUE TITLE
Prevent predicates for conditional registrations from running twice

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#346]
Deep down in the `Registration` class, during the generation of a `NewExpression`, the class causes the `InstanceProducer` instance for each dependency twice.

The first request is through the `IDependencyInjectionBehavior.BuildExpression` interface and is used to build up the actual expression tree. The `BuildExpression` implemention than calls back into the container to call the Container's internal `GetRegistrationEvenIfInvalid` method.

The second request when the `Registration` builds up the list of 'known relationships'. It does this by calling (again) into the `GetRegistrationEvenIfInvalid` method.

Requesting such `InstanceProducer` twice normally has no observable effect to the user, except when the dependency is a conditional registration. In that case the registration's predicate will be called twice, with the exact same context.

Although the performance penalty is usually low, it is confusing and counter intuitive that the library *allways* calls the predicate least twice for every consumer the dependency is injected into.

This unfortunate behavior is caused by the way Simple Injector has evolved over time. Simple Injector's diagnostic abilities (that use known relationships) did not exist during the time that the XXXBehavior strategies where added.

Since `IDependencyInjectionBehavior` is an important extension point through which users can change the way dependencies are constructed, the use of `IDependencyInjectionBehavior` can't be removed from `Registration`. Likewise does `Registration` need to get the `InstanceProducer` dependencies to build the list of known types; the diagnostic system completely relies on this. The only way to fix this issue is to make a breaking change to the `IDependencyInjectionBehavior` interface to let it return the `InstanceProducer`. There are a few ways this can be done, depending on the level of change we allow to be made:

 - Add an `out` parameter of type `InstanceProducer` to the `IDependencyInjectionBehavior.BuildExpression` method.
 - Change the return value of `IDependencyInjectionBehavior.BuildExpression` to be a tuple of some sort that contains both the `Expression` and the `InstanceProducer`.
 - Rename the `IDependencyInjectionBehavior.BuildExpression` to `GetProducer` and let it return the `InstanceProducer`.

Every option has its pro's and con's. The third option will for instance require the creation of `Expression` based `InstanceProducer`s to be simplified, since users now need to return a full `InstanceProducer` instead of just an `Expression`.

**Comment by YehudahA** [comment]
Please update this article.
https://cuttingedge.it/blogs/steven/pivot/entry.php?id=94

**Comment by dotnetjunkie** [comment]
@YehudahA, could you provide me with some more context of why you think that article needs to be updated?

**Comment by YehudahA** [comment]
See the implementation of ```IDependencyInjectionBehavior```.

``` cs
public Expression BuildExpression(InjectionConsumerInfo consumer) 
 {
        return this.convention.CanResolve(consumer.Target)
            ? this.convention.BuildExpression(consumer)
            : this.decoratee.BuildExpression(consumer);
    }
```

**Comment by dotnetjunkie** [comment]
Now I see. You are correct, the definition of the `IDependencyInjectionBehavior` has changed in Simple Injector v4. You should replace that code snippet with the following:

``` c#
public InstanceProducer GetInstanceProducer(InjectionConsumerInfo consumer, bool throwOnFailure)
{
    if (!this.convention.CanResolve(consumer.Target))
    {
        return this.decorated.GetInstanceProducer(consumer, throwOnFailure);
    }

    return InstanceProducer.FromExpression(
        serviceType: consumer.Target.TargetType,
        expression: this.convention.BuildExpression(consumer),
        container: this.container);
}
```

For the full code sample, please take a look [here](https://github.com/simpleinjector/SimpleInjector/blob/v4.0.x/src/SimpleInjector.CodeSamples/ParameterConventionExtensions.cs).
