### ISSUE TITLE
Problem with scoping in Web API after updating from 2.7.3 to 2.8.0

### ISSUE THREAD

**Issue by Tornhoof** [simpleinjector/SimpleInjector#35]
Hi,
I tried to use the new 2.8.0 version and noticed that all my OWIN httplistener tests fail now with the following exception:

An error has occurred.","ExceptionMessage":"Cannot reuse an 'ApiController' instance. 'ApiController' has to be constructed per incoming message. Check your custom 'IHttpControllerActivator' and make sure that it will not manufacture the same instance."

I uploaded my test project to http://s000.tinyupload.com/index.php?file_id=51564532068892027082
This test project is a heavily reduced version of an evaluation project, if I can replace autofac by simple injector.

Setup:

1. One Engine class, doing the container registration and setup
2. Services and Controllers registered in that class
3. A hybrid lifestyle of ExecutionContext and WebApiRequest
4. I basically want to use the same "Engine" for both command line applications and for the Web project

In my test class I basically test two things, first that the Standalone resolving works (for the command line application) and if I can talk to an owin  httplistener resolving all the controllers. (see the NUnit tests in the test project).

In 2.7.3 I could start my executionscope in the Engine and it worked for standalone, owin tests and IIS
In 2.8.0, if I start my executionscope in the Engine it only works for standalone and IIS, but not for the owin tests anymore.

I saw that you changed the webapi scope generation to be dependent on a previously existing scope, i.e. create the webapi scope only if no other scope exists (work item 21015). This works fine for IIS apparently, but for the Owin Httplistener apparently the executioncontext is still the same, so it never starts a new scope for each request resulting in the above error message. If i understand the scope stuff correctly, I basically had a nested scope previously (executioncontext first then the forced webapi request context), which is basically the same as I did in Autofac

I'm perfectly aware that I could pass the owin test server some setting to not start the executioncontext only for the owin part, but i would prefer not to, since currently I only have two execution paths for testing (standalone and web) and with that setting I have three paths (standalone, owin test and IIS).

I also know that I could easily write my own dependencyresolver which uses the old way, but i would prefer to use yours.

That's why I'm asking myself, is this a regression, is my Idea to have one Engine for both types of application completely nuts or did I miss something?

Regards,
Torni.

**Comment by dotnetjunkie** [comment]
I hate when that happens. We had analysed and discussed this change back and forward and concluded that the changes of breaking anybody's code was very slim. But it seems we misjudged this. The irony of this all is that the main reason for this behavioural change in the SimpleInjectorWebApiDependencyResolver is to be able to integrate more easily with OWIN.

 I will take a look at the code you uploaded tomorrow to better understand the issue and report back to you after that. 

Thanks for taking the time to report this.

**Comment by dotnetjunkie** [comment]
Do note btw that the `WebApiRequestLifestyle` is exactly the same as the `ExecutionContextScopeLifestyle`, but with just a more convenient name. So having a hybrid lifestyle mixing both the `WebApiRequestLifestyle` and `ExecutionContextScopeLifestyle` is rather useless. Just use one or the other.

**Comment by dotnetjunkie** [comment]
I pushed version 2.8.1 of the SimpleInjector.Integration.WebApi package to NuGet. In this new version, `SimpleInjectorWebApiDependencyResolver` contains an overloaded constructor that takes in a `DependencyResolverScopeOption`. This allows you to override the new behaviour in 2.8 and fallback to the old behaviour as follows:

``` c#
new SimpleInjectorWebApiDependencyResolver(container, DependencyResolverScopeOption.RequiresNew)
```

**Comment by Tornhoof** [comment]
Thank you very much, I can verify that 2.8.1 and the fallback behaviour fixes my problem and thank you for your suggestion about the scope.

I will close this bug for now and you can set it to done.
