### ISSUE TITLE
Reconsider initialization behavior of RegisterSingleton<TService>(TService)

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#353]
Considering the following code:

``` c#
container.RegisterSingleton<IService>(new MyService());
container.RegisterInitializer<MyService>(c => c.ConnectionString == "foobar");
```

Simple Injector v3 will not run the initializer for `MyService` when resolving `IService`, even though it has all the type information available to do this.

Reason for this is to keep the behavior identical to the following:

``` c#
container.Register<IService>(() => new MyService());
container.RegisterInitializer<MyService>(c => c.ConnectionString == "foobar");
```

With the registration of the delegate, Simple Injector does not have the information of the implementation type available and will never be able to run the initializer.

But take a look at the following registration:

``` c#
container.Register<IService, MyService>();
container.RegisterInitializer<MyService>(c => c.ConnectionString == "foobar");
```

Here Simple Injector actually has the type information available and this will cause the initializer to run on `MyService`.

Question now becomes: how should `RegisterSingleton<TService>(TService)` behave: Like `Register<TService>(Func<TService>)` or like `Register<TService, TImplementation>()`?

Should we change the v3 behavior in v4?

**Comment by dotnetjunkie** [comment]
The current behavior in v3 is very inconsistent. While some code paths use the service type for the creation of such singleton, other features use the implementation type.

**Comment by TheBigRic** [comment]
I'm having a hard time understanding the problem and the question... 

> The current behavior in v3 is very inconsistent.

Only thing I can say at this moment is that inconsistency should be prevented. On the other hand, I never came across questions regarding this, so apparently everything works well enough from a users perspective.

**Comment by dotnetjunkie** [comment]
In the meantime, Simple Injector v4 was released. That version renamed `RegisterSingleton<T>(T)` to `RegisterInstance<T>(T)`. This makes the difference between that call and the other singleton-registration operations more obvious. Because of that, I decided to keep this behavior as-is.
