### ISSUE TITLE
Disposable Transient Components (WebApi Controllers) - Warning still exists in 2.8

### ISSUE THREAD

**Issue by tynor88** [simpleinjector/SimpleInjector#36]
The warning still exists in version 2.8, but according to this post on Stackoverflow, it was fixed in 2.8 http://stackoverflow.com/questions/28542970/simple-injector-lifestyle-warnings-for-web-api-controllers

I am using the ```_container.RegisterWebApiControllers(config)``` overload to register my Webapi controllers. I am analyzing the container with this method ```Analyzer.Analyze(_container)```

**Comment by dotnetjunkie** [comment]
I'm unable to reproduce this issue. Can you show a code it takes to reproduce this?

**Comment by tynor88** [comment]
Sorry, please ignore this. For some reason my nuget manager was showing my package was updated to the newest version, but the reference in my project was not. I have updated it again, and everything is fine - there is no warning for WebApi controllers.
