### ISSUE TITLE
Drop support for ambient context-less scoping

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#365]
With #226 we added to possibility to flow `Scope` instances through the object graph, instead of using Ambient Context styles that depended on `AsyncLocal<T>` or `ThreadLocal<T>`.

Issue #364 however proves that this feature isn't complete yet.

The advantages of context-less scoping are slim however:
 - The performance benefits are neglectable.
 - Every modern platform has support for the required ambient context (Simple Injector can always be used).

Major downside of context-less scoping is the increased complexity that this model brings for the user, which is something that can be easily understood from #364.

Since there is ATM no documentation about this feature, chances are small that users are actually using this feature.

Instead of investing into this feature (as #364 suggests), we should instead drop this feature completely.

**Comment by TheBigRic** [comment]
This seems the best option!

**Comment by dotnetjunkie** [comment]
In case we drop support in v4, we should probably mark it as deprecated in v3.3.

**Comment by dotnetjunkie** [comment]
Aaannnd.....  it's gone :)
