### ISSUE TITLE
AccountController set up guide

### ISSUE THREAD

**Issue by vashue** [simpleinjector/SimpleInjector#37]
Hello,

I am quite new about IoC and simpleInjector.

I am following the document and I just installed SimpleInjector.Integration.WebApi.WebHost.QuickStart package.(vs2013, asp.net mvc5, web api.2.2, individual identification)

I cannot get over the AccountController injection. 

Could I get a step by step guide to set up AccountController using SimpleInjector?
I google it heaps but really hard to find a guide.

Sincerely,

**Comment by dotnetjunkie** [comment]
The default ASP.NET template that gets pre-installed with VS2012 and VS2013 are about the worst templates you can imagine. It lures developers into a ton of bad practices.

The easiest way to get your application working is to remove the overloaded constructor of the `AccountController` class.

You can find a more detailed discussion about this [here](https://simpleinjector.codeplex.com/discussions/564822).

**Comment by vashue** [comment]
@dotnetjunkie Thank you so much (x1000). The link is really really helpful.
Could I ask little bit more?
You said VS2012 & VS2013 Authentication template is terrible.

How about VS2015RC template?
Could you recommend an authentication source which has a good structure I can study?

**Comment by dotnetjunkie** [comment]
Unfortunately I'm not familiar with the VS2015RC template, so I can't feedback on that. Neither can I point at any authentication source for you. I would say that you should stick to the good practices. I would say this basically means: stick to the SOLID principles (which is hard enough to do). A good book that teaches the SOLID principles is Robert Martin's [Agile Principles and Patterns](http://www.amazon.com/Software-Development-Principles-Patterns-Practices/dp/0135974445) and after that, you should read Mark Seemann's [Dependency Injection in .NET](http://www.manning.com/seemann/). You might also find some articles of myself interesting, such as [this one](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91) and [this one](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=92).

**Comment by vashue** [comment]
@dotnetjunkie Words can't describe how thankful I am :+1:

**Comment by dotnetjunkie** [comment]
When using ASP.NET vNext with Visual Studio 2015, also take a look at [this thread about integrating Simple Injector with vNext](https://github.com/simpleinjector/SimpleInjector/issues/41).
