### ISSUE TITLE
Visual Studio .NET 2017 RC build error for SimpleInjector.Integration.AspNetCore

### ISSUE THREAD

**Issue by deastr** [simpleinjector/SimpleInjector#379]
Hi,

I'm using VS.NET 2017 RC (Version 15.0.26206.0 D15REL) and when I add `SimpleInjector.Integration.AspNetCore` using NuGet the project  fails to build:

`RG003	TargetFrameworkName is not recognized as a PCL or package based framework. Specify NuSpecTfm instead of using 'auto'`

`RG001	Only PCLs are supported by this tool. TargetFrameworkProfile or TargetFrameworkVersion is missing`

`MSB3073	The command ""C:\Users\deastr\.nuget\packages\nuspec.referencegenerator\2.0.0-beta-bld14\build\portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10\..\..\tools\RefGen.exe" generate-single -m ".NETFramework,Version=v4.5.2;" -t auto -n "D:\Projects\MyProject.nuspec" -p "D:\Projects\MyProject.csproj" -f "D:\Projects\MyProject\bin\Debug\net452\MyProject.exe"" exited with code -1`

.NET version:
```
dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

Project is ASP.NET MVC Core project targeting .NET 4.5.2:

```
<PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
  </PropertyGroup>
```

**Comment by dotnetjunkie** [comment]
Thanks for reporting this. 

At this time I've got no solution for this problem. Try adding the dependency by hand, or use VS 2015 instead.

**Comment by deastr** [comment]
Thanks. I've manually added SimpleInjector.Integration.AspNetCore.dll (4.5.1) and it builds now.

As for an additional info, SimpleInjector package just builds fine.

**Comment by dotnetjunkie** [comment]
Weird shit.

**Comment by sharifmamun** [comment]
@dotnetjunkie I am actually getting the exact same issue for `SimpleInjector.Integration.AspNetCore.Mvc`, in my case I have some other projects, which crash if I upgrade to any version later than 3.3.0. I am not sure if anyone else reported this issue recently as this issue was raised more than two and half years back.
