### ISSUE TITLE
Multi DLL's - WebAPI

### ISSUE THREAD

**Issue by riwos** [simpleinjector/SimpleInjector#386]
Hi, 
I have a problem with some dll's and reference them. Maybe I've missed some posts but I did not find post like that. Anyway, I want explain my situation and maybe someone will be able to help me. I do not have any idea how to fix that. I will read documentation again from start to end becuse maybe I missed something important, but please help me :)

ASP.NET:

Project has dll A and has class for example BaseA

``` c#
public class BaseA : System.Web.HttpApplication
{
    protected void Application_Start()
    {
        AreaRegistration.RegisterAllAreas();
        GlobalConfiguration.Configure(WebApiConfig.Register);
        FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
        RouteConfig.RegisterRoutes(RouteTable.Routes);

        var container = new Container();
        container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
        container.Register<IUnitOfWork, UnitOfWork>(Lifestyle.Transient);
        Init(container);
        container.RegisterWebApiControllers(GlobalConfiguration.Configuration);
        container.Verify();
        GlobalConfiguration.Configuration.DependencyResolver =
            new SimpleInjectorWebApiDependencyResolver(container);
    }

    public virtual void Init(Container container)
    {
    }
} 
```
Ok, I've created another project ( called B) where I referenced DLL A. This project has class ChildB

``` c#
public class ChildB : BaseA
{
    public override void Init(SimpleInjector.Container container)
    {
        container.Register<IRepository<Model.customer>,
            Repository<Model.customer>>(Lifestyle.Transient);

        container.Register<IRepository<Model.order>,
            Repository<Model.order>>(Lifestyle.Transient);
    }
}
```
The last one project is the web project which referenced DLL A and B and has file Global.asax like this:

``` c#
public class MvcApplication : ChildB
{
    
}
```

After that I want to run web project but I have a error:  

> Could not load file or assembly 'SimpleInjector, Version=3.2.2.0, Culture=neutral, PublicKeyToken=984cb50dea722e99' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

> Line 1:  <%@ Application Codebehind="Global.asax.cs" Inherits="MvcApplication" Language="C#" %>

I am not a expert about DI, but I think my scenario is not difficult but maybe I am not aware something or I should not make something like that...

**Comment by dotnetjunkie** [comment]
This seems like a binding redirect problem. This is typically caused by NuGet not doing its job. You should check whether all assemblies reference the same version of Simple Injector v3.2.2.0.

About your application, prevent using your DI container inside class libraries. Instead, apply the concept of the [Composition Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/), which means that you encapsulate your container with all its registrations inside the entry-point of the start-up project.

**Comment by riwos** [comment]
1. Assembly version fixed
2. Your link: [Composition Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/) closed discussion for any cases like mine. The link explains everything, many thanks, I owe you a beer.
