### ISSUE TITLE
Never fail silently and Roslyn

### ISSUE THREAD

**Issue by ScarlettCode** [simpleinjector/SimpleInjector#390]
Hi, just a question about whether something is technically possible.

I love the things never fail silently so as soon as you try load any page it'll let you know that

`
The constructor of type SomeService contains the parameter with name 'SomeRepository' and type ISomeRepository that is not registered. Please ensure ISomeRepository is registered, or change the constructor of SomeService.`

That's easy to fix, and rebuild but you still only get this message once you've built and try run the app. Would it be possible to look into Roslyn and add these errors as compiler errors before you even build?

Thanks

**Comment by dotnetjunkie** [comment]
Is it possible to integrate with Roslyn? Absolutely! But it won't be easy and that's why we never pursued that course.

The thing we currently advise is to call Verify

**Comment by dotnetjunkie** [comment]
There is an [old Codeplex discussion](https://simpleinjector.codeplex.com/discussions/542618) from 2014 where we started to discuss what useful things we could do in Roslyn. Main difficulty is that batch-registration makes it quite hard to do analysis in Roslyn.

**Comment by Sebazzz** [comment]
The main problem with Roslyn is that you would be duplicate implementing the entire business logic of the library but you gain very little. It is best to either call verify or set-up your container in some kind of unit test.

**Comment by dotnetjunkie** [comment]
I'm closing this discussion for now, since I don't see any possibility to integrate S.I. with Roslyn.
