### ISSUE TITLE
RegisterMvcControllers(): No service for type ApplicaitonPartManager has been registered

### ISSUE THREAD

**Issue by solomon87** [simpleinjector/SimpleInjector#391]
Exception is thrown when calling container.RegisterMvcControllers(). I'm trying to replicate the example given in the [ASP.NET Core MVC Integration Guide](http://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html).

**Versions**
 - SimpleInjector: v3.2.2
 - SimpleInjector.Integration.AspNetCore: v3.2.2
 - **SimpleInjector.Integration.AspNetCore.Mvc:** v3.3.2
 - Microsoft.AspNetCore: v1.1.1
 - Microsoft.AspNetCore.Mvc: v1.1.2

**Message**

> No service for type 'Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager' has been registered

**My startup file**
```c#
public class MvcStartup
{
    private Container container = new Container();

    public MvcStartup(IHostingEnvironment env)
    {
        // ASP.NET default stuff here
    }

    // This method gets called by the runtime.
    public void ConfigureServices(IServiceCollection services)
    {
        // ASP.NET default stuff here

        services.AddSingleton<IControllerActivator>(
            new SimpleInjectorControllerActivator(container));
        services.AddSingleton<IViewComponentActivator>(
            new SimpleInjectorViewComponentActivator(container));
    }

    // Configure is called after ConfigureServices is called.
    public void Configure(IApplicationBuilder app, IHostingEnvironment env,
        ILoggerFactory factory)
    {
        app.UseSimpleInjectorAspNetRequestScoping(container);

        container.Options.DefaultScopedLifestyle = new AspNetRequestLifestyle();

        InitializeContainer(app);

        container.Verify();

        // ASP.NET default stuff here
    }

    private void InitializeContainer(IApplicationBuilder app)
    {
        // Add application presentation components:
        container.RegisterMvcControllers(app); // EXCEPTION THROWN HERE
        container.RegisterMvcViewComponents(app);

        // Cross-wire ASP.NET services (if any). For instance:
        container.RegisterSingleton(app.ApplicationServices.GetService<ILoggerFactory>());
        // NOTE: Prevent cross-wired instances as much as possible.
        // See: https://simpleinjector.org/blog/2016/07/
    }
}
```

**Comment by dotnetjunkie** [comment]
You will at least have to call `services.AddMvcCore()` inside the `ConfigureServices` method. Otherwise no MVC registrations are made and the required `ApplicationPartManager` is missing.

**Comment by solomon87** [comment]
Ah okay, thanks for pointing this out. I missed that bit on Microsoft's startup documentation. I submitted a pull request to clear up some of the confusion in the integration guide. I submitted a pull request in simpleinjector/Documentation#58 to update the documentation with the necessary MVC configuration.

**Comment by dotnetjunkie** [comment]
I notided your pull request. Thanks for taking the time for that. I have some problems with this PR though, which I discussed on the PR.
