### ISSUE TITLE
Allow dependency to be injected with additional metadata

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#393]
A similar feature already exists but is currently only available for decorators, where a [decorator context can be injected](https://simpleinjector.readthedocs.io/en/latest/aop.html#using-contextual-information-inside-decorators). This allows the decorator to read metadata for the given dependency, like the actual implementation type and any applied decorators:

``` c#
public class TransactionCommandHandlerDecorator<T> : ICommandHandler<T> {
    public TransactionCommandHandlerDecorator(
        // DecoratorContext will be supplied automatically by Simple Injector to decorators
        DecoratorContext decoratorContext, ICommandHandler<T> decoratee) {
        // Access implementation type
        decoratorContext.ImplementationType;
    }

    public void Handle(T command) => ...
}
```

This however would be useful generally, where inject the dependency, wrapped in a metadata object and inject this into an adapter that's part of the composition root.

A practical use case for this is when some message dispatcher must forward the message to one of the supplied handlers, based on its concrete type, where those handlers might be decorated (which means the original type can't be retrieved using instance.GetType()).

Here are some ideas of what we might do:

``` c#
// Wrap the dependency in a Metadata<T> object
public Consumer(Metadata<IHandler<ShipOrder>>> handler) { ... }

// Or inject a collection of Metadata<T> objects
public Consumer(IEnumerable<Metadata<IHandler<T>>> handlers) { ... }

// Inject InstanceProducer
// Advantage of InstanceProducer is that it is a factory and contains some metadata
// (but not much).
public Consumer(InstanceProducer<IHandler<ShipOrder>> handlerFactory) { ... }

// Or a collection of InstanceProducers.
public Consumer(IEnumerable<InstanceProducer<IHandler<T>>> factories) { 
    this.handlers = factories.ToList().ToDictionary(
        keySelector: x => x.ImplementationType,
        itemSelector: x => x);

    // Usage
    this.handlers[typeof(ShipOrderHandler)].GetInstance().Handle(message);
}

// Inject Metadata<Func<T>>
// This mixes the factory behavior of InstanceProducer, while allowing extra metadata 
// to be added. Perhaps Metadata<T> can be used by decorators as well.
public Consumer(IEnumerable<Metadata<Func<IHandler<T>>>> handlers) { ... }
```

**Comment by dotnetjunkie** [comment]
[feature-393](https://github.com/simpleinjector/SimpleInjector/tree/feature-393) branch created.

**Comment by dotnetjunkie** [comment]
I went with the reuse of `InstanceProducer<T>` as metadata container. `InstanceProducer<T>` and `IEnumerable<InstanceProducer<T>>` (and other collection types) can now be injected into consumers.

I went with the injection of `InstanceProducer<T>` because this allows reuse of existing types. In other words, it doesn't increase the API. For now, the implemented feature is limited, because there isn't a lot of metadata on `InstanceProducer` at the moment (no list of applied decorators, for instance), but this can be added in a future release.

This change introduced the following API changes:
* Removed the `where TService : class` type constraint from `InstanceProducer<TService>`
* Constructor of `InstanceProducer` became obsolete
* `InstanceProducer.Create` factory methods added
* New generic overloads of `Container.GetRegistration` (i.e.`Container.GetRegistration<TService>()` and `Container.GetRegistration<TService>(bool)`)  methods added.

**Comment by qujck** [comment]
Does this feature introduce vendor lock-in?

**Comment by dotnetjunkie** [comment]
It's hard to imagine being able to supply metadata without the use of custom types, similar to what `SimpleInjector.DecoratorContext` already achieves for decorators. As long as `InstanceProducer<T>` (and `DecoratorContext`) are solely used within the [Composition Root](https://freecontent.manning.com/dependency-injection-in-net-2nd-edition-understanding-the-composition-root/), there is no issue of vendor lock-in. When used outside the Composition Root, things obviously start to change and such feature would more easily cause a vendor lock-in for sure.

**Comment by qujck** [comment]
Is there an option for defining a type outside SI and configuring a mapping in the container for how available values should be mapped to it at runtime?

**Comment by dotnetjunkie** [comment]
It needs some custom adapters within your Composition Root, but sure; you can do the following:

``` c#
// Application code
public interface IMetadataThingy<T>
{
    T Get();
    Type ImplementationType { get; }
}

// Inside Composition Root
public class SimpleInjectorMetadataThingyAdapter<T> : IMetadataThingy<T>
{
    private readonly InstanceProducer<T> producer;
    public SimpleInjectorMetadataThingyAdapter(InstanceProducer<T> producer) =>
        this.producer = producer;

    public T Get() => this.producer.GetInstance();
    public Type ImplementationType => this.producer.ImplementationType;
}

// Allows injecting metadata enumerabes
public class SimpleInjectorMetadataThingyAdapterCollection<T>
    : IEnumerable<IMetadataThingy<T>>
{
    private readonly IEnumerable<IMetadataThingy<T>> thingies;

    public SimpleInjectorMetadataThingyAdapterCollection(
        IEnumerable<InstanceProducer<T>> producers)
    {
        this.thingies = producers
            .Select(p => new SimpleInjectorMetadataThingyAdapter<T>(p))
            .OfType<IMetadataThingy<T>>()
            .ToArray();
    }

    public IEnumerator<IMetadataThingy<T>> GetEnumerator() => this.thingies.GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
}

// Registration
container.RegisterSingleton(
    typeof(IMetadataThingy<>),
    typeof(SimpleInjectorMetadataThingyAdapter<>));

container.RegisterSingleton(
    typeof(IEnumerable<>),
    typeof(SimpleInjectorMetadataThingyAdapterCollection<>));
```

Now you can depend on the following:

``` c#
public Component(
    IMetadataThingy<IService> serviceMetadata,
    IEnumerable<IMetadataThingy<ILogger> loggersMetadata)
```

**Comment by dotnetjunkie** [comment]
The injection of `InstanceProducer<T>` as form of metadata-container has some unfortunate downsides that I didn't consider before. It considerably slows down the registration phase.

This design forces all instance producers to be `InstanceProducer<T>` implementations. This is problematic, because it forces all non-generic registrations (which will be be the majority of registrations in big applications due to the use of Auto-Registration) to use slow reflection calls to create generic `InstanceProducer<T>` instances (by calling `Activator.CreateInstance(typeof(InstanceProducer<>).MakeGenericType(type))`).

These slow reflection calls can't be speed up using expression tree compilation, because there will typically be exactly one closed-generic `InstanceProducer<T>` instance, making any other method (for instance using expression tree compilation) much slower. This slow reflection can take up to 50% of the registration phase, which is way too much for such a feature.

Conclusion: back to the drawing board on this one. I'll re-implement this feature using a new `DependencyMetadata<TService>` class instead.

**Comment by dotnetjunkie** [comment]
This change introduced the following API changes:

* `SimpleInjector.DependencyMetadata<TService>` class added
* Removed the `where TService : class` type constraint from `InstanceProducer<TService>`
* `InstanceProducer.ImplementationType` property added to allow retrieving the originally registered implementation type. Note that `InstanceProducer.Registration.ImplementationType` changes after a decorator is applied and can, therefore, not used to determine the original implementation.
