### ISSUE TITLE
Integration.WebApi 4.0.0 package depends on deprecated Extensions.ExecutionContextScoping 4.0.0 package

### ISSUE THREAD

**Issue by Tornhoof** [simpleinjector/SimpleInjector#395]
This looks like an error, either the context scopign package should not be deprecated or more likely the dependency in the webapi package is too much.

**Comment by Tornhoof** [comment]
Ah found it, your nuspec still contains the reference:
https://github.com/simpleinjector/SimpleInjector/blob/master/src/BuildTools/Nuget/.NET/SimpleInjector.Integration.WebApi/SimpleInjector.Integration.WebApi.nuspec.

I guess simply removing the ExecutionContextScoping line (line 12) from the nuspec should do the trick. I can't provide a pull  request, because I can't test it on my machine here, I have problems with VS 2017 atm.

**Comment by dotnetjunkie** [comment]
Ouch. Good catch. Will push a patch release a.s.a.p.

**Comment by dotnetjunkie** [comment]
I pushed version 4.0.1 of the Web API integration package. That fixes the problem.
