### ISSUE TITLE
Configuration for ReactiveUI

### ISSUE THREAD

**Issue by vector-man** [simpleinjector/SimpleInjector#396]
Hi. I'm not sure whether to ask this question here or at ReactiveUI. I'm trying to replace Splat in ReactiveUI with SimpleInjector. I am using the package addon for SI. Here's my configuration:

``` c#
public void RegisterServices(Container container)
{
    Locator.Current = new FuncDependencyResolver((service, contract) =>
    {
        if (contract != null) return container.GetAllInstances(service);
        var items = container.GetAllInstances(service);
        var list = items.ToList();
        return list;
    },
    (factory, service, contract) =>
    {
        container.AppendToCollection(service,
            Lifestyle.Transient.CreateRegistration(service, container));
    });
}
```

As soon as I use Bind in my project, this throws an exception:

> An exception of type 'System.TypeInitializationException' occurred in Project1.Windows.dll but was not handled in user code
>
> Additional information: The type initializer for 'ReactiveUI.BindingMixins' threw an exception.

**Comment by dotnetjunkie** [comment]
With the current amount of detail, your best bet is to ask this on the ReactiveUI forum. I'm not sure if there is anyone following these issues that has experience with ReactiveUI, but I sure don't.

**Comment by vector-man** [comment]
Okay, thank you!

**Comment by vector-man** [comment]
The problem looks like this: "{"The container can't be changed after the first call to GetInstance, GetAllInstances and Verify. Please see https://simpleinjector.org/locked to understand why the container is locked.
