### ISSUE TITLE
Scope ends after OAuthBearerAuthentication middleware

### ISSUE THREAD

**Issue by Kahbazi** [simpleinjector/SimpleInjector#401]
I'm using OAuthAuthentication with SimpleInjector in Owin. I follow the [OWIN Integration Guide](http://simpleinjector.readthedocs.io/en/latest/owinintegration.html) to write my code.
the problem is I get this exception after `OAuthBearerAuthentication` middleware

> The Startup.Foo is registered as 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope.

It appears somehow `AsyncScopedLifestyle` ends in `OAuthBearerAuthentication` middleware. I know this middleware has nothing to do with simpleinjector and is written by Microsoft, but is there any workaround to solve this issue?

``` c#
public class Startup
{
    public void Configuration(IAppBuilder app)
    {
        var container = new Container();
        container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
        container.Register<Foo, Foo>(Lifestyle.Scoped);

        app.Use((context, next) =>
        {
            using (var scope = AsyncScopedLifestyle.BeginScope(container))
            {
                scope.WhenScopeEnds(() => Console.WriteLine("End of Scope"));
                return next();
            }
        });

        app.Use((context, next) =>
        {
            container.GetInstance<Foo>(); // Works fine!
            return next();
        });

        app.UseOAuthBearerAuthentication(
            new Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationOptions());

        app.Use((context, next) =>
        {
            container.GetInstance<Foo>(); // Exception occurs!
            return next();
        });
    }

    public class Foo
    {
    }
}
```

**Comment by dotnetjunkie** [comment]
I'm insure what causes the `UseOAuthBearerAuthentication` to 'kill' the current asynchronous context, but you can fix this by moving the `UseOAuthBearerAuthentication` call up in your configuration:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
container.Register<Foo, Foo>(Lifestyle.Scoped);

// Place this method before starting the AsyncScopedLifestyle
app.UseOAuthBearerAuthentication(
    new Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationOptions());

app.Use((context, next) =>
{
    using (var scope = AsyncScopedLifestyle.BeginScope(container))
    {
        scope.WhenScopeEnds(() => Console.WriteLine("End of Scope"));
        return next();
    }
});

app.Use((context, next) =>
{
    container.GetInstance<Foo>();
    return next();
});

app.Use((context, next) =>
{
    container.GetInstance<Foo>();
    return next();
});
```

**Comment by Kahbazi** [comment]
well your method will definitely work, but I can't move my middleware.
I looked up in `UseOAuthBearerAuthentication()` , it seems like this line : `app.UseStageMarker(PipelineStage.Authenticate);` is 'killing' the  current asynchronous context. I replace the middleware with this line and still get the error

```
public class Startup
{
    public void Configuration(IAppBuilder app)
    {
        var container = new Container();
        container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
        container.Register<Foo, Foo>(Lifestyle.Scoped);

        app.Use((context, next) =>
        {
            using (var scope = AsyncScopedLifestyle.BeginScope(container))
            {
                scope.WhenScopeEnds(() => Console.WriteLine("End of Scope"));
                return next();
            }
        });

        app.Use((context, next) =>
        {
            container.GetInstance<Foo>(); // Works fine!
            return next();
        });

        //app.UseOAuthBearerAuthentication(new Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationOptions());
        app.UseStageMarker(PipelineStage.Authenticate);

        app.Use((context, next) =>
        {
            container.GetInstance<Foo>(); // Exception occurs!
            return next();
        });
    }

    public class Foo
    {
    }
}
```

And also all of these examples work fine in Owin Self Host environment, it's in the IIS that exception occurs, and now it makes sense since `UseStageMarker()` choose in which IIS integrated pipeline, middlewares must execute. maybe this code changes execution pipeline and asynchronous context is only available in its own pipeline

**Comment by dotnetjunkie** [comment]
What you can do is start a second scope after the `UseStageMarker` call. This does mean that there are practically two scopes in the application, which means that each scope will get its own scoped instance. You have to do some analysis whether this is a workable solution, but I think this would typically not be a problem, since the operations you do at that boundary of the request, often don't require that same scope. But your mileage can obviously vary.

**Comment by Tornhoof** [comment]
Yes, the second scope is what I do, I have my own Scope middleware which always starts a scope as early as possible
```csharp
app.UseOAuthAuthorizationServer(oAuthOptions);
app.UseOAuthBearerAuthentication(oAuthBearerOptions);
app.UseExecutionScopeMiddleware(engine);
```
and the execution scope middleware (it's still the simpleinject 3 naming and ignore the engine, it's just a wrapper, you should get the idea) looks like:

```csharp
    public class ExecutionContextScopeMiddleware : OwinMiddleware
    {
        private readonly Engine m_Engine;

        public ExecutionContextScopeMiddleware(OwinMiddleware next, Engine engine)
            : base(next)
        {
            m_Engine = engine;
        }

        [DebuggerStepThrough]
        public override async Task Invoke(IOwinContext context)
        {
            using (m_Engine.BeginExecutionContextScope())
            {
                await Next.Invoke(context).ConfigureAwait(true);
            }
        }
    }

    public static class ExecutionContextScopeExtension
    {
        public static IAppBuilder UseExecutionScopeMiddleware(this IAppBuilder app, Engine engine)
        {
            app.Use(typeof(ExecutionContextScopeMiddleware), engine);
            app.UseStageMarker(PipelineStage.AcquireState);
            return app;
        }
    }
```
