### ISSUE TITLE
Issue when setting DefaultScopedLifestyle to WebRequestLifestyle in MVC5 application

### ISSUE THREAD

**Issue by feugen24** [simpleinjector/SimpleInjector#402]
Hi,

After upgrading to latest version 3 I used the default WebRequestLifestyle as suggested in docs for default setting.

``` c#
var webLifestyle = new WebRequestLifestyle();
mvcContainer.Options.DefaultLifestyle = Lifestyle.Scoped;
mvcContainer.Options.DefaultScopedLifestyle = webLifestyle;
```
Everything worked fine until I got to a special case when recursively rendering a partial view to display some tree structure (it was calling another partial view witch called the first one).

This causes an exception because of how simple injector solves some(not sure what) dependency. (Controllers seem to be registered as Transient, I checked with debug)
Part of stack trace:

```
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.Stack`1.Peek()
at System.Web.WebPages.WebPageBase.Write(Object value)
at ASP._Page_Views_Shared_Posts__DetailsChildPostItem_cshtml.Execute() in ..._DetailsChildPostItem.cshtml
at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
at System.Web.Mvc.Html.RenderPartialExtensions.RenderPartial(HtmlHelper htmlHelper, String partialViewName, Object model)
at ASP._Page_Views_Shared_Posts__DetailsPostItemChildren_cshtml.Execute()
```
I managed to pinpoint the root of the problem(default web lifestyle) because other guys seemed to have similar problem with  [structuremap](https://github.com/webadvanced/Structuremap.MVC5/issues/14).

In my case the solution was simple, i just removed WebRequestLifestyle default lifestyle so it defaults to transient and i do all specific registrations by passing the WebRequestLifestyle . I just upgraded to v4 and it is the same behaviour.

I added this post because it took me some time to find the issue so maybe others get into this problem.

*btw: great work with v3+, it really helped me track hidden configuration issues and probably i won't use another DI if it has no verify functionality.

**Comment by dotnetjunkie** [comment]
@feugen24, how are you resolving views? You are resolving views with Simple Injector? How did you implement this?

**Comment by feugen24** [comment]
@dotnetjunkie It's very hard to remember the actual context after all this time. Views are created using view/partial view name +data model, they are not registered in Simple Injector nor do I try to resolve things with SI inside a view.

As I can't provide more context and others didn't have this problem, I think you can close this.

**Comment by dotnetjunkie** [comment]
I'm sorry for this 4 months delay. Your post went off the radar, because you didn't really have a question and it seemed more like you were documenting this (which is great, thank you for that). I now tried to analyze this to see whether there is something that could be improved in the Simple Injector integration libraries to make this problem go away.
