### ISSUE TITLE
After Simple Injector Update Web Api injection fails

### ISSUE THREAD

**Issue by boomtopper** [simpleinjector/SimpleInjector#410]
Hi,

Since updating Simple Injector today my web api constructor injection has stopped working and is now giving this as a response when called via ajax?

> An error occurred when trying to create a controller of type 'CreateNewProcedureHeaderController'. Make sure that the controller has a parameterless public constructor.

Downgrading to the version before seems to fix it.
Here is the global.asax for my web app

```vb.net
Imports SimpleInjector.Integration.WebApi
Imports System.Security.Claims
Imports System.Web.Helpers
Imports System.Web.Http
Imports System.Web.Optimization

Public Class MvcApplication
    Inherits System.Web.HttpApplication

    Protected Sub Application_Start()
        GlobalConfiguration.Configure(AddressOf WebApiConfig.Register)
        AreaRegistration.RegisterAllAreas()
        FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters)
        RouteConfig.RegisterRoutes(RouteTable.Routes)
        BundleConfig.RegisterBundles(BundleTable.Bundles)

        'This is need for the anti forgery token cookie
        AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.NameIdentifier
        'Setup Devexpress Model Binder
        ModelBinders.Binders.DefaultBinder = New DevExpress.Web.Mvc.DevExpressEditorsBinder()

        'Setup dependcy injection
        Dim container = Bootstrap()

        DependencyResolver.SetResolver(New SimpleInjector.Integration.Web.Mvc.SimpleInjectorDependencyResolver(container))
        GlobalConfiguration.Configuration.DependencyResolver = New SimpleInjectorWebApiDependencyResolver(container)
    End Sub
End Class
```

**Comment by dotnetjunkie** [comment]
Can you please supply us with more information:

- The version of Simple Injector you upgraded to.
- The version of Simple Injector you upgraded _from_.
- The full stack trace and other exception details of the exception _and all inner exceptions_.

**Comment by boomtopper** [comment]
@dotnetjunkie 
I upgraded from 4.0.0 to 4.0.2.
Here is my stack trace.

```
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "An error occurred when trying to create a controller of type 'CreateNewProcedureHeaderController'. Make sure that the controller has a parameterless public constructor.",
  "ExceptionType": "System.InvalidOperationException",
  "StackTrace": "   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)\r\n   at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()",
  "InnerException": {
    "Message": "An error has occurred.",
    "ExceptionMessage": "Attempt by security transparent method 'System.Threading.AsyncLocal`1<T>.get_Value()' to access security critical method 'System.Runtime.Remoting.Messaging.CallContext.LogicalGetData(System.String)' failed.\n\nAssembly 'SimpleInjector, Version=4.0.2.0, Culture=neutral, PublicKeyToken=984cb50dea722e99' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.",
    "ExceptionType": "System.MethodAccessException",
    "StackTrace": "   at System.Threading.AsyncLocal`1.get_Value()\r\n   at SimpleInjector.Lifestyles.AsyncScopedLifestyle.<>c__DisplayClass6_0.<CreateManager>b__0()\r\n   at SimpleInjector.Lifestyles.ScopeManager.get_CurrentScopeInternal()\r\n   at SimpleInjector.Lifestyles.ScopeManager.GetCurrentScopeWithAutoCleanup()\r\n   at SimpleInjector.Lifestyles.AsyncScopedLifestyle.GetCurrentScopeCore(Container container)\r\n   at SimpleInjector.ScopedLifestyle.GetCurrentScope(Container container)\r\n   at SimpleInjector.Integration.WebApi.SimpleInjectorWebApiDependencyResolver.System.Web.Http.Dependencies.IDependencyResolver.BeginScope()\r\n   at System.Net.Http.HttpRequestMessageExtensions.GetDependencyScope(HttpRequestMessage request)\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator)\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)"
  }
}
```

**Comment by dotnetjunkie** [comment]
To summarize, the error is this:

> Attempt by security transparent method 'System.Threading.AsyncLocal`1<T>.get_Value()' to access security critical method 'System.Runtime.Remoting.Messaging.CallContext.LogicalGetData(System.String)' failed. Assembly 'SimpleInjector, Version=4.0.2.0, Culture=neutral, PublicKeyToken=984cb50dea722e99' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.

**Comment by dotnetjunkie** [comment]
Well that sucks. Due to some project structural changes, the `AllowPartiallyTrustedCallersAttribute` was accidentally removed from v4.0.0, so I added it again in v4.0.2. Unfortunately though, the `AsyncScopedLifestyle` (which depends on `AsyncLocal<T>`) is now part of the core library. `AsyncLocal<T>` however doesn't seem to be able to cope with the calling library allowing partially trusted callers. This hasn't been a problem before. In v3, that lifestyle lived in an assembly that wasn't marked with `AllowPartiallyTrustedCallersAttribute`. Apparantly, everything works in that case, which is something I don't understand.

I will push a patch release that removes the `AllowPartiallyTrustedCallersAttribute`.

**Comment by boomtopper** [comment]
Letting you know that the update that has been pushed out updating to version 4.0.3 has fixed it now. Thanks.
