### ISSUE TITLE
GetInstance of IDisposable not in active scope

### ISSUE THREAD

**Issue by DrifterApps** [simpleinjector/SimpleInjector#412]
Hi,

I'm writing an Android application. I have a class registered which implements IDisposable. Version 4 states that the registration must be in scope. So I've done the registration like this:

`container.Register<ITransactionManager, TransactionManager>(Lifestyle.Scoped);

My issue is that I need this class for the life of my Activity.

If I get the instance in a scope, my class gets disposed as soon as I get out of the scope:

```
using(ThreadScopedLifestyle.BeginScope(container))
{
    manager = container.GetInstance<ITransactionManager>();
}
```

But if I get my instance like this, I get an an Exception with this message

> This method can only be called within the context of an active (Scoped) scope.

```
protected override void OnCreate(Bundle savedInstanceState)
{
    base.OnCreate(savedInstanceState);
    _scope = ThreadScopedLifestyle.BeginScope(container);
    manager = container.GetInstance<ITransactionManager>();
}

protected override void OnDestroy()
{
    base.OnDestroy();
    _scope?.Dispose();
}
```
Any ideas how I can resolve this?

Thanks

**Comment by dotnetjunkie** [comment]
That's a really weird exception to get. Can you please post the full exception details, i.e. stack trace, exception type and message of the exception and _all_ inner exceptions?

**Comment by DrifterApps** [comment]
Very sorry for this but I just found the problem... I should sleep more... the problem was between the chair and the keyboard...

The code I had put above was a simplification of my problem. My simplification fixed my problem.

All is fine now!!
