### ISSUE TITLE
Split SimpleInjector.Integration.AspNetCore.Mvc to Api and Razor

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [simpleinjector/SimpleInjector#413]
Hi,

I recently had to create some web api in .NET Core and wanted to use SimpleInjector.
I found good article how to strip MVC part out of API
https://andrewlock.net/removing-the-mvc-razor-dependencies-from-the-web-api-template-in-asp-net-core/ 
anyway the problem is that SimpleInjector.Integration.AspNetCore.Mvc has also dependencies to full MVC.
Will it be possible to split that integration package to two parts? One for pure WEB API and second dependant on it to also cover Razor services?

**Comment by dotnetjunkie** [comment]
Why is it a problem for you to have the Razor assemblies in your project?

**Comment by dotnetjunkie** [comment]
Fixed. You can now depend on [SimpleInjector.Integration.AspNetCore.Mvc.Core](https://www.nuget.org/packages/SimpleInjector.Integration.AspNetCore.Mvc.Core/) in case you're not interested in adding custom TagHelper activators.
