### ISSUE TITLE
Updating to SimpleInjector 4.0.3 Causes TypeAccessException

### ISSUE THREAD

**Issue by jmojiwat** [simpleinjector/SimpleInjector#415]
After updating SimpleInjector.Packaging to 4.0.3, I get the following error:

Attempt by security transparent method 'SimpleInjector.PackageExtensions.RegisterPackages(SimpleInjector.Container, System.Collections.Generic.IEnumerable`1<System.Reflection.Assembly>)' to access security critical type 'SimpleInjector.Container' failed.

when calling container.RegisterPackages.

Moving back to 4.0.2 removes the error.

I'm using MVC5 on .NET 4.6.2

**Comment by dotnetjunkie** [comment]
This issue is a duplicate of #410 and #408.

**Comment by dotnetjunkie** [comment]
@jmojiwat, but you can try out [SimpleInjector.Packaging 4.0.4](https://www.nuget.org/packages/SimpleInjector.Packaging/4.0.4).

**Comment by jmojiwat** [comment]
@dotnetjunkie I updated to SimpleInjector 4.0.6 and everything is working great again. Thank you very much Stephen and team for SimpleInjector.
