### ISSUE TITLE
How to get current scope with new CreateHybrid method

### ISSUE THREAD

**Issue by dvladimirovich** [simpleinjector/SimpleInjector#422]
I'm using SimpleInjector v4 and use new `CreateHybrid` functionality as you mentioned in this question [#340](https://github.com/simpleinjector/SimpleInjector/issues/340). But how could I then get current scope, depending on container (e.g. `_container.GetCurrentExecutionContextScope()`). Thanks!

**Comment by dotnetjunkie** [comment]
You will have to create a new scope first. Within the context of that scope, you can use `GetCurrentExecutionContextScope()` in v3 and `AsyncScopeLifestlye.GetCurrentScope(container)` in v4 to get the current scope.

**Comment by dvladimirovich** [comment]
`AsyncScopeLifestlye.GetCurrentScope(container)` says that I need to instantiate object for non static field...

**Comment by dotnetjunkie** [comment]
Correct. It's an instance field. You'll need to create an `AsyncScopedLifestyle` instance:

``` c#
var lifestyle = new AsyncScopedLifestyle();
container.Options.DefaultScopedLifestyle = lifestyle;

var current = lifestyle.GetCurrentScope(container);
```

**Comment by dvladimirovich** [comment]
Oh I understand, but what if my lifestyle is hibryd and defined in another class?

**Comment by dotnetjunkie** [comment]
You still do the same:

``` c#
var lifestyle = new AsyncScopedLifestyle();
container.Options.DefaultScopedLifestyle = Lifestyle.Hybrid(lifestyle, new WebRequestLifestyle());

// Somewhere else:
var current = lifestyle.GetCurrentScope(container);
```

**Comment by dvladimirovich** [comment]
Oh, I see. Thank you for such fast and intelligible answer!

**Comment by dotnetjunkie** [comment]
I simplified the code snippets a bit.

**Comment by dvladimirovich** [comment]
Ok, I see, thank you! But in a link I've mentioned in my first comment author says "If I use Lifestyle.Scoped.GetCurrentScope(Ioc.Container), it gives me a base Scope class which I can't choose the scope over another scope."

**Comment by dotnetjunkie** [comment]
I'm not sure I understand the problem. Can you explain what it is you are trying to achieve?

**Comment by dvladimirovich** [comment]
I'm trying to achieve current scope (it is hybrid in my variant). And I came up with this:
```
public class SimpleInjectorExecutionContextScopeEndFilter : JobFilterAttribute, IServerFilter
{
    private readonly Container _container;
    public SimpleInjectorExecutionContextScopeEndFilter(Container container)
    {
        _container = container;
    }

    public void OnPerforming(PerformingContext filterContext)
    {
        _container.BeginExecutionContextScope();
    }

    public void OnPerformed(PerformedContext filterContext)
    {
        var lifestyle = new AsyncScopedLifestyle();

        var scope = lifestyle.GetCurrentScope(_container);
        if (scope != null)
            scope.Dispose();
    }
}
```
In Bootstrap class:
```
public static void Bootstrap()
{
    Container = new Container();

    Container.Options.DefaultScopedLifestyle = Lifestyle.CreateHybrid(
            defaultLifestyle: new WebRequestLifestyle(),
            fallbackLifestyle: new AsyncScopedLifestyle());
    // ...
}
```

**Comment by dotnetjunkie** [comment]
Ahh, I see, you need to get a hold of the scope of the `AsyncScopedLifestyle` specifically. It's unfortunate that you're dealing with a design (the `JobFilterAttribute`) that splits the operation in two (namely `OnPerforming` and `OnPerformed`). If it was designed like a decorator, it would have been easier, since you could simply create a `using` statement.

Eitherway, what you're doing is correct.

You can cache the `AsyncScopedLifestyl` instance indefinately, there is no need in recreating it again and again:

``` c#
public class SimpleInjectorAsyncScopeFilterAttribute : JobFilterAttribute, IServerFilter
{
    private static readonly AsyncScopedLifestyle lifestyle = new AsyncScopedLifestyle();

    private readonly Container _container;
    
    public SimpleInjectorAsyncScopeFilterAttribute(Container container)
    {
        _container = container;
    }

    public void OnPerforming(PerformingContext filterContext) =>
        AsyncScopedLifestyle.BeginScope(_container);

    public void OnPerformed(PerformedContext filterContext) =>
        lifestyle.GetCurrentScope(_container)?.Dispose();
}
```

**Comment by dvladimirovich** [comment]
Am I right that if there will be `WebRequestScope` this situation will also work correctly or then I won't need to use `SimpleInjectorAsyncScopeFilterAttribute` and everything will work correct?

**Comment by dotnetjunkie** [comment]
That is something I can't comment on, because I'm unsure what framework you are using here. That said though, in general, when you are using that hybrid lifestyle that mixes Web Request and Async Scoped lifestyles, Simple Injector will automatically resolve from the correct scope.

If this attribute is applied to _all_ operations, you might even consider removing the hybrid lifestyle and use async scoped solely as your scoped lifestyle.

**Comment by dvladimirovich** [comment]
Thank you for your advice and I think its time when issue is solved)
