### ISSUE TITLE
Display Bug for Intellisense DebugDisplay Output in DiagnosticResult.cs

### ISSUE THREAD

**Issue by Tornhoof** [simpleinjector/SimpleInjector#424]
Hi,
I get an error message for the Debug Display Output in DiagnosticResult.cs in SimpleInjector 4.06
![error](https://cloud.githubusercontent.com/assets/7989549/26584113/fe818f8e-4547-11e7-89f8-e50179893720.png)

Steps to reproduce:
1. Create a container with an error during validation
2. Mouse-over the diagnostic result to see the validation error

**Comment by dotnetjunkie** [comment]
Thanks for reporting this. Will be fixed with the next patch release.

**Comment by dotnetjunkie** [comment]
I just pushed patch [release v4.0.8](https://www.nuget.org/packages/SimpleInjector/4.0.8) to NuGet that fixes this problem.
