### ISSUE TITLE
Resolving Non Generic Proxies of Generic Interfaces

### ISSUE THREAD

**Issue by ptsteward** [simpleinjector/SimpleInjector#426]
I came across an interesting issue when try to override a batch registration with a mock implementation produced by NSubstitute. The generated type name of the proxy contains the -> **\`** <- character which causes SimpleInjector to see the type as a generic type. When SimpleInjector then tries to determine the number of generic arguments it parses the end of the generated type name which returns, for example, **2Proxy**. This causes a format exception to be thrown since the expectation is that only a number comes after the -> **\`** <- . Here's a simple repro:

``` c#
using NSubstitute;
using NUnit.Framework;
using SimpleInjector;

namespace SimpleInjectorRepro {

    [TestFixture]
    public class SimpleInjectorProxyTests {

        [Test]
        public void NonGeneric_Proxy_Type_Name_Causes_FormatException() {
            var proxy = Substitute.For<IQueryHandler<MockQuery, MockResult>>();
            var container = new Container();
            container.Register(typeof(IQueryHandler<,>), proxy.GetType());
            
            Assert.Throws<ActivationException>(
                () => container.GetInstance<IQueryHandler<MockQuery, MockResult>>());

            //this name is parsed in src/SimpleInjector/Types.cs GetGenericArguments
            //Which causes it to attempt to convert 2Proxy to int
            Assert.AreEqual("IQueryHandler`2Proxy", proxy.GetType().Name);

            //Instead of trigger on `, just check IsGenericType
            Assert.IsFalse(proxy.GetType().IsGenericType);
        }
    }

    public interface IQueryHandler<TQuery, TResult> { }

    public class MockQuery { }

    public class MockResult { }
}
```

To correct this I'd propose to change 

**this:**

``` c#
 if (!type.Name.Contains("`"))
{
    return Enumerable.Empty<Type>();
}
```
**To:**

``` c#
 if (!type.IsGenericType)
{
    return Enumerable.Empty<Type>();
}
```

**Comment by dotnetjunkie** [comment]
Thanks for reporting this bug. Unfortunately, the fix is a bit more complex than that. Your fix will break in case the name of a nested type is generated, whose declaring type is a generic type. For instance:

``` c#
public class Parent<T>
{
    public class Nested { }
}
```

In that case `typeof(Parent<int>.Nested).IsGenericType` returns `true`, while `Nested` itself didn't declare any generic type arguments.

Instead, the `GetGenericArguments` should be rewritten to:

``` c#
type.IsNested
    ? type.GetGenericArguments().Skip(type.DeclaringType.GetGenericArguments().Length)
    : type.GetGenericArguments();
```

This is simpler, faster and much more reliable.

`type.GetGenericArguments().Skip(type.DeclaringType.GetGenericArguments().Length)` does the trick, because the list of generic arguments returned from `GetGenericArguments()` on a nested type will be prepended with the generic types of its base type. Thus, if we 'cut off' those prepended types, we have a reliable set of the generic arguments that the nested type declared itself, without having to juggle with string names.

**Comment by ptsteward** [comment]
Awesome, thanks for jumping right on this!

**Comment by dotnetjunkie** [comment]
I just pushed patch [release v4.0.8](https://www.nuget.org/packages/SimpleInjector/4.0.8) to NuGet that fixes this problem.

**Comment by dotnetjunkie** [comment]
As you will notice when you upgrade to v4.0.8, the bug in v4.0.7 prevented Simple Injector from throwing a correct exception describing the real problem with your configuration. With v4.0.8 you'll see the following exception:

> SimpleInjector.ActivationException: The constructor of type IQueryHandler&#96;Proxy contains the parameter with name '' and type ICallRouter that is not registered. Please ensure ICallRouter is registered, or change the constructor of IQueryHandler&#96;Proxy.

In other words, Simple Injector is complaining that your type has a constructor that requires `ICallRouter` and that it is not registered. You should either add a registration for `ICallRouter` or change your registration to the following:

``` c#
container.RegisterSingleton(proxy);
```

**Comment by ptsteward** [comment]
Ah yes, I did see that error shortly after upgrading and changed the registration. Those detailed error messages are probably the most helpful of any out there. Thanks again.
