### ISSUE TITLE
Registering decorators

### ISSUE THREAD

**Issue by OnamChilwan** [simpleinjector/SimpleInjector#428]
I have a fairly simple requirement whereby I want to register a bunch of decorators but struggling to do this. Before we begin let me provide the interface I am working with:

```
    public interface IFoo
    {
        string Bar(string value);
    }
```

I have a couple of implementations of this and for brevity let us call these `HelloDecorator` and `WorldDecorator`. **They both take instances of `IFoo` in their constructor.**

When I am writing the installer I can get it working using this approach:

```
            container.RegisterSingleton<IFoo>(
                new HelloDecorator(
                    new WorldDecorator(
                        new NullDecorator(null))));
```

However, I am trying to use `RegisterDecorator` but I get the message IFoo has not been registered. I guess how do I register the interface, do I need to? The docs mention using the generic registration approach but my case is very simple. Any ideas?

```
           // feels as though there is something missing, register IFoo?
            container.RegisterDecorator<IFoo, HelloDecorator>(Lifestyle.Singleton);
            container.RegisterDecorator<IFoo, WorldDecorator>(Lifestyle.Singleton);
            container.RegisterDecorator<IFoo, NullDecorator>(Lifestyle.Singleton);
```

Link to docs http://simpleinjector.readthedocs.io/en/latest/aop.html#decoration

Thanks.

**Comment by TheBigRic** [comment]
For a decorator to be applied, there of course has to be something to decorate. So what seems to be a little strange is this:

``` c#
container.RegisterSingleton<IFoo>(
                new HelloDecorator(
                    new WorldDecorator(
                        new NullDecorator(null))));
```

Here you only decorate `null` where as I expect you have an implementation to decorate. That's why Simple Injector correctly tells you there is missing a registration for `IFoo`.

 Because of the name, I think with `NullDecorator` you mean to break the chain. Decorators could be used for, but with the supplied sample code, it would be better if you use the Null Object pattern for this. So this would work:

``` c#
public class NullFoo : IFoo
{
    public string Bar(string value)   {  }
}

// register as:
container.RegisterSingleton<IFoo, NullFoo>();

container.RegisterDecorator<IFoo, WorldDecorator>();
container.RegisterDecorator<IFoo, HelloDecorator>();
```

**Comment by OnamChilwan** [comment]
Sorry I was being an idiot, as soon as a I read the first paragraph of your comment the penny dropped. I have changed the registration of the `NullDecorator` to match yours. 

Thanks for clarifying though really appreciate it.
