### ISSUE TITLE
Owin based WebApi and dependency resolving in filter attributes

### ISSUE THREAD

**Issue by pfeigl** [simpleinjector/SimpleInjector#431]
From http://simpleinjector.readthedocs.io/en/latest/webapiintegration.html#injecting-dependencies-into-web-api-filter-attributes I understand, that injection into FilterAttributes is not possible.

The workaround described is to use the DependencyResolver and put all the logic from the attribute into a service class.

Now in an owin based application, there won't be a GlobalConfiguration.Configuration, but you will create your own HttpConfiguration, which is not globally available.

Do you see any chance to still get depedencies resolved within the attributes in this usecase?

**Comment by pfeigl** [comment]
Thanks for the feedback, I'll guess splitting the attribute into a dto and a connected IActionFilter is the most solid implementation.

For now, I found another approach in the Autofac documentation, which seems to work just great and doesn't feel "too bad" ;-) See here: http://docs.autofac.org/en/latest/faq/per-request-scope.html?highlight=attribute#no-per-request-filter-dependencies-in-web-api

In the end, the current request (available through actionContext.Request) provides an GetDependencyScope method to retrieve the current request's dependency scope, which than allows me to resolve the required dependencies on a per-request basis, which is just what I want.

**Comment by TheBigRic** [comment]
Notice that I think the docs you're referencing are solely for Asp.Net Core. Maybe you're doing .Net Core, you didn't say, but just be noticed. 

> which seems to work just great and doesn't feel "too bad" ;-)
Well that is just a matter of taste I think. I would absolutely hate this and sits very much in the way when you would want to unittest the 'handler'. But if it works for you, go with it. 

On the other hand, this is still servicelocation and servicelocation on itself is not bound to `GlobalConfiguration.Configuration`. You could always make the container accessible to your `ActionFilter`, by injecting the configured container (which is a singleton no matter what) into your ActionFilter as I described in the third possibiltiy.

**Comment by dotnetjunkie** [comment]
I think it all depends o  the number of attributes you have and the amount of code you have in them. If you have just one or two attributes, implementing them as a Humble Object where logic moved to an Aggregate Service works very well; this Aggregate Service can be resolved from the current dependency scope, as you rightfully point out. Or you could even  have the code in the attribute, and resolve the required services from the dependency scope (although I only would do this if the attribute code is really really simple).

If on the other hand, you get more attributes it will start to make more sense to create passive attributes.
