### ISSUE TITLE
Documentation improvement for plugins

### ISSUE THREAD

**Issue by rold2007** [simpleinjector/SimpleInjector#436]
I am currently implementing plugins in my application using Simple Injector and it wasn't clear from the documentation how I could generate many instances of the same plugin without relying on the `Container` itself.

I finally found what the information I was looking for in [this answer](https://stackoverflow.com/a/25951296/263228), that `IEnumerable<IPlugin>` gives you a new instance every time it is iterated through.

I believe it would be useful to other users if this information (as sample code maybe ?) was available with the [Package registrations documentation](https://simpleinjector.readthedocs.io/en/latest/howto.html#package-registrations) and/or [Registering plugins dynamically](https://simpleinjector.readthedocs.io/en/latest/advanced.html#plugins).

In the end, I was able to find that behavior described in the [Collection types](http://simpleinjector.readthedocs.io/en/latest/using.html?highlight=ienumerable#collection-types) documentation but only because I knew what I was looking for after reading your answer on StackOverflow...

**Comment by dotnetjunkie** [comment]
Good point. I'll move this as work item to the [documentation repo](https://github.com/simpleinjector/Documentation).

**Comment by dotnetjunkie** [comment]
Moved to https://github.com/simpleinjector/Documentation/issues/65
