### ISSUE TITLE
Bring back cross-wiring in SimpleInjector.Integration.AspNetCore

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#437]
The beta releases of Simple Injector's ASP.NET Core integration library contained a `CrossWire` method that allowed to simplify registration of services that should be resolved from the ASP.NET Core container. This feature was however removed before RTM because of its limitations and because it promotes a model where people would do a lot of cross-wirings, instead of hiding those services behind application-specific abstractions.

In colaboration with @TheBigRic, I've been looking at the integration path of Identity Framework core. Ric and I found out that cross-wiring Identity types such as `UserManager<T>` and `SignInManager<T>` was extremely cumbersome without having this functionality as part of the integration library. Although much of the problems is caused by design flaws in Identity Framework and its default Visual Studio template, both are hard to work around for a user that just wants to bootstrap everything. This makes the experience of using Simple Injector in this case very cumbersome. 

For this reason, the `CrossWire` functionality has to returns. Important behavior for this feature is:

- The cross-wired dependencies should have the same lifestyle as they have in the ASP.NET Core configuration system, to prevent false positives in Simple Injector's Captive Dependency warnings.
- The `DisposableTransientComponent` warning should be suppressed for transient cross-wired dependencies that implement `IDisposable`, since the Core configuration system is responsible for disposing them.
- Cross-wired dependencies should be resolved from the ASP.NET request scope, in case there is a request.
- Verification should not fail on cross-wired dependencies when there is no HttpContext available.

**Comment by TheBigRic** [comment]
That is some nice piece of code you produced there! 

Will it help you if I took the burden of documenting this new feature? Maybe with some sample code how you can use this to make the default VS template with Identity can be made working.

**Comment by dotnetjunkie** [comment]
> Will it help you if I took the burden of documenting this new feature?

Absolutely! That would certainly help. Thanks.

**Comment by dotnetjunkie** [comment]
[Pushed to Nuget](https://www.nuget.org/packages/SimpleInjector.Integration.AspNetCore/4.0.9)

**Comment by QuantumHive** [comment]
@TheBigRic Did you manage to create documentation to integrate Identity core with Simple Injector?

**Comment by tim-elvidge** [comment]
Looking forwards to trying all this out, thanks for all the work @dotnetjunkie and @TheBigRic documentation.

**Comment by QuantumHive** [comment]
@TheBigRic looking forward to the docs, I'll try it out too and report feedback if needed.

**Comment by TheBigRic** [comment]
The documentation is available [here](http://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html#cross-wiring-asp-net-and-third-party-services)

**Comment by tim-elvidge** [comment]
@TheBigRic thanks for the bootstrap worked a treat.
