### ISSUE TITLE
AsyncScopedLifestyle occasionally resolve instance from different web request.

### ISSUE THREAD

**Issue by DimaMelnik** [simpleinjector/SimpleInjector#439]
I have configuration of injector 

``` c#
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

container.Register<IProfile, Profile>(Lifestyle.Scoped);

GlobalConfiguration.Configuration.DependencyResolver = 
    new SimpleInjectorWebApiDependencyResolver(container);
```

When multiple simultaneous requests to webApi doing resolve of  IProfile instance in ActionFilterAttribute sometimes it resolves instance of Profile that has been initiated for different web request.

to resolve instance in filter i use this code:

``` c#
Profile = 
    GlobalConfiguration.Configuration.DependencyResolver.GetService(typeof(IProfile)) as IProfile;
```

It seems it resolves proper instance of IProfile for the controller that is being called. 

I have tried to use WebApiRequestLifestyle and WebRequestLifestyle with the same success.

.net framework 4.5.2  SimpleInjector 4.0.8

**Comment by dotnetjunkie** [comment]
How did you detect the same instance is being reused over requests?

**Comment by DimaMelnik** [comment]
@dotnetjunkie I have added Guid which  gets populated in Profile constructor and added logger for all resolved instances in a filter. My suspicion is Filters are singleton and this is why it happens.

**Comment by dotnetjunkie** [comment]
> My suspicion is Filters are singleton and this is why it happens. 

Well, that's actually a fact. Attributes are caches as singletons by Web API. We documented this in the [Web API integration guide](https://simpleinjector.readthedocs.io/en/latest/webapiintegration.html#injecting-dependencies-into-web-api-filter-attributes). You should not store any dependencies into an attribute, that will lead to a [Captive Dependency](http://blog.ploeh.dk/2014/06/02/captive-dependency/).
