### ISSUE TITLE
Show namespace of type in exceptions from Verify()

### ISSUE THREAD

**Issue by rstenner** [simpleinjector/SimpleInjector#443]
I am working on a project using SimpleInjector 4.0.8 where we have a lot of classes with similar names in different namespaces (to reduce smurf naming). When Container.Verify() throws an InvalidOperationException I'm only given a hint to the type name "Screen" and the missing parameter. Without a namespace I am left to searching for a class with the same name matching the same parameters manually. Is there a way to configure the exception messages to include the full namespace of the Type being created, or could the thrown exceptions be enhanced to include this information?

> System.InvalidOperationException: 'The configuration is invalid. Creating the instance for type Screen failed. The constructor of type Screen contains the parameter with name 'items' and type IEnumerable<Model> that is not registered. Please ensure IEnumerable<Model> is registered, or change the constructor of Screen. Note that there exists a registration for a different type System.Collections.Generic.IEnumerable<UIBase.Topic.Model> while the requested type is System.Collections.Generic.IEnumerable<PluginManager.Navigation.Item.Model>.'

**Comment by TheBigRic** [comment]
The container has some options you can configure. One of the options is

``` c#
container.Options.UseFullyQualifiedTypeNames = true;
```

This will output fully qualified names and should be make it easier to find the offending type.

**Comment by rstenner** [comment]
Simple and effective. Excellent!
Thanks
