### ISSUE TITLE
Manually initialize and inject constructor params

### ISSUE THREAD

**Issue by rdzidziguri** [simpleinjector/SimpleInjector#449]
First of all thank you for this great package we recently moved to Simple Injector and so far we find it very useful, but we have a situation where we need to use DI but pass it type information of the class we want to create and fulfill its constructor parameters from DI as well

We found some examples
http://simpleinjector.readthedocs.io/en/latest/extensibility.html#building-up-external-instances here but it is not clear for us how to adjust it with our project.

``` c#
InstanceProducer producer = builder.GetRegistration(typeInformation, throwOnFailure: true);
//targetExtension = ??? 
//How can we create instance for that typeinfo and automatically inject constructor params from DI?
Registration registration = producer.Registration;
registration.InitializeInstance(targetExtension);
```

This `initializeinstance` is void but what we want to do in our case is to cast created and initialized instance to some interface and invoice method there.

We also found that `InstanceProducer` has `GetInstance` method but as far as I understand it only returns underlying implementation of the registration.

Could you help us understand the way this could be utilized? 

To make things more clear our framework is like how MVC works and there is custom core system which as structure like Controllers and Actions but this is custom core so what we want to have is to do kind of same staff as ASP.NET Web API and MVC are doing when they can directly utilize DI and inject anything in Controller constructor when it defines which controller to use.

Not Sure but maybe this is correct way to get it done?

``` c#
InstanceProducer producer = 
    builder.GetRegistration(typeof(GlobalRestDependencyDescriptor), throwOnFailure: true);
var rawInstance = producer.GetInstance();
Registration registration = producer.Registration;
registration.InitializeInstance(rawInstance);
```

**Comment by dotnetjunkie** [comment]
Can you a concrete example of what it is you are trying to achieve?

**Comment by rdzidziguri** [comment]
@dotnetjunkie 
Sure there is nothing special actually functinality should be very like what MS ASP.NET Web API does when it looks for Controllers in DI and creates and initializes those controllers and DI builds graph and injects whatever is needed in a controller constructor.

**Comment by dotnetjunkie** [comment]
Hi @rdzidziguri,

You have to give some examples here, because I have no idea what it is you are trying to do. Without some concrete examples, I'm afraid I'll be unable to help.

**Comment by dotnetjunkie** [comment]
Closed because of inactivity.
