### ISSUE TITLE
ASP.NET WebForm UserControl Injection

### ISSUE THREAD

**Issue by bowb** [simpleinjector/SimpleInjector#45]
Is there any way to integrate into UserControls like what is done for Pages?

http://simpleinjector.readthedocs.org/en/latest/webformsintegration.html

**Comment by dotnetjunkie** [comment]
You can find examples of how to do this [here](https://stackoverflow.com/questions/29341192/resolving-asp-net-web-forms-image-control-derived-class-registered-via-simple-in) and [here](https://github.com/simpleinjector/SimpleInjector/blob/master/SimpleInjector.Integration.Web.WebForms/SimpleInjectorWebFormExtensions.cs).

**Comment by bowb** [comment]
Thanks,

those work.
