### ISSUE TITLE
Batch / Automatic registration signature mismatch for Register() and RegisterSingleton()

### ISSUE THREAD

**Issue by abatishchev** [simpleinjector/SimpleInjector#450]
The code from the [doc](http://simpleinjector.readthedocs.io/en/latest/advanced.html#batch-registration):

``` c#
container.Register(typeof(IValidator<>), new[] { typeof(IValidator<>).Assembly });
```

uses this method:

``` c#
public void Register(Type openGenericServiceType, IEnumerable<Assembly> assemblies)
```

But this code (which works fine for the 'standard' registration):

``` c#
container.RegisterSingleton(typeof(IValidator<>), new[] { typeof(IValidator<>).Assembly });
```

uses wrong (unexpected) method:

``` c#
public void RegisterSingleton(Type serviceType, object instance);
```

Is it possible to add the appropriate overload for `RegisterSingleton()` as well?

P.S. Few more ideas:

``` c#
public void Register(Type openGenericServiceType, params Assembly[] assemblies);

public void RegisterSingleton(Type openGenericServiceType, params Assembly[] assemblies);
```

**Comment by dotnetjunkie** [comment]
Good suggestion. I'll add it to the v4.1 milestone.

**Comment by abatishchev** [comment]
Ok, I got it reviewed and approved by the lawers. Now only a signature by my management is pending. Hopefully I'll get it soon.
