### ISSUE TITLE
Support to AddDbContextPool

### ISSUE THREAD

**Issue by Jonatthu** [simpleinjector/SimpleInjector#453]
How I should implement SimpleInjector when we are using this feature on entity framework core and asp.net core version 2?

``` c#
services.AddDbContextPool<TyNETDbContext>(
    options => options.UseSqlServer(Configuration["ConnectionString"]));
```

**Comment by dotnetjunkie** [comment]
You just cross-wire the DbContext from Simple Injector:

``` c#
container.CrossWire<TyNETDbContext>(app);
```

For more information about cross-wiring, [see the documentation](https://simpleinjector.org/aspnetcore).

**Comment by Jonatthu** [comment]
thanks that works closing this issue
