### ISSUE TITLE
Reuse previous scope instance in nested scope.

### ISSUE THREAD

**Issue by malylemire1** [simpleinjector/SimpleInjector#456]
Is this non tested code a way to reuse previous scope instance in a nested scope?

``` c#
public void RegisterReuseScope<TService>() where TService : class, new()
{
    var lifestyle = new AsyncScopedLifestyle;

    Register<TService>(
        () => lifestyle.GetCurrentScope(this) == null
            ? new TService() 
            :  (TService)lifestyle.GetCurrentScope(this).GetItem(new TService().GetType().Name),
        lifestyle);
}
```
In an EF TransactionScope, I need to reuse previous db context connection from a previous scope in a nested scope to prevent upgrade to a MSDTC distributed transaction.

**Comment by malylemire1** [comment]
The new TService().GetType().Name is really bad I know but I just want to know if item key is the type name.

**Comment by dotnetjunkie** [comment]
I did a small refactoring to make the code more readable and understandable for myself, and make sure it fitted on the width of a page.

**Comment by dotnetjunkie** [comment]
> I need to reuse previous db context connection from a previous scope in a nested scope to prevent upgrade to a MSDTC distributed transaction.

This should not happen. I've been using `TransactionScope` for years and since SQL Server 2008 R2 you can create as many `SqlConnection` instances within the same transaction without TransactionScope escalates the transaction to a distributed transaction using MSDTC, as long as:

- All connections have the exact same connection string, and
- A previous connection has been closed.

Since you like to reuse a previous connection, that means that the connection is left open. If you simply make sure the connection is closed (which will automatically happen if you let EF manage the connection, instead of passing in an open connection), things should just work. Again, I've been doing this for years with both EF en LINQ to SQL mixed with nested scopes and TransactionScope.

**Comment by malylemire1** [comment]
I should have mention that I use new DB Context per thread in a Task.WhenAll inside a transaction scope.
Each task has it's own AsyncExecutionScope with a DB Context. I wanted to test if I could share connection between thread to prevent escalation to MSDTC.

**Comment by malylemire1** [comment]
ObjectContext should not be a problem beacause it's only used for AsNoTracking queries.

**Comment by dotnetjunkie** [comment]
> I wanted to test if I could share connection between thread to prevent escalation to MSDTC.

You mean you are running code in _parallel_? You should never share connections that are used simultaniously by multiple threads. That's just a disaster waiting to happen.

Each parallel operation should run in isolation. This means that each operation must have its own TransactionScope, it's own connection(s) and its own DbContext(s).

When you do that, there should not be any escalation to the MSDTC.

**Comment by malylemire1** [comment]
For now I have :
AsynExecutionScope(With new DBContext)
Task.WhenAll(
    AsynExecutionScope(With new DBContext)
    AsynExecutionScope(With new DBContext)
   )
and it's fine.

What i wanted to acheive is this
TransactionScope(TransactionScopeAsyncFlowOption.Enabled)
AsynExecutionScope(With new DBContext)
Task.WhenAll(
    AsynExecutionScope(With new DBContext(using existing connection))
    AsynExecutionScope(With new DBContext(using existing connection))
   )

**Comment by malylemire1** [comment]
Anyway i'll just stick to this version and test it if there is problems with sharing connections.
TransactionScope(TransactionScopeAsyncFlowOption.Enabled)
AsynExecutionScope(With new DBContext)
Task.WhenAll(
AsynExecutionScope(With new DBContext)
AsynExecutionScope(With new DBContext)
)

**Comment by dotnetjunkie** [comment]
> What i wanted to acheive is this

You can't. Period. You can't run parallel operations within the same TransactionScope or Connenection or DbContext. That will cause concurrency bugs in your application. Each parallel operation **must** have its own connection.

**Comment by malylemire1** [comment]
Ok thanks a lot for the info I was thinking parallel operations was supported by TransactionScope with TransactionScopeAsyncFlowOption.

**Comment by dotnetjunkie** [comment]
> Ok thanks a lot for the info I was thinking parallel operations was supported by TransactionScope with TransactionScopeAsyncFlowOption.

`TransactionScopeAsyncFlowOption` allows **asynchronous** execution, not **parallel** execution. You can do this:

``` c#
// will run asynchronous but sequential
TransactionScope(TransactionScopeAsyncFlowOption.Enabled)
{
    await AsynExecutionScope(With new DBContext)
    await AsynExecutionScope(With new DBContext)
    await AsynExecutionScope(With new DBContext)
}
```

but not this:

``` c#
TransactionScope(TransactionScopeAsyncFlowOption.Enabled)
{
    // This will cause the operations to run in parallel
    Task.WhenAll(
        AsynExecutionScope(With new DBContext)
        AsynExecutionScope(With new DBContext))
}
```
