### ISSUE TITLE
How to inject EndPointBehaviour

### ISSUE THREAD

**Issue by quintelab** [simpleinjector/SimpleInjector#457]
I am trying to migrate from Ninject and I could find almost everything that I need. It is a WCF project and I am using EndPointBehaviours. With Ninject I can inject it from my web.config:

```
<extensions>
  <behaviorExtensions>
    <add name="myBehaviour"
      type="Ninject.Extensions.Wcf.BaseNinjectBehaviorExtensionElement+NinjectBehaviorExtensionElement`1[[MyProject.MyBehaviourClassName, MyProject]], Ninject.Extensions.Wcf" />
  </behaviorExtensions>
</extensions>
```

is there a way to do that using Simple Injector ?

**Comment by dotnetjunkie** [comment]
What is it you are trying to achieve? What does that behavior extension do?

**Comment by quintelab** [comment]
It implements IDispatchMessageInspector. I can get the request before my WCF starts the "main code" and I can get the Response just before sending it back to the customer.

**Comment by dotnetjunkie** [comment]
There is nothing like that built into the Simple Injector integration package for WCF. You will have to build this yourself.

**Comment by quintelab** [comment]
Ok. Thank you Steven
