### ISSUE TITLE
Auto registration - target class implementations only?

### ISSUE THREAD

**Issue by evvo1961** [simpleinjector/SimpleInjector#458]
I am attempting to implement auto registration of my classes within my SI initialiser class. 

Initially i used manual registration to get it up and running and identify the classes/interfaces needing to be registered.

The problem i am having is for example:-

i am targeting the relevant assemblies i am interested in them looping through them to get all exported types and any interfaces before registering each service/implementation...

however whereas manual registration is precise as to which classes to be registered, targeting the assembly is of course looping through all the classes within the assembly, and trying to register classes i am not interested in/ do not implement an interface / or attempts to register types within them like enums that cannot be registered and causes the code to error...

is there a way within SI to filter on classes for specific conditions like only those that implement an interface to get around this issue?

**Comment by dotnetjunkie** [comment]
> is there a way within SI to filter on classes for specific conditions like only those that implement an interface to get around this issue?

Not really. As the documentation [states](https://simpleinjector.readthedocs.io/en/latest/advanced.html#batch-registration):

> Although many other DI libraries contain an advanced API for doing convention based registration, we found that doing this with custom LINQ queries is easier to write, more understandable, and can often prove to be more flexible than using a predefined and restrictive API.

Simple Injector focusses its batch-registration facilities around types having the same (generic/non-generic) interface. For instance, if you model types in your system around a few generic abstractions, you can register most of them in a few lines of code. For instance:

``` c#
container.Register(typeof(ICommandHandler<>), assemblies);
container.Register(typeof(IQueryHandler<,>), assemblies);
container.RegisterCollection(typeof(IValidator<>), assemblies);
```

This does batch-registration where Simple Injector searches the supplied assemblies for non-generic implementations of the given open-generic abstraction.

Most (bigger) applications benefit from such model with generic abstractions, as described [here](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=91) and [here](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=92). Refactoring an existing application to such a model however can be quite an undertaking.

Another way to find types of a given abstraction is using `GetTypesToRegister`:

``` c#
Type loggerTypes = container.GetTypesToRegister(typeof(ILogger), assemblies);
```

If however you want to register all types that share no commanlity, you will have to apply the filtering yourself.

**Comment by evvo1961** [comment]
Thanks... I think i may have to just stick with registering the 30 or so classes manually, i just wanted to do away with the overhead of having to remember to create the registration for any new classes...

i tried your examples but get this error:-

The supplied type IWebUserService is not a generic type. This method only supports open generic types. If you meant to register all available implementations of IWebUserService, call RegisterCollection(typeof(IWebUserService), IEnumerable<Assembly>) instead.

Another issue i had with my own auto registration once i added some filtering was multiple constructors so split these into derived classes. Then i get an error saying it cannot accept String as a parameter type in the constructor. So not sure how i would handle / recognise these situations when looping through all the types?

**Comment by dotnetjunkie** [comment]
>  multiple constructors

Prevent having multiple constructors: [Dependency Injection anti-pattern: multiple constructors](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=97)

> So not sure how i would handle / recognise these situations when looping through all the types?

This is where the ability to batch-register types stops. Batch-registration only works for cases where the arguments of the given types are not ambiguous. A `string` type is ambiguous, because the Container will not be able to know which exact value it should inject. It could be a connection string, or a file path, or... So types that require these primitive dependencies need to be registered explicitly.

**Comment by evvo1961** [comment]
ok how would that syntax look for registering these string types such as for this example constructor?

public ClientCache(string hostname, string port)
        {

        }

**Comment by dotnetjunkie** [comment]
For instance:

``` c#
string hostname = ConfigurationManager.AppSettings["cache.hostname"];
string port = ConfigurationManager.AppSettings["cache.port"];

container.Register<IClientCache>(() => new ClientCache(hostname: hostname, port: port));
```

**Comment by evvo1961** [comment]
ok thanks, i have another question...

in my example there is a reason for the 2 constructors but as it turns out the 2nd one with the string parameters is not needed to be recognised or handled by SI so is there a way to just tell SI to only use the first constructor for example  when it finds more than one?

**Comment by dotnetjunkie** [comment]
> SI so is there a way to just tell SI to only use the first constructor

This will not be a problem if you call the constructor yourself, i.e.:

``` c#
container.Register<IClientCache>(() => new ClientCache(hostname, port));
```

**Comment by evvo1961** [comment]
i cant do this approach as i haven't got the session id at the point of initialisation within global.ascx.cs which gets the values of these parameters... the user wont have logged in...

looking at the documentation i'm trying this approach... 

MostResolvableParametersConstructorResolutionBehavior 

"always select the constructor with the most parameters from the list of constructors with only resolvable parameters"

but i am still getting the error highlighting my constructor with string parameters. ive created the class to implement the SI constructor logic and it may be working when called just after creating the container but is probably still being processsed in my loop thru the assembly registrations later on... is there any way to ignore those at this point? i presume not....

**Comment by dotnetjunkie** [comment]
> i cant do this approach as i haven't got the session id at the point of initialisation

A session id is runtime data. You should _not_ inject runtime data into components during their initialization. You can read more about that in [this article](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99).

> looking at the documentation i'm trying this approach... MostResolvableParametersConstructorResolutionBehavior

Please don't. Your components should really-really [don't have multiple constructors](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=97).

> but i am still getting the error highlighting my constructor with string parameters.

That will not work, because you can't auto-wire a constructor (meaning that Simple Injector will use reflection to look at the constructor arguments and inject them based on their type) when you have an primitive or other ambiguous type.
