### ISSUE TITLE
Typo in extension method name AutoResolveUnregisteresTypes

### ISSUE THREAD

**Issue by Tornhoof** [simpleinjector/SimpleInjector#463]
In commit
https://github.com/simpleinjector/SimpleInjector/commit/c3726f2a0d4262cf9f95880e70a449433e7f434d you added the method AutoResolveUnregistere**s**Types. I guess you actually mean AutoResolveUnregistere**d**Types, just as the extension class is named.

See:
https://github.com/simpleinjector/SimpleInjector/blob/a297795bbf141aafdbcc41b488702ec80c542a73/src/SimpleInjector.CodeSamples/AutoResolveUnregisteredTypeExtensions.cs#L15

**Comment by dotnetjunkie** [comment]
Good catch. I was clearly not paying much attention.

**Comment by dotnetjunkie** [comment]
Fixed.
