### ISSUE TITLE
passing around global container

### ISSUE THREAD

**Issue by stokara** [simpleinjector/SimpleInjector#464]
In the documentation for Async Scoped Lifestyle the example references the container. 
I'd like to stay away from passing around the container as well as Service Locator but I don't see how this can be done with my Async Scoped Unit of work class.

**Comment by dotnetjunkie** [comment]
There is no harm in referencing the container inside the Composition Root. Within the Composition Root, a reference to the container is not an implementation of the Service Locator anti-pattern.

So make aure that you start an async scope inside the Composition Root and you'll be fine.

**Comment by dotnetjunkie** [comment]
Note that the upcoming book [Dependendency Injection in .NET second edition](https://manning.com/seemann2/) contains an elaborate discussion on the *Composition Root* in chapter 4.
