### ISSUE TITLE
Replacing MEF

### ISSUE THREAD

**Issue by evvo1961** [simpleinjector/SimpleInjector#465]
Im tasked with replacing all MEF references within a number of applications with Simple Injector. Many instances of MEF Import and Export are straightforward with adding registrations to the SI config (Exports) or injecting the type parameters into the class constructors (Imports).

However i am coming across a number of files where classes have attributes such as

``` c#
[Export(typeof(IJobRepository)), PartCreationPolicy(CreationPolicy.NonShared)]
```

Removing these references outputs errors, and i am not too familair with MEF so am wondering how i replace this code with Simple Injector....

**Comment by dotnetjunkie** [comment]
> and i am not too familair with MEF

Mean either.

If you can describe what that this means in MEF, I can supply you with the equivalent in Simple Injector.

**Comment by devhb** [comment]
[Export(typeof(IJobRepository)), PartCreationPolicy(CreationPolicy.NonShared)]

The type is registered as IJobRepository with NonShared lifestyle, which means in simpleinjector transient.

**Comment by dotnetjunkie** [comment]
In that case:

``` C#
container.Register<IJobRepository, [Type]>(Lifestyle.Transient);
```

**Comment by evvo1961** [comment]
thanks ill try that out

**Comment by evvo1961** [comment]
ive encountered a few other MEF statements that im not overly sure how to replace with Simple Injector (or whether i need to?)

e.g.  container.ComposeExportedValue("WebSettings", (IWebSettings)Settings.Default);
            container.ComposeExportedValue((ICacheSettings)Settings.Default);

also: ContainerHelper.Container.SatisfyImportsOnce(this); (this being the controller class)

**Comment by dotnetjunkie** [comment]
@evvo1961, It would be so much easier if you described to us what the intended behavior is. So instead of trying to mimic these expressions, explain how you wish the system to behave and we can work from that.
