### ISSUE TITLE
Choosing the correct Lifestyle

### ISSUE THREAD

**Issue by gcapnias** [simpleinjector/SimpleInjector#470]
My container used the following lifestyle in order to register 

``` c#
var mixLifestyle = Lifestyle.CreateHybrid(
    defaultLifestyle: new ThreadScopedLifestyle(), 
    fallbackLifestyle: new AsyncScopedLifestyle());
var lifestyle = Lifestyle.CreateHybrid(
    () => HttpContext.Current != null, 
    new WebRequestLifestyle(), 
    mixLifestyle);

container.Register(GetDataContext, lifestyle);
container.Register<IUnitOfWork, UnitOfWork>(lifestyle);
```

Inside my ASP.NET MVC application I start a background process with the following

``` c#
HostingEnvironment.QueueBackgroundWorkItem(async cancelationToken =>
{
    await SearchProvider.searchFunction(model, HttpContext.Session.SessionID, 
        user, Request.UserHostAddress);
});
```

The code inside my method start like this

``` c#
public static void Process(IService service, SearchHeader searchHeader, string partNumber, 
    string description)
{
    var _unitOfWork = DependencyInitializer.Resolve<IUnitOfWork>();
    var _errorLogRepository = DependencyInitializer.Resolve<IErrorLogRepository>();
```

As soon as the execution point reaches the Process() function I get the error:

> SimpleInjector.ActivationException: The SearchHeaderRepository is registered as 'Hybrid Web Request / Thread Scoped / Async Scoped' lifestyle, but the instance is requested outside the context of an active (Hybrid Web Request / Thread Scoped / Async Scoped) scope.
   at SimpleInjector.Scope.GetScopelessInstance[TImplementation](ScopedRegistration`1 registration)

Can anyone offer some pointer how to fix this problem?

**Comment by dotnetjunkie** [comment]
Where do you start the Thread or Async scope on your background thread?

**Comment by gcapnias** [comment]
I am sorry the last snippet I provided is not relative to the case...

The correct is:

`

        public static async Task searchFunction(SearchBindingView model, string SessionID, User user, string UserHostAddress)
        {
            log.InfoFormat("searchFunction({0})", SessionID);

            try
            {
                ISearchHeaderRepository _searchHeaderRepository = DependencyInitializer.Resolve<ISearchHeaderRepository>();
                IUnitOfWork _unitOfWork = DependencyInitializer.Resolve<IUnitOfWork>();

                var searchHeader = new SearchHeader();
                searchHeader.DateTime = DateTime.Now;
                searchHeader.WhoSearched = user?.Name;
                searchHeader.SearchPartNumber = model.PartNumber;
                searchHeader.SearchPartDescription = model.Description;
                searchHeader.IPAddress = UserHostAddress;
                searchHeader.Type = SearchSourceTypes.SearchSite.ToString();
                _searchHeaderRepository.Add(searchHeader);
                _unitOfWork.SaveChanges();

`

**Comment by dotnetjunkie** [comment]
Let me ask this again, since I think here lies the culprit: Where do you start the Thread or Async scope on your background thread? You need this code!

**Comment by gcapnias** [comment]
I am not quite sure what you are asking; There is a MVC Controller, there is a request on an action/method, before the method end inside the controller, I call HostingEnvironment.QueueBackgroundWorkItem, while letting the client get the controllers response.

Is this what you asking?

**Comment by dotnetjunkie** [comment]
If you've read [this part](https://simpleinjector.readthedocs.io/en/latest/lifetimes.html#async-scoped-async-await) of the documentation, you see that `AsyncScopedLifestyle` and `ThreadScopedLifestyle` require the explicit start and end of a scope, as shown in this example:

``` c#
using (AsyncScopedLifestyle.BeginScope(container)) {
    var uow1 = container.GetInstance<IUnitOfWork>();
    await SomeAsyncOperation();
    var uow2 = container.GetInstance<IUnitOfWork>();
    await SomeOtherAsyncOperation();

    Assert.AreSame(uow1, uow2);
}
```

So where in your code do you call `AsyncScopedLifestyle.BeginScope`?

And if you don't call that method, there is your problem.

**Comment by gcapnias** [comment]
Thank you!

Your first pointer was enough to solve the problem.

I had skimmed the page before you point it out, but after getting your pointer, I had to use explicitly use AsyncScopedLifestyle.BeginScope(), it all come together.

I must say I was skeptical at the beginning, if it would work, but it did! 

Thanks!

**Comment by dotnetjunkie** [comment]
> I must say I was skeptical at the beginning

Wat? Did you just say you didn't trust me? Shame on you :)

**Comment by Ruud-cb** [comment]
@dotnetjunkie I am fighting a littlebit with this. I have the `container.Options.DefaultScopedLifestyle` set to what you mentioned, which fixed the problem that something was registered as WebRequestLifestyle.
Thereafter I register my database for example like this:

`_Container.Register<DatabaseContext>(Lifestyle.Scoped);`

Then I get the error when I try to retrieve something from the database:

'The ObjectContext instance has been disposed and can no longer be used for operations that require a connection.'
Also tried to do this `_Container.Register<DatabaseContext>(Lifestyle.CreateHybrid(defaultLifestyle: Lifestyle.Scoped, fallbackLifestyle: new AsyncScopedLifestyle()));`  but that didn't work.

What is called

```
        private void RefreshRolesAndControllers()
        {
            using (AsyncScopedLifestyle.BeginScope(DependencyInjectionCoreSetup._Container))
            {
                var userHelper = DependencyInjectionCoreSetup._Container.GetInstance<ICurrentUser>();
                userHelper.ReloadWarehouseAndRoleData();
            }
        }
```

Which is called by this after Action is almost finished:

```
HostingEnvironment.QueueBackgroundWorkItem(token => RefreshRolesAndControllers());
```

What am I doing wrong?

**Comment by dotnetjunkie** [comment]
@Ruud-cb, can you post the full stack trace you get?

**Comment by dotnetjunkie** [comment]
> I have the container.Options.DefaultScopedLifestyle set to what you mentioned

To what did you set your `DefaultScopedLifestyle`? It might be good to post a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve).

**Comment by AlissonRS** [comment]
It seems this code:

`var lifestyle = Lifestyle.CreateHybrid(
    defaultLifestyle: new WebRequestLifestyle(), 
    fallbackLifestyle: new AsyncScopedLifestyle());`

...doesn't compile in my project. There is no such overload, I guess this has a different implementation for .NET Standard (I'm using 1.6 btw). I'm trying to mix **AspNetRequestLifestyle** and **AsyncScopedLifestyle**.

How can I achieve this? I need to fallback to **AsyncScopedLifestyle** when there is not ASP.NET Request. The first parameter is a `Func<bool>` which decides if we should fallback, but I'm not sure how to check that and provide a proper function.

**Comment by AlissonRS** [comment]
Nevermind, I found in another thread:

`var lifetimeScopeLifestyle = new LifetimeScopeLifestyle();
Lifestyle.CreateHybrid(
    lifestyleSelector: () => lifetimeScopeLifestyle.GetCurrentScope(container) != null,
    trueLifestyle: lifetimeScopeLifestyle,
    falseLifestyle: new ExecutionContextScopeLifestyle());`

**Comment by dotnetjunkie** [comment]
There are several `CreateHybrid` overloads, namely:

* `CreateHybrid(ScopedLifestyle, Lifestyle)`
* `CreateHybrid(ScopedLifestyle, ScopedLifestyle)`
* `CreateHybrid(Func<bool>, Lifestyle, Lifestyle)`
* `CreateHybrid(Func<bool> lifestyleSelector, ScopedLifestyle, ScopedLifestyle)`

You should prefer using the overload that doesn't take in a `Func<bool>`, because that leads to simpler code. If there isn't such overload, you are probably using a really old version of Simple Injector, or the compiler is confused because it can't find one of your supplied lifestyles. With the most recent version of Simple Injector, your first code example should work.
