### ISSUE TITLE
register class with multiple implementations

### ISSUE THREAD

**Issue by evvo1961** [simpleinjector/SimpleInjector#473]
I have a class (Settings.cs) that implements 3 interfaces related to settings ie each interface solely comprises of property getters...

I have been registering them in this way

``` c#
container.Register<IWebSettings, Settings>(Lifestyle.Transient);
container.Register<ICacheSettings, Settings>(Lifestyle.Transient);
container.Register<IDirectorySettings, Settings>(Lifestyle.Transient);
```

is this correct?

as far as i can determine they are being used correctly in the application

**Comment by dotnetjunkie** [comment]
I think I'm missing some context here. How does this `Settings` class look like and how are you using it?

**Comment by evvo1961** [comment]
Its being used to read set values from a settings file

however it may be easier to explain what im trying to do which is replace both Unity and MEF within a project

Unity has been straightforward but im less familair with MEf. The Import and Export attributes are just replaced by registrations in my SI config file and adding the appropriate imports to my constructors, but in MEF this settings class is handed with

container.ComposeExportedValue((IWebSettings)Settings.Default);

so perhaps my question is how this MEF method is done with simple injector?

**Comment by dotnetjunkie** [comment]
After some [little googling](https://stackoverflow.com/a/4842427/264697), it seems that `ComposeExportedValue` is equivalent to Simple Injector's `RegisterSingleton<T>(T)`:

``` c#
container.RegisterSingleton<IWebSettings>(Settings.Default);
```

**Comment by evvo1961** [comment]
thanks
 i have one more (hopefully final!) question...

My mvc project references a class library project that has MEF references, would i replace these with a SI config setup within the class library project and call via it's global.asax or keep all SI configuration with the MVC (startup) project?

**Comment by dotnetjunkie** [comment]
Your MVC (startup) project contains the [Composition Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/), meaning it contains the code that wires up the container.

No other libraries (but the startup projects) should typically contain _any_ reference to your DI Container. There are some exceptions to this, but in general, your class libraries should not have a Composition Root, nor have any dependency on your DI Container.

So yes, you should keep all your DI configuration inside the startup project.

Do note that a Composition Root is not a single location or single class. You can see it more as a layer or module that can consist of multiple classes that together allow the application to be composed. With MVC applications we typically put this layer in the same assembly as our Presentation Logic layer (i.e. the startup project), but note that no code in the Presentation Logic should depend on the Composition Root layer. [Here's an interesting q/a](https://stackoverflow.com/questions/9501604/ioc-di-why-do-i-have-to-reference-all-layers-assemblies-in-entry-application) about this. And chapter 4 of [Dependency Injection in .NET second edition](https://manning.com/seemann2/) goes into more detail as well.
