### ISSUE TITLE
Register controllers in a class library

### ISSUE THREAD

**Issue by evvo1961** [simpleinjector/SimpleInjector#474]
within my application i have replaced MEF with SI in a web MVC project but have another class library project in the solution that needs the MEf replacing too.

i essentially copied the code from the web project to the class library but my application wasn't working correctly and noticed my controllers in the class library were not being registered.
by mistake i had copied from my MVC web project 

``` c#
container.RegisterMvcControllers(Assembly.GetExecutingAssembly());
```

into the config for my class library so it wasn't locating the correct assembly...

in my class library SI config i then changed this to

``` c#
var assembly = Assembly.Load("MyApplication.WebService");
container.RegisterMvcControllers(assembly); 
```

i can verify that the assembly is loaded correctly into my variable but im still not getting my controllers registered and added to the container

**Comment by dotnetjunkie** [comment]
The only thing I can think of is that `MyApplication.WebService` is not the assembly that contains the MVC controllers. Try reflecting over the assembly using `.GetTypes()` or `.GetExportedTypes()` perhaps by filtering it with `.Where(t => t.Name.EndsWith("Controller"))`.

**Comment by evvo1961** [comment]
ok when  i debug through and look at the assembly values both DefinedTypes and ExportedTypes contains references to my controllers ie MyApplication.WebService.ListsController etc

**Comment by dotnetjunkie** [comment]
Simple Injector uses the following logic to extract the MVC Controllers it tries to register:

``` c#
from assembly in assemblies
where !assembly.IsDynamic
from type in GetExportedTypes(assembly)
where typeof(IController).IsAssignableFrom(type)
where !type.IsAbstract
where !type.IsGenericTypeDefinition
where type.Name.EndsWith("Controller", StringComparison.Ordinal)
select type
```

It might be that one of these conditions isn't met which might cause the controller types to be excluded.

**Comment by evvo1961** [comment]
ah found it then, these controllers do not ultimately implement IController, butApiController (via an abstract class ODataController to get that specific type of data)

**Comment by dotnetjunkie** [comment]
In that case you should use the `RegisterWebApiControllers` extension method which is in the [Web API Integration package](https://www.nuget.org/packages/SimpleInjector.Integration.WebApi/).

**Comment by evvo1961** [comment]
thanks thats done the trick
