### ISSUE TITLE
ODataController registration

### ISSUE THREAD

**Issue by evvo1961** [simpleinjector/SimpleInjector#475]
do i need to do anything different to register odatacontroller in simple injector
im using the

``` c#
container.RegisterWebApiControllers(GlobalConfiguration.Configuration);
```

but my contructors are not hit, i get an error that i need a parameterless constructor

if i add this and set up my service via

``` c#
DependencyResolver.Current.GetService<T>
```

it works ok

**Comment by dotnetjunkie** [comment]
Can you supply more information?

- Can you post the relevant parts of the configuration that allow reproducing the issue?
- Where is that ODataController located? Which assembly?
- Does `GlobalConfiguration.Configuration.Services.GetAssembliesResolver().GetAssemblies()` contain that assembly?
- Can you post the complete exception and stack trace information, including inner exceptions?

**Comment by evvo1961** [comment]
I tracked it down, was basic really i was using SimpleInjectorDependencyResolver
rather than SimpleInjectorWebApiDependencyResolver in the RegisterRevolver method... now the DI constructor injection is working fine...

**Comment by dotnetjunkie** [comment]
Case closed :)
