### ISSUE TITLE
Threading issue with .verify() method

### ISSUE THREAD

**Issue by bapti** [simpleinjector/SimpleInjector#48]
Hi, just a small bug to report.  I have the following 2 integration tests

```
[Fact]
public void Should_Verify_Api_Container()
{
    // some setup stuff
    container.Verify();
    var results = Analyzer.Analyze(container);
    // assert results are zero
}

[Fact]
public void Should_Verify_Worker_Container()
{
    // some setup stuff
    container.Verify();
    var results = Analyzer.Analyze(container);
    // assert results are zero
}
```

These test ran fine however when I upgraded to xunit 2.0 the tests started intermittently failing.  By default in xunit 2 the tests all run in parallel.  I added on the attribute `[Collection("verify")]` to each class containing the tests - which makes them run in sequence.  This made the tests pass again.  I can only assume there's a threading issue or something like that and thought you'd like to know.

Cheers
Neil

**Comment by qujck** [comment]
Are both tests using the same instance of the container?

**Comment by dotnetjunkie** [comment]
Hi Neil, can you share the exception details of the failing test? Which version of Simple Injector are you running?

**Comment by bapti** [comment]
Hi guys,

The exception was the same as this one in the stackoverflow question
http://stackoverflow.com/questions/18916981/registering-decorators-conflicts-with-registration-of-ienumerablet

The containers were both new-ed up separately, the repro was also very intermittent and only occurred on our teamcity agent using the xunit console runner.

**Comment by bapti** [comment]
We're also using the latest of simple injector as of Monday this week I updated all packages.  When I get back to my work PC I can check the version specifically

**Comment by dotnetjunkie** [comment]
The `Verify()` method does start a lock, so no two threads can execute `Verify` simultaneously on the same `Container` instance. Multiple container instances do not share any global state, so I'm not sure why it could fail when multiple container instances are verified simultaneously.

Can you be a more specific with the exception details? The exception and stack trace in that question are specific to that question. Can you post the details of your exact exception message and stack trace?
