### ISSUE TITLE
Support for ServiceFabric

### ISSUE THREAD

**Issue by kushboojain** [simpleinjector/SimpleInjector#487]
How to use SimpleInjector to register ServiceFabric Services(Actors, Stateful/Stateless) ?

**Comment by dotnetjunkie** [comment]
I don't know, but perhaps [this article](http://www.jamessturtevant.com/posts/Dependency-Injection-with-Azure-Service-Fabric/) helps.

**Comment by kushboojain** [comment]
@dotnetjunkie Currently we are using the approach mentioned in the article you have referred. Our actors have dependencies like logger, etc that have to be injected. What we are looking at is abstracting the injection similar to [this article](https://alexmg.com/posts/introducing-the-autofac-integration-for-service-fabric). Autofac has simple extension methods that help registering servicefabric service.

**Comment by dotnetjunkie** [comment]
I'm sorry, but I have no experience with ServiceFabric, so this is not something I can help with. You might come up with an integration model for Simple Injector based on the Autofac integration.

There might be simpler options, but again, my lack of experience here hinders me from saying anything useful about this. Perhaps a design as [this](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=91) would make things easier, but hopefully other, with more experience around this subject, could feedback on this.

**Comment by kushboojain** [comment]
Thank you for the help.
