### ISSUE TITLE
The service type provided could not be loaded as a service because it does not have a default (parameter-less) constructor.

### ISSUE THREAD

**Issue by rajarajanb** [simpleinjector/SimpleInjector#489]
I am using SimpleInjector for my WCF project, which will be self-hosted (DEV) or WAS hosted (PROD), I am getting the above error.

My Service **InstanceContextMode** is **PerCall**, I am just injecting a logger interface, I have created **Bootstrapper**, **HostFactory** and SVC file as mentioned in the document, but still I am getting this error.

I have seen similar issues in the forums Q&A by other  developers and mostly it is the issue with 
**InstanceContectMode** being **Single**.

I am not able to understand, why it is failing also there are suggestion highlighting about extending **IInstanceProvider**, but I am not sure the SimpleInjector document suggest this.

Is there anything wrong in my understanding, if not why I am getting this error.

**Comment by dotnetjunkie** [comment]
Can you provide me with a reproducible example?

**Comment by rajarajanb** [comment]
Do you want the code files?

**Comment by dotnetjunkie** [comment]
I would like to have the [minimal amount of working code](https://stackoverflow.com/help/mcve) and steps that produce the issue.

**Comment by rajarajanb** [comment]
**Hope This helps**
**SVC Entry**
<%@ ServiceHost
Service="Delivery"
CodeBehind="Delivery.cs"
Language="C#"
Factory="MyNamespace.WcfServiceFactory, Delivery"
%>
**Bootstrapper.cs**
public static class Bootstrapper
    {
        public static readonly Container Container;
        static Bootstrapper()
        {
            var container = new Container();
            container.Options.DefaultScopedLifestyle = new WcfOperationLifestyle();
            container.Register<IFileLogger>(() => new FileLogger("LogFile"));
            container.Register<IDelivery, Delivery>();
            //Other Supporting Interfaces...
            container.Verify();
            Container = container;
        }
    }

**WcfServiceFactory.cs** 
public class WcfServiceFactory : SimpleInjectorServiceHostFactory
    {
        protected override ServiceHost CreateServiceHost(Type serviceType,
        Uri[] baseAddresses)
        {
            return new SimpleInjectorServiceHost(
            Bootstrapper.Container,
            serviceType,
            baseAddresses);
        }
    }
**Delivery.cs**
[ServiceBehavior(InstanceContextMode=InstanceContextMode.PerCall,ConcurrencyMode =ConcurrencyMode.Multiple)]
    public class Delivery : IDelivery
    {
        private readonly ILogger logger;

        public Delivery(ILogger logger)
        {
            this.logger = logger;
        }
        
       public int Test(int testdata)
        {
            return testdata;
        }
    }

**IDelivery.cs**
[ServiceContract(SessionMode = SessionMode.Allowed)]
    public interface IDelivery
    {
        [OperationContract]
        int Test(int testdata);
    }

**Program Main**
        static void Main(string[] args)
        {
            ServiceHost host = new ServiceHost(typeof(Delivery));
            host.Open();
            Console.ReadLine();
        }


This is a very simple project with just one API exposed from a service.
I am  using latest SimpleInjector and SimpleInjector.Integration.Wcf;

**Comment by dotnetjunkie** [comment]
Replace:

``` c#
ServiceHost host = new ServiceHost(typeof(Delivery));
```

with:

``` c#
var host = new SimpleInjectorServiceHost(Bootstrapper.Container, typeof(Delivery), new Uri[0]);
```

**Comment by rajarajanb** [comment]
Thanks, It works perfectly.

A query on the service hosting, Can host multiple ServiceTypes? 
Looking at SimpleInjectorServiceHost method, it only supports one serviceType.

**Comment by pjopaul** [comment]
Don't we need add to following code before instantiating the service host?
```
// Register the container to the SimpleInjectorServiceHostFactory.
            SimpleInjectorServiceHostFactory.SetContainer(container);
```
Or this required only if we don't have svc file means if we hosting the service in the console application?

**Comment by dotnetjunkie** [comment]
`SimpleInjectorServiceHostFactory.SetContainer` only needs to be called when the `SimpleInjectorServiceHostFactory` is used to create `ServiceHost` instances. In case you create `SimpleInjectorServiceHost` instances manually, there is no need to call `SimpleInjectorServiceHostFactory.SetContainer`.
