### ISSUE TITLE
Generic Data Repository and DataBase Context

### ISSUE THREAD

**Issue by smarteez** [simpleinjector/SimpleInjector#490]
Hi trying to register 2 repository but getting errors the first one is a Generic Data Repository

``` c#
container.RegisterDecorator(typeof(IDataRepository<>) ,typeof(DataRepository<>);
```

i am getting this error 

> For the container to be able to use DataRepository&lt;T> as a decorator, its constructor must include a single parameter of type IDataRepository&lt;T> (or Func&lt;IDataRepository&lt;T>>) - i.e. the type of the instance that is being decorated. The parameter type IDataRepository&lt;T> does not currently exist in the constructor of class DataRepository&lt;T>. Parameter name: decoratorType'

I have no idea what to do 

``` c#
container.Register<DbContext, DataBaseContext>();
```

this is also giving me an error

**Comment by dotnetjunkie** [comment]
Simple Injector is telling you that `DataRepository<T>` is _not_ a [Decorator](https://en.wikipedia.org/wiki/Decorator_pattern).

Please explain what it is you want to achieve? Do you wish to wrap `DataRepository<T>` around another type that implements `IDataRepository<T>` or do you simply want to make sure that `DataRepository<T>` is returned any time a `IDataRepository<T>` is requested?

- In case `DataRepository<T>` should be decorated around another type, please make sure it contains the proper constructor argument.
- In case you want to do the latter, please call `Register` instead of `RegisterDecorator`.

**Comment by smarteez** [comment]
i was using Autofac before and i chnage to code to use Simple Injector i have Generic Data Repository

          //Register DbContext
            containerBuilder.RegisterType<SmarteezMediaDBContext>().As<DbContext>().InstancePerRequest();

            //Registration of Generic DataRepository
            containerBuilder.RegisterGeneric(typeof(DataRepository<>)).As(typeof(IDataRepository<>)).InstancePerRequest();

what should i do for th above ?

**Comment by dotnetjunkie** [comment]
``` c#
container.Register<DbContext>(() => new SmarteezMediaDBContext(), Lifestyle.Scoped);

container.Register(typeof(IDataRepository<>), typeof(DataRepository<>), Lifestyle.Scoped);
```

**Comment by smarteez** [comment]
I am getting this error 
on this line 

container.Register<DbContext>(() => new SmarteezMediaDBContext(), Lifestyle.Scoped);


To be able to use the Lifestyle.Scoped property, please ensure that the container is configured with a default scoped lifestyle by setting the Container.Options.DefaultScopedLifestyle property with the required scoped lifestyle for your type of application

**Comment by dotnetjunkie** [comment]
Did you actually go through the trouble to [read the manual](https://simpleinjector.org/documentation)? I can advice you to do so. If you have any questions [after reading it](https://simpleinjector.org/lifestyles#scoped), please feel free to ask here again.

**Comment by smarteez** [comment]
Hi i found the answer reading the document 
thanks 

 container.Options.DefaultScopedLifestyle =  new AsyncScopedLifestyle();
