### ISSUE TITLE
WPF Integration

### ISSUE THREAD

**Issue by stokara** [simpleinjector/SimpleInjector#493]
I implemented the recommended startup in my WPF project and ran into a few small problems that I have worked around but wanted to let you know, either to be corrected or give feedback.

In RunApplication after `var app = new App();`
 
I needed to add: `app.InitializeComponent();`
for the resource dictionaries defined in app.xaml to be loaded.

Further, because I configured my container with the startup view which relies on these resources I was unable to call container.Verify() (as it seems to try instantiate the views) until after these resources are loaded, so that the first lines of RunApplication are now:
`var app = new App();
app.InitializeComponent();
container.Verify();`

`var mainWindow = container.GetInstance<MainWindow>();
...(more init stuff)
 app.Run(mainWindow);
`
With this my program starts and works as expected.

**Comment by ogiesen** [comment]
I had the same issue regarding resources defined in App.xaml and with the solution described here I was indeed able to run my application again. However, with the `app.InitializeComponent()`-call in there, the application process no longer terminates after I close the main window... When I pause the Debugger then, it's always just pointed at the `app.Run(mainWindow);` line in my Program.cs ...

Any ideas?

**Comment by TheBigRic** [comment]
@ogiesen Can you share the code for starting the application, incl. the bootstrapper to register components in Simple Injector, possible splash screens, MVVM bootstrapper if any, etc.

The reasons could be numerous, without knowing these details it is possible to answer.
