### ISSUE TITLE
ASP.NET Core MVC: Replacing the Inbuilt DI

### ISSUE THREAD

**Issue by richardcox13** [simpleinjector/SimpleInjector#495]
As described on the [ASP.NET Core documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection#replacing-the-default-services-container) it is possible – by returning an `IServiceProvider` instamce from `Startup.ConfigureServices` – to replace the inbuilt DI container.

If I do this with SimpleInjector then startup immediately fails due to services not being available.

I assume this is because `RegisterMvcControllers` and `RegisterMvcViewComponents` have yet to be called. But they depend on `IApplicationBuilder` which is passed to `Setup.Configure` called later.

How can I used SimpleInjector to resolve calls to `IServiceProvider`?

**Comment by dotnetjunkie** [comment]
Please [read the integration guide](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html) to learn how to integrate Simple Injector with ASP.NET Core. 

Integrating Simple Injector means you don't replace the built-in container, as is described in the ASP.NET Core documentation, but you simply use Simple Injector to resolve your _application components_. To learn why Simple Injector takes this route, please read [this article](https://simpleinjector.org/blog/2016/06/whats-wrong-with-the-asp-net-core-di-abstraction/).

**Comment by richardcox13** [comment]
Please consider documenting that in the [integration guide](http://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html). Depending on finding a blog post just leaves users frustrated.

**Comment by dotnetjunkie** [comment]
@richardcox13 good point. I updated the documentation.
