### ISSUE TITLE
Registering query handlers which are implemented through interfaces

### ISSUE THREAD

**Issue by mshafii** [simpleinjector/SimpleInjector#497]
I am trying to register some specific query handlers which all share the same interface and return type of `IQuery<Pricing>`.

From the documentation (and trial and error) it seems that `Register()` will not work for this, but rather `RegisterCollection()` is supposed to be used. However, I only use the `IQueryHandler` interface to handle multiple types of queries; each query handler does not have a unique instance. How would I register a collection in this scenario? 

All of the things I have tried end up throwing an exception when I try to call upon one of the queries, with the message

> The parameter is incorrect

Here are the ways I have attempted to register the collection:

``` c#
container.RegisterCollection(typeof(IQueryHandler<IQuery<Pricing>, Pricing>), this.assemblies)
```

``` c#
container.RegisterCollection(
    typeof(IQueryHandler<,>),
        new[]
        {
            typeof(IQueryHandler<GetFreightByPriceList, Pricing>),
            typeof(IQueryHandler<GetFreightPriceListRateId, Pricing>),
            typeof(IQueryHandler<GetFreightPriceListPayId, Pricing>)
        });
```

``` c#
container.Register<IQueryHandler<GetFreightByPriceList, Pricing>>();
container.Register<IQueryHandler<GetFreightPriceListRateId, Pricing>>();
container.Register<IQueryHandler<GetFreightPriceListPayId, Pricing>>();
```

**Comment by mshafii** [comment]
That's the thing; there are no individual query handler implementations. There is one query handler and the business logic manager classes have Handle() methods for each type of query. I am trying to avoid registering all query handlers, but I have no way to distinguish the actual handlers for these specific queries. I think perhaps there is no way to do this in this case.

**Comment by dotnetjunkie** [comment]
I'm afraid I don't follow you. Can you please show the relevant code?

**Comment by dotnetjunkie** [comment]
Closed due to inactivity.
