### ISSUE TITLE
RegisterDecorator overload that accepts lifestyle is missing generic constraints

### ISSUE THREAD

**Issue by onyxmaster** [simpleinjector/SimpleInjector#499]
I wonder if [this overload](https://github.com/simpleinjector/SimpleInjector/blob/b7daa99987f41f4f3f3db2b07105846bbfc7ba0e/src/SimpleInjector/Container.Registration.Decorators.cs#L145) omits the constraints present on [the other one](https://github.com/simpleinjector/SimpleInjector/blob/b7daa99987f41f4f3f3db2b07105846bbfc7ba0e/src/SimpleInjector/Container.Registration.Decorators.cs#L88) intentionally?

**Comment by dotnetjunkie** [comment]
That's a bug.

**Comment by dotnetjunkie** [comment]
And fixed.

Thanks for reporting this.

Simple Injector v4.1 will contain the fix.
