### ISSUE TITLE
DI in Azure Function static class

### ISSUE THREAD

**Issue by superbmilkyway** [simpleinjector/SimpleInjector#503]
Hi, 

I read documents and search heaps but I don't know what the right approach to manage dependencies in static class. Azure Function must use static class like as following

``` c#
public static class Function1
{
    public static async Task<IActionResult> Run(...)
    {
        // create depedencies here        
    }
}
```

There is a way I can use Simple Injector in Azure Function?
Regardless possible to use Simple Injector, using DI is correct to approach in Azure Function(static class)?

Could you share your experience how to handle dependencies in a Azure Function(static class)?

**Comment by dotnetjunkie** [comment]
Azure Functions are static, which means you can't inject any dependencies into them. Instead, you should view an Azure Function as a [Humble Object](http://xunitpatterns.com/Humble%20Object.html), part of your [Composition Root](http://blog.ploeh.dk/2011/07/28/CompositionRoot/).

What this means is that:

- Your Azure Function should do as little as possible.
- You can achieve this by extracting _all_ logic out of the Azure Function into a separate component.
- Within the Azure Function you request this component directly from your DI Container and call its method that invokes the old code.
- In case you are using the `AsyncScopedLifestyle`, the Azure Function will also has to wrap the resolve and invocation of the component into a new async scope by calling `AsyncScopedLifestyle.BeginScope`.

This might look as follows:

``` c#
public static class Function1
{
    public static async Task<IActionResult> Run(...)
    {
        using (AsyncScopedLifestyle.BeginScope(Global.Container))
        {
            var component = Global.Container.GetInstance<Function1Component>();
            return await component.Run(...);
        }
    }
}
```

**Comment by superbmilkyway** [comment]
@dotnetjunkie Thank you for you answer. I learned a lot.
