### ISSUE TITLE
Method not found: 'Void SimpleInjector.SimpleInjectorWebApiExtensions.RegisterWebApiControllers(SimpleInjector.Container, System.Web.Http.HttpConfiguration)

### ISSUE THREAD

**Issue by adrianiftode** [simpleinjector/SimpleInjector#507]
Hi Steven,

I have this issue,

Steps to reproduce:

1. Create new ASP.NET Web Application (.Net Framework) -> Web Api project
2. Install SimpleInjector Quick Start >= 4.0.0, comment the #error
3. Ctrl + F5
       
And e get the following error 

```
[MissingMethodException: Method not found: 'Void SimpleInjector.SimpleInjectorWebApiExtensions.RegisterWebApiControllers(SimpleInjector.Container, System.Web.Http.HttpConfiguration)'.]
   SimpleInjectorIssue.App_Start.SimpleInjectorWebApiInitializer.Initialize() in D:\dump\simpleinjector\SimpleInjectorPossibleIssue\SimpleInjectorIssue\App_Start\SimpleInjectorWebApiInitializer.cs:25

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +79
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +101
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +21
   WebActivator.BaseActivationMethodAttribute.InvokeMethod() +239
   WebActivator.ActivationManager.RunActivationMethods() +340
   WebActivator.ActivationManager.RunPostStartMethods() +27
   WebActivator.StartMethodCallingModule.Init(HttpApplication context) +125
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +536
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +173
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +10042604
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +95
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254
```

This doesn't reproduce with SimpleInjector 3.2.2

I tried to use the Owin setup, but I got the same issue.

[Here](https://github.com/adrianiftode/SimpleInjectorPossibleIssue) is a setup that reproduces it.

I'm I missing something?

Thanks!

**Comment by dotnetjunkie** [comment]
I'm unsure what's going wrong, but if I reproduce by creating a new Web API project, adding the quick start package and commenting out the #error, the application will start, and I can access the Web API /api/values. 

I cloned your repository, and scanned it shortly, but can't seem to find what's going wrong in your case.

**Comment by adrianiftode** [comment]
I cloned it from another machine and the issue doesn't reproduce here.
One in difference I'm aware is that I have installed .Net Framework 4.7.1 on the machine where I get this issue.

**Comment by dotnetjunkie** [comment]
I have no idea what's going on, but it rather seems a local problem. MethodNotFound implies that the references assembly is found, but the method is missing. Please check:

- To which version of the SimpleInjector.Integration.WebApi.dll your Web API dll refers to (using Reflector or ILAsm or similar tool)
- Which version of SimpleInjector.Integration.WebApi.dll exists on disk at the location the application is started from (typically /bin)
- If that physical version of SimpleInjector.Integration.WebApi.dll contains the missing method `Void SimpleInjector.SimpleInjectorWebApiExtensions.RegisterWebApiControllers(SimpleInjector.Container, System.Web.Http.HttpConfiguration)`.

**Comment by adrianiftode** [comment]
Many thanks for your help. I tried with other repos from github. They went
well until I upgraded the packages. I'll check the dlls on Monday, then
l'll get back to you.

Pe 27 ian. 2018 10:56 a.m., "Steven" <notifications@github.com> a scris:

**Comment by adrianiftode** [comment]
I can now clearly reproduce the issue and to fix it.
The steps are the same, create a project, install the quickstart via package manager, make it compile and run.

This is due to a missing or incorrect assembly binding related to this dependent assembly System.Web.Http. The error doesn't appear once added this in the web.config

```  
<dependentAssembly>
         <assemblyIdentity name="System.Web.Http" publicKeyToken="31BF3856AD364E35" culture="neutral"/>
         <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0"/>
 </dependentAssembly>
```

`SimpleInjector.Integration.WebApi` references `System.Web.Http, Version=4.0.0.0`, but my application is referencing `System.Web.Http, Version=5.2.0.0`, the version in the Visual Studio project template.

Also VS had a warning related to this, but I missed that :)

**Comment by dotnetjunkie** [comment]
Wow... great you found that. That's something that can be really hard to find. And weird that the application starts up initially, but crashes on recycle.

**Comment by umartopia** [comment]
For me, it was due to missing binding redirect  for System.Net.Http:

I had to added the following in web.config to fix the issue:
`<dependentAssembly>
<assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
<bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" /></dependentAssembly>`
