### ISSUE TITLE
Microsoft.Web.Infrastructure not part of the GAC/.net framework

### ISSUE THREAD

**Issue by kasperskov909** [simpleinjector/SimpleInjector#509]
`SimpleInjector.Integration.WebApi.WebHost.QuickStart` package has a **framework** reference to `Microsoft.Web.Infrastructure`. As far as I know, the _Infrastructure_ assembly is a NuGet package - in other words not part of the GAC.

See my issue here:
https://stackoverflow.com/questions/48580482/unable-to-install-nuget-pck-microsoft-web-infrastructure-is-not-in-my-gac

Please correct me if I'm wrong.

**Comment by dotnetjunkie** [comment]
Hmmmm.... that's weird. I swear this was part of the framework in the past. We never had any complaints about this before.

I'll add this issue to the v4.1 backlog, and will fix the NuGet package (and that of SimpleInjector.Integation.MVC3 as well) with v4.1.

In the meantime, you can manually add the Microsoft.Web.Infrastructure NuGet package to your Web API project or don't add the SimpleInjector.Integration.WebApi.WebHost.QuickStart NuGet package to your project, but just the SimpleInjector.Integration.WebApi NuGet package and add the required code manually. The WebHost.QuickStart package is in fact nothing more than a reference to the integration package while injected some code into your application anyway.

The Web API integration page in the documentation describes how to set up a Web API project using Simple Injector.

**Comment by kasperskov909** [comment]
Thanks for the tip.
Unfortunately my parent package has a dependency to the WebHost.QuickStart so that's not possible. I'll contact the package owner and pass on the info.

**Comment by dotnetjunkie** [comment]
> my parent package has a dependency to the WebHost.QuickStart

What package is that?

**Comment by kasperskov909** [comment]
Some Umbraco stuff from a private NuGet server (company stuff).

**Comment by kasperskov909** [comment]
For anyone struggling with this there's a fix from Microsoft:
http://www.microsoft.com/en-us/download/details.aspx?id=1491

**Comment by dotnetjunkie** [comment]
@kasperskov909 Do you have any aditional details on why that ASP.NET MVC 3 Tools Update fixes the problem? Since that update fixes the problem, is there in your opinion still any action from our side required? Is there still something that should be fixed on our side?

**Comment by kasperskov909** [comment]
Give me a couple of days to do some research on this. Seems weird that there is a "fix" for something they deliberately removed from the framework.

**Comment by dotnetjunkie** [comment]
won't fix. This problem seems localized and we are not investing in Web API integration any longer.
