### ISSUE TITLE
RegisterCollection like action using LifeStyle

### ISSUE THREAD

**Issue by guy-lud** [simpleinjector/SimpleInjector#516]
Hi @dotnetjunkie,

I have a question about the ability to register a collection using a `LifeStyle`.

The scenario is when an `ResolveUnregisteredType` event is invoked i'll check to see if the `UnregisteredServiceType` is of type `IEnumerable<>`.

After getting the `ElementType` i would like to register the type as a collection with the same LifeStyle as the `ElementType` was registered (if was registered).

This is an edge case i am trying to solve and not the best practice, yet it needs to be done

**Comment by dotnetjunkie** [comment]
I'm not sure I completely follow what it is you are trying to achieve.

I'm I correct that you wish to mimic the behavior of other DI Containers, in such way that when a single component is registered (using `Register`), that this component can automatically be resolved as collection as well? And you wish in that case to have the collection have a singleton lifestyle, while the component is resolved from the collection/stream using its original lifestyle (which is typical Simple Injector behavior).

Could you describe if my assumption is correct, and why you would want such type of behavior?

**Comment by guy-lud** [comment]
@dotnetjunkie Yes, your assumption is correct.

I need this behavior on limited amount of whitelist of objects. 

Is it possible (i rather not use attributes to mark those objects)

**Comment by dotnetjunkie** [comment]
Do you have that list available at application start-up?

**Comment by guy-lud** [comment]
No, the list is loaded dynamically as types using reflection

**Comment by dotnetjunkie** [comment]
In that case, `ResolveUnregisteredType` seems like the correct hook, although I feel obliged that in general registrations are either one-to-one _or_ collections, but not both. If you have many of those registrations, that seems smelly to me.

That warning set aside, the following code would get collections auto-registered using the stream-behavior of Simple Injector collections:

``` c#
container.ResolveUnregisteredType += (s, e) =>
{
    Type serviceType = e.ResolveUnregisteredType;
    
    if (serviceType.IsGenericType && serviceType.GetGenericTypeDefinition() ==typeof(IEnumerable<>))
    {
        Type elementType = serviceType.GetGenericArguments().Single();
    
        InstanceProducer[] producers = /* load relevant producers */;

        // Create a stream
        var castMethod = typeof(Enumerable).GetMethod("Cast").MakeGenericMethod(elementType);
        object stream = producers.Select(p => p.GetInstance());
        stream = castMethod.Invoke(null, new[] { stream });
        
        // Register stream as singleton
        e.Register(
            Lifestyle.Singleton.CreateRegistration(serviceType, () => stream, container));
    }
};
```

**Comment by guy-lud** [comment]
@dotnetjunkie Thank you.

As i understand this is the way you register collections ?

BTW I agree with your warning that a system should choose between Single and Collection registration.
For those of you who read this and don't understand why, lets imagine that container A allow to do such a thing. One service has a dependency of the collections and he will get a collection of services. A second developer build a service with a single service from this collection, which one will it get ?? this ambiguity is very unhealthy and could have side effects.

Thanks You

**Comment by dotnetjunkie** [comment]
An even more elaborate explanation about why to separate collections from non-collections can be found in the documentation [here](https://simpleinjector.org/decisions#separate-collections).

**Comment by dotnetjunkie** [comment]
> As i understand this is the way you register collections ?

I'm in doubt about what you exactly mean by this question, but the code I shown above does mimic Simple Injector's behavior when it comes to handling collections, i.e. when calling `RegisterCollection`, the registered _collection_ is always a reference to a single _stream_ instance (a  `Singleton` ), that will start resolving elements from the container, every time it is iterated. So lifestyle of the elements is maintained.

To my knowledge, Simple Injector is the only DI Container that truly sees `IEnumerable<T>` dependencies as _streams_.

**Comment by guy-lud** [comment]
This is why i love it
