### ISSUE TITLE
Simplify working with subsets of collections

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#517]
Simple Injector has a very decent strategy when it comes to working with collections. However, when subsets of collections need to be registered to certain consumers, the solution becomes rather complicated.

Take the following example for instance where there is a collection of `IZ` instances and two consumers `C1` and `C2` that both depend on `IEnumerable<IZ>`, but both require a subset of `IZ` instances.

``` c#
public interface IZ { }
public class Z1 : IZ { }
public class Z2 : IZ { }
public class Z3 : IZ { }
public class Z4 : IZ { }

public class C1
{
    public C1(IEnumerable<IZ> collection) => Collection = collection;
    public IEnumerable<IZ> Collection { get; }
}

public class C2
{
    public C2(IEnumerable<IZ> collection) => Collection = collection;
    public IEnumerable<IZ> Collection { get; }
}
```

With Simple Injector v4.0, this can be achieved as follows:

``` c#
var container = new Container();

container.Register<C1>();
container.Register<C2>();
var z1 = Lifestyle.Transient.CreateProducer<IZ, Z1>(container);
var z2 = Lifestyle.Transient.CreateProducer<IZ, Z2>(container);
var z3 = Lifestyle.Transient.CreateProducer<IZ, Z3>(container);
var z4 = Lifestyle.Transient.CreateProducer<IZ, Z4>(container);

// Z1, Z2, Z3 injected into C1
container.RegisterConditional(typeof(IEnumerable<IZ>),
    Lifestyle.Singleton.CreateRegistration(() => ProducerIterator(z1, z2, z3), container),
    c => c.Consumer.ImplementationType == typeof(C1));

// Z2, Z3, Z4 injected into C2
container.RegisterConditional(typeof(IEnumerable<IZ>),
    Lifestyle.Singleton.CreateRegistration(() => ProducerIterator(z2, z3, z4), container),
    c => c.Consumer.ImplementationType == typeof(C2));
```

Here, `ProducerIterator` is the following extension method:

``` c#
private IEnumerable<T> ProducerIterator<T>(params InstanceProducer<T>[] producers) where T : class
{
    foreach (var producer in producers) yield return producer.GetInstance();
}
```

**Comment by dotnetjunkie** [comment]
I suggest adding a `Collections` property to the `Container` instance to allow grouping of collection related methods that allow simplifying working with collections. For instance:

#### `Collections.Create<TService>`

``` c#
// Collections.Create allows creating a stream based on the supplied types. Iterating the stream
// would produce instances according to their lifestyle (as usual).
IEnumerable<IZ> stream1 = container.Collections.Create<IZ>(typeof(Z1), typeof(Z2), typeof(Z3));
IEnumerable<IZ> stream2 = container.Collections.Create<IZ>(typeof(Z2), typeof(Z3), typeof(Z4));

container.RegisterSingleton(new C1(stream1));
container.RegisterSingleton(new C2(stream2));
```

#### `Collections.CreateRegistration<TService>(params Type[])`

``` c#
container.Register<C1>();
container.Register<C2>();

container.RegisterConditional(typeof(IEnumerable<IZ>),
    container.Collections.CreateRegistration<IZ>(typeof(Z1), typeof(Z2), typeof(Z3)),
    c => c.Consumer.ImplementationType == typeof(C1));

container.RegisterConditional(typeof(IEnumerable<IZ>),
    container.Collections.CreateRegistration<IZ>(typeof(Z2), typeof(Z3), typeof(Z4)),
    c => c.Consumer.ImplementationType == typeof(C2));
```

#### `Collections.CreateRegistration<TService>(params InstanceProducer<TService>[])`

``` c#
var z1 = Lifestyle.Transient.CreateProducer<IZ, Z1>(container);
var z2 = Lifestyle.Transient.CreateProducer<IZ, Z2>(container);
var z3 = Lifestyle.Transient.CreateProducer<IZ, Z3>(container);
var z4 = Lifestyle.Transient.CreateProducer<IZ, Z4>(container);

container.RegisterConditional(typeof(IEnumerable<IZ>),
    container.Collections.CreateRegistration(z1, z2, z3),
    c => c.Consumer.ImplementationType == typeof(C1));

container.RegisterConditional(typeof(IEnumerable<IZ>),
    container.Collections.CreateRegistration(z2, z3, z4),
    c => c.Consumer.ImplementationType == typeof(C2));
```

The `Container.Collections` method grouper also allow making the 'append to collection' feature more discoverable, since that feature now hidden behind the `SimpleInjector.Advanced` namespace:

``` c#
// This
container.Collections.AppendTo(typeof(IValidator<>), typeof(DataAnnotationsValidator<>));

// instead of
using SimpleInjector.Advanced;
container.AppendToCollection(typeof(IValidator<>), typeof(DataAnnotationsValidator<>));
```

**Comment by TheBigRic** [comment]
Although I do not really understand when and why somebody would need a subset of a collection I think, assuming this is a valid use case, the approach is very clean, super easy to read  and therefore far more understandable then the needed syntax in 4.0. 

Maybe offtopic, but:
Is there also possibility we can make it a little easier to differ from lifestyles in through this new "namespace"?

Consider this registration:
``` c#
container.RegisterCollection(typeof(IValidator<>), assemblies);
```

Maybe I'm wrong but I think this is the equivalent of:
``` c#
var types = container.GetTypesToRegister(typeof(IValidator<>), assemblies, 
                new TypesToRegisterOptions
                {
                    IncludeComposites = false
                });
var collection = new SomeSuperSmartSimpleInjectorContainerControllerCollectionClass();
foreach (var type in types)
{
    // when the configured default lifestyle == Lifestyle.Transient:
    var registration = Lifestyle.Transient.CreateRegistration(type, container); 
    collection.Add(registration);
}

container.RegisterSingleton(typeof(IEnumerable<IValidator<>>), collection);
```

Which makes it somewhat hard to specify the lifestyle of the items in the stream. Agreed not a feature needed often, but there are some corner cases where I need this.

**Comment by dotnetjunkie** [comment]
> Maybe I'm wrong but I think this is the equivalent of:

Pretty close.

> Which makes it somewhat hard to specify the lifestyle of the items in the stream. 

Not at all. You can change the lifestyle of individual registrations in a collection as follows:

``` c#
var types = new[]
{
    typeof(OrderValidator), typeof(CustomerValidator), typeof(ProductValidator)
};

container.RegisterCollection(typeof(IValidator<>), types);

// Override lifestyles
container.Register<CustomerValidator>(Lifestyle.Singleton);
container.Register<ProductValidator>(Lifestyle.Scoped);
```

**Comment by TheBigRic** [comment]
Well of course. But that is not really intuitive code if you ask me. Especially if you compare that to my code sample, where I let Simple Injector scan for all implementations and let it group this by type. 

I use this extension method to do this and my question was if that was maybe something useful to add to the `Collection` method grouper:

``` c#
private static void RegisterCollection<TService>(this Container container, 
                            IEnumerable<Assembly> assemblies, Lifestyle lifestyle)
{
    var options = new TypesToRegisterOptions
    {
        IncludeComposites = false,
        IncludeDecorators = false,
        IncludeGenericTypeDefinitions = true,
    };
    var types = container.GetTypesToRegister(typeof(TService), assemblies, options);
    container.RegisterCollection(typeof(TService),
        from type in types
        select lifestyle.CreateRegistration(type, container));
}
```

**Comment by dotnetjunkie** [comment]
> Which makes it somewhat hard to specify the lifestyle of the items in the stream. 

There are several ways to influence the lifestyle of the items in the collection:

1. You can register the concrete type using `Register<T>(Lifestyle)` as shown in my [last comment](https://github.com/simpleinjector/SimpleInjector/issues/517#issuecomment-370845271).
2. You can supply a list of `Registration` instances to `RegisterCollection`.
3. You can replace the default `ILifestyleSelectionBehavior`.

### You can supply a list of `Registration` instances to `RegisterCollection`

``` c#
var types = container.GetTypesToRegister(
    typeof(IValidator<>),
    assemblies,
    new TypesToRegisterOptions { IncludeComposites = false });
  
//   DetermineLifestyle is a custom method
var registrations =
    from type in types
    let lifestyle = DetermineLifestyle(type)
    select lifestyle.CreateRegistration(type, container);
    
container.RegisterCollection(typeof(IValidator<>), registrations);
```

### You can replace the default `ILifestyleSelectionBehavior`

``` c#
// Here MyCustomLifestyleBehavior has the same role as DetermineLifestyle
// of the previous example, but is now used globally by the container.
container.Options.LifestyleSelectionBehavior =
    new MyCustomLifestyleBehavior(container);
    
container.RegisterCollection(typeof(IValidator<>), assemblies);
```

**Comment by dotnetjunkie** [comment]
Perhaps the `Container.RegisterCollection` methods should be moved as well.

Using the new `Collections.AppendTo`, this will be typical codeL

``` c#
container.RegisterCollection(typeof(IValidator<>), typeof(IValidator<>).Assembly);
container.Collections.AppendTo(typeof(IValidator<>), typeof(DataAnnotationsValidator<>));
```

Perhaps this should become:

``` c#
container.Collections.Register(typeof(IValidator<>), typeof(IValidator<>).Assembly);
container.Collections.AppendTo(typeof(IValidator<>), typeof(DataAnnotationsValidator<>));
```

@TheBigRic, any opinion about this?

**Comment by TheBigRic** [comment]
I have normally an opinion about everything.. :-)

Looks very clean. As a matter of fact I think this will further clarify that S.I. separates normal registrations from registration of collections. Questions regarding this still pop us regulary on the interwebs
