### ISSUE TITLE
Using AsyncScopedLifestyle.BeginScope() on DelegatingHandler

### ISSUE THREAD

**Issue by johnfercher** [simpleinjector/SimpleInjector#521]
I'd like to create a logger component with `Scoped.LifeStyle` for my WebApi application, I want to carry some attributes in the logger through all objects that will eventually called in a request. But, I'm having problems with my approach.

I'm trying to create the AsyncScope like shown in the second commentary in this issue (https://github.com/simpleinjector/SimpleInjector/issues/419)

I'm starting the `Scope` in a `DelegatingHandler`, using the example in the bottom of (https://simpleinjector.readthedocs.io/en/latest/webapiintegration.html)

Here is my `DelegatingHandlerProxy`.

``` c#
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using SimpleInjector;
using SimpleInjector.Lifestyles;

namespace ChargebackApi.Infrastructure
{
    public class DelegatingHandlerProxy<THandler> : DelegatingHandler
        where THandler : DelegatingHandler
    {
        private readonly Container container;

        public DelegatingHandlerProxy(Container container)
        {
            this.container = container;
        }

        protected override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request, CancellationToken cancellationToken)
        {
            using (AsyncScopedLifestyle.BeginScope(container))
            {
                var handler = this.container.GetInstance<THandler>();

                if (!object.ReferenceEquals(handler.InnerHandler, this.InnerHandler))
                {
                    handler.InnerHandler = this.InnerHandler;
                }

                var invoker = new HttpMessageInvoker(handler);

                return invoker.SendAsync(request, cancellationToken);
            }            
        }
    }
}
```

Here is my `LogMessageHandler`.

``` c#
using System;
using ChargebackApi.Infrastructure.Interface;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using SimpleInjector.Lifestyles;

namespace ChargebackApi.Infrastructure
{
    public class LogMessageHandler : DelegatingHandler
    {
        public readonly ILogger Logger;

        public LogMessageHandler(ILogger logger)
        {
            Logger = logger;
        }

        protected override async Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request, CancellationToken cancellationToken)
        {
            Logger.IpAddress = IpAddressReader.GetClientIp(request);
            Logger.RequestId = Guid.NewGuid().ToString();

            var response = await base.SendAsync(request, cancellationToken);

            return response;
        }
    }
}
```

Here is my `SimpleInjectorInitialize`.

``` c#
var container = new Container();

container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
container.Register<LogMessageHandler>(Lifestyle.Scoped);
container.Verify();

GlobalConfiguration.Configuration.MessageHandlers.Add(
    new DelegatingHandlerProxy<LogMessageHandler>(container));
GlobalConfiguration.Configuration.DependencyResolver = 
    new SimpleInjectorWebApiDependencyResolver(container);
```

With my approach I keep the properties, but, when the `LogMessageHandler` called by `DelegatingHandlerProxy` uses the the method `base.SendAsync(request, cancellationToken)`, the `DelegatingHandlerProxy` is called again and at some moment the application break.

**Comment by dotnetjunkie** [comment]
I'm unsure whether or not this is the proble, but what I find suspicious, is that you create a new scope in your `DelegatingHandlerProxy<T>`. The [documentation](https://simpleinjector.readthedocs.io/en/latest/webapiintegration.html) instead calls `request.GetDependencyScope();`.

Creating a scope, can cause multiple nested scopes, because each proxy will get its own scope, and controllers might again run in their own scope.

**Comment by dotnetjunkie** [comment]
I've been trying to reproduce the issue you are having, but I don't see the "application break". What I do see however is, that, as stated above, once you start to add more delegating handlers, your original logger values are 'wiped', because inner handlers run in their own scope.

In other words, while the following configuration would work:

``` c#
configuration.MessageHandlers.Add(new DelegatingHandlerProxy<LogMessageHandler>(container));
```

The following would fail:

``` c#
configuration.MessageHandlers.Add(new DelegatingHandlerProxy<LogMessageHandler>(container));
configuration.MessageHandlers.Add(new DelegatingHandlerProxy<EmptyMessageHandler>(container));
```

This will fail, because the `EmptyMessageHandler` and everything running after it, will get its own isolated scope.

The solution therefore is to change the `DelegatingHandlerProxy<T>` to the following:

``` c#
public sealed class DelegatingHandlerProxy<THandler> : DelegatingHandler
    where THandler : DelegatingHandler {
    private readonly Container container;

    public DelegatingHandlerProxy(Container container) {
        this.container = container;
    }

    protected override Task<HttpResponseMessage> SendAsync(
        HttpRequestMessage request, CancellationToken cancellationToken) {

        // Important: Trigger the creation of the scope.
        request.GetDependencyScope();

        var handler = this.container.GetInstance<THandler>();

        if (!object.ReferenceEquals(handler.InnerHandler, this.InnerHandler)) {
            handler.InnerHandler = this.InnerHandler;
        }

        var invoker = new HttpMessageInvoker(handler);

        return invoker.SendAsync(request, cancellationToken);
    }
}
```

So instead of creating a scope, just call `request.GetDependencyScope()`. This approach is outlined in [the  documentation](https://simpleinjector.readthedocs.io/en/latest/webapiintegration.html).

> and at some moment the application break.

If the previous information doesn't fix the problem, please provide more details about how your application breaks. What is the exception, the message and the stack trace. Please include the details of any inner exception as well.

**Comment by johnfercher** [comment]
I've made the changes that you suggested. But now I'm getting the error below,

```
SimpleInjector.ActivationException: 'The LogMessageHandler is registered as 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope.'
```

**Comment by dotnetjunkie** [comment]
Please provide full error details.

**Comment by johnfercher** [comment]
SimpleInjector.ActivationException
  HResult=0x80131500
  Message=The LogMessageHandler is registered as 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by dotnetjunkie** [comment]
Please provide the stack trace.

**Comment by johnfercher** [comment]
Here's the stack trace.
`
"Message": "An error has occurred.",
"ExceptionMessage": "The LogMessageHandler is registered as 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope.",
"ExceptionType": "SimpleInjector.ActivationException",
"StackTrace": "   at SimpleInjector.Scope.GetScopelessInstance[TImplementation](ScopedRegistration`1 registration)
at SimpleInjector.Scope.GetInstance[TImplementation](ScopedRegistration`1 registration, Scope scope)
at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
at lambda_method(Closure )
at SimpleInjector.InstanceProducer.GetInstance()
at SimpleInjector.Container.GetInstanceForRootType[TService]()
at SimpleInjector.Container.GetInstance[TService]()
at WebApi.Infrastructure.DelegatingHandlerProxy`1.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in 
C:\\Path\\DelegatingHandlerProxy.cs:line 24
at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
`

**Comment by dotnetjunkie** [comment]
I'm unable to reproduce this. Could you provide me with the a minimal working example that demonstrates the issue? Feel free to post it here, or create a Github repository with the _minimal_ amount of code that demonstrates the problem.
