### ISSUE TITLE
This is not actually an 'Issue', I just wanted to say thank you!

### ISSUE THREAD

**Issue by seangwright** [simpleinjector/SimpleInjector#525]
Reading the SI docs, your blog, your SO answers and all the issues opened and answered here has (I'd like to think) made me a better (or at least more thoughtful) developer.

I come back to the repo and read issues, often unrelated to anything I'm working on, just to gain some insight and wisdom. Sometimes something that I don't think is related to my work ends up being directly applicable.

Your adherence to SOLID principles and opinionated approach to architecture with SI is awesome and for someone like myself who understands SOLID but really wants to see practical approaches to implementing those principles in real world scenarios all your work within the community has been very appreciated.

I don't think there are any other people of standing in the .net community that I've seen spend as much time helping out developers with answers to their problems that are always so much more detailed and helpful than I would expect anyone to have the time or patience to give.

So, thanks! Your efforts are very appreciated.

I am also planning to get a [copy of the book](https://mng.bz/BYNl) you and Mark Seemann are working on. I recommend your blog (and this repo) to any developers I meet asking a good place to go to learn more about .net and design patterns. I'll recommend your book now too!

**Comment by dotnetjunkie** [comment]
@sgwatgit, well, what can I say? Just doing the best I can, with the amount of time given. Thank you very much for your gratitude and support. I hope I can continue doing this for a long time to come.

**Comment by devhb** [comment]
True words @sgwatgit and I totally agree. Big thanks to @dotnetjunkie for the effort

**Comment by carstengehling** [comment]
+1(million) from me as well - this is a truly remarkable example of, how good software should be crafted. Bowing in respect.

**Comment by Der-Inder** [comment]
i too mirror what all others have earlier said.
Huge thanks to @dotnetjunkie for the effort, time and guidance for improving my and other developer's skills.
Today I had bought the MEAP edition of @dotnetjunkie upcoming book, after having the first edition from mark Seemann. pretty sure will learn a lot from it.

**Comment by sgwatgit** [comment]
Just want to say I purchased Dependency Injection in .NET, Second Edition last night and I recommend everyone to do the same.

I was reading through the Manning forums for the book and found even more great knowledge.

Thanks!
