### ISSUE TITLE
Handling multiple databases with NHibernate 

### ISSUE THREAD

**Issue by hellboy81** [simpleinjector/SimpleInjector#531]
I am trying to use NHibernate with Simple Injector. 

At the moment only one Oracle database is used. 

The existing working code should be updated to handle one another Oracle database to execute "read only" sql queries (`SELECT`)

Normal run:

- `TestDbSessionFactoryProvider` for repos _Type 1_ 
- `AnotherTestDbSessionFactoryProvider` for repos _Type 2_ // AnotherTestDb is new

Unit tests:

- `TestDbSessionFactoryProvider for "read" repos _Type 1_
- `AnotherTestDbSessionFactoryProvider` for repos _Type 2_
- `SQLiteSessionFactoryProvider` for "write" repos _Type 1_ // SQLite is new

- "Read repo" only executes select SQL or SP
- "Write repo" only saves or updates entities:

Due on lack advanced experience I have trouble to update this code to handle multiple database connections.

``` C#
public static void RegisterTestDatabaseServices(SimpleInjector.Container container)
{
    // Is it correct way to regsiter "multiple" providers?
    container.RegisterCollection<ISessionFactoryProvider>(
		new [] 
		{
			// Used for "read" repositories Type 1 and "write" repositories Type 1
			typeof(TestDbSessionFactoryProvider), 
			// Used only for "read" repositories Type 2
			typeof(AnotherTestDbSessionFactoryProvider), 
			// Used forto mock "write" repositories Type 1
			typeof(SQLiteSessionFactoryProvider) 
		});
	
	// TODO Should be updated 
	container.Register(() => container
		// replace with GetAllInstances ???
	   .GetInstance<ISessionFactoryProvider>()
	   // from SessionProvider
	   .GetInstance());
	
	// TODO Should be updated 
	// Session Provider implememts `ISession GetCurrenSession()`
	container.Register<ISessionProvider, SessionProvider>();
	
	// TODO Should be updated 
	// IWriteSession is descendand for ISession and used by "write repos"  as 
	// Constuctor dependency
	// Here TestDbSessionFactoryProvider by default should be choosen
	// but also SQLiteSessionFactoryProvider for NUnit tests
	// Important: only one SessionFactoryProvider is used at runtime
	container.Register(typeof(IWriteSession), () => container
	   .GetInstance<ISessionProvider>()
	   .GetCurrentSession()
	   );
	
	// TODO Should be updated 
	// May be IReadSession should be splited into ITestDbReadSession for repos type 1
	// and IAnotherTestDbReadSession for repos type 2
	// Important: BOTH SessionFactoryProvider' s can be used at runtime
	container.Register(typeof(IReadSession), () => container
	   .GetInstance<ISessionProvider>()
	   .GetCurrentSession()
	   );
}
```

**Comment by dotnetjunkie** [comment]
I think you want to make your provider registrations conditional based on their consumer. You can find more information on how to do this, here: https://simpleinjector.readthedocs.io/en/latest/advanced.html#context-based-injection

**Comment by hellboy81** [comment]
As I mentioned there are some design issues here:

![image](https://user-images.githubusercontent.com/341600/38793398-6b1152d2-4151-11e8-82db-f3e13a91c238.png)


```cshrap

// Wrong design
// IReadRession is "derived" from NHibernate's ISession 
ISession baseSession = GetBaseCurrentSession();

// baseSession is NHibernateSessionImpl
// readSession is null
IReadSession readSession = baseSession as IReadSession; 
```

**Comment by hellboy81** [comment]
As I mentioned OUW and Repository are antipatterns and not suitable to handle multiple database connections.

See answer on [SO](https://stackoverflow.com/questions/48572072/simpleinjector-register-multiple-database-connections/48573496#48573496)
