### ISSUE TITLE
IoC in WCF hosted in Windows Service and container lifetime per call

### ISSUE THREAD

**Issue by JurgenStillaert** [simpleinjector/SimpleInjector#537]
I have a few clients (web and desktop apps) that must connect to a few services which are WCF services hosted in a Windows Service. These services must get data from one or more databases, but it is the client who determines from which database, there can be one or more databases from the same type defined.

I have a setup in the service with datacontexts, repositories, business managers and an implementation for the services. Datacontext is injected by the SimpleInjector container and off course, the registrations in the container takes place before the creation of the ServiceHosts, which are created in context mode Per Call.

I have written an implementation of the IDispatchMessageInspector that will intercept all SOAP messages and read the message header and set the database connnection string of the datacontext depending on the values in the message header. But this will lead to problems because it is not "thread safe", or at least when one call is not finished yet, the next call will maybe set another connectionstring to the same datacontext, messing it all up.

So, I'm trying to get this registered as per call (async, wcf lifestyle) but because this is a Windows Service, it will not close and the container is not scoped properly.

What can I do in this scenario to make it work?

![image](https://user-images.githubusercontent.com/6113713/38997220-425f9ca6-43ed-11e8-8427-e61a97cba4e9.png)

Container creation and service host start:

![image](https://user-images.githubusercontent.com/6113713/38997379-9d0f6dd4-43ed-11e8-919c-6f5ceec4e063.png)

The container is also in a static class as suggested in the docs.

**Comment by dotnetjunkie** [comment]
This is a duplicate: https://stackoverflow.com/questions/29349577/reuse-specflow-steps-in-another-project-in-the-same-solution
