### ISSUE TITLE
Remove the use of ThreadLocal<T> in the decorator sub system

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#540]
The use of `ThreadLocal<T>` within Simple Injector is problematic whenever the user creates an infinite number of `Container` instances (which btw is a practice that is not encouraged). `ThreadLocal<T>` causes memory leaks when it is not disposed properly.

The decorator sub system currently makes use of `ThreadLocal<T>` instances to build a list of decorators used for a given registration. This information is then provided to predicates, to allow decorators to be applied conditionally.

Changes should be made to the decorator sub system, in such way that `ThreadLocal<T>` is only used for a short period of time (during the time that `ExpressionBuilt` events are running, for instance), so that caching of `ThreadLocal<T>` instance for the duration of the container can be prevented.

This prevents memory leaks, such as described in #539.

**Comment by dotnetjunkie** [comment]
[feature-540 branch](https://github.com/simpleinjector/SimpleInjector/tree/feature-540) created.

**Comment by andreminelli** [comment]
Hi. 
I know this issue is closed, but ThreadLocal<bool> usage is still an important "contributor" to overall memory usage in scenarios with hundreds of container (I know is not encouraged, but this makes some use cases easier). 

Is there any plans to keep replacing it?

**Comment by dotnetjunkie** [comment]
There are no plans currently in further reducing the usage of `ThreadLocal<T>`.

I'm curious, can you explain why you are using "hundreds of container" instances?

**Comment by dotnetjunkie** [comment]
Can you also describe your memory usage and how you measured this, and what percentage of memory usage is caused by `ThreadLocal<T>`?

**Comment by andreminelli** [comment]
BTW, there is [an issue in dotnet runtime](https://github.com/dotnet/runtime/issues/2382) about this memory usage on ThreadLocal implementation.

**Comment by andreminelli** [comment]
> Can you also describe your memory usage and how you measured this, and what percentage of memory usage is caused by `ThreadLocal<T>`?

We took a memory dump and analyze it. 
We have spotted very large arrays (4 Million in length, in some cases) of ThreadLocal<bool>.LinkedSlot on LOH, the majority of them "attached" to CyclicDependencyValidator. This sample had about 6GB, and LOH allocated spaced (which was very fragmented) was about 2GB.

**Comment by dotnetjunkie** [comment]
> the majority of them "attached" to CyclicDependencyValidator. 

Ah... the good old `CyclicDependencyValidator`.  

> We have spotted very large arrays (4 Million in length, in some cases)

Ouch.. that's a lot of data.

But this is actually something I can help you with, because the `CyclicDependencyValidator` internal `ThreadLocal<bool>` is easily disposed of. In fact, it's so easy that I'm wondering why I never did this before, because I know I've looked at this in the past.

I published a [beta of v5.4.1](https://www.nuget.org/packages/SimpleInjector/5.4.1-beta1) for you on NuGet. I hope you'll be able to test this and report back if this changes your situation and by how much it changes this.

The only change between v5.4.1-beta1 and v5.4.0 is the disposal of the `CyclicDependencyValidator` and its underlying `ThreadLocal<bool>`.

Let me know what the results are. If you're happy with the results I'll create an official patch release for v5.4.1.

**Comment by andreminelli** [comment]
Wow, that was quick :)
I will sure test it, and I will let you know about any findings we come up with.
Thank you for this!

**Comment by dotnetjunkie** [comment]
> Wow, that was quick :)

At your service ;-)

**Comment by dotnetjunkie** [comment]
Please also test the just pushed 5.4.1-beta2. This version completely removes the `ThreadLocal<bool>` and replaces it with a custom (internal) implementation, which might remove the problem altogether.

 I hope you can run both versions through a benchmark to see whether they work and which one works best.

I'm waiting for your feedback.

**Comment by andreminelli** [comment]
@dotnetjunkie , on a 'lab test' (creating pretty much the same dependency tree we use in production where the original memory dumps were extracted, although using less complicated 'state machine definitions') I have observed a small decrease on LOH using 5.4.1-beta release. 
Probably this marginal improvement is because the 'tricky part' you mentioned on this #956, right?

Using 5.4.0 the LOH has:

```
Memory address	Type	Size in bytes
 
 0x212818B1118	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x212718110A8	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x212618E90F8	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x212618690C0	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x212617E9088	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x212519586B8	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x21241911150	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x21241891118	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x212318E90F8	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x212318690C0	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x212317E9088	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x21221889130	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x21251805E10	System.Byte[]	108264
 0x212617D1038	System.Int32[]	98352
```

Using 5.4.1-beta it was like this (observe the last ThreadLocal+LinkedSlotVolatile<System.Boolean>[] was smaller - I have added "***" to emphasize it):

```
Memory address	Type	Size in bytes
 
 0x2B95E9690C0	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x2B94EA110E0	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x2B94E9910A8	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x2B92E9C0550	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x2B90E9910A8	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x2B8FE9B1070	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x2B8FE931038	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x2B8EEA71118	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
 0x2B8EE9F10E0	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	524312
0x2B93E9910E0	System.Threading.ThreadLocal+LinkedSlotVolatile<System.Boolean>[]	262168 ***
 0x2B92E965E10	System.Byte[]	108264
 0x2B95E931038	System.Int32[]	98352
```
As reference, the pseudo-code for this test is below:
```csharp
var containers = CreateContainers(count: 1000);
Parallel.ForEach(containers, container =>
    {
        var _ = container.GetInstance<IRootObject>();
    });

GC.Collect();

Parallel.ForEach(containers.ToArray(), container =>
    {
        container.Dispose();
        containers.Remove(container);
    });

GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();
```

**Comment by andreminelli** [comment]
Indeed, using 5.4.1-beta2 we have this:

```
Memory address	Type	Size in bytes
 
 0x280F7645E10	System.Byte[]	108264
 0x28137611038	System.Int32[]	98352
```

The final question is: how confident about your hand-written 'thread local' implementation are you? :)
You think is good enough for production systems?

**Comment by dotnetjunkie** [comment]
> The final question is: how confident about your hand-written 'thread local' implementation are you? :)

I'll let you be the judge of that.

You can review the new implementation [here](https://github.com/simpleinjector/SimpleInjector/blob/v5.4.x/src/SimpleInjector/Internals/CyclicDependencyValidator.cs).

**Comment by andreminelli** [comment]
It seems simple enough..

If you allow me, I would like to make some observations:
1) Usually is not a good practice to lock using `this` - use a private, dedicated object, is recommended.
2) It seems safer to me getting the current thread id right from the start of the method, as you did on `MarkCurrentThreadAsEntering`, so if a context switch (and maybe a thread switch, too) happens, the original thread id is retained inside the method. If so, this 'pattern' should be applied to `MarkCurrentThreadAsLeaving` and `IsCurrentThreadReentering` too.

**Comment by andreminelli** [comment]
> I feel that the guideline doesn't apply here, because the type is internal and references are not shared

Makes sense to me.

> To my knowledge its impossible for a context switch to cause the managed thread id to change

You are right, a context switch doesn't change the thread at all.

> Thanks for this code review.

Man, don't even mention it.
Thank you again for this!

When do you expect to release version 5.4.1?

**Comment by dotnetjunkie** [comment]
> When do you expect to release version 5.4.1?

Two minutes ago.
