### ISSUE TITLE
Allow List<T> and Collection<T> to be injected into constructor arguments

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#545]
Simple Injector supports a wide range of collection types, such as:

-    `IEnumerable<T>`
-    `IList<T>`
-    `ICollection<T>`
-    `IReadOnlyList<T>`
-    `IReadOnlyCollection<T>`

All these abstractions behave as streams and injected instances are all immutable, which allows them to be injected as singleton.

Besides those abstractions, Simple Injector allows injecting array as mutable type. Because of array's mutability, arrays are injected as transient:

- `T[]`

Because Simple Injector allows injecting array as mutable transient collection type, there is no reason why it wouldn't support:

- `List<T>`
- `Collection<T>`

**Comment by dotnetjunkie** [comment]
Since `T[]` is a mutable type, it is injected as a `Transient`, since, even if all elements in the array are `Singletons`, someone could still change the array, which could break the application, because the array would be reused.

Since `List<T>` is mutable and does not allow its underlying behavior to be influenced (i.e. it doesn't contain any `virtual` methods), it should be registered as `Transient` as well. This follows the same argument as for arrays.

The big design question here is: how should `Collection<T>` behave? There are 3 options here:

- `Collection<T>` is kept mutable and injected as `Transient`, which mimics the behavior of `T[]` and `List<T>`.
- `Collection<T>` is made immutable (i.e. by overriding its virtual methods), but the lifestyle is kept `Transient`.
- `Collection<T>` is made immutable and gets the lifestyle gets promoted to the shortest lifestyle of its elements. E.g. in case all the elements are `Singletons`, the `Collection<T>` will become a singleton as well.

What is impossible to do however, is to let `Collection<T>` behave as a stream, since, although its command methods can be overridden, its query methods can't.

How should `Collection<T>` behave?

**Comment by TheBigRic** [comment]
I would follow the KISS principle here.  Option 1: Keep `Collection<T>` mutable and inject as `Transient`.

Option 2 is a strange one, because all other immutable implementations are `Singleton`.

Option 3 sounds ok, but since it is impossible to let `Collection<T>` to behave as a stream, choosing option 3 introduces a third kind of collection and thus will lead to extra documentation and support. 

Letting `Collection<T>` behave as an `Array` and `List<T>` keeps documentation as simple as possible. I guess this will be the same for the codebase.

**Comment by dotnetjunkie** [comment]
In contrast to what I stated above, a `Collection<T>` can easily function as stream. Although it is impossible to override all methods, inheritance is not required. A `Collection<T>` is just a wrapper of an underlying `IList<T>` that is supplied through its constructor. An `Collection<T>` itself contains no state. When the supplied `IList<T>` works as a stream, so will the `Collection<T>` that wraps it.

Since streaming behavior works for `Collection<T>`, we should go with that behavior. It has the best performance and is the same behavior as what most other collection types have.
