### ISSUE TITLE
Donation / Monetary Sponsorship Link Please

### ISSUE THREAD

**Issue by ferventcoder** [simpleinjector/SimpleInjector#549]
Hello @dotnetjunkie! 

We have just kicked off our philanthropy to give back to FOSS projects in the Windows and .NET space. We've decided to start with projects that we use.

We'd love to discuss more on this. Can you provide us donation link or paypal email please?

**Comment by dotnetjunkie** [comment]
Please see https://github.com/simpleinjector/SimpleInjector/issues/481

**Comment by ferventcoder** [comment]
@dotnetjunkie I'll respond over there.
