### ISSUE TITLE
Iterating collection with scoped dependencies in singleton consumer accidentally succeeds inside Verify()

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#554]
Consider the following code:

``` c#
public class Consumer
{
    private readonly ILogger[] loggers;
    public Consumer(IEnumerable<ILogger> loggers)
    {
        this.loggers = loggers.ToArray();
    }
}
```

Using this class, the following code will fail:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

container.Register<NullLogger>(Lifestyle.Scoped);
container.RegisterCollection<ILogger>(new[] { typeof(NullLogger) });
container.Register<Consumer>(Lifestyle.Singleton);

container.GetInstance<Consumer>();
```

With the following exception:

> The NullLogger is registered as 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope.

However, when a `Verify()` call is added, it accidentally succeeds:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

container.Register<NullLogger>(Lifestyle.Scoped);
container.RegisterCollection<ILogger>(new[] { typeof(NullLogger) });
container.Register<Consumer>(Lifestyle.Singleton);

container.Verify(); // added

container.GetInstance<Consumer>(); // now succeeds
```

What happens is the following:

- When running inside `Verify()`, Simple Injector implicitly creates a `Scope` to allow `Scoped` instances to be resolved.
- Since `Verify()` created the `Singleton` `Consumer`, the collection is iterated inside a `Scope`. This means creation of `Consumer` succeeds.
- Since `Consumer` is a `Singleton`, it will be cached and the following `GetInstance<Consumer>` call simply returns that cached instance.

This might actually be quite tricky to fix, because `Verify()` requires a `Scope` to function. This would mean that `Scope` should be suppressed during construction of `Singleton` instances. This however might be a breaking change.

**Comment by lobster2012-user** [comment]
Replace 
`public Consumer(IEnumerable<ILogger> loggers)`
on
`public Consumer(ILogger[] loggers)`

And you get the expected error without `verify`

**Comment by dotnetjunkie** [comment]
Here are some other interesting use cases:

``` C#
public class SomeDecorator : IService
{
    IService decoratee;
    public SomeDecorator(Func<IService> decorateeFactory)
    {
        this.decoratee = decorateeFactory();
    }
}
```

And:

``` c#
public class SomeComponent : IComponent
{
    IService service;
    public SomeComponent(Func<IService> serviceFactory)
    {
        this.service = serviceFactory();
    }
}
```

In both cases, factories are injected, but invoked right inside the constructor. This is generally a bad practice and will can cause captive dependencies.

**Comment by dotnetjunkie** [comment]
Branch [feature-554](https://github.com/simpleinjector/SimpleInjector/compare/feature-554) contains this change.

**Comment by dotnetjunkie** [comment]
I added documenation about this feature [here](https://simpleinjector.readthedocs.io/en/latest/LifestyleMismatches.html#iterating-injected-collections-during-construction-can-lead-to-warnings). Feedback on the documentation is very welcome.
