### ISSUE TITLE
Add .NET Standard 2.0 version

### ISSUE THREAD

**Issue by borrrden** [simpleinjector/SimpleInjector#559]
I am filing this as a response to [an issue filed on my own repo](https://github.com/couchbase/couchbase-lite-net/issues/1027) but the 1.x .NET Standard versions have a dependency on NETStandard.Library which seems to balloon the dependency list for people using packages.config (see the scary looking screenshot in the issue I linked).  .NET Standard 2.0 should require only `System.ComponentModel` as a dependency.  If you like I can try building and packaging it up and submit a PR for the nuspec.

**Comment by dotnetjunkie** [comment]
Feel free to create a pull request for this. You can take the [v4.4.x](https://github.com/simpleinjector/SimpleInjector/tree/v4.4.x) branch.

**Comment by dotnetjunkie** [comment]
A new version of Simple Injector (v4.4) has been released that contains this feature/fix.
