### ISSUE TITLE
How to call a other form from a first form

### ISSUE THREAD

**Issue by danilobicas** [simpleinjector/SimpleInjector#561]
In my Program.cs I have

`Application.Run(container.GetInstance<Form1>());`

And when show the form I click in menu item with this code:

`var frm = container.GetInstance<Form2>();`

in form2 I have the constructor

```
public Form2(IInterface1 interface1)
{
        _interface1 = interface1;
}
I'm using windows forms and my registers is correct.
```

Occur a error on getinstance tha sey don't have a instance of object.

Five days sufferer!!!! tk's

**Comment by dotnetjunkie** [comment]
Hi,

To be able to help you out, please post a minimal reproducible example that includes all exception details, such as exception messages and stack traces of the exception and all inner exceptions.
