### ISSUE TITLE
Support for .NET Standard 2.0

### ISSUE THREAD

**Issue by mariotoffia** [simpleinjector/SimpleInjector#565]
Can you provide with dependencies and target netstandard2.0 in addition to the other targets?

Cheers,
 Mario

**Comment by dotnetjunkie** [comment]
Can you describe why you need a .NET Standard 2.0 version of Simple Injector, considering the fact that you can reference the .NET Standard 1.3 version from .NET Standard 2.0 projects.

**Comment by mariotoffia** [comment]
I have the problem that I get a warning each time I build for projects where netstandard 1.3 ```System.Security.Principal.Windows``` conflicts with later version.

1.3 do reference_4.0.0.0_ whereas later version uses _4.1.0.0_ as I can see from the logs. 

This results in a warnings:

_"2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Security.Principal.Windows" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed."_

**Comment by dotnetjunkie** [comment]
I'm unable to reproduce this issue. I created a .NET Standard 2.0 class library and referenced both Simple Injector and System.Security.Principal.Windows, but the code keeps compiling.

Can you post a minimal example that reproduces the issue?

**Comment by dotnetjunkie** [comment]
Closed due to inactivity.
