### ISSUE TITLE
SimpleInjector.DiagnosticVerificationException

### ISSUE THREAD

**Issue by Robert969696** [simpleinjector/SimpleInjector#570]
First of all sorry for so much code but i belive it will be easier to find an issue here. I am using SimpleInjector and getting error inside Program class on container.Verify(); line, it says as below. I was trying to investigate throug docs website but still cannot figoure out how to fix that.

> SimpleInjector.DiagnosticVerificationException: 'The configuration is invalid. The following diagnostic warnings were reported: -[Disposable Transient Component] FrmLogin is registered as transient, but implements IDisposable. See the Error property for detailed information about the warnings. Please see https://simpleinjector.org/diagnostics how to fix problems and how to suppress individual warnings.'

**Full code:**

``` c#
static class Program
{
	private static Container container;

	[STAThread]
	private static void Main()
	{
		Application.EnableVisualStyles();
		Application.SetCompatibleTextRenderingDefault(false);
		Bootstrap();
		Application.Run(container.GetInstance<FrmLogin>());
	}

	private static void Bootstrap()
	{
		container = new Container();   
		container.Register<IRepositoryDal<User>, UserRepositoryDal>();
		container.Register<IRepositoryDal<Order>, OrderRepositoryDal>();
		container.Register<IDbManager>(() => new DbManager("sqlserver"));
		container.Register<IGenericBal<User>, UserBal>();
		container.Register<IGenericBal<Order>, OrderBal>();
		container.Register<FrmLogin>();
		container.Verify();
	}
}

public partial class FrmLogin : Form
{
	private readonly IGenericBal<User> _userBal;
	private readonly IGenericBal<Order> _orderBal;

	public FrmLogin(IGenericBal<User> userBal, IGenericBal<Order> orderBal)
	{
		InitializeComponent();

		_userBal = userBal;
		_orderBal = orderBal;
	}
}

public interface IGenericBal<out T> where T : IEntity
{
	IEnumerable<T> SearchByName(string name);
}

public class UserBal : IGenericBal<User>
{
	private readonly IRepositoryDal<User> _userRepositoryDal;

	public UserBal(IRepositoryDal<User> userRepositoryDal)
	{
		_userRepositoryDal = userRepositoryDal;
	}
}

public interface IRepositoryDal<T> where T : IEntity
{
	IEnumerable<T> SearchByName(string username);
	T SearchById(string id);
	void Update(T entity);
	void Remove(T entity);
	void Add(T entity);
}

public class UserRepositoryDal : IRepositoryDal<User>
{
	private readonly IDbManager _dbManager;

	public UserRepositoryDal(IDbManager dbManager)
	{
		//read from either singleton or configuration file !!
		_dbManager = dbManager;
	}
}
```

 **I tried to also make like this:**
```

var container = new Container();
// Select the scoped lifestyle that is appropriate for the application
// you are building. For instance:
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

// DisposableService implements IDisposable
container.Register<FrmLogin>(Lifestyle.Scoped);
```

but then i get following error:

> "SimpleInjector.DiagnosticVerificationException:
 'The configuration is invalid. The following diagnostic warnings were 
reported: -[Lifestyle Mismatch] FrmLogin (Async Scoped) depends on 
IGenericBal<User> implemented by UserBal (Transient). -[Lifestyle 
Mismatch] FrmLogin (Async Scoped) depends on IGenericBal<Order> 
implemented by OrderBal (Transient). See the Error property for detailed
 information about the warnings. Please see simpleinjector.org/diagnostics how

**Comment by dotnetjunkie** [comment]
You should suppress the diagnostic warnings for Forms. Most pragmatic solution is to create a helper extension method for the registration of forms:

``` c#

public static void RegisterForm<TForm>(this Container container) where TForm : Form
{
    var r = Lifestyle.Transient.CreateRegistration<TForm>(container);
    r.SuppressDiagnosticWarning(DiagnosticType.DisposableTransientComponent, "Done manually.");
    container.AddRegistration<TForm>(r);
}
```

You can use this method as follows:

``` c#
container.RegisterForm<FrmLogin>();
```

**Comment by Robert969696** [comment]
Thanks. You were right however i wonder why it was not written in simpleinjector docs form default?

Second: Why this below was not enough? According to docs should:
```

var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

// DisposableService implements IDisposable
container.Register<FrmLogin>(Lifestyle.Scoped);
```

**Comment by dotnetjunkie** [comment]
> You were right however i wonder why it was not written in simpleinjector docs form default?

You are right, we should update the documentation.

> Why this below was not enough? According to docs should

That's because scoping in Win Forms is a bit harder, but if it works for you, that's great. When you want to do scoping in Win Forms, you should start to resolve from the `Scope` instance directly. For instance:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = ScopedLifestyle.Flowing;

container.Register<FrmLogin>(Lifestyle.Scoped);

using (var scope = new Scope(container))
{
    scope.GetInstance<FrmLogin>().ShowDialog();
}
```

btw, here's a more elaborate discussion on Win Forms with Simple Injector, and how to create forms: https://stackoverflow.com/questions/38417654/

**Comment by dotnetjunkie** [comment]
The documentation now contains information on [Flowing scopes](https://simpleinjector.org/lifestyles+flowing-scopes).
