### ISSUE TITLE
RegisterSingleton with implementation already registered fails

### ISSUE THREAD

**Issue by paulomorgado** [simpleinjector/SimpleInjector#571]
I had this working on previous versions but now (4.3.0) it's not working:

``` c#
void Main()
{
    using (var container = new Container())
    {
        container.RegisterSingleton<Dependency>();
        container.RegisterSingleton<C>(() => new C(0, "", container.GetInstance<Dependency>()));

        // ArgumentException: The constructor of type UserQuery.C contains parameter 'i' of type 
        // Int32 which can not be used for constructor injection because it is a value type.
        // Parameter name: TImplementation
        container.RegisterSingleton<I1, C>();
        container.RegisterSingleton<I2, C>();
    }
}

public class Dependency { }
public interface I1 { }
public interface I2 { }
public class C : I1, I2
{
    public C(int i, string s, Dependency d) { }
}
```

Is there a new way of declaring this kind of dependencies?

**Comment by paulomorgado** [comment]
This is not an option:

```
void Main()
{
    using (var container = new Container())
    {
        container.RegisterSingleton<Dependency>();
        container.RegisterSingleton<C>(() => new C(0, "", container.GetInstance<Dependency>()));
        container.RegisterSingleton<I1>(() => container.GetInstance<C>());
        container.RegisterSingleton<I2>(() => container.GetInstance<C>());
        container.Verify();
    }
}

public class Dependency { }
public interface I1 { }
public interface I2 { }
public class C : I1, I2, IDisposable
{
    private bool isDisposed;
    
    public C(int i, string s, Dependency d) { }

    public void Dispose()
    {
        if (isDisposed) throw new InvalidOperationException();
        isDisposed = true;
    }
}
```

I have third party dependencies that do not allow multiple invocations to `IDisposable.Dispose()`.

**Comment by dotnetjunkie** [comment]
> I had this working on previous versions but now (4.3.0) it's not working:

If this has worked in the past, it was most likely a bug that I fixed. But none of the v4.x versions actually allows the previously code to run, so it must at least be a v3.x release that contained that particular behavior.

> I have third party dependencies that do not allow multiple invocations to IDisposable.Dispose().

That's scary shi... stuff. This basically means that they **are breaking the `IDisposable` contract**, which clearly states that the `Dispose` method should be idempotent. If you can, file a bug!

> Is there a new way of declaring this kind of dependencies?

The way to do this is by creating a `Registration` instance, as shown below:

``` c#
container.RegisterSingleton<Dependency>();

var creg = Lifestyle.Singleton.CreateRegistration(
    () => new C(0, "", container.GetInstance<Dependency>()), 
    container);

container.AddRegistration<I1>(creg);
container.AddRegistration<I2>(creg);
```

Note that this is functionality not 'new'; it has probably been available since v2.0.

Ideally, however, you would want to extract the two primitive dependencies into their own Parameter Object. This would allow you to simplify the registration:

``` c#
container.RegisterSingleton<Dependency>();
container.RegisterInstance(new CConfig(0, ""));
container.RegisterSingleton<I1, C>();
container.RegisterSingleton<I2, C>();

// ctor: C(CConfig config, Dependency dependency)
```

Since you're dealing with a third-party API, you might not be able to change that code. What you can do, however, is derive from `C` (assuming it is not sealed):

``` c#
public sealed class MyC : C
{
    public MyC(CConfig config, Dependency d) : base(config.A, config.B, d) { }
}

container.RegisterSingleton<Dependency>();
container.RegisterInstance(new CConfig(0, ""));
container.RegisterSingleton<I1, MyC>();
container.RegisterSingleton<I2, MyC>();
```

I hope this helps

**Comment by paulomorgado** [comment]
Thanks, @dotnetjunkie.

For the time being, I think the first option is the best suited.

On a side note, would you be able to point me to where the `IDisposable` contract clearly states that the `Dispose` method should be idempotent? I'd like to open a few bugs in the .NET Framework.

**Comment by dotnetjunkie** [comment]
> would you be able to point me to where the IDisposable contract clearly states that the Dispose method should be idempotent?

Yes, sure. [The documentation](https://msdn.microsoft.com/en-us/library/system.idisposable.dispose(v=vs.110).aspx) on the `Dispose` method is pretty clear:

> If an object's Dispose method is called more than once, the object must ignore all calls after the first one. The object must not throw an exception if its Dispose method is called multiple times. Instance methods other than Dispose can throw an ObjectDisposedException when resources are already disposed.

So if you see different behavior, that is a clear violation of the contract.

You can also point at section 9.4 (page 326) of the Framework Design Guidelines, second edition by Krzysztof Cwalina and Brad Abrams. This book contains the guidelines that Microsoft uses to build its frameworks.

**Comment by paulomorgado** [comment]
[here](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern)'s the online version of that chapter.

It is only explicitly mentioned that:

> DO allow the Dispose(bool) method to be called more than once. The method might choose to do nothing after the first call.

But the given implementation for `Dispose()` shows that if `Dispose(bool)` is idempotent, so is `Dispose()`.

Thanks, @dotnetjunkie.
