### ISSUE TITLE
Help with registering nested open generic type / partially closed

### ISSUE THREAD

**Issue by Eldar1205** [simpleinjector/SimpleInjector#573]
Hi,

I like to have the following pseudo registration:

`container.RegisterSingleton(typeof(IContextProvider<IOperationContext<>>), typeof(OperationContextProvider<>)`

The `OperationContextProvider<TData>` class is generic with same generic argument as `IOperationContext` mentioned above, and it implements `IContextProvider<IOperationContext<TData>>`, how can I teach the container to add that registration? Right now I'm having an issue creating an instance of `Type` that represents the open generic type `IContextProvider<IOperationContext<>>`, and I'm not sure it's even possible. Note that I don't want to modify the design, I need to keep the generic `IContextProvider` as well as the generic `IOperationContext` in order for overall design to work as expected.

**Comment by dotnetjunkie** [comment]
You came to the right place, since this is absolutely something that is supported in Simple Injector, compared to most other DI Containers.

Since `IContextProvider<IOperationContext<>>` is not something that can be expressed natively in C#, you only have one option: you build up this partially-closed generic type using reflection, as shown below:

``` c#
container.RegisterSingleton(
    typeof(IContextProvider<>).MakeGenericType(IOperationContext<>), 
    typeof(OperationContextProvider<>));
```

**Comment by Eldar1205** [comment]
Thanks Steven, that was my first attempt and it failed with exception that
the service type is not open generic, I guessed it is because
IContextProvider has a type argument and it is no longer open, and it is
not enough that the type argumeny itself is open generic

**Comment by Eldar1205** [comment]
I see. I'll try that and close issue if works. Thanks!

**Comment by dotnetjunkie** [comment]
For completeness, can you post the definition of the `OperationContextProvider<T>` class? i.e. show how it implements the `IContextProvider<T>` interface.

**Comment by Eldar1205** [comment]
It worked, verified with UT, thanks! :)
