### ISSUE TITLE
Accessing container from another assembly

### ISSUE THREAD

**Issue by hellboy81** [simpleinjector/SimpleInjector#577]
I have following use case:

- The main project uses IoC container SimpleInjector
- The main project references "utility" project which still does not use IoC container
- The main project uses class in "utility" project indirectly by 3rd party framework I don't control:
I cannot instantiate class manually to pass my own parameters 

How can I do that (pass  my own parameters)  using IoC container or maybe another more suitable solution?

**Comment by dotnetjunkie** [comment]
Please post a concrete example that demonstrates your problem.

**Comment by dotnetjunkie** [comment]
Closed due to inactivity.
