### ISSUE TITLE
Slow to run

### ISSUE THREAD

**Issue by andcurrie** [simpleinjector/SimpleInjector#579]
Hi - I am relatively new to DI though I have used NInject before.

I see simple injector is advertised as quick and, well, simple (clue in the name!) this seems to be what I read elsewhere.  I am, however, really struggling with speed.  I have multiple projects in my solution (5) and interfaces and concrete classes spread throughout the projects.  My main project being Web MVC.   I have registered only 5 interfaces with one concrete class each using the simple register method.  The verify call takes, seemingly, forever.

I also knocked up an integration test and used the DI container just really for some metrics.  I find that verify method takes just as long (Visual Studio often thrown a COM timeout exception) and the GetInstance method also takes just as long.  Is there something I am doing wrong or are my expectations too high?  Anyone else struggled with speed?

**Comment by dotnetjunkie** [comment]
The `Verify()` method creates an instance for all registrations. If you have tens of thousands of registrations, this could take some time.

In your case, however, you just registered a few, and in that case, `Verify()` itself will be very fast, almost instantly.

When `Verify()` is really slow, this is typically an indication that you are doing I/O in the constructors of your components. You should prevent doing this, as explained [here](http://blog.ploeh.dk/2011/03/03/InjectionConstructorsshouldbesimple/) by Mark Seemann.

**Comment by andcurrie** [comment]
Thanks for the super fast response.

I am just reworking my code, and indeed followed that advice.  With a fresh day, I realise I missed a rogue constructor which initialises the DB.  Thanks for the pointer - I found it immediately with your tip!  Much, much faster now.
