### ISSUE TITLE
Singleton types created twice due to how Verify() works

### ISSUE THREAD

**Issue by Eldar1205** [simpleinjector/SimpleInjector#580]
Hi,

We have an issue with singleton registrations. The implementations' constructors are called twice during service lifetime because Verify() invokes all constructors and doesn't keep singletons in memory, so next time they are resolved a new singleton instance is created. In an ideal world constructors shouldn't have side effects so we shouldn't care that they are called twice, but we have legacy code with a Unity container that we want to transition to SimpleInjector and we want to call Verify() in order to validate registrations with fail-fast behavior (legacy code with Unity has semantics similar to "Verify" that aren't compatible with SimpleInjector since it resolves instances as they are registered).

Assuming we can't change legacy code and constructors will have side effects, how would you recommend that we benefit from Verify(), if it's possible at all, in a simplest way?

Notes: 

1. We've considered implementing proxies for every legacy singleton that don't have constructor side effects and register them to SimpleInjector, but that is a lot of work and we might miss legacy singletons with side effects unless we implement proxies for all hundreds of them.

2. We don't object coping the code In Verify() along with any internal dependencies it has and change few things to meet the desired semantics, this is viable depending on the amount of work required.

**Comment by dotnetjunkie** [comment]
Please post a minimal example that demonstrates the problem.

**Comment by dotnetjunkie** [comment]
Simple Injector gives a strong guarantee about the creation of Singletons. It is designed to never create more than one instance of a Singleton registration during the lifetime of a `Container` instance. This guarantee spans the use of `Verify` as well. My expectation therefore is that the classes in question are *not* instantiated by Simple Injector, but by some other part of your code base.

Please post a minimal example that demonstrates the problem so I can determine whether this is a problem in Simple Injector or in your code base.

**Comment by Eldar1205** [comment]
I think I may have used an earlier version of SimpleInjector, I had a Console Application that registered a singleton which prints something in constructor and it was printed twice when Verify() was called following GetInstance<> call, however right now with SimpleInjector 4.3.0 that's indeed not the case, sorry for wasting your time.

**Comment by dotnetjunkie** [comment]
In that case, I am very curious which version of Simple Injector you used. I can't find a bug fix in the change log of both v4 and v3 that might describe the fix of such a bug. That means that you used a v1 or v2 version.

**Comment by dotnetjunkie** [comment]
Hi @alexandrevk,

I tried to reproduce your issue using the following code:

``` c#
using System;
using System.Linq;
using System.Reflection;
using SimpleInjector;
using SimpleInjector.Advanced;

public interface IMessageHandler { }
public class MessageHandler : IMessageHandler
{
    public MessageHandler() => Console.WriteLine("Constructor called.");
}

static class Program
{
    private static Container _container;

    static void Main(string[] args)
    {
        _container = new Container();
        _container.Options.ConstructorResolutionBehavior = new DefaultConstructorBehavior();
        _container.RegisterSingleton<IMessageHandler, MessageHandler>();

        _container.Verify();

        _container.GetInstance<IMessageHandler>();

        Console.WriteLine("Done");

        Console.ReadLine();
    }

    private class DefaultConstructorBehavior : IConstructorResolutionBehavior
    {
        public ConstructorInfo GetConstructor(Type implementationType) =>
            implementationType.GetConstructors().Single();
    }
}
```

However, this code produces the following output:

```
Constructor called.
Done
```

In other words, I'm unable to reproduce your issue. Also, please note my earlier comment from above:

> Simple Injector gives a strong guarantee about the creation of Singletons. It is designed to never create more than one instance of a Singleton registration during the lifetime of a Container instance. This guarantee spans the use of Verify as well. My expectation therefore is that the classes in question are not instantiated by Simple Injector, but by some other part of your code base.

The example you posted does not demonstrate the problem. Please post a minimal example that demonstrates the problem so I can determine whether this is a problem in Simple Injector or in your code base.

**Comment by dotnetjunkie** [comment]
There could be a few possible causes I can think of:

* The call to `Verify` and `GetInstance` are done on *different* `Container` instances. `Singleton` registrations are only guaranteed to be unique *per container instance*. Each `Container` gets its own cache.
* You accidentally create multiple `Registration` instances for this `FixMessageHandler` class. In most cases, Simple Injector will deduplicate `Registration` instances created by a `Lifestyle` to prevent [Torn Lifestyles](https://simpleinjector.org/diatl), but doesn't happen when, for instance, you register delegates, as Simple Injector can't deduplicate them.

If you can't reproduce this using a console application, you should strip out as much as registrations from your application until the problem disappears. This allows you to provode us with a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that reproduces the problem.

Good luck.
