### ISSUE TITLE
Registering dependencies from plugins

### ISSUE THREAD

**Issue by hvidgaard** [simpleinjector/SimpleInjector#582]
I am creating a plugin based RestApi shell in Asp.Net Core. I've got that working by locating dlls and loading them. This works perfectly, but I would like to register dependencies for each plugin, with possible overlapping types. So in essence a "nested container", and when asp.net core is resolving a controller it should use the appropiate "nested container", and if resolution fails in that, try the parent container. Nested containers is not possible with SI, but I wonder if something else can achieve the same. I've been browsing the documentation and code, but I'm coming to the conclusion that it's probably beyond what I can figure out, if it is possible.

The gist of the idea of what I want to do in code is

In Startup.cs

``` c#
foreach (var plugin in plugins){
    plugin.RegisterDepencencies(container);
}
```
In each implementation of plugin.
``` c#
RegisterDepencencies(Container cont){
    cont.AddSingleton<MyInterface, MyImpl>(pluginAssemblyName);
    ....
    cont.Register<MyOtherInterface, MyOtherImpl>(pluginAssemblyName);
}
```

So whenever `SimpleInjectorControllerActivator` tries to resolve a controller instance, it will get the `AssemblyName` the controller lives in, and use that to resolve dependencies that is "tagged" with that particular `AssemblyName`. This of course also applies to all dependencies with the controller as the root.

I was briefly considering using `RegisterConditional` but that would not work with dependencies of dependencies as far as I understand, as it's not possible to traverse the object graph with the `PredicateContext`.

Do you have any pointers of where to focus my attention?

**Comment by dotnetjunkie** [comment]
Could you elaborate on your question, because after reading it, it's still unclear what it exactly is you are trying to achieve. For instance, you are talking about "possible overlapping types". What does that mean? Why wouldn't it work to have everything registered in one single container instance?

**Comment by hvidgaard** [comment]
Basically I load plugins the following way

```
services.Configure<RazorViewEngineOptions>(options =>
{
    foreach (var pluginAssembly in pluginAssemblies)
    {
        
        var pluginRootPath =
            Path.Combine(
                pluginsRootPath,
                pluginAssembly.GetName().Name
            );

        options
            .FileProviders
            .Add(new PhysicalFileProvider(Path.GetDirectoryName(pluginAssembly.Location)));
    }
});
```

And for each plugin I want to search for a class implementing a `IPluginRegistration` interface, which could be

```
IPluginRegistration.RegisterDepencencies(Container cont){
    cont.AddSingleton<MyInterface, MyImpl>();
    ....
    cont.Register<MyOtherInterface, MyOtherImpl>();
}
```

Other developers will then simply make a dll that will be dropped in the appropiate folder and the Controller is loaded and ready to serve requests.

The problem is if plugin1 register `AddSingleton<IRepository, DBRepository>` and plugin2 register `AddSingleton<IRepository, RestRepository>`. Every controller i plugin2, and all dependencies with one of them as the root, should get the `RestRepository `when requesting `IRepository`

**Comment by hvidgaard** [comment]
I was looking into that, but abandoned it because I would miss the ability to satisfy dependencies from the "main" container if the plugin hasn't have any registration for ILogger for instance. The way forward is probably to document a known few registrations that all containers get, logging for one, and then plugins should decorate them if they need to.

**Comment by dotnetjunkie** [comment]
> I would miss the ability to satisfy dependencies from the "main" container if the plugin hasn't have any registration for ILogger for instance

The start-up project would create the `Container` instances and would register its 'core' dependencies (such as `ILogger`) first into every plugin container, and register all plugin dependencies after that. That would give each plugin component access to the core `ILogger` dependency as well.

Only downside of having non-shared root containers is that it becomes a bit more difficult if you have registrations that should be truly app-domain scoped singletons—each container manages its own singletons. For the few registrations where this actually matters, you can new them manually and feed them to each container using `RegisterInstance`.

**Comment by hvidgaard** [comment]
I believe separate containers is actually the better solution anyway. Only explicit defined registrations is shared between plugins, which I do prefer. For anyone else seeing this thread, this is the simple version of the solution.

```
public class SimpleInjectorIndependentControllerActivator : IControllerActivator
{
    private readonly IDictionary<string, Container> ContainerDictionary;
    public SimpleInjectorIndependentControllerActivator(IDictionary<string, Container> containerDictionary)
    {
        this.ContainerDictionary = containerDictionary;
    }

    public object Create(ControllerContext context)
    {
        var assemblyName = context.ActionDescriptor.ControllerTypeInfo.AssemblyQualifiedName;

        var container =
            this.ContainerDictionary.ContainsKey(assemblyName) ?
            this.ContainerDictionary[assemblyName] :
            this.ContainerDictionary["default"];

        return container.GetInstance(context.ActionDescriptor.ControllerTypeInfo.AsType());
    }

    public void Release(ControllerContext context, object controller) { }
}
```

And Startup.cs has the following

```
public void ConfigureServices(IServiceCollection services)
{
    IList<Assembly> pluginAssemblies;

    services.AddMvc()
            .AddPlugins(out pluginAssemblies)
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

    var containerDictionary = new Dictionary<string, Container>();

    foreach (var assembly in pluginAssemblies)
    {
        var cont = CreatePluginContainer();

        var pluginType = assembly.GetTypes().Single(t => typeof(IPlugin).IsAssignableFrom(t));
        ((IPlugin)Activator.CreateInstance(pluginType)).RegisterDependencies(cont);
        containerDictionary.Add(assembly.FullName, cont);
    }

    IntegrateSimpleInjector(services, containerDictionary);
}

private Container CreatePluginContainer()
{
    var cont = new Container();
    cont.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
    RegisterCrossPluginDepedencies(cont);

    return container;
}

private void RegisterCrossPluginDepedencies(Container cont)
{

}

private void IntegrateSimpleInjector(IServiceCollection services, IDictionary<string, Container> containerDictionary)
{
    container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

    services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

    containerDictionary.Add("default", container);

    services.AddSingleton<IControllerActivator>(
        new SimpleInjectorIndependentControllerActivator(containerDictionary));

    services.EnableSimpleInjectorCrossWiring(container);
    services.UseSimpleInjectorAspNetRequestScoping(container);
}
```

I am unsure if I need to do something with crosswiring or requestscoping in the plugin containers?

**Comment by hvidgaard** [comment]
@dotnetjunkie Isn't there going to be scoping issues when using this solution? the `RequestScopingStartupFilter` takes care of this for "normal" use of the SimpleInjector in asp.net core, but since I'm creating separate containers for each controller, the individual plugin containers knows nothing about the scope of a request, since that is defined on the default container.

**Comment by dotnetjunkie** [comment]
When using multiple container instances, you can't use the `UseSimpleInjectorAspNetRequestScoping` extension method as a way to wrap requests in a scope, since it expects a single container instance to be used (each container gets its own scope). So you will, instead, have to implement scoping differently, because you have to get access to the container instance to be able to start a scope.

**Comment by hvidgaard** [comment]
I think we're unlikely to go above 20-30 plugins/containers.

If the requests start to saturate a server, it's the cue that some parts of the api should live in it's own site anyway, rather than in a general plugin structure designed to require minimal development and asp.net core knowledge.

**Comment by dotnetjunkie** [comment]
I've run the creation of `AsyncScopedLifestlye` scops through Benchmark.NET, which resulted in the following summary:

![Async scopes benchmark](https://user-images.githubusercontent.com/1506621/42560423-e8ab8346-84f6-11e8-9be5-93080d188d70.png)

I used the following code to benchmark:

``` c#
public class ScopeBenchmark
{
    Container[] containers;

    public ScopeBenchmark()
    {
        containers = Enumerable.Range(0, 100).Select(_ => new Container()).ToArray();
    }

    [Benchmark]
    public void OneContainer()
    {
        using (AsyncScopedLifestyle.BeginScope(containers[0])) { }
    }

    [Benchmark]
    public void HundredContainers()
    {
        Scope[] scopes = new Scope[100];
        for (int i = 0; i < 100; i++) scopes[i] = AsyncScopedLifestyle.BeginScope(containers[i]);
        for (int i = 99; i <= 0; i--) scopes[i].Dispose();
    }
}
```

What this shows is that the creation and disposal of an unused `AsyncScopedLifestyle` `Scope` takes around 2 ns. In other words, the overhead of creating and disposing scopes is really tiny.

**Comment by hvidgaard** [comment]
So, having 10.000 plugins will add less than 0.1ms to every request. That's a performance trade off that's worth taking.

**Comment by hvidgaard** [comment]
I've updated the previous code with the request scoping. Thanks for your help, was incredibly helpful to get some feedback from you when diving into something new involving SimpleInjector :)

**Comment by dotnetjunkie** [comment]
You're most welcome.

**Comment by hvidgaard** [comment]
I was finalizing an implementation of this, but realized that there is still scoping issues if any dependency has a scoped lifestyle. The following snippet illustrates the issue with two interleaving requests and scoped registrations.

```
public interface IScopeTest { }

public class ScopeTestObject : IScopeTest
{
    private readonly Guid guid = Guid.NewGuid();

    public override string ToString()
    {
        return this.guid.ToString();
    }
}

public class Program
{
    static void Main(string[] args)
    {
        new Program().TestScoping();
    }

    public void TestScoping()
    {

        var cont1 = new Container();
        cont1.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
        cont1.Register<IScopeTest, ScopeTestObject>(Lifestyle.Scoped);

        var scope1 = AsyncScopedLifestyle.BeginScope(cont1);
        Console.WriteLine($"ScopeObject1 {cont1.GetInstance<IScopeTest>()}");


        var scope2 = AsyncScopedLifestyle.BeginScope(cont1);
        Console.WriteLine($"ScopeObject2 {cont1.GetInstance<IScopeTest>()}");

        scope2.Dispose();
        Console.WriteLine($"ScopeObject3 {cont1.GetInstance<IScopeTest>()}");
    }
}
```

However, what I did was to postpone the creation of the scope until I had knowledge of what container was needed - that happens in the `ControllerActivator`. So, to make sure I have a scope for every request. I've modified the `IStartupFilter` to set a value in the context to null, and when activating a controller I check for that value. Should it be null I start the scope, otherwise I can assume that it has already been created. This works because the container is not used at any point before the controller is activated (as far as I can tell).

This is the implementation we're currently trialing for use in production:

StartupFilter
```
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using SimpleInjector;

internal sealed class EndContextScopeStartupFilter : IStartupFilter
{
    public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
    {
        return builder =>
        {
            ConfigureRequestScoping(builder);

            next(builder);
        };
    }

    private void ConfigureRequestScoping(IApplicationBuilder builder)
    {
        builder.Use(async (context, next) =>
        {
            context.Items["requestScope"] = null;

            await next();

            if (context.Items["requestScope"] is Scope contScope)
            {
                contScope.Dispose();
            }
        });
    }
}
```

ControllerActivator
```
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Controllers;
using SimpleInjector;
using SimpleInjector.Lifestyles;
using System;
using System.Collections.Generic;

public class SimpleInjectorIndependentControllerActivator : IControllerActivator
{
    private readonly IDictionary<string, Container> ContainerDictionary;
    public SimpleInjectorIndependentControllerActivator(IDictionary<string, Container> containerDictionary)
    {
        if (!containerDictionary.ContainsKey("default"))
        {
            throw new ArgumentException("No default container, it is required. Did you forget to add it witht the key 'default'?", nameof(containerDictionary));
        }

        this.ContainerDictionary = containerDictionary;
    }

    public object Create(ControllerContext context)
    {
        var assemblyName = context.ActionDescriptor.ControllerTypeInfo.AssemblyQualifiedName;

        var container =
            this.ContainerDictionary.ContainsKey(assemblyName) ?
            this.ContainerDictionary[assemblyName] :
            this.ContainerDictionary["default"];


        if (context.HttpContext.Items["requestScope"] == null)
        {
            context.HttpContext.Items["requestScope"] = AsyncScopedLifestyle.BeginScope(container);
        }

        return container.GetInstance(context.ActionDescriptor.ControllerTypeInfo.AsType());
    }

    public void Release(ControllerContext context, object controller) { }
}
```

Startup.cs
```
private Container defaultContainer => containerDictionary["default"];
private IDictionary<string, Container> containerDictionary = new Dictionary<string, Container>();

public Startup(IConfiguration configuration)
{
    containerDictionary.Add("default", new Container());
    defaultContainer.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
    RegisterCrossPluginDepedencies(defaultContainer);
    this.context = context;
}

public void ConfigureServices(IServiceCollection services)
{

    services.AddMvc()
            .AddPlugins(out IList<Assembly> pluginAssemblies, this.context)
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

    foreach (var assembly in pluginAssemblies)
    {
        try
        {
            var cont = CreatePluginContainer();

            var pluginType = assembly.GetTypes().SingleOrDefault(t => typeof(IPlugin).IsAssignableFrom(t));
            if (pluginType != null)
            {
                try
                {
                    ((IPlugin)Activator.CreateInstance(pluginType)).RegisterDependencies(cont);
                }
                catch
                {
                    // Log
                }
            }
            containerDictionary.Add(assembly.FullName, cont);
        }
        catch
        {
            // Log
        }
    }

    IntegrateSimpleInjector(services, containerDictionary);
}


private Container CreatePluginContainer()
{
    var cont = new Container();
    cont.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

    RegisterCrossPluginDepedencies(cont);

    return cont;
}

private void RegisterCrossPluginDepedencies(Container cont)
{
}

private void IntegrateSimpleInjector(IServiceCollection services, IDictionary<string, Container> containerDictionary)
{
    services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

    services.AddSingleton<IControllerActivator>(
        new SimpleInjectorIndependentControllerActivator(containerDictionary));

    foreach (var cont in containerDictionary.Select(kvp => kvp.Value))
    {
        services.EnableSimpleInjectorCrossWiring(cont);
    }

    services.AddSingleton<IStartupFilter>(new EndContextScopeStartupFilter());
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    InitializeContainers(app);

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    foreach (var cont in containerDictionary.Values)
    {
        cont.Verify();
    }

    app.UseMvc();
}

protected virtual void InitializeContainers(IApplicationBuilder app)
{
    foreach (var cont in containerDictionary.Select(kvp => kvp.Value)){
        cont.AutoCrossWireAspNetComponents(app);
    }
}
```

IPlugin for completeness
```
using SimpleInjector;

public interface IPlugin
{
    void RegisterDependencies(Container container);
}
```
