### ISSUE TITLE
Entity Framework And Net Core

### ISSUE THREAD

**Issue by patsadow2** [simpleinjector/SimpleInjector#586]
Is there any way to inject `DbContext` in .NET Core 2.0 ? 

``` C#
services.AddDbContext<AppContext>(options => options.UseSqlServer(
    Configuration.GetConnectionString("Database")));

//Fail
container.AutoCrossWireAspNetComponents(app);

container.Register<IAppApiContext>(()=>new AppApiContext(), Lifestyle.Scoped);

container.Verify();
```

**Comment by dotnetjunkie** [comment]
How does the call to `AutoCrossWireAspNetComponents` fail? Please post all the relevant exception details, such as message and stack trace. Please include the details of _all_ inner exceptions as well.

**Comment by patsadow2** [comment]
When use:

      services.AddDbContext<ApiContext>(options => options.UseSqlServer(Configuration.GetConnectionString("ApiDatabase")));
            
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
                .AddJsonOptions(options => {
                    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                });

            container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            services.EnableSimpleInjectorCrossWiring(container);
            services.UseSimpleInjectorAspNetRequestScoping(container);

and 

            container.AutoCrossWireAspNetComponents(app);

            container.Register<IApiContext>(()=>new ApiContext(
                new DbContextOptionsBuilder<AppApiContext>().UseSqlServer(Configuration.GetConnectionString("ApiDatabase")).Options
                ), Lifestyle.Scoped);

            container.Verify();

not sure how to set options ;/

Unable to resolve service for type 'Api.DatabaseContext.IAppContext' while attempting to activate 'Api.Controllers.UserController'.

If i use https://blog.matthieurobineau.com/binding-dbcontext-in-simple-injector/ and 

container.Register<IApiContext>(() => app.GetRequiredRequestService<ApiContext>(), Lifestyle.Scoped);

Run time error " 'Unable to request service 'ApiContext from ASP.NET Core request services.Please make sure this method is called within the context of an active HTTP request.'"

**Comment by dotnetjunkie** [comment]
Make sure you follow the [integration guide](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html) closely. You seem to forget calling `RegisterMvcControllers`, which causes Simple Injector to cross-wire the controller from ASP.NET instead of resolving it from itself.
