### ISSUE TITLE
Question: AsyncScopedLifestyle and constructor injected objects

### ISSUE THREAD

**Issue by deastr** [simpleinjector/SimpleInjector#590]
The documentation dictates that getting items using `GetInstance `should be encapsulated with `AsyncScopedLifestyle.BeginScope(container)`. What about objects that are injected as contructor parameters? Do we need to do anything special while using these instances?

**Comment by dotnetjunkie** [comment]
You don't need to do anything special. The whole graph of objects will be resolved within the declared scope. Any time a scope is absent, Simple Injector will throw an exception explaining the problem. It will never fail silently.
