### ISSUE TITLE
Proposal for AsyncWebRequestLifestyle.

### ISSUE THREAD

**Issue by malylemire1** [simpleinjector/SimpleInjector#593]
Hi,

I have made and AsyncWebRequestLifestyle to resolve the problem with sub thread in a request. 
This is not the same as having an hybrid lifestyle has it keep the current scope in sub thread of a request.
Here is the proposal

``` c#
public sealed class AsyncWebRequestLifestyle : AsyncScopedLifestyle
{
    private static readonly object ScopeKey = new object();

    static public bool InRequest => HttpContext.Current != null || asyncScope != null;

    static private Scope currentScope =>
        HttpContext.Current != null ? (Scope)HttpContext.Current.Items[ScopeKey] : asyncScope;

    static private Scope asyncScope;

    public AsyncWebRequestLifestyle() : base() { }

    internal static void CleanUpWebRequest(HttpContext context)
    {
        var scope = currentScope;

        if (scope != null)
        {
            scope.Dispose();
            asyncScope = null;
        }
    }

    protected override Scope GetCurrentScopeCore(Container container)
        => GetOrCreateScope(container);

    protected override Func<Scope> CreateCurrentScopeProvider(Container container)
    {
        return () => GetOrCreateScope(container);
    }

    private static Scope GetOrCreateScope(Container container)
    {
        Scope scope = currentScope;

        if (scope == null)
        {
            scope = BeginScope(container);

            HttpContext context = HttpContext.Current;
            if (context != null)
            {
                context.Items[ScopeKey] = scope;
            }

            asyncScope = scope;
        }

        return scope;
    }
}
```

You can use it in a an hybrid lifestyle with execution scope.

``` c#
GetExecutionScopeWebRequest = (container) => Lifestyle.CreateHybrid(
    lifestyleSelector: () => AsyncWebRequestLifestyle.InRequest
        && executionScope.GetCurrentScope(container) == null,
    trueLifestyle: webRequestScope,
    falseLifestyle: executionScope);
```

**Comment by dotnetjunkie** [comment]
Can you elaborate whats "the problem with sub thread in a request". What is the actual problem you are trying to solve?

**Comment by malylemire1** [comment]
Hi,

Let me elaborate. I have some Task.Run inside a request from a class blirabry with ConfigureAwait(false) that won't use current synchronization context and will have no HttpContext.Current. 
Even with solution like this one : https://blogs.msdn.microsoft.com/friis/2017/12/05/asp-net-httpcontext-in-asyncawait-patterns-using-the-task-parallel-library-part-3/

```
await Task.Factory.StartNew(myBackgroundDelegate(),
CancellationToken.None,
TaskCreationOptions.RunContinuationsAsynchronously,
TaskScheduler.FromCurrentSynchronizationContext());
```
This will flow the HttpContext to the started task, but if any parent await is called with ConfigureAwait(false), the synchronization context will not be resumed and the HttpContext will be lost.

I need nested tasks to use the same scope to prevent instance duplicates.

Thanks

**Comment by malylemire1** [comment]
Hi,

Here is a version without static reference to Scope. 
The HttpContext is never null in CleanUpWebRequest. The ConfigureAwait(false) should never be used in controller Task call. But this implementation prevent problems with class library and ConfigureAwait(false). 

```
public sealed class AsyncWebRequestLifestyle : AsyncScopedLifestyle
{
    private static readonly object ScopeKey = new object();

    public AsyncWebRequestLifestyle() : base()
    {
    }

    public static bool InRequest(Container container, AsyncWebRequestLifestyle lifeStyle)
    {
        return HttpContext.Current != null || lifeStyle.GetCurrentScope(container) != null;
    }

    internal static void CleanUpWebRequest(HttpContext context)
    {
        Scope scope = (Scope)HttpContext.Current.Items[ScopeKey];

        if (scope != null)
        {
            scope.Dispose();
        }
    }

    protected override Scope GetCurrentScopeCore(Container container) => GetOrCreateScope(container);

    protected override Func<Scope> CreateCurrentScopeProvider(Container container)
    {
        return () => GetOrCreateScope(container);
    }

    private Scope GetOrCreateScope(Container container)
    {
        Scope scope = GetCurrentAsyncScope(container);

        if (scope == null)
        {
            scope = BeginScope(container);

            HttpContext context = HttpContext.Current;
            if (context != null)
            {
                context.Items[ScopeKey] = scope;
            }
        }

        return scope;
    }

    private Scope GetCurrentAsyncScope(Container container)
    {
        return HttpContext.Current != null ? (Scope)HttpContext.Current.Items[ScopeKey] : base.GetCurrentScopeCore(container);
    }
}
```

**Comment by dotnetjunkie** [comment]
If I undertand correctly, you wish to span parallel background operations from within a web request, and have them run in their own isolated scope.

The adviced way of doing this is by using a hybrid lifestyle that falls back on the `WebRequestLifestyle` in case there is no active `AsyncScopedLifestyle`, while wrapping those background operations in an `AsyncScopedLifestyle.

You can define your hybrid lifestyle as follows:

``` c#
Lifestyle.CreateHybrid(
    defaultLifestyle: new AsyncScopedLifestyle(),
    fallbackLifestyle: new WebRequestLifestyle());
```

When spanning a background operation, you must make sure that that resolve of the required service and its execution is done within a `Scope`. Wrapping such operation can be done as follows:

``` c#
using (AsyncScopedLifestyle.BeginScope(container))
{
    var service = container.GetInstance<ISomeService>();
    service.DoSomething(...);
}
```

**Comment by dotnetjunkie** [comment]
In that case it would be better to simply go full-async. In other words, ditch the `WebRequestLifestyle` completely and just use `AsyncScopedLifestyle` and wrap a request in a `Scope` using `AsyncScopedLifestyle.BeginScope`.

**Comment by malylemire1** [comment]
Hi, 

I agree. I just wanted to avoid doing this in every method of every controllers.

Thanks

**Comment by malylemire1** [comment]
I'll try to implement this instead of using HttpContext.

Thanks
