### ISSUE TITLE
Internal classes in seperate assemblies

### ISSUE THREAD

**Issue by riwos** [simpleinjector/SimpleInjector#595]
I give up.. I do not have any idea how to fix it.

Let's assume we have three assemblies:

Assembly - Internal

```
 // ITestInternal.cs
public interface ITestInternal
 {
        string TestMethod();
 }


// TestInternal.cs
internal class TestInternal : ITestInternal
 {
     public TestInternal()
      {

       }

       public string TestMethod()
       {
            return "new text";
        }
 }
```
Assembly - Public

```
 // IPublicTest.cs
public interface IPublicTest
{
        void testPublicMethod();
 }

// PublicClass.cs
public class IPublicClass : IPublicTest
{
        private readonly ITestInternal _internalTestService = null;

        public IPublicClass(ITestInternal internalTestService)
        {
            _internalTestService = internalTestService;
        }

        public void testPublicMethod()
        {
            var text = _internalTestService.TestMethod();
        } 
}
```

Assembly - MainProgram (Referenced: Internal, Public)

// registration
```
public class Startup
{
     private static Container container = new Container();

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            // SimpleInjector DI

             // doesn't work
             container.Collection.Register<ITestInternal>(typeof(ITestInternal).Assembly);

            container.Register<IPublicTest, IPublicClass>(Lifestyle.Transient);
            
            // container.Verify(); => ERROR 1
// When I've commented Verify() method and I've used something like this,
 // it works but it is not what I would like have..
          var instance = container.GetAllInstances<ITestInternal>();
           var test = instance.ElementAt(0);
        }
}
```

I'm using in ASP.NET Core on Controller but I've got this error:

ERROR 1:
"ActivationException: color:ActivationException: The constructor of type IPublicClass contains the parameter with name 'internalTestService' and type ITestInternal that is not registered. Please ensure ITestInternal is registered, or change the constructor of IPublicClass. There is, however, a registration for IEnumerable<ITestInternal>; Did you mean to depend on IEnumerable<ITestInternal>? If you meant to depend on ITestInternal, you should use one of the Register overloads instead of using Container.Collection.Register"

I have two questions:

- how use SimpleInjector to inject internal classes
- how to resolve aftert that..

Any advice I will be appreciated :)

**Comment by dotnetjunkie** [comment]
Fromthe top of my head:

``` c#
var type = container.GetTypesToRegister<ITestInternal>(typeof(ITestInternal).Assembly)
    .Single();

container.Register(typeof(ITestInternal), type);
```

And you can use reflection manually as well:

``` c#
var implementation = typeof(ITestInternal).Assembly.GetTypes()
    .Where(t => typeof(ITestInternal).IsAssignableFrom(t))
    .Where(t => t.IsClass)
    .Single();

container.Register(typeof(ITestInternal), implementation);
```
 
The simplest solution, however, is to make the class public. When building Line of Business applications, there is typically little reason to make classes internal, sinve this is exactly what you are achieving by programming to abstractions. You can even enforce this by moving the implementation to a different assembly.

**Comment by riwos** [comment]
Thanks @dotnetjunkie I am very appreciated ;) This explanation is enough for me and I have direction now. Mayn thanks again ;)
