### ISSUE TITLE
Prevent container injection

### ISSUE THREAD

**Issue by omares** [simpleinjector/SimpleInjector#60]
This is more a question than an issue:

In our project we have a view model first navigation (instead of navigating pages, you navigate to view models and the "framework" takes care of the page creation). So View Models are dependent on each other: ViewModelA -> ViewModelB -> ViewModelC

Newsting the view models via constructor injection is not practicable, as that would result in unnecessary instantiation of objects. We decided on creating the view models just in time, before navigating to it. As view models can have dependencies we want to inject these using the DI, so we have to pass the DI inside our view models but that somehow feels like the wrong solution because of breaking the dependency chain.

What would be the suggested way to solve this issue? Or is it the right way to inject the di container?

P.S.: Is there a SimpleInjector related chat? :)

**Comment by dotnetjunkie** [comment]
My advice here would be the same as the one I gave in question #58, and that is to separate runtime data from application components. A class is either runtime data (a newable, a message) that is passed through the object graph, or it is an application component (injectable) where runtime data is passed through.

There are typically two models for view models. You have the view model classes as they are often used in MVC models, where the view model is just a data package, built by the controller to be processed by the view. The other model is what we know from MVVM where the view model is actually an application service, with a role that is similar to the controller of MVC. In this case the view model shouldn't contain any runtime data at all, and should rather be stateless. So in this case the view model will have dependencies that are injected through its constructor, but runtime data only passes through method calls.

I don't know what type of application you are building, but I would suggest to pick either one of the models. Either your view models are data only, or they are behavior only and stateless. Don't drink and drive ;-)

**Comment by TheBigRic** [comment]
Following @dotnetjunkie advice I'm assuming you will only 'drink', meaning you're using MVVM and your View Models are acting as application services, this is how you could handle this: By using a message based architecture like CommandHandler as described [here](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91).

By defining an interface, which each ViewModel will implement (all with a different T!):
```c#
public interface IViewModel<T>
{
    void InitViewModel(T data);
} 
```

You can create a `ViewModelProcessor` which can retrieve a build up viewmodel from the Simple Injector container, bind this to your view (manually or by using a MVVM framework like Caliburn Micro). An implementation would look like:

``` c#
public class ViewModelProcessor
{
    private readonly Container container;

    public ViewModelProcessor(Container container)
    {
          this.container = container;
    }

    public void ShowViewModel<T>(T data)
    {
        var viewModelType = typeof(IViewModel<>).MakeGenericType(data.GetType());
        var viewModel = (IViewModel<T>)this.container.GetInstance(viewModelType );

        // bind viewModel to view e.g. retrieve view from container based on convention
        // or use a MVVM tool to do this
        
        viewModel.InitViewModel(data);
        this.someKindOfWindowManager.ShowWindow(viewModel, view);
    }
}
```

**Comment by omares** [comment]
Oh i think my point was misunderstood. My concern was about premature object creation and not the state of the objects. Our ViewModels are stateless and used in a MVVM application, so injecting them is not an issue here.

Lets take following dependency three:

    class ViewModelStart { ViewModelStart(ViewModelPageOne one, ViewModelPageAwesome awesome) { /* */ } }

    Class ViewModelPageOne { ViewModelB(ViewModelPageTwo two) { /* */ } }
    Class ViewModelPageAwesome { ViewModelB(ViewModelEvenMoreAwesome more) { /* */ } }

    Class ViewModelEvenMoreAwesome { ViewModelB(ViewModelTwo two) { /* */ } }

    Class ViewModelPageTwo { /* */ }


Now when calling `Container.GetInstance<ViewModelStart>()` the container would create an instance of all models. The question was/is how to prevent the premature creation of all the objects. Its not obvious if the user will ever navigate to `ViewModelEvenMoreAwesome` and also not necessary to create the view model that early to preserve memory (mobile app)

After discussion with others we opted for the lazy and/or factory pattern to solve the problem.

**Comment by dotnetjunkie** [comment]
> How to prevent the premature creation of all the objects.

But why is this a problem?

**Comment by omares** [comment]
1. On a mobile platform i do want to preserve memory as good as possible. And i would say that applies to other platforms too.
2. Why should i create objects i am not certain if i will ever use them.

Tbh i do not understand the counter question. Why should i create objects at a point i dont expect them. Even if i had the memory and resources i probably would not do it because every object i do not have to create is an object i dont need to care about.

**Comment by dotnetjunkie** [comment]
The UI frameworks on those mobile platforms usually generate way more memory than those few extra bytes of objects from your object graph. Please note that an object in your object graph is somewhere between 12 and 28 bytes (12 bytes if it contains 0 dependencies and 28 bytes if it contains 5 dependencies).

And in case you are working in an application with really tight memory constraints, you should rather use singleton object graphs anyway. This way you just instantiate the object graph once, and never have this extra pressure of extra GC collects. It should usually be fairly easy to do so, since we already established that your components should be stateless anyway.

The use of factories increases the complexity of your application, because you introduce new abstractions and postponing creation of the object graph makes it harder to verify the application's DI configuration. In most cases, factories don't bring much benefits.
