### ISSUE TITLE
Using DI with code generation in game

### ISSUE THREAD

**Issue by GeorgeR** [simpleinjector/SimpleInjector#600]
I'm writing a code generation tool, and dependency injection is getting a bit out of hand and I could use some advice! I have several issues:

You can see my current implementation here:
https://github.com/GeorgeR/GameArchitect

1) Each target language has a specific implementation of a service, for example C++ has a CXXMetadataProvider, etc. 
These all take generic services like an ITypeTransformer and INameTransformer, in a mixed environment with multiple target languages, how do I ensure CXXMetadataProvider gets a CXXNameTransformer? They inherit from a base class so giving it an explicit CXXNameTransformer isn't possible.

2) I have several implementations, such as metadata types and templates that require a list of services as well as an explicit argument, for example CXXTypeInfo requires not just a bunch of services, but an object of type Type to wrap. A CXXHeaderTemplate has the same issue (see UnrealTemplateFactory.cs). Additionally, CXXTypeInfo created CXXPropertyInfo, etc, but it needs DI to do this - do I pass it factories or do I inject the container itself?

I'm currently using Microsofts abstraction but i'll be returning to Simple Injector because I recall it being far more capable. I appreciate any input.

Note that currently, generic services are configured for a single target language but I want to change this as I say above.

**Comment by dotnetjunkie** [comment]
I must admit that I don't fully understand the problem you are facing, and I, unfortunately, don't have the time to go through your code base to understand what you are doing and how it could be improved.

You might want to try giving more concrete code examples that demonstrate the problems your are facing.

**Comment by GeorgeR** [comment]
Thanks for the response. Take for example this:
https://github.com/GeorgeR/GameArchitect/blob/master/src/GameArchitect.Tasks.CodeGeneration.Unreal/Templates/UnrealTypeTemplate.cs

I'm installing a bunch of dependencies, and ITypeInfo which needs to be specified every time I new it up. How do I handle such a situation?

**Comment by dotnetjunkie** [comment]
I think the main problem here us your base class. You should prefer composition over inheritance instead. The base class is strongly coupled to the derived class, and with it all its behavior and dependencies.

Composition, however, provides us with a much more losely coupled model, since it allows, for instance, cross-cutting concern, like logging, to be wrapped around implementation using decorators.
