### ISSUE TITLE
Inheritance interfaces

### ISSUE THREAD

**Issue by riwos** [simpleinjector/SimpleInjector#604]
Does it possible to make something like this or I am going to wrong way.

DLL ONE

``` c#
public interface ITest<TEntity> where TEntity : class
{
}

public class TestImplementation<TEntity> : ITest<TEntity> 
    where TEntity : class
{
}
```

DLL TWO

``` c#
public interface IAnimal<TEntity> where TEntity : class
{
}

public interface ITestZZZ<TEntity> : ITest<TEntity> 
    where TEntity : class
{
}

public abstract class Animal<TEntity> : IAnimal<TEntity> 
    where TEntity : class
{
    private readonly  ITest<TEntity> _test = null;
    
    public Animal(ITest<TEntity> test)
    {
        _test = test;
    }
}

public interface IDog<TEntity> : IAnimal<TEntity> 
    where TEntity : class
{
}

public class Dog : Animal<upAnimal>, IDog<upAnimal>
{
    public Dog(ITestZZZ<upAnimal> dog111) : base(dog111)
    {    
    }
}

 public class upAnimal
    {
    }
```

DI

``` c#
container.Register<ITest<upAnimal>, TestImplementation<upAnimal>>();
container.Register<IDog<upAnimal>, Dog>();
```

but I've got:

> The constructor of type Dog contains the parameter with name 'dog111' and type ITestZZZ&lt;TEntity> that is not registered. Please ensure ITestZZZ&lt;TEntity> is registered, or change the constructor of Dog.

Any sugesstions?

**Comment by dotnetjunkie** [comment]
Your code example doesn't make much sense. The following code should *not be able to compile*:

``` c#
container.Register<IDog<TEntity>, Dog<TEntity>>();
```

If it *does* compile, it means that you declared `TEntity` as a class in your application. Go look for that implementation *and remove it* from your application.

Instead, your registrations should be as follows:

``` c#
container.Register(typeof(ITest<>), typeof(TestImplementation<>));
container.Register(typeof(IDog<>), typeof(Dog<>));
```

Note that the only way in C# to express open-generic types, is by using the `typeof` keyword.

**Comment by riwos** [comment]
I apologize, that was my mistke. I've changed the code but even that I am getting this error:

"
SimpleInjector.ActivationException: 'The constructor of type Dog contains the parameter with name 'dog111' and type ITestZZZ<upAnimal> that is not registered. Please ensure ITestZZZ<upAnimal> is registered, or change the constructor of Dog.'
"

**Comment by dotnetjunkie** [comment]
The exception message does not match your initial code example. Please post a minimal, complete, reproducable example. Preferably something that I can copy-paste as-is to a console application and can run without having to make adjustments.

**Comment by riwos** [comment]
I hope so this zip should give you everything to fix my silly issue. Thanks a lot :)

[AnimalSimpleInjectorGit.zip](https://github.com/simpleinjector/SimpleInjector/files/2270195/AnimalSimpleInjectorGit.zip)

**Comment by dotnetjunkie** [comment]
So to summarize, this is your code:

``` c#
public interface ITest<TEntity> where TEntity : class { }

public class TestImplementation<TEntity> : ITest<TEntity> where TEntity : class { }

public interface IAnimal<TEntity> where TEntity : class { }
public interface IDog<TEntity> : IAnimal<TEntity> where TEntity : class { }    
public interface ITestZZZ<TEntity> : ITest<TEntity> where TEntity : class { }

public abstract class Animal<TEntity> : IAnimal<TEntity> where TEntity : class
{
    private readonly ITest<TEntity> _test;
    public Animal(ITest<TEntity> test) => _test = test;
}

public class upAnimal { }

public class Dog : Animal<upAnimal>, IDog<upAnimal>
{
    public Dog(ITestZZZ<upAnimal> dog111) : base(dog111) { }
}

public class TestDog
{
    private readonly IDog<upAnimal> _dog;
    public TestDog(IDog<upAnimal> dog) => _dog = dog;
}    
```

And this is your Composition Root:

``` c#
static void Main(string[] args)
{
    Container container = new Container();

    //   container.Register<ITest<upAnimal>, TestImplementation<upAnimal>>();
    //container.Register<IDog<upAnimal>, Dog>();

    container.Register(typeof(ITest<>), typeof(TestImplementation<>));
    container.Register(typeof(IDog<>), typeof(Dog));

    var instance = container.GetInstance<IDog<upAnimal>>();

    TestDog t = new TestDog(instance);

    Console.ReadLine();
}
```

**Comment by riwos** [comment]
I agree with you :)  I was thinking what I can do when you have inheritance between interfaces. I thought that maybe exist  any way to support this but it looks this is wrong way.

I am assuming does not exist solution and it is not correct way of implementation..

Anyway thank you for your time and effort :)
