### ISSUE TITLE
Register and resolving classes with primitive parameters

### ISSUE THREAD

**Issue by vkg-mca** [simpleinjector/SimpleInjector#605]
I am using Simple Injector version 4.3.0. and have a problem where I want to register a class with single constructor having three string parameters, but parameter values are not known until runtime. So my problem is

**Step#1**

``` c#
private Container container = new Container();
container.RegisterSingleton<IEventHubConfiguration, EventHubConfiguration>();
```

Class has three parameters

**Step#2**

``` c#
public class EventHubConfiguration : IEventHubConfiguration
{
    public EventHubConfiguration(string key, string value, string account)
    {
        //Some code here
    }
}
```

**PROBBLEM=>**

 In **Step#1**, I cannot register the class as it is asking for all three parameters to be passed. I can NOT pass the parameter values because these are NOT known yet. I can pass hardcoded values during registration and update them back when get the actual values but not sure if this is right solution.

**Comment by dotnetjunkie** [comment]
You'll find the source of your trouble and the solution in the article [Dependency-injection Code Smell: Injecting runtime data into components](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=99).
