### ISSUE TITLE
Weird package dependency in Xamarin.iOS

### ISSUE THREAD

**Issue by jzeferino** [simpleinjector/SimpleInjector#611]
I get some weird (don't make sense to me) referenced packages when adding SimpleInjector into a Xamarin.iOS project.

Mainly:

`Microsoft.NETCore.Platforms`
`Microsoft.Win32.Primitives`

![screen shot 2018-09-10 at 11 19 22](https://user-images.githubusercontent.com/10722952/45291924-69320480-b4eb-11e8-8e27-0434e9cacda2.png)

**Comment by jzeferino** [comment]
Its weird because its a iOS application. Will it have any problem?

**Comment by dotnetjunkie** [comment]
I dunno. I bet that assembly is empty under iOS.

**Comment by jzeferino** [comment]
I can confirm that the assembly is empty under iOS. Its kinda messed to see all of this packages as dependencies since they are empty for iOS.
