### ISSUE TITLE
Injecting a value into GetInstance

### ISSUE THREAD

**Issue by petterek** [simpleinjector/SimpleInjector#612]
When developing typicaly framework stuff, I often need to inject values from the "current context". 
I my selfdeveloped DI container I have the posibility to inject types into the GetInstance method. 

# Lik this
```csharp
Public class SomeType : ISomeType {
   Public SomeType(ContextValue cv) { ...  } 
}

var contextValue = new ContextValue();
var instance = container.GetInstace<ISomeType>(contextValue);
```
The ContextValue is never registered in the container. 

How should this be solved in SI? 
I do not want to take any dependencies on WebContext etc.

**Comment by dotnetjunkie** [comment]
I'm sorry, but I'm afraid you supplied too little information to answer your question. Please explain:

* what this `ContexValue` represents. Is it a component that consists of behavior, some object that contains configuration values, or does it contain runtime data, that might be different per request?
* Is there just one `ContextValue` class and inject a different instance per requested type, or are there many different types that you wish to inject based on some type?
* How do you map such `ContextValue` to an abstraction? What rules do you follow, or is this 'registration' done on a per-type basis?

**Comment by petterek** [comment]
It contains runtime data that is different pr request, I have solved it when using the IServiceProvide/IServiceCollection from MS using a factory, but it is kind of cumbersome..

**Comment by dotnetjunkie** [comment]
In that case the solution is simple: don't do this, but change your design instead. You should refrain from injecting runtime data into a type's constructor, as explained [here](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=99).

**Comment by petterek** [comment]
I see your point in your blog, very good +1 
In my case it is more of an "ambient context value" created by the framework. E.g the path of the webrequest (in a non IIS, dotNet application).  
Or from your example, given you need some factory to create your command object,you would probably need to pass in the "body" of the webrequest to be able to deserialize it to the correct instance

**Comment by petterek** [comment]
Thank you very much for your answer, and yes I totally agree with you.. 
I think the Scoped variant is the best one in my case :)
