### ISSUE TITLE
Clarification on resolving a collection with scoped Dependencies

### ISSUE THREAD

**Issue by alexbestul** [simpleinjector/SimpleInjector#614]
I'm experimenting with Simple Injector in Azure Functions. I've followed the advice in https://github.com/simpleinjector/SimpleInjector/issues/536 to set up my composition root. Things work fine for common injection scenarios, but I'm having trouble with the specific combination of collection injection and an async-scoped dependency.

In my sample code (below), I have a service that depends on a collection of `IEchoer`, which is configured to contain a single instance of `Echoer`. `Echoer` in turn depends on a scoped `StringBuilder`. If I inject the collection as `IEchoer[]`, everything works as expected. If I inject the collection as `IEnumerable<IEchoer>`, the following error is thrown from `HttpRequestHandler.Handle()`

> SimpleInjectorTestFunction. SimpleInjector: The StringBuilder is registered as 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope.

In addition to injecting an array, the error can also be avoided by injecting as `IEnumerable<IEchoer>` and then materializing the collection (for example, by calling `ToList()`) within the constructor.

Given all that, I can tell that the instances in the `IEnumerable<IEchoer>` aren't resolved until the collection is enumerated. By that time, we're no longer in the async scope (which closed immediately after resolving the root object), and unable to resolve the scoped dependency.

Can you tell me what's actually wrong here? Is this delayed resolution an oversight on Simple Injector's part? Am I using the async scope incorrectly (I know I don't actually have any `async`/`await` code in my example, but is that a problem)? Do I just need to hold the scope open until execution completes?

PS: My goal is to have a per-function-invocation scope. If you have any advice on how to implement that, I'd love to hear it.

---

Here's the full code I'm using. I've omitted constructors for brevity, but this is otherwise functional code.

```c#
public static class SimpleInjectorTestFunction
{
    [FunctionName("SimpleInjectorTestFunction")]
    public static IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get")]HttpRequest req)
        => DIConfig.Container.GetScopedInstance<HttpRequestHandler>().Handle();
}
```
```c#
public static class DIConfig
{
    public static readonly Container Container;

    static DIConfig()
    {
        Container = new Container();
        Container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
        
        Container.Collection.Register<IEchoer>(new Type[] { typeof(Echoer) });
        Container.Register(() => new StringBuilder(), Lifestyle.Scoped);

        Container.Verify();
    }

    public static T GetScopedInstance<T>(this Container container) where T : class
    {
        using (AsyncScopedLifestyle.BeginScope(container))
            return container.GetInstance<T>();
    }
}
```

```c#
class HttpRequestHandler
{
    readonly IEnumerable<IEchoer> echoers;
    readonly StringBuilder stringBuilder;
    
    public IActionResult Handle()
    {
        foreach (var echoer in echoers)
            echoer.Write();

        return new OkObjectResult(stringBuilder.ToString());
    }
}
```

```c#
interface IEchoer
{
    void Write();
}
```

```c#
class Echoer : IEchoer
{
    readonly StringBuilder stringBuilder;
    
    public void Write() => stringBuilder.AppendLine($"Echoer says hello");
}
```

**Comment by dotnetjunkie** [comment]
> Is this delayed resolution an oversight on Simple Injector's part? 

Collections in Simple Injector are _streams_. You can read more about this in [the documentation](https://simpleinjector.org/collections):

> **Simple Injector will always inject a reference to the same stream (the `IEnumerable<T>` or `ICollection<T>` itself is a singleton) and each time you iterate the `IEnumerable<T>`, for each individual component, the container is asked to resolve the instance based on the lifestyle of that component.**
> 
> **Warning: In contrast to the collection abstractions, an array is registered as transient.**

> Here's the full code I'm using
> ``` c#
> public static T GetScopedInstance<T>(this Container container) where T : class
> {
>     using (AsyncScopedLifestyle.BeginScope(container))
>         return container.GetInstance<T>();
> }
> ```
>
> Do I just need to hold the scope open until execution completes?

You should always keep the scope open until _after_ execution. This will hold for any DI Container you will use. The reason this worked with arrays is accidental, but will change once you start using disposable classes. A disposable scoped instance will be disposed by the container when its scope is disposed, which in your case happens immediately after the call to `GetInstance<T>`, before you had a change of actually using that resolved object.

So instead, you should do something as follows:

``` c#
public static TResult Handle<T, TResult>(this Container container, Func<T, TResult> handler) 
    where T : class
{
    using (AsyncScopedLifestyle.BeginScope(container))
        return handler(container.GetInstance<T>());
}

public static class SimpleInjectorTestFunction
{
    [FunctionName("SimpleInjectorTestFunction")]
    public static IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get")]HttpRequest req)
        => DIConfig.Container.Handle<HttpRequestHandler>(h => h.Handle());
}
```

**Comment by alexbestul** [comment]
D'oh. I had read the documentation on collections-as-streams, but the consequences didn't click until you re-explained just now. The consequences for disposables make  sense, too.

Thanks for your help!

**Comment by dotnetjunkie** [comment]
I created a new [Azure Functions Integration](https://simpleinjector.org/azurefunctions) page. This demonstrates how to integrate Simple Injector with  Azure Functions v3.
