### ISSUE TITLE
Resolve service depending on a created scope

### ISSUE THREAD

**Issue by Dundercover** [simpleinjector/SimpleInjector#617]
I have IoC set up in a ASP.NET MVC web app using SimpleInjector. I'm also using another tool called [hangfire](https://www.hangfire.io) inside the web app which is using the same container but separate async scoped lifestyle when executing (apart from the usual web request lifestyle). 

I want some logic (which is inside a service of a service etc) to differ depending on if it is being run in a web request or inside a hangfire worker. The tricky part is that the logic is also dependent on some information from hangfire (when in the async scope) that is only available during scope creation. I'm using [this piece of code](https://github.com/devmondo/HangFire.SimpleInjector/blob/master/src/HangFire.SimpleInjector/SimpleInjectorJobActivator.cs) to begin an async scope when activating a hangfire job.

Is there any way I can solve this? 

I appreciate any help I can get!

**Comment by dotnetjunkie** [comment]
Csn you please share some information (preferably code) that demonstrates the logic you wish to run and how it depends on Hangfire?

**Comment by Dundercover** [comment]
I ended up creating another scoped service which i populate with the necessary info right after the async scope begun. Sry for taking up your time!

**Comment by Dundercover** [comment]
@TheBigRic Wow, thank you for the feedback! My team has discussed using a separate container for hangfire before but decided against it, I'll see if we'll change our mind now that we have some more concrete data to go by :)

**Comment by dotnetjunkie** [comment]
Hi @Dundercover. I think @TheBigRic's answer is absolutely awesome. You should definitely give it a spin.

Can you explain why your team thought that having a second container instance is a bad idea?
