### ISSUE TITLE
Close IDbConnection after AsyncScopedLifestyle by disposal

### ISSUE THREAD

**Issue by leandrocurioso** [simpleinjector/SimpleInjector#620]
I have the following registrations:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
container.Register<ISqlConnectionFactory, MySqlConnectionFactory>(Lifestyle.Singleton);
container.Register<IDbConnection>(() =>
    container.GetInstance<ISqlConnectionFactory>().Fabricate(), Lifestyle.Scoped);
```
Then I start a scope with: 

``` c#
using (AsyncScopedLifestyle.BeginScope(container))
{
   var myRepository = container.GetInstance<IMyRepository>();
   var myOtherRepository = container.GetInstance<IMyOtherRepository>();
   var result1 =  await myRepository.SomeMethod();          
   var result12=  await myOtherRepository.SomeMethod();        
 }
```

Both IMyRepository and IMyOtherRepository will get the same IDbConnection and that is fine!

But after the using scope how I call a custom dispose code to close the IDbConnection?

**Comment by dotnetjunkie** [comment]
Simple Injector will automatically dispose any registered component that is registered with the `Scoped` lifestyle in case the resolved type implements `IDisposable`. This means that the cached instance, returned from `Fabricate()`, will be automatically disposed by Simple Injector.

**Comment by leandrocurioso** [comment]
> Simple Injector will automatically dispose any registered component that is registered with the `Scoped` lifestyle in case the resolved type implements `IDisposable`. This means that the cached instance, returned from `Fabricate()`, will be automatically disposed by Simple Injector.

Okay but since it is an IDbConnection how do I know that the code will call:

`
 connection.Close();
`

Because I need to ensure the connection is closed. Any idea?

**Comment by dotnetjunkie** [comment]
You don't need to explicitly close a connection if you call dispose.

**Comment by leandrocurioso** [comment]
Oh I see. I did not know that  IDispose from IDbConnection would automatically close the conneciton.

I thought I would need to close by myself.

**Comment by leandrocurioso** [comment]
> You don't need to explicitly close a connection if you call dispose.

Oh I see. I did not know that IDispose from IDbConnection would automatically close the conneciton.

I thought I would need to close by myself.

**Comment by dotnetjunkie** [comment]
You're welcome :)
