### ISSUE TITLE
How to inject instances in Controller Action

### ISSUE THREAD

**Issue by Ahmed-Raouf** [simpleinjector/SimpleInjector#625]
Hello,

I'm using simple injector in ASP .Net Core 2 web application. When I was using structure map, I was injecting the instances in the controller action using FromServices attribute. But now when I used Simple Injection, I can't do this.
Please advice.

Thanks

**Comment by dotnetjunkie** [comment]
See: https://github.com/simpleinjector/SimpleInjector/issues/623

**Comment by dotnetjunkie** [comment]
See: [using [FromServices] in ASP.NET Core controllers](https://simpleinjector.org/aspnetcore#using-fromservices-in-asp-net-core-controllers)
