### ISSUE TITLE
Is variance supported when registering collection with registrations?

### ISSUE THREAD

**Issue by voroninp** [simpleinjector/SimpleInjector#626]
I am trying to register multiple implementations of a contravarinat interface `IBeforeCommitDomainEventHandler<in TEvent>`, but get exception:

> Test method threw exception: 
> System.ArgumentException: The supplied type IBeforeCommitDomainEventHandler&lt;DomainEvent&gt; does not implement IBeforeCommitDomainEventHandler<BeforeCommitEventsDispatcherTests.ChildDomainEvent>.
> Parameter name: registrations
>     at SimpleInjector.Requires.ServiceIsAssignableFromImplementations(Type serviceType, IEnumerable&lt;Type&gt; typesToRegister, String paramName, Boolean typeCanBeServiceType)
>    at SimpleInjector.ContainerCollectionRegistrator.Register(Type serviceType, IEnumerable&lt;Registration&gt; registrations)

However, `ChildDomainEvent` is actually a subclass of `DomainEvent`.

Here's the code which fails:

```CSharp
var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

var handler1Events = new List<DomainEvent>();
var handler2Events = new List<DomainEvent>();

var handler1Mock = new Mock<IBeforeCommitDomainEventHandler<DomainEvent>>();
handler1Mock.Setup(h => h.HandleAsync(It.IsAny<object>()))
    .Callback((object e) => handler1Events.Add((DomainEvent)e))
    .Returns(Task.CompletedTask);

var handler2Mock = new Mock<IBeforeCommitDomainEventHandler<ChildDomainEvent>>();
handler1Mock.Setup(h => h.HandleAsync(It.IsAny<object>()))
    .Callback((object e) => handler2Events.Add((DomainEvent)e))
    .Returns(Task.CompletedTask);

var reg1 = Lifestyle.Scoped.CreateRegistration(() => handler1Mock.Object, container);
var reg2 = Lifestyle.Scoped.CreateRegistration(() => handler2Mock.Object, container);

container.Collection.Register<IBeforeCommitDomainEventHandler<ChildDomainEvent>>(new[]{reg1, reg2});
            
```

**Comment by dotnetjunkie** [comment]
Variant typing _certainly_ is supported. However, you unfortunately ran into [a bug](https://github.com/simpleinjector/SimpleInjector/issues/627).

This bug only manifests itself in case you make the registration using `Registration` types, where the _implementation_ is unknown to Simple Injector.

You make the following call:

``` c#
Lifestyle.Scoped.CreateRegistration<IBeforeCommitDomainEventHandler<DomainEvent>>(() => ...,
    container)
```

Note how I removed type inference so you can now see what call is made.

Because of this, the `Registration.ImplementationType` property will become `typeof(IBeforeCommitDomainEventHandler<DomainEvent>)`.

Unfortunately, due to this bug, Simple Injector does not match the types correctly. I will try to fix this bug in the next minor release v4.4.

However, the registration you are making is quite unusual, which is why nobody h8as noticed this before. Typically, Simple Injector is in control over the registered implementations. For instance, the following code doesn't have this problem:

``` c#
var container = new Container();

container.Collection.Register(typeof(IBeforeCommitDomainEventHandler<>),
    typeof(IBeforeCommitDomainEventHandler<>).Assembly);
```

In this case, a set of implementation types is registered, which allows Simple Injector to correctly do the type check. Not only would this work around your problem, it:

* Leads to simpler code
* allows the `IBeforeCommitDomainEventHandler<DomainEvent>` to be part of an `IEnumerable<IBeforeCommitDomainEventHandler<DomainEvent>>` without having to explicitly register it.

**Comment by voroninp** [comment]
I have a question about your example.

If my service is already registered as implementation of `ISomeService` and it happens to implement multiple `IBeforeCommitDomainEventHandler<>`  (closed) interfaces, how many different instances will SimpleInjector create?

**Comment by dotnetjunkie** [comment]
I don't understand your question. Can you provide a small example? 

The other thing that confuses me is that you use a container in a unit test? What is the function of using the container in a test? What are you testing here?

**Comment by voroninp** [comment]
=D

My intention is to decouple domain events generation and handling.

Just before transaction is commited we need to dispatch all events to the handlers.
I'd like to avoid explicit subscription (and related lifetime headache), therefore I decided to use marker interface `IBeforeCommitDomainEventHandler<>`. I resolve all closed instances with the help of container. (Yes, here it is a Service Locator).

Every time  `Dispatcher.DispatchAsync(TEventBase @event)` is called, container is asked for all instances  of type:

```CSharp
var handlerType = typeof(IBeforeCommitDomainEventHandler<>).MakeGenericType(@event.GetType())
```
I want some domain services to be handlers as well:

```CSharp
public class DeviceService: IDeviceService, IBeforeCommitDomainEventHandler<DeviceRenamed>
{
   ...
}
```
`DeviceService` is explicitly registered as implementation of `IDeviceService`.
Now let's do a batch registration of handlers:

```CSharp
container.Collection.Register(typeof(IBeforeCommitDomainEventHandler<>),
    typeof(IBeforeCommitDomainEventHandler<>).Assembly);
```
I want to know whether container returns same instance of `DeviceService`.

I use container in unit tests of dispatcher.

**Comment by dotnetjunkie** [comment]
> Yes, here it is a Service Locator

As long as you have the logic that calls into the container _inside_ your [Composition Root](https://freecontent.manning.com/dependency-injection-in-net-2nd-edition-understanding-the-composition-root/), rest asure that you are [not](https://blog.ploeh.dk/2011/08/25/ServiceLocatorrolesvs.mechanics/) applying the Service Locator anti-pattern. In other words, place your `Dispatcher` implementation _inside_ the Composition Root and you're fine.

> I want to know whether container returns same instance of DeviceService.

You can very easily test this by calling `Container.Verify()`. In case the collection registration for `DeviceService` gets a different lifestyle (the default is `Transient` for collections), `Verify` will fail.

Here's a simple test to check this:

``` c#
var container = new Container();

container.Register<IDeviceService, DeviceService>(Lifestyle.Singleton);

container.Collection.Register(typeof(IBeforeCommitDomainEventHandler<>), this.GetType().Assembly);

container.Verify();
```

Running this example produces the following exception:

> The configuration is invalid. The following diagnostic warnings were reported:
-[Ambiguous Lifestyles] The registration for IDeviceService (Singleton) maps to the same implementation (DeviceService) as the registration for IBeforeCommitDomainEventHandler&lt;DeviceRenamed> (Transient) does, but the registration maps to a different lifestyle. This will cause each registration to resolve to a different instance.

In other words, no this does not work.

Reason for this is that `Register.Collection` will look up a registration for given concrete type to use its lifestyle, but falls back to the `Options.DefaultLifestyle` (which defaults to `Transient`). The `Register.Collection` call, however, can't find that registration, because there is only a registration for `IDeviceService`—not for `DeviceService`.

So to fix this, you can add the following registration:

``` c#
container.Register<DeviceService>(Lifestyle.Singleton);
```


Here's a simple test to verify this:

``` c#
var container = new Container();

container.Register<DeviceService>(Lifestyle.Singleton);
container.Register<IDeviceService, DeviceService>(Lifestyle.Singleton);

container.Collection.Register(typeof(IBeforeCommitDomainEventHandler<>), this.GetType().Assembly);

container.Verify();
```

Now verify succeeds.

Do do a double check, (in case you don't trust Simple Injector), you can add the following code:

``` c#
Assert.AreSame(
    container.GetInstance<IDeviceService>(),
    container.GetAllInstances<IBeforeCommitDomainEventHandler<DeviceRenamed>>().Single());
```

This Assert statement will succeed.

**Comment by dotnetjunkie** [comment]
> I use container in unit tests of dispatcher.

Ahh, I see. You are testing your dispatcher. A simpler registration would be the following:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();

var handler1Events = new List<DomainEvent>();
var handler2Events = new List<DomainEvent>();

var handler1Mock = new Mock<IBeforeCommitDomainEventHandler<DomainEvent>>();
handler1Mock.Setup(h => h.HandleAsync(It.IsAny<object>()))
    .Callback((object e) => handler1Events.Add((DomainEvent)e))
    .Returns(Task.CompletedTask);

var handler2Mock = new Mock<IBeforeCommitDomainEventHandler<ChildDomainEvent>>();
handler1Mock.Setup(h => h.HandleAsync(It.IsAny<object>()))
    .Callback((object e) => handler2Events.Add((DomainEvent)e))
    .Returns(Task.CompletedTask);

container.Collection.Register<IBeforeCommitDomainEventHandler<ChildDomainEvent>>(
    new[] { handler1Mock.Object, handler2Mock.Object });
```

But do note that I would not advice any of those two options. Problem with both approaches is that you are _not_ testing anything useful at all. Your dispatches will most likely be a few lines of code, and the thing that you want to test is whether the application's _real_ configuration is dispatched correctly by the dispatcher.

So instead, prefer creating an integration test that pulls the dispatcher from the application's real container, and use that to verify whether one or two handlers are handled.

``` c#

```

**Comment by dotnetjunkie** [comment]
> I think this "double" registration may be somewhat confusing

I can agree, so if you choose this approach, it might be good to add a code comment to explain this. Independently of which container you pick, however, you will always have these kinds of 'quirks'. Every design choice that simplifies one thing, will influence another.

The reason that the `Register.Collection` method tries to find an explicit concrete registration is to be able to handle the following use case (from the [docs](https://simpleinjector.readthedocs.io/en/latest/using.html#collections)):

``` c#
container.Register<ILogger, FileLogger>();
container.Register<MailLogger>(Lifestyle.Singleton);

container.Collection.Register<ILogger>(
    typeof(MailLogger), // Becomes singleton because of Register<MailLogger>
    typeof(SqlLogger),
    typeof(ILogger)); // Maps to FileLogger because of Register<ILogger, FileLogger>
```

In this example there are practically two registrations:

* A registration for `ILogger` that will return a `Transient` instance of `FileLogger`
* A registration for an `IEnumerable<ILogger>` (a collection of loggers) that returns a `Singleton` `MailLogger`, a `Transient` `SqlLogger`, and a `Transient` `FileLogger`.

Technically it would be possible for Simple Injector to go even one step further and go look for the matching concrete type, even if it is registered through one of its abstractions, as is the case with your `DeviceService`, that would be tricky without causing a breaking change. And the question becomes: how to handle ambuigity? For instance, what if there is an `Register<IA, DeviceService>(Lifestyle.Scoped)` and `Register<IB, DeviceService>(Lifestyle.Singleton)` registration. I know, this would be really ugly, and verification would throw an exception on that. Verification, however, can be deliberately skipped, or this particular error can be suppressed. Now the question becomes, which lifestyle should `Register.Collection` pick? Whatever comes first? Should it fall back on the default lifestyle? That would violate [this rule](https://simpleinjector.org/principles#never-fail-silently). Should we throw? Better, perhaps. But how to prevent Simple Injector from throwing?

All in all not an easy fix.

But there are alternative registration approaches you might want to consider.

For instance, if all registrations are by default `Scoped`, you can just make `Scoped` the default lifestyle:

``` c#
container.Options.DefaultLifestyle = new AsyncScopedLifestyle();
```

This allows you to simplify things as follows:

``` c#
container.Register<IDeviceService, DeviceService>();
container.Collection.Register(typeof(IBeforeCommitDomainEventHandler<>), assemblies);
```

Or you can keep transient the default but override Simple Injector's [lifestyle selection behavior](https://simpleinjector.org/xtpls):

``` c#
container.Options.LifestyleSelectionBehavior = new MyOwnLifestyleSelectionBehavior(
    type =>type.Name.EndsWith("Service") ? Lifestyle.Scoped : Lifestyle.Transient);
```

With `MyOwnLifestyleSelectionBehavior` being implemented as:

``` c#
public class MyOwnLifestyleSelectionBehavior : ILifestyleSelectionBehavior {
    private readonly Predicate<Type> selector;
    public MyOwnLifestyleSelectionBehavior(Predicate<Type> selector) => this.selector = selector;
    public Lifestyle SelectLifestyle(Type implementationType) => selector(implementationType);
}
```

**Comment by voroninp** [comment]
> Technically it would be possible for Simple Injector to go even one step further and go look for the matching concrete type, even if it is registered through one of its abstractions

But isn't it achieved via explicitly creating registrations of a concrete type and then telling the container that this registration implements `ISomeInterface1`, `ISomeInterface2` and so on?
<br/>
Let me describe my _mental model_ of DI container.

- We have _Interfaces_ (in general sense)/Services and _Implementors_.
- _Implementor_ can implement multiple Interfaces.
- _Interface_/_Service_ can be implemented by multiple _Implementors_.

What are the use cases?

- Define the lifetime for the concrete instance being resolved for particular _Interface_.
- Define how many instances of a concrete _Implementor_ can exist in the context of a given lifestyle.

**Example:**
```CSharp
public class Foo: IBar1, IBar2 {}
```
I want both `IBar1` and `IBar2` be singletons, so every class which depends on `IBar1` always gets the same instance `A`. And class dependent on `IBar2` gets insnatnce `B`.
I still want to be able to decide, where `A` and `B` refer to the same instance of class `Foo` or there are two separate instances.
But what if we add `IBar3` to the equation, should instance of `C` equal to `A` or to `B`?
If we put it to extremes we may need to say:
```CSharp
// no IBar3 here, separate instance is created for IBar3
container.ShareImplementorBetweenServices(typeof(IBar1), typeof(IBar2)); 
```

Then comes the question of sane defaults:

Let's consider APIs:

```CSharp
Container.RegisterImplementorAndAllItsServices<TImplementor>(Lifestyle servicesLifestyle);
Container.RegisterSharedImplementorAndAllItsServices<TImplementor>(Lifestyle servicesLifestyle);
```
In case of _transient_ lifestyle these calls are equivalent, but I would prohibit the second call for _transient_ lifestyle, because semantics of sharing in not applicable.
In case of _scoped_ and _singleton_ lifestyle calls differ: `Shared` means `A` and `B` and `C` are same instances.
<br/>
Couple of words about collections.

For me collections are just the natural result of registering multiple _implementors_ of the _interface_

```CSharp
public class Foo1 : IBar {}
public class Foo2: IBar {}

container.RegisterImplementorAndAllItsServices<Foo1>(Lifestyle.Scoped);
container.RegisterImplementorAndAllItsServices<Foo2>(Lifestyle.Scoped);
container.Verify();
```
`IBar` has multiple registered implementors. So we already have a collection. We would even have a collection, if only `Foo1` was regsitered. This would  be a collection containing one item.

(Moreover, if different lifestiles were used, we'd have `IBar` mapped to `Foo1` for one lifestyle and to 
'Foo2' for the other one.)

```CSharp
public class GiveMeBar {
    public GiveMeBar(IEnumerable<IBar> bars) {}
}
```
If we register `GiveMeBar` as _transient_ it gets all `IBar`s: _transient_, _scoped_, and _singletons_.
If we register it as _scoped_ - only _scoped_ and _singletons_.
 
**The real problem is ambiguity!** 
Wich instance to create when class depends on single instance of `IBar`? 
I think this can be defined in settings: _first wins_, _last wins_, it is an ambiguity and container throws on `Verfiy()` unless ambiguity is resolved explicitly:

```CSharp
container.PreferImplmentor<IBar, Foo1>(LifeStyle.Scoped);
container.PreferImplementor<IBar, Foo3>(LifeStyle.Singleton);
```
I agree, abmiguity resolution is hard.

Final core API:
```CSharp
public class Container
{
    public Implementor Implementor(Type implementorType) {...}
    // Real regsitration of (concrete type, service it implements, lifestyle)
    public RegisterService(Service service) {...}
    public void ShareImplementorInstanceBetweenServices(IEnumerable<ScopedService> services) {...}
    public void ShareImplementorInstanceBetweenServices(IEnumerable<SingletonService> services) {...}
    public void PreferredImplementations(IEnumerable<Service> services) {..}
}

public class Implementor 
{
     public SingletonService AsSingletonService(Type serviceType);
     public TransientService AsTransientService(Type serviceType);
     public ScopedService AsScopedService(Type serviceType);
}

public class Service {}
public class SingletonService : Service {}
public class TransientService : Service {}
public class ScopedService : Service {}
```

Sure, this is a navie view which lacks consideration of thousand outher caseses, but the API  (I hope) does not leave much space for alternative and contradictory interpretations.
I find it confusing that most of DI frameworks have some implicit defaults and behaviours which are not clear from API calls.

**Comment by voroninp** [comment]
This test works fine, but I am confused even more =)

```CSharp
[TestMethod]
public async Task Test()
{
            var container = new Container();

            var handler1Events = new List<DomainEvent>();
            var handler2Events = new List<DomainEvent>();

            var handler1Mock = new Mock<IBeforeCommitDomainEventHandler<DomainEvent>>();
            handler1Mock.Setup(h => h.HandleAsync(It.IsAny<object>()))
                .Callback((object e) => handler1Events.Add((DomainEvent)e))
                .Returns(Task.CompletedTask);

            var handler2Mock = new Mock<IBeforeCommitDomainEventHandler<ChildDomainEvent>>();
            handler2Mock.Setup(h => h.HandleAsync(It.IsAny<object>()))
                .Callback((object e) => handler2Events.Add((DomainEvent)e))
                .Returns(Task.CompletedTask);

            container.Collection.Register(handler1Mock.Object);
            container.Collection.Register(handler2Mock.Object);

            var dispatcher = new BeforeCommitEventsDispatcher(container);

            var event1 = new DomainEvent();
            var event2 = new ChildDomainEvent();

            await dispatcher.DispatchAsync(event1);
            await dispatcher.DispatchAsync(event2);

            handler1Events.Should().BeEquivalentTo(event1, event2);
            handler2Events.Should().BeEquivalentTo(event2);
 }
```
Injector resolves both handlers for `ChildDomainEvent`. ...

**Comment by dotnetjunkie** [comment]
> Injector resolves both handlers for ChildDomainEvent. ...

Please show the code of `BeforeCommitEventsDispatcher`.

**Comment by voroninp** [comment]
```CSharp
public interface IBeforeCommitDomainEventsDispatcher<in TEventBase>
{
    Task DispatchAsync(TEventBase @event);
}

public interface IBeforeCommitDomainEventHandler
{
    Task HandleAsync(object @event);
}

public interface IBeforeCommitDomainEventHandler<in TEvent> : IBeforeCommitDomainEventHandler
{

}

public abstract class BeforeCommitDomainEventsDispatcher<TEventBase> : IBeforeCommitDomainEventsDispatcher<TEventBase>
{
    protected abstract IReadOnlyCollection<IBeforeCommitDomainEventHandler> GetHandlers(TEventBase @event);

    public async Task DispatchAsync(TEventBase @event)
    {
        Guard.ArgumentNotNull(@event, nameof(@event));

        var handlers = GetHandlers(@event) ?? Array.Empty<IBeforeCommitDomainEventHandler>();

        foreach (var handler in handlers.Where(h => !(h is null)))
        {
            var task = handler.HandleAsync(@event) ?? Task.CompletedTask;
            await task;
        }
    }
}

public class BeforeCommitEventsDispatcher: BeforeCommitDomainEventsDispatcher<DomainEvent>
{
    private readonly Container _container;

    public BeforeCommitEventsDispatcher(Container container)
    {
        Guard.ArgumentNotNull(container, nameof(container));

        _container = container;
    }

    private static readonly ConcurrentDictionary<Type, Type> HandlerTypes = new ConcurrentDictionary<Type, Type>();


    protected override IReadOnlyCollection<IBeforeCommitDomainEventHandler> GetHandlers(object @event)
    {
        Guard.ArgumentNotNull(@event, nameof(@event));

        var eventType = @event.GetType();
        var handlersType = HandlerTypes.GetOrAdd(
            eventType,
            t => typeof(IBeforeCommitDomainEventHandler<>).MakeGenericType(t));

        var handlers = _container.GetAllInstances(handlersType).Cast<IBeforeCommitDomainEventHandler>().ToList();

        return handlers;
    }
}

```

**Comment by dotnetjunkie** [comment]
> Injector resolves both handlers for ChildDomainEvent. ...

What is the behavior you are expecting here?

**Comment by voroninp** [comment]
Exactly this behavior.

But I got from your explanation, that I have to explicitly map interfaces and concrete types. In other words I had to explcictly register `handler1Mock.Object` as  `IBeforeComminEventHandler<DomainEvent>` and '`IBeforeComminEventHandler<ChildDomainEvent>`.

**Comment by dotnetjunkie** [comment]
No, that's not the case. Even when registering a closed type directly, Simple Injector will place all registrations of its open-generic type in the same bucket, and will later make sure all compatible registrations are put in a collection.

**Comment by voroninp** [comment]
It would be nice, by the way, to have an option to specify collection of services as optional, that is it will be empty, if no service is registered.

Now injector throws on `GetAllInstances`, if no registrations were made for collection.

**Comment by dotnetjunkie** [comment]
You can just call:

```c#
container.Options.ResolveUnregisteredCollections = true;
```

But TBH, we decided to block resolving unregistered collections by default since the introduction of v3, because we saw that this behavior let to confusion.

Out of curiosity, why do you think auto-resolve unregistered collections is "nice"? Is that just for testing purposes, or do you have a specific use case (for your actual production code) where this is beneficial?

**Comment by voroninp** [comment]
It's same task, imagine:

```CSharp
public class Notifier
{
    public Notifier([Optional] IEnumerable<INotfificationHandler>> handlers)
    {
    }
}
```

Why should I require here the existence of registered handlers?

**Comment by dotnetjunkie** [comment]
Let me turn it around: why shouldn't you require a registration? What's tge problem of explicitly stating there are 0 handlers?

**Comment by voroninp** [comment]
Because I want implcit autowiring.
Suppose, I defined this class in a separate assembly and provided continer integration package.
```CSharp
Notifier.RegisterHandlersWith(continer, assembliesToScan);
```
In this method I search for types implementing interface `INotificationHandler` and register collection.
In this approach developer does not need to register type explcicitly, implementing interface is sufficient.
Delepoer does not have to go into specifics of particular container.
It would just work out of the box.

**Comment by dotnetjunkie** [comment]
The whole idea is that you explicitly make a collection registration, even if there are 0. This typically works when doing auto-registration, where you're not sure there there are any implementation. Especially when dealing with generic interfaces you'll see that some closed versions have no implementations.
