### ISSUE TITLE
Object reference does not set object instance.

### ISSUE THREAD

**Issue by zhangzihan** [simpleinjector/SimpleInjector#629]
Version: v4.4x

AutoCrossWireSettings.cs

Line 38: return new AutoCrossWiringDisabledScope(settings.isDisabled);

Line 67: 
public AutoCrossWiringDisabledScope(ThreadLocal<bool> isDisabled)
{
this.originalValue = this.isDisabled.Value; //this.isDisabled is a null object;

**Comment by dotnetjunkie** [comment]
Thank you for reporting this. This is a stupid error from my side. I pushed patch releases v4.4.1 for the AspNetCore integration packages. That should fix the problem.
