### ISSUE TITLE
SimpleInjector SignalR Core integration throws SimpleInjector.ActivationException on LongPolling

### ISSUE THREAD

**Issue by NimaAra** [simpleinjector/SimpleInjector#630]
I have been using the integration sample suggested in https://github.com/simpleinjector/SimpleInjector/issues/232 to integrate _SimpleInjector_ with _SignalR Core_. 

Everything works as expected until the protocol is set to _LongPolling_ where the following exception is thrown:

> SimpleInjector.ActivationException: 'The MyHub is registered as 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope.'

I have put together a server and client [example](https://github.com/NimaAra/SignalR.Sample) where it can be reproduced.

If you change the protocol at [THIS](https://github.com/NimaAra/SignalR.Sample/blob/f2430ca2a6e819d552240a59007e528f443b36c2/SignalR.Sample.Client/Program.cs#L20) line to _LongPolling_, you will see the exception thrown.
```
.WithUrl(ENDPOINT, o => o.Transports = HttpTransportType.LongPolling)
```

The _SimpleInjector_ integration methods can found in [`SimpleInjectorHelper`](https://github.com/NimaAra/SignalR.Sample/blob/master/SignalR.Sample.Server/SimpleInjectorExtensions.cs).

**Comment by dotnetjunkie** [comment]
Can you post a full stack trace?

**Comment by NimaAra** [comment]
Sure:

```
   at SimpleInjector.Scope.GetScopelessInstance[TImplementation](ScopedRegistration`1 registration)
   at SimpleInjector.Advanced.Internal.LazyScopedRegistration`1.GetInstance(Scope scope)
   at lambda_method(Closure )
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.Container.GetInstance[TService]()
   at SignalR.Sample.Server.SimpleInjectorHelper.SimpleInjectorHubActivator`1.Create() in D:\My Code\GitHub\SignalR.Sample\SignalR.Sample.Server\SimpleInjectorExtensions.cs:line 36
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
```

**Comment by dotnetjunkie** [comment]
In your case, you need to implement a custom `HubDispatcher<T>`, because SignalR's default hub dispatcher is in control of managing scopes. Unfortunately, SignalR Core didn't really learn from the past, so this is actually more complicated than it should. But eitherway, you can use this implementation:

``` c#
private sealed class SimpleInjectorScopeHubDispatcher<THub> : HubDispatcher<THub> where THub : Hub
{
    private readonly Container container;
    private readonly HubDispatcher<THub> decorated;

    public SimpleInjectorScopeHubDispatcher(Container container, DefaultHubDispatcher<THub> decorated)
    {
        this.container = container;
        this.decorated = decorated;
    }

    public override async Task DispatchMessageAsync(HubConnectionContext connection, HubMessage hubMessage)
    {
        using (this.BeginScope()) await this.decorated.DispatchMessageAsync(connection, hubMessage);
    }

    public override async Task OnConnectedAsync(HubConnectionContext connection)
    {
        using (this.BeginScope()) await this.decorated.OnConnectedAsync(connection);
    }

    public override async Task OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
    {
        using (this.BeginScope()) await this.decorated.OnDisconnectedAsync(connection, exception);
    }

    public override IReadOnlyList<Type> GetParameterTypes(string name) => this.decorated.GetParameterTypes(name);
    public override Type GetReturnType(string invocationId) => this.decorated.GetReturnType(invocationId);
    private Scope BeginScope() => AsyncScopedLifestyle.BeginScope(this.container);
}
```

Using this class, your Simple Injector/SignalR configuration will look as follows.

``` c#
services.AddSingleton(typeof(IHubActivator<>), typeof(SimpleInjectorHubActivator<>));
services.AddSingleton(typeof(DefaultHubDispatcher<>));
services.AddSingleton(typeof(HubDispatcher<>), typeof(SimpleInjectorScopeHubDispatcher<>));
```

**Comment by NimaAra** [comment]
Excellent, works great! Thanks for the quick reply.

**Comment by dotnetjunkie** [comment]
Note that the above integration does not work any longer in ASP.NET Core 3, because `HubDispatcher<THub>` has become internal. For the moment, LongPolling is not supported. [This page](https://github.com/simpleinjector/SimpleInjector/issues/631) shows the most current way to integrate with SignalR.

We are planning on [adding an official integration library](https://github.com/simpleinjector/SimpleInjector/issues/783) to Simple Injector.

**Comment by dotnetjunkie** [comment]
The introduction of Simple Injector v4.9 simplified the integration with SignalR Core. I updated the [SignalR Core integration page](https://github.com/simpleinjector/SimpleInjector/issues/631) accordingly. The described integration also fixes the long-polling problems.
