### ISSUE TITLE
Use scoped registration outside scope

### ISSUE THREAD

**Issue by anton-putau** [simpleinjector/SimpleInjector#636]
I have my own simple service bus. I send command, receive it and invoke handler. Handler I am resolving using small abstraction over any DI container

``` c#
public class DependencyContainer : IDependencyContainer
{
    private readonly Container _container;

    public DependencyContainer(Container container)
    {
        _container = container;
    }

    public object GetService(Type serviceType)
    {
        return _container.GetInstance(serviceType);
    }
}
```

My problem is next:  my handlers are registered as Async Scope, so I cant do something like this (inside endpoint listener) - `DependencyContainer.Resolve(MyHandler )` -

> The MyHandler is registered as 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope

I need do something next -

``` c#
using (AsyncScopedLifestyle.BeginScope(container)) {
     var handler = container.Resolve(MyHandler )
}
```

I cant understand how to work with scope. I cant place this code inside endpoint because I should use simpleinjector directly. I can't place this code inside `DependencyContainer `- it's not the task of `DependencyContainer`. Could any point me how to deal with this?

P.S

If it was something like CreateChildContainer and per container lifetime then  I will have no problem. `Using `block is a headache for me.

**Comment by dotnetjunkie** [comment]
I made the following comment on [your SO question](https://stackoverflow.com/questions/53374313/resolve-scoped-registration):

> What you wish to accomplish, is not possible. You will either have to change your abstraction or apply scoping on a different level. 

As SO is not suited for open design discussions, we can do that here instead. But the fact is, _you are missing an abstraction_.

**Comment by anton-putau** [comment]
@dotnetjunkie , thanks for reply. I guess I need to make an abstraction around scope. Then I will be able to do something like

```
var scope = DiWrapper.GetScope()

using(scope)
{
     scope .Resolve(MyType)
}

```
Thanks for ideas.

**Comment by diegobonano** [comment]
I have a project with DDD that contains a WebAPI project and a WindowsService project. WindowsService is a multithread so I need to adjust the LifeStyle.

`public static void Initialize(string typeRequest)
        {
            if (_container == null)
            {
                _container = new Container();

                if (typeRequest == "WebApi")
                {
                    _container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
                }
                else if (typeRequest == "MVC")
                {
                    _container.Options.DefaultScopedLifestyle = new WebRequestLifestyle();
                }
            }
            
            RegisterServices(typeRequest);

            _container.Verify();

        }
        
        public static Container InitializeWithReturn(string typeRequest)
        {
            Initialize(typeRequest);

            return _container;
        }

        public static void RegisterServices(string typeRequest)
        {
            if (!_servicesIsRegistereds)
            {
                Lifestyle lifeStyle = null;

                if (typeRequest == "WebApi" || typeRequest == "MVC")
                {
                    lifeStyle = Lifestyle.Scoped;
                }
                else
                {
                    lifeStyle = Lifestyle.Singleton;
                }

                _container.Register<OxygenNFeContext>(lifeStyle);
                
                _container.Register(typeof(IServiceBase<>), typeof(ServiceBase<>), lifeStyle);`


What's the correct way to do this?

**Comment by dotnetjunkie** [comment]
I have a project with DDD that contains a Web API project and a Windows Service project. WindowsService is a multithread so I need to adjust the `Lifestyle`.

``` c#
public static void Initialize(string typeRequest)
{
    if (_container == null)
    {
        _container = new Container();

        if (typeRequest == "WebApi")
        {
            _container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();
        }
        else if (typeRequest == "MVC")
        {
            _container.Options.DefaultScopedLifestyle = new WebRequestLifestyle();
        }
    }
    
    RegisterServices(typeRequest);

    _container.Verify();
}

public static Container InitializeWithReturn(string typeRequest)
{
    Initialize(typeRequest);

    return _container;
}

public static void RegisterServices(string typeRequest)
{
    if (!_servicesIsRegistereds)
    {
        Lifestyle lifeStyle = null;

        if (typeRequest == "WebApi" || typeRequest == "MVC")
        {
            lifeStyle = Lifestyle.Scoped;
        }
        else
        {
            lifeStyle = Lifestyle.Singleton;
        }

        _container.Register<OxygenNFeContext>(lifeStyle);
        
        _container.Register(typeof(IServiceBase<>), typeof(ServiceBase<>), lifeStyle);
    }
}
```

What's the correct way to do this?


There's not a single correct way to do this.

What I noticed, however, in your example, that you make certain registrations as `Singleton` in the Windows Service, where you would make them as `Scoped` in the Web Application. Although this is not a bad thing per se, prefer keeping those registrations `Scoped` in the Windows Service as well, as a Windows Service will typically live for a very long time, which could cause problems if those services (especially things like Entity Framework `DbContext` instances, e.g. your `OxygenNFeContext`) are cached forever. Even if there are no multi-threaded issues.

Using a `Scoped` lifestyle in the Windows Service does mean that you will have to explicitly start a scope 'somewhere' in the Windows Service just before you resolve a service and dispose it after you invoked the resolved service. This can be done with the `AsyncScopedLifestyle`, for instance.

But if you do this, you can reduce the complexity of your registrations, which is a really nice plus. For instance:

``` c#
public static void Initialize(Container container)
{
    RegisterServices();
}

public static Container InitializeWithReturn(ScopedLifestyle scopedLifestyle)
{
    container = new Container();
    
    // Setting the technology-specific lifestyle to the default scoped lifestyle
    container.Options.DefaultScopedLifestyle = scopedLifestyle;
    
    Initialize(container);

    container.Verify();
    
    return container;
}

public static void RegisterServices(Container container)
{
    // Biw always registered as Scoped lifestyle.
    container.Register<OxygenNFeContext>(Lifestyle.Scoped);
    
    container.Register(typeof(IServiceBase<>), typeof(ServiceBase<>), Lifestyle.Scoped);
}
```

Also note that I removed the initialization checks and the caching of the container. Prefer having methods that just create a new container instance. Having null checks wouldn't be useful as the `Initialize` should only be called anyway.

By adding the `ScopedLifestyle` as input argument of `InitializeWithReturn` you can call it from within the different Composition Roots of your application:

``` c#
// Web API Composition Root
var container = Bootstrapper.InitializeWithReturn(new WebApiRequestLifestyle());
GlobalConfiguration.Configuration.DependencyResolver =
    new SimpleInjectorWebApiDependencyResolver(container);

// MVC Composition Root
var container = Bootstrapper.InitializeWithReturn(new WebRequestLifestyle());
DependencyResolver.SetResolver(new SimpleInjectorDependencyResolver(container));

// Windows Service Composition Root
var container = Bootstrapper.InitializeWithReturn(new AsyncScopedLifestyle());
```

Integrating Simple Injector in a Windows Service is similar to that of integrating with a Console Application. Please see the [Console Application integration guide](https://simpleinjector.org/console).

**Comment by dotnetjunkie** [comment]
Hi @diegobonano,

As described in https://simpleinjector.org/scoped, you will have to wrap the resolve of a graph that contains Async Scoped registrations with a Async Scope.

Your Windows Service is *request based* and each timer pulse can be considered a request. This means that this is the point where you should start a new Async Scope. In other words, change your `ProcessarFila` method in an Async scope as follows:

``` c#
private void ProcessarFila()
{
    using (AsyncScopedLifestyle.BeginScope(container))
    {
        var queueService = IoC.Resolve<IQueueService>();
        QueueProcess itemToProcess = queueService.GetNextQueue();
        // do something with itemToProcess before scope ends
    }
}
```

**Comment by diegobonano** [comment]
Hi @dotnetjunkie, nice, for this method works.

But I have a global

`private readonly ILogger _logger;`

That is used on multiple methods: constructor, OnStop, OnStart, ProcessarFila()

How can I instance this global variable? Isn't possible declare inside a using block.

Thank!

**Comment by dotnetjunkie** [comment]
As a general rule, everything that is registered created by the container should be resolved from the container, and never cached. As your logger is required even before you register the container, do not resolve it from the container on start. Instead, create it directly (or request it directly from your logging framework) and store that instance in your `O2SWinService` class. You can, however, still register that logger in your container in case it is injected into consumers, though. Example:

``` c#
namespace O2S.WinService
{
    public partial class O2SWinService : ServiceBase
    {
        private static readonly ILogger _logger = LogManager.GetLogger(typeof(O2SWinService));

        private readonly Timer _timer;

        public O2SWinService()
        {
            InitializeComponent();
           
            _timer = new Timer();
            _timer.Elapsed += TimerElapsed;
        }

        protected override void OnStart(string[] args)
        {
            _logger.Debug("Serviço iniciado as " + DateTime.Now);

            IoC.Resolve<IQueueService>().ReprocessStatus();

            _timer.Interval = Convert.ToInt32(ConfigurationManager.AppSettings.Get("Interval"));
            _timer.Start();
        }

        ...
    }
}
```
