### ISSUE TITLE
Registration of sub types when abstraction is required.

### ISSUE THREAD

**Issue by stevengopmo** [simpleinjector/SimpleInjector#642]
Hi @dotnetjunkie and team,

I'm having a problem getting my head around a registration/integration here that I'm hoping someone can help with.  Here's the scenario.

I have an abstraction 

```` c#
public interface IProcessor<in T> where T : ProcessFile
{
        Task<FileProcessingReport> ProcessFile(T processFile);
}
````

And this registration

```` c#
container.Register(typeof(IProcessor<>), new[] {typeof(IProcessor<>).Assembly});
container.RegisterDecorator(typeof(IProcessor<>), typeof(ExecutionTimeDecorator<>));
````
So far so good.  `IProcessor` handles ProcessFile messages (an abstraction)

```` c#
    public interface IProcessor<in T> where T : ProcessFile
    {
        Task<FileProcessingReport> ProcessFile(T processFile);
    }
````

I use Rebus to handle messages that will eventually need to be handled by `IProcessor` but to get Rebus to handle the base message I have to specify the message type

```` c#
    internal class ProcessFileHandler : 
        IHandleMessages<ProcessFile>, 
        IHandleMessages<IFailed<ProcessFile>>
    {
        private readonly IProcessor<ProcessFile> _processor;
        private readonly IBus _bus;

        public ProcessFileHandler(IProcessor<ProcessFile> processor, IBus bus)
        {
            _processor = processor;
            _bus = bus;
        }

        public async Task Handle(ProcessFile message)
        {
            var result = await _processor.ProcessFile(message);

            await _bus.Send(new DeliverReport(result));

        }
    }
````

Of course when I do this, I get an error from SI.

> The constructor of type ProcessFileHandler contains the parameter with name 'processor' and type IProcessor&lt;ProcessFile> that is not registered. 
Please ensure IProcessor&lt;ProcessFile> is registered, or change the constructor of ProcessFileHandler. 
Note that there exists a registration for a different type Vortext.Ingestion.Common.Processors.IProcessor&lt;T> while the requested type is Vortext.Ingestion.Common.Processors.IProcessor&lt;Vortext.Ingestion.Common.Messages.ProcessFile>.'

Obviously this is because 
> Types that are registered by their abstraction, can only be resolved by their abstraction

So the question is how do I register `IProcessor<ProcessFile>` for all the ProcessFile subtypes?  I'm sure this is probably obvious but I'm just not seeing it.

**Comment by dotnetjunkie** [comment]
What implementations do you have for `IProcessor<T>`? I would expect your code base to have something as follows:

``` c#
public class ProcessFileProcessor : IProcessor<ProcessFile> { ... }
```

With such an implementation, Simple Injector will automatically pick it up when you call `Register(typeof(IProcessor<>), new[] {typeof(IProcessor<>).Assembly});` (assuming it lives in the same assembly as the `IProcessor<T>` interface).

In case you have one generic implementation:

``` c#
public class ProcessorImpl<T> : IProcessor<T> { ... }
```

I'd expect to see a different registration (as the batch-registration will _not_ pick up generic types):

``` c#
container.Register(typeof(IProcessor<>), typeof(ProcessorImpl<>));
```

**Comment by stevengopmo** [comment]
I have about a dozen implementations of `IProcessor<T>` through an abstract implementation and you are right about SimpleInjector picking it up if my Handler class took an `IProcessor<T>` but my handler requires 'IProcessor<ProcessFile>` that's why I'm getting the error.  

Does that make sense?  `ProcessFile` is an abstract class and all the inheritors get their own processor.

**Comment by dotnetjunkie** [comment]
Can you post the definition of `ProcessFile` and the definition of some implementations? Is it something as follows?:

``` c#
public abstract class ProcessFile { }
public class Derived1 : ProcessFile { }
public class Derived2 : ProcessFile { }

public class Derived1Processor : IProcessor<Derived1> { }
public class Derived2Processor : IProcessor<Derived2> { }
```

**Comment by stevengopmo** [comment]
Process file and derived
````
    public abstract class ProcessFile
    {
        protected ProcessFile(string fileFullPath, Tenant tenant)
        {
            FileFullPath = fileFullPath;
            Tenant = tenant;
        }

        public string FileFullPath { get; }
        public Tenant Tenant { get; }
        public abstract FileType FileType { get; }
    }
    public class ProcessInsuranceFile : ProcessFile
    {
        public ProcessInsuranceFile(string fileFullPath, Tenant tenant) : base(fileFullPath, tenant)
        {
        }
        public override FileType FileType => FileType.Insurance;
    }
````
IProcessor, Processor (abstract) and simple Impl
````
    public interface IProcessor<in T> where T : ProcessFile
    {
        Task<FileProcessingReport> ProcessFile(T processFile);
    }

    public abstract class Processor<TProcessFile, TModel> : IProcessor<TProcessFile> 
        where TProcessFile : ProcessFile
    {
        protected readonly Func<FileInfo, IDelimitedFileReader<TModel>> ReaderFactory;

        protected Processor(Func<FileInfo, IDelimitedFileReader<TModel>> readerFactory)
        {
            ReaderFactory = readerFactory;
        }
        protected abstract Task<IEnumerable<(int row, string message)>> ProcessItems(IEnumerable<TModel> items);

        public async Task<FileProcessingReport> ProcessFile(TProcessFile processFile)
        {
//removed for brevity
        }
    }

    public class Processor : Processor<ProcessInsuranceFile, SqlDataRecord>
    {
        private readonly BulkLoadDtoDataAccess<InsuranceCompanyDto> _insuranceCompanyDataAccess;

        public Processor(BulkLoadDtoDataAccess<InsuranceCompanyDto> insuranceCompanyDataAccess,
            Func<FileInfo, BulkLoadDelimitedFileReader<InsuranceCompanyDto>> readerFactory) : base(readerFactory)
        {
            _insuranceCompanyDataAccess = insuranceCompanyDataAccess;
        }

        protected override async Task<IEnumerable<(int row, string message)>> ProcessItems(IEnumerable<SqlDataRecord> items)
        {
            return await _insuranceCompanyDataAccess.BulkLoad(items);
        }

````

**Comment by dotnetjunkie** [comment]
This means that your `Processor` class implements `IProcessor<ProcessInsuranceFile>`.

Question: As your `ProcessFileHandler` depends on `IProcessor<ProcessFile>`, assuming there are many `IProcessor<T>` implementations, which implementation do you want to have injected into `ProcessFileHandler`?

**Comment by stevengopmo** [comment]
That's a great question.  I want to have the `IProcessor<T>` implementation that matches the 'ProcessFile` message implementation.  For example if the message is `ProcessInsuranceFile`, I want `InsuranceProcessor` (the last in the above message) to be injected.

**Comment by stevengopmo** [comment]
sorry Stephen, I'm really struggling with that concept.  As far as I can tell Scenario #2 in that article is the one that applies to me.

> In this scenario we want to configure the container in such way that when we request a single event handler for a particular event, it would return the single registered instance for that event, or is case it doesn't exist, return a compatible registered event handler.
(if you exchange event for command) and it seems like I should be using container.Collection.Register but I don't see that property in the container anywhere (I'm using 4.0.3) so maybe I need to upgrade? :)

But I guess what I fail to grasp really is why everything works if I have a handler like the following
````
    internal class ProcessInsuranceHandler : ProcessFileHandler<ProcessInsuranceFile>, 
        IHandleMessages<ProcessInsuranceFile>, 
        IHandleMessages<IFailed<ProcessInsuranceFile>>
    {

        public ProcessInsuranceHandler(IProcessor<ProcessInsuranceFile> processor, IBus bus) : base(processor, bus)
        {
        }

        public async Task Handle(ProcessInsuranceFile message)
        {
            await HandleMessage(message);
        }

        public async Task Handle(IFailed<ProcessInsuranceFile> message)
        {
            await HandleFailed(message);
        }
````
I guess this is because I'm being explicit about which ProcessFile message to handle?

**Comment by dotnetjunkie** [comment]
> and it seems like I should be using container.Collection.Register but I don't see that property in the container anywhere (I'm using 4.0.3) so maybe I need to upgrade? :)

Always use the latest version :)

But otherwise, `Container.Collection.Register` in v4.1 and up replaces `Container.RegisterCollection`. The behavior is identical.

> But I guess what I fail to grasp really is why everything works if I have a handler like the following

The `Processor` class implements `IProcessor<ProcessInsuranceFile>`. This makes Simple Injector register it by that abstraction, similar to the following registation:

``` C#
container.Register<IProcessor<ProcessInsuranceFile>, Processor>();
```

Since the mapping is exclicit, Simple Injector can find it without help if you change your constructor argument to `IProcessor<ProcessInsuranceFile>`.

Another option is to inject an `IEnumerable<IProcessor<ProcessFile>>`. But in that case you would have to iterate the collection.
