### ISSUE TITLE
Can I decorate non-open generics with an open generic?

### ISSUE THREAD

**Issue by seangwright** [simpleinjector/SimpleInjector#644]
I have an `IEntityCommand<T>` type.

```csharp
public interface IEntityCommand<TCommandParams>
{
    Task Execute(TCommandParams commandParams);
}
```

I have created 'named' interfaces of this type that define the generic type.

```csharp
public interface ICustomerUpdateCommand : IEntityCommand<Customer>
{
}
```

I've done this to make the code more legible. Developers can inject `ICustomerUpdateCommand` into a service and call `Execute()` on it. I'm using this approach instead of having developers inject `IEntityCommand<Customer>` into their services.

I then have implementations of my 'named' interfaces.

```csharp
public class CustomerUpdateCommand : ICustomerUpdateCommand
{
    private readonly IDbContext context;

    public CustomerUpdateCommand(IDbContext context)
    {
        this.context = context;
    }

    public Task Execute(Customer customer) { ... }
}
```

The problem I'm encountering is that I would like to decorate a handful of these 'named' interface types with a class that clears a cache after calling `Execute()` on the decorated type.

Unfortunately I think I've painted myself into a corner using these 'named' interfaces instead of the `IEntityCommand<T>` because I can't create a single class that can decorate all 'named' interfaces because nothing injects `IEntityCommand<Customer>` and instead `ICustomerUpdateCommand` is injected.

Are there any options for using SimpleInjector to decorate these 'named' interface types with a single open-generic class or do I need to change my architecture to remove the 'named' interfaces and instead inject the closed-generic types, relying on the generic type to give context to the developers?

I use decoration with great success elsewhere in my app where I am trying to use 1 class to decorate 1 specific command - but this approach isn't scaleable for my current requirements.

Thanks!

**Comment by dotnetjunkie** [comment]
I recently answered an SO question about this exact subject. Please read this: https://stackoverflow.com/q/53537171/264697

> Are there any options for using SimpleInjector to decorate these 'named' interface types with a single open-generic class 

Nope

> or do I need to change my architecture to remove the 'named' interfaces and instead inject the closed-generic types, relying on the generic type to give context to the developers?

Yep.

**Comment by seangwright** [comment]
Gotcha! That's what I thought.

I like the autonaming that Visual Studio does for constructor parameters of a type by using camelCase of the type name - it will be unfortunate to lose that when I'm orchestrating multiple Commands/Queries in a service.

I'm using Mediatr in my application - I could always re-use that pattern but I wanted to differentiate between Requests/Handlers which are used at my Api layer and Commands/Queries which are used in my Core domain layer. I suppose I could inject my closed generic `IEntityCommand<>` for specific parameter types and name my parameter types in a descriptive manner (ex `IEntityCommand<CustomerUpdateCommandParams>`.

... or I could re-implement Mediatr with my own naming conventions. But then I lose the 'Go To Definitions/Implementations' which is one of my gripes about the disconnectedness of Mediatr.

Have you come up with any creative ways to deal with this?

**Comment by dotnetjunkie** [comment]
> Have you come up with any creative ways to deal with this?

If 'go to definition' is an issue, a simple solution is to place the command/query classes in the same file as their corresponding handler. When you go to the definition of a command message, you immediately end up with its handler implementation. Of course, this only works when there is no architectural need to move the commands and queries to a separate assembly (for instance when you are using them as contract between client and server).

Another option is to create a Roslyn or Resharper plugin that will be a specialized "go to implementation" but that considers the closed-generic implementation rather than the open-generic implementation. I bet this shouldn't be that hard actually.
