### ISSUE TITLE
Add IsTypeRegistered(Type) method

### ISSUE THREAD

**Issue by vitidev** [simpleinjector/SimpleInjector#646]
This will allow to emulate the functionality TryRegister*** and GetInstance(required: false)

**Comment by dotnetjunkie** [comment]
This functionality is already implemented. You can achieve this by calling `GetRegistration(Type)` or calling `GetRegistrations().Any(r => r.ServiceType == type)`.

**Comment by vitidev** [comment]
I know. I use it that way. But it enumerate full collection every time.

**Comment by vitidev** [comment]
TryResolve

My application uses many small modules that load dynamically. I pass container to each module and module fills container. In this case, it is normal if some module will not be loaded. The calling code knows this and can handle it. I use an extension method that checks the type for existence (GetRegistrations().Any) and resolves it
One could say "use MEF". But why, if the container can all the same. 
The container inside itself most likely has access to a type dictionary, so I'll get a slight increase in performance

TryRegister

There is only a theory. I see Microsoft extend its libraries [in this manner (first method)](https://github.com/aspnet/Extensions/blob/master/src/HttpClientFactory/Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs). Here I am only trying to understand the benefits of such an approach, but I know about it and therefore I mentioned it.

**Comment by dotnetjunkie** [comment]
> The container inside itself most likely has access to a type dictionary, so I'll get a slight increase in performance

If performance is your concern, you should call `Container.GetRegistration` instead. For instance, a `TryRegister` extension method can be made with a few lines of code:

``` c#
public static void TryRegister<TService, TImplementation>(this Container container) 
    where TImplementation: TService, TService: class
{
    if (container.GetRegistration(typeof(TService)) == null)
        container.Register<TService, TImplementation>();
}
```

`GetRegistration(Type)` will internally do a dictionary lookup. This is an O(1) operation.
