### ISSUE TITLE
Add information about lifestyles to VisualizeObjectGraph

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#648]
When `InstanceProducer.VisualizeObjectGraph` is called, a string representation of the object graph is returned. For instance:

```
UserListController(
    SqlRepository<User>(
        SqlConnectionFactory()),
    FileLogger())
```

It would be useful to add lifestyle information to this graph:

```
UserListController( // Transient
    SqlRepository<User>( // Async Scoped
        SqlConnectionFactory()), // Singleton
    FileLogger()) // Singleton
```

Perhaps this can be presented as an option:

``` c#
public string VisualizeObjectGraph(bool includeLifestyleInformation)
```

or:

``` c#
public string VisualizeObjectGraph(VisualizationOptions options)

public class VisualizationOptions
{
    public bool IncludeLifestyleInformation { get; set; } = true;
}
```

**Comment by kwlin** [comment]
@dotnetjunkie : Can I pick this issue up & make a pull request to learn more about this nice project?

**Comment by dotnetjunkie** [comment]
@kwlin: Sure. You should follow the [How to Contribute](https://simpleinjector.readthedocs.io/en/latest/contribute.html) guide. This means that you should sign and send an CLA, as described in the documentation.

After you've done that, you can fork the project and add your code, xml docs and unit tests to the [feature-648](https://github.com/simpleinjector/SimpleInjector/tree/feature-648) branch. When you're done, you can send a pull request. After you sent the PR, we can start discuss your PR.

Have fun!

feature-648

**Comment by dotnetjunkie** [comment]
Few other tips:

* Go with the `VisualizationOptions` approach
* Set `IncludeLifestyleInformation` to true by default.

**Comment by kwlin** [comment]
Thnx for the input. I was also thinking of the VisualizationOptions approach ;) I hope I can make a pull request next week!

**Comment by kwlin** [comment]
I've got a first implementation for this issue. 

Shall I make Work In Progress pull request so the first code reviews/comments could be provided?

PS: The CLA is still work in progress!

**Comment by dotnetjunkie** [comment]
The CLA is only required for us to accept the pull request. Feel free to create the PR though.

**Comment by kwlin** [comment]
See pull request https://github.com/simpleinjector/SimpleInjector/pull/659 for first implementation!
