### ISSUE TITLE
Add type factory overload to RegisterConditional

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#65]
Just like with the the RegisterDecorator method:

``` c#
RegisterConditional(
    Type serviceType, 
    Func<PredicateContext, Type> implementationTypeFactory,
    Lifestyle lifestyle,
    Predicate<PredicateContext> predicate);
```

Typical use case:

``` c#
container.RegisterConditional(typeof(ILogger),
    c => typeof(Logger<>).MakeGenericType(c.Consumer.ImplementationType),
    Lifestyle.Singleton,
    c => true);
```

**Comment by dotnetjunkie** [comment]
Here we have an interesting choice to make. Since the `implementationTypeFactory` is responsible of generating the implementation type, we either have a few choices:
- We call the `implementationTypeFactory` after calling `predicate` (just as `RegisterDecorator` does), meaning that the `PredicateContext.ImplementationType` property will be `null` during the execution of that predicate.
- We call the `implementationTypeFactory` before calling `predicate`. This allows the `PredicateContext.ImplementationType` to be filled during the time the predicate is executed, but this makes this behavior inconsistent with `RegisterDecorator` and causes `PredicateContext.ImplementationType` to still be null during the time `PredicateContext.ImplementationType` is executed.
- We don't use `PredicateContext` but a different type that lacks this `ImplementationType` property, to prevent confusion. Downside is that it becomes harder for users to reuse predicate logic, because they're dealing with a different type.

**Comment by qujck** [comment]
This looks like it is part of the API for ComplexInjector ;-D

Would it be better to offer both options:

```csharp
RegisterConditional(
    Type serviceType, 
    Predicate<PredicateContext> preFactoryPredicate
    Func<PredicateContext, Type> implementationTypeFactory,
    Lifestyle lifestyle,
    Predicate<PredicateContext> postFactoryPredicate);
```

**Comment by dotnetjunkie** [comment]
I agree that this isn't the simplest thing, but I think it is important to have support for such thing. I really like to keep developers away from the `RegisterWithContext` extension method, because it does runtime resolution, while anyone should prefer 'compile-time' resolution. Besides, this feature is already available when dealing with decorators. Perhaps we can simplify the API somehow?

Do note that I think that the option you are giving is even more complex :-/

**Comment by qujck** [comment]
Yes it is more complicated, but if you need this feature you also need guidance on how to approach it with care and forethought. If we choose between 1 or 2 above, someone, somewhere, someday will need the other option. Maybe this feature belongs in the `Advanced` namespace?

Does it fully replace `RegisterWithContext`?

**Comment by dotnetjunkie** [comment]
No, it doesn't replace `RegisterWithContext` completely, because with `RegisterWithContext`, the user supplies a delegate that return an *instance*, while the `RegisterConditional` methods only allow working with types. In other words, with `RegisterConditional`, Simple Injector is *always* in control over the creation and caching of instances, while with `RegisterWithContext`, it is the user who is in control.

I was thinking about moving it to the advanced namespace at all. This might be a good idea.

What's even a better idea is to cut this feature from v3. This gives us a bit more time to figure out what the API should look like and where it should be located. Besides, the internal adjustments I had to do to get this feature in didn't please me. The code really became a mess.

Let's pull it out.

**Comment by dotnetjunkie** [comment]
There seems to be a fourth option:

``` c#
RegisterConditional(
    Type serviceType, 
    Func<TypeFactoryContext, Type> implementationTypeFactory,
    Lifestyle lifestyle,
    Predicate<PredicateContext> predicate);
```

Here we introduce a new type `TypeFactoryContext` that contains the same information as `PredicateContext` does, only without the `ImplementationType`. The `PredicateContext` can still contain the `ImplementationType` property, and its value can be lazily loaded with the value from the `implemenationTypeFactory`. In other words, in case the user accesses the `PredicateContext.ImplementationType` property, the `implementationTypeFactory` will be called to retrieve the type.

What this means is, that the `implementationTypeFactory` only get called by Simple Injector after the `predicate` returns true, except when the user decided to call the `ImplementationType` property inside the `predicate`. This allows the user supply an `implementationTypeFactory` that is can only work when the `predicate` returns true (because of building a closed type based on an open type with generic type constraints for instance), but does allows the user to use that `ImplementationType` if required.

**Comment by dotnetjunkie** [comment]
I think I managed to get this feature in the way as described above. Although it might need some refactoring, but I'm quite pleased with the result, because:
- The behavior is quite intuitive and inline with that of the decorator subsystem.
- The amount code changes to get this in where actually quite limited. That's in contrast to what I said in my last comment on June 23. Probably because I could have a fresh look at this after a month, and some refactorings on the code base have been done in the meantime that made this easier.

I'm still a bit in doubt about where to place this new method. I think there are basically two options:
 1. Put in as instance method on the Container, making it a fully visible part of the API. Downside of this is that that IntelliSense is polluted with a method that is not often needed, and is not very easy to use.
 2. Put it as extension method in the SimpleInjector.Advanced namespace, making it only visible to anyone who includes the Advanced namespace. Downside is that it becomes practically invisible, because almost nobody knows about the existence of this namespace.

My current preference is to add it to the main API, even though it might pollute the IntelliSense list a bit.

**Comment by dotnetjunkie** [comment]
Ouch... I just discovered a small design flaw with the new conditional stuff. So a quick poll here, given the examples below, what would for you the expected behavior be per example. That is: what should the call to `GetRegistration` result in? If it returns a value, which registration should it return? If it doesn't return a value, does it return `null` or throw an exception? Is if throws an exception, what exception do you expect?

Example 1:
``` c#
container.RegisterConditional(typeof(ILogger), typeof(NullLogger), c => false);
container.RegisterConditional(typeof(ILogger), typeof(ConsoleLogger), c => false);

var producer = container.GetRegistration(typeof(ILogger));
```
Example 2:
``` c#
container.RegisterConditional(typeof(ILogger), typeof(NullLogger), c => false);
container.RegisterConditional(typeof(ILogger), typeof(ConsoleLogger), c => true);

var producer = container.GetRegistration(typeof(ILogger));
```
Example 3:
``` c#
container.RegisterConditional(typeof(ILogger), typeof(NullLogger), c => true);
container.RegisterConditional(typeof(ILogger), typeof(ConsoleLogger), c => true);

var producer = container.GetRegistration(typeof(ILogger));
```
Example 4:
``` c#
// Note: c.Consumer is null in case the registration is a root type.
container.RegisterConditional(typeof(ILogger), typeof(NullLogger),
    c => c.Consumer.ImplementationType == typeof(HomeController));
container.RegisterConditional(typeof(ILogger), typeof(ConsoleLogger), c => true);

var producer = container.GetRegistration(typeof(ILogger));
```

**Comment by qujck** [comment]
I would expect null in all these examples.

Is it feasible to create a method GetConditionalRegistration?

**Comment by dotnetjunkie** [comment]
The current behavior is as follows:

 1. returns `null`.
 2. returns `null`.
 3. returns `ConsoleLogger`
 4. `ActivationException` "Multiple applicable registrations found for ILogger".
 5. `NullReferenceException` (because `c.Consumer` is null).

When `GetRegistration(type)` is called, about the same pipeline is executed as when you call `GetInstance(type)`. In other words, Simple Injector will go through all applicable conditional registrations and will call their predicate to see if the registration matches. This means that for example 1 and 2, there are no matching registrations (because all predicates return `false`) and `GetRegistration` therefore returns `null`. For that same reason, example 3 returns the `InstanceProducer` for `ConsoleLogger`, since there is one matching registration.

Example 4 throws a "Multiple applicable registrations found for ILogger" exception, because that's what `GetInstance` would throw as well in that case; there is ambiguity in the registration.

The reason example 5 throws an exception is again because `GetRegistration(type)` mimics `GetInstance(type)`. In other words, `GetRegistration(type)` will try to resolve an `InstanceProducer` as if it is a root type. This means that the `PredicateContext.Consumer` property `null` is; since there is no consumer; the registration is a root registration. That does mean though that a `NullReferenceException` is thrown.

While writing this, I think I must come to the conclusion that this behavior is actually fine. I think it is okay that `GetRegistration` mimics `GetInstance`. With example 1 and 2, a call to `GetInstance<ILogger>()` will cause an exception, because there is no applicable registration. With example 4, `GetInstance` will throw the same "Multiple applicable registrations" exception.

Only example 5 is perhaps a bit different, because in case the user writes `c => c.Consumer.ImplementationType == typeof(HomeController)`, the registration is never meant to be used as root type. But again, the same exception will happen when you call `GetInstance`.

Don't forget that `GetRegistration` is often used to implement a `TryGetInstance(Type)` functionality as follows:

``` c#
public static bool TryGetInstance<T>(this Container container, Type type, out T instance)
    where T : class {
    instance = container.GetRegistration(type)?.GetInstance() as T;
    return instance != null;
}

```
In case `GetRegistration` would start to behave differently for conditional registrations, such try-get functionality would break. For instance, if `GetRegistration` would return `null` in example 3, `TryGetInstance` would return `false` while `GetInstance<ILogger>()` would return a `ConsoleLogger`. That would cause inconsistent behavior.
