### ISSUE TITLE
Resolving IEnumerable When Cross-Wiring With Microsoft Container 

### ISSUE THREAD

**Issue by Kahbazi** [simpleinjector/SimpleInjector#650]
Hi, I'm using `SimpleInjector` with `Microsoft.Extensions.DependencyInjection` with auto cross-wire and I need to resolve IEnumerable of services with SimpleInjector. The problem is that those services are registered in Microsoft container SimpleInjector would not resolve them, and it make sense since cross-wire is applied using `ResolveUnregisteredType`, but is there any way to achieve this?

Also is there a way to resolve IEnumerable of services both from SimpleInjector and Microsoft container?

**Comment by dotnetjunkie** [comment]
Can you explain which services from the built-in container you wish to cross-wire and how you are using them?

**Comment by Kahbazi** [comment]
I'm doing some experiment on using SimpleInjector as main `IServiceProvider` in ASP.NET Core, so the resolving of each services (even Microsoft.Extensions.*) goes through SimpleInjector container. I have to say I've read https://simpleinjector.org/blog/2016/06/whats-wrong-with-the-asp-net-core-di-abstraction and understand your point of view. 

Right now i'm stuck at the beginning since ASP.NET Core needs `IEnumerable<IStartupFilter>` and SimpleInjector returns `null`.

I guess I can read the services from Microsoft container and add to SimpleInjector container, but I was wondering if there's a way like auto cross-wiring for enumerable.

**Comment by dotnetjunkie** [comment]
I'm afraid I can't help you with this. What you are trying to accomplish will simply not work, as I described in many places, such as the post you are referring to.

Please stick to the adviced way of integration or simply stick to using the built-in container.
