### ISSUE TITLE
INotificationHandler for an INotification with a GenericType Argument

### ISSUE THREAD

**Issue by oferns** [simpleinjector/SimpleInjector#656]
Hi,
in short, using .net core 2.2 + SI 4.4.3 (+ SI.AspNetCore &  SI.AspNetCore.Mvc) I am trying to do exactly what this old question on the Mediatr page is asking.

https://github.com/jbogard/MediatR/issues/21

I am registering like this

` container.Collection.Register(typeof(INotificationHandler<>), assemblies);`

I am publishing like this

` await mediator.Publish(new ChangeNotifier<T> {  Previous = null,  Updated = obj }, token);`

and my classes look like this

```
    public class ChangeNotifier<T> : INotification where T : class {

        public T Previous { get; set; }
        public T Updated { get; set; }

    }
```

```
    public class GenericChangeHandler<T> : INotificationHandler<ChangeNotifier<T>> where T : class {
        private readonly IMediator mediator;

        public GenericChangeHandler(IMediator mediator) {
            this.mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
        }

        public Task Handle(ChangeNotifier<T> notification, CancellationToken token) {
            throw new Exception("I wish I would happen!");
        }
    }
```
but my exception is never reached. I have an equivalent non-generic implementation that is identical otherwise and that is being called. I realise you didnt write mediatr but I thought you might have some insight. The author seems to suggest it should work.
Thanks,
Ollie

**Comment by dotnetjunkie** [comment]
If you expect your generic `GenericChangeHandler<T>` to be registered by the call to

```
container.Collection.Register(typeof(INotificationHandler<>), assemblies);
```

You are wrong. The call to `Collection.Register` will skip generic types by default. You can add this generic type seperately by calling `Collection.Append`.

**Comment by oferns** [comment]
thanks for the response. that has worked nicely.
