### ISSUE TITLE
SignalR Core and Strongly Typed Hubs

### ISSUE THREAD

**Issue by ScarlettCode** [simpleinjector/SimpleInjector#657]
Hi,

Is [this](https://github.com/simpleinjector/SimpleInjector/issues/631) still the best way to integrate SignalR into Simple Injector? And is there anything different I need to do if I'm using a [strongly typed hub](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2#strongly-typed-hubs)?

At the moment I can't seem to get any hub to register when I try inject it into a controller. Ideally I want to get it working with a strongly typed hub if possible

Thanks

**Comment by dotnetjunkie** [comment]
I don't have any new knowledge that makes me assume things should be done differently, but I must admit that I don't know how strongly typed hubs change the equation.

**Comment by ScarlettCode** [comment]
I worked it out, needed to crosswire the hub

container.CrossWire<IHubContext<ChatHub, IChatHub>>(app);

**Comment by dotnetjunkie** [comment]
See this [SignalR Core integration post](https://github.com/simpleinjector/SimpleInjector/issues/631) for the best-known way to integrate with SignalR Core.
