### ISSUE TITLE
Instance of Service is not created, when lazy loaded

### ISSUE THREAD

**Issue by TerrySlack** [simpleinjector/SimpleInjector#658]

**Comment by dotnetjunkie** [comment]
Wow. Great question. Are you willing to elaborate and demonstrate the problem using a code example, or do you want me to just close this issue?

**Comment by dotnetjunkie** [comment]
I'm closing this issue due to [unclearity](https://idownvotedbecau.se/unclearquestion) and [being unresponsive](https://idownvotedbecau.se/beingunresponsive). Feel free to include more details in order to get this question reopened again.
