### ISSUE TITLE
Feature Request template

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#675]
The following text is a proposal for the _Feature Request template_. My hope is that the addition of several templates will improve the issues raised by our users which allows us to help them faster.

When templates are enabled, this would look similar to the following:

![new issue page with multiple templates](https://help.github.com/assets/images/help/issues/new-issue-page-with-multiple-templates.png)

Proposal below. Let's discuss:

----

Please do not post feature requests. Please use the _Question template_ and describe the problem you are trying to solve. Possible new features always emerge from problem descriptions. If we conclude that a feature must be added, we will create the related feature issue our selves.

**Comment by TheBigRic** [comment]
Isn't it possible to not supply a feature template at all? And incorporate the text into the question template?

Headstrong people like myself would otherwise think: "well ok, you may think you do not need this feature but I'm sure it's useful and because there is a template I will just post it"

**Comment by dotnetjunkie** [comment]
@TheBigRic that a good idea. I incorporated this into the [Question template](https://github.com/simpleinjector/SimpleInjector/issues/674)
