### ISSUE TITLE
Consider supporting ContainerControlledCollection.Contains

### ISSUE THREAD

**Issue by onyxmaster** [simpleinjector/SimpleInjector#677]
Currently, when one attempts a collection as services as an `IEnumerable<TService>` somewhere, and invokes the `Enumerable<TSource>.Contains<TSource>(TSource item)` on the specified collection, the LINQ [built-in optimization](https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,1364) "sees" that it's actually an `ICollection<T>` (being an instance of `ContainerControlledCollection<TService>`), and invokes the `ICollection<T>.Contains(T)` method, instead of the usual iteration.
Unfortunately, this leads to unexpected exceptions with (quite cryptic) `NotSupportedException` exception being thrown, since `ContainerControlledCollection<TService>.Contains(TService)` is [not implemented](https://github.com/simpleinjector/SimpleInjector/blob/42a9d4e71a875e55767846215df7e81aa3ad8faf/src/SimpleInjector/Internals/ContainerControlledCollection.cs#L106).
I believe that this method could be implemented using simple iteration, since iteration is allowed in the first place by the `ContainerControlledCollection<TService>`.
To work around this, one can use `collection.Any(service =>service == value)` or the `collection.Contains(value, null)` "hacks", but I don't think this is a good solution.

**Comment by dotnetjunkie** [comment]
Interesting idea. I do agree that not implementing this method is not really nice, as this sort of breaks the contract of `ICollection<T>` (although [FDG](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/) do allow members to throw).

Reason, however, that this method is not implemented, is because calling `Contains` would typically have not the desired effect, as collections in Simple Injector behave as streams. This means that in most cases, iterating the stream will result in a new set of instances (assuming the `Transient` lifestyle) and this means that `Contains` would always return `false`, as the supplied `item` to compare will never match, as the comparison is done using reference equality.

Can you go into more detail on your specific use case? Why do you need to call `Contains` in your case? And why would `Contains` work in your specific case?

**Comment by onyxmaster** [comment]
I've got a check in that verifies if any of the instances are nulls and throws the exception if it's the case.
I hit the described issue when converting an existing class from manual composition to container-based.
In fact, I believe that to have this check produce results that are consistent in the future, I probably should copy the service enumeration using something like .ToList(), but this feels wrong (it may be that this feeling is wrong by itself).

**Comment by dotnetjunkie** [comment]
> I've got a check in that verifies if any of the instances are nulls and throws the exception if it's the case.

That's an interesting case. Although checking for null is not something that is useful in the context of Simple Injector, as it will never inject null or allow null to be returned from container controlled collections, from an application perspective it might still make sense, as at that point you are writing your code oblivious to the DI Container.

> I probably should copy the service enumeration using something like .ToList()

That might fail in v4.5 with the implementation of #554 as it detects iteration of collections inside constructors.

Funny, though, is that after all these years, you are the first to report the missing `Contains` implementation.

Even though that calling `Contains` would not have the expected results with container controlled collections, it wouldn't harm implementing it. And in that case we can implement a short-circuit for the `null` case, as Simple Injector collections will never contain `null`. This short-circuit will prevent the collection from being iterated which will prevent #554 from being triggered.

**Comment by onyxmaster** [comment]
This would be a satisfactory resolution, because I don't really see any need to check for anything other than null.

**Comment by onyxmaster** [comment]
> ... from an application perspective it might still make sense, as at that point you are writing your code oblivious to the DI Container.
Yes, this is exactly the case -- I had a manually instantiated (as a part of SimpleInjector registration instance producer) composite that worked and just changing it to be DI-instantiated was leading to a NotSupportedException, almost no other code was changed.

**Comment by dotnetjunkie** [comment]
I published v4.5.1 that contains this fix. Thanks for taking the time to report this.

**Comment by dotnetjunkie** [comment]
I decided to implement both `IndexOf` and `Contains` (as that was no extra work) and decided that calling either one of those methods should never trip of a lifestyle mismatch (as described in #554), as neither one of those methods actually return an instance, so it is impossible for the user to store an instance. These methods can, therefore, not cause captive dependencies.
