### ISSUE TITLE
Allow VisualizeObjectGraph to generate fully qualified type names when Options.UseFullyQualifiedTypeNames is set

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#685]
Simple Injector's `Options.UseFullyQualifiedTypeNames` allows Simple Injector to report fully qualified type names (type name + namespace). This, however, currently only works when Simple Injector throws exception messages. When calling `InstanceProducer.VisualizeObjectGraph`, on the other hand, it will currently *always* generate 'friendly class names' instead.

 `Options.UseFullyQualifiedTypeNames` should be able to influence `InstanceProducer.VisualizeObjectGraph`.

On top of that, it would be good if `VisualizeObjectGraph` would be able to override this default, for instance by letting the user do the following:

``` c#
producer.VisualizeObjectGraph(new VisualizationOptions
{
    UseFullyQualifiedTypeNames = true // Nullable<bool>
});
```

**Comment by dotnetjunkie** [comment]
[Feature-685 branch](https://github.com/simpleinjector/SimpleInjector/tree/feature-685) created.

**Comment by kwlin** [comment]
Working on it!

**Comment by kwlin** [comment]
Pull request accepted. See https://github.com/simpleinjector/SimpleInjector/pull/686 

Thanks @dotnetjunkie for the fast acceptance!
