### ISSUE TITLE
Prevent PredicateContext.Consumer from returning null

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#694]
The `PredicateContext.Consumer` property will be null when a conditional registration is resolved as root type, e.g.:

``` c#
container.RegisterConditional<ILogger, NullLogger>(
    c => c.Consumer.ImplementationType == typeof(HomeController));

// Resolves ILogger as root type, causing c.Consumer to be null
container.GetInstance<ILogger>();
```

With C# 8.0, however (and when #649 is implemented), the possibility of `Consumer` being null, will cause a warning (or compile error) in the user's code. This forces the user to do explicit null checks to prevent the compiler from tripping. Changing `PredicateContext.Consumer` to never return `null`, however, is a breaking change, because users might currently explicitly check for null when something actually is a root type.

I see the following options here:

1. <s>[Non-breaking] Leave the API the way it is, but do possibly internally use a Null Object implementation of `InjectionConsumerInfo` object to prevent from passing null throughout the code base.</s>
2. [Breaking] Prevent `PredicateContext.Consumer` from returning null, and instead throw an `InvalidOperationException` when the property is used on a root object. Additionally add a `IsRootObject`, `IsDirectResolve`, or similar that allows the user to check, without forcing him to catch an exception, where the earlier `InvalidOperationException` explains the use of that property.
3. <s>[Breaking] Let `PredicateContext.Consumer` return a Null Object `InjectionConsumerInfo` instance in case there is no consumer. Downside of this approach is that it forces `InjectionConsumerInfo.ImplementationType` and `InjectionConsumerInfo.Target` to become `null` values which basically means we're moving the problem. Or we use default values for `Target` and `ImplementationType`, but now the question becomes: what should those values be? `System.Object` or `SimpleInjector.Container` for `ImplementationType`? Both awkward. And what about `Target`? A `Target` is an `InjectionTargetInfo` which either wraps a `PropertyInfo` or a `ParameterInfo`. Should it return an empty `Target`?</s>

**Comment by Dheeraj-GL** [comment]
I am getting error because of this any work around ??

**Comment by dotnetjunkie** [comment]
Hi Dheeraj, the "workaround" is to check for null and act accordingly.

**Comment by dotnetjunkie** [comment]
[feature-694](https://github.com/simpleinjector/SimpleInjector/tree/feature-694) branch created.

**Comment by dotnetjunkie** [comment]
I decided to go with option 2:

> [Breaking] Prevent PredicateContext.Consumer from returning null, and instead throw an InvalidOperationException when the property is used on a root object. Additionally add a IsRootObject, IsDirectResolve, or similar that allows the user to check, without forcing him to catch an exception, where the earlier InvalidOperationException explains the use of that property

**Comment by dotnetjunkie** [comment]
API Changes:

* `PredicateContext.Consumer` never returns null, but throws an exception instead.
* `PredicateContext.HasConsumer` boolean property added.
