### ISSUE TITLE
Lower the threshold for Potential Single Responsibility Violations to 7

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#70]
The threshold for the warning was increased to 8 dependencies in Simple Injector 2.x release, to prevent too many false positives. But Simple Injector 3 differentiates between information and warning messages. The threshold can be lowered again.

**Comment by dotnetjunkie** [comment]
I think this threshold is still fine.

**Comment by qujck** [comment]
Is there any benefit in making this a configurable setting?

**Comment by dotnetjunkie** [comment]
I'm not sure. Seems like a bad idea to me. In v3 this has become an info message anyway, so i wouldn't like anyone to increase the threshold.
