### ISSUE TITLE
Support for new GenericHost

### ISSUE THREAD

**Issue by Nekromancer** [simpleinjector/SimpleInjector#705]
Hi,

I'm trying to use SimpleInjector with new generic host in asp (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host), but i'm not really sure if that's possible right now. Do you support generic host right now? The `SimpleInjector.Integration.AspNetCore` NuGet has dependencies on AspNetCore framework and i'm trying to stick to `Microsoft.Extensions.*` only. Your documentation doesn't mention generic host either

**Comment by dotnetjunkie** [comment]
You came to tge right place. There's a beta for you to try and feedback on. For more info, see: https://github.com/simpleinjector/SimpleInjector/issues/639#issuecomment-485453641

**Comment by Nekromancer** [comment]
Sorry, i seem to be very bad at searching information today. I'll try it out and give you some feedback on linked issue. Thanks!

**Comment by dotnetjunkie** [comment]
Cool. Thanks!
