### ISSUE TITLE
Register overload for registering all implementations in a single registration

### ISSUE THREAD

**Issue by qujck** [simpleinjector/SimpleInjector#72]
What are your thoughts on having an overload that can automatically register all implementations in a class within the same `Registation`, and thereby avoiding *torn lifestyle*?

[Inspired by this question](http://stackoverflow.com/q/31186121/1515209)

**Comment by dotnetjunkie** [comment]
Can you show an example of what you're trying to achieve here?

**Comment by qujck** [comment]
I don't have my own use case

```csharp
var container = new Container();

var registration = Lifestyle.Singleton.CreateRegistration<FooBar>(container);

container.AddRegistration(typeof(IFoo), registration);
container.AddRegistration(typeof(IBar), registration);

container.Verify();
```

**Comment by dotnetjunkie** [comment]
But this is what we already can do. Can you show some pseudo code of what you think should be possible?

**Comment by qujck** [comment]
```csharp
container.RegisterAllImplementationsAsOne<FooBar>(LifeStyle.Singleton);
```

**Comment by dotnetjunkie** [comment]
Problem with this is that it's very implicit. In the first example, you explicitly register both `IFoo` and `IBar`. In the second example you register all interfaces that `FooBar` implements. This can be more than `IFoo` and `IBar`, and just adding an interface to `FooBar` will cause the configuration to change. I know some DI libraries have this behavior, but this isn't something that fits the Simple Injector API that likes things to be explicit.

**Comment by dotnetjunkie** [comment]
This method is easily added as follows:

``` c#
public static void RegisterAllImplementationsAsOne<TImplementation>(this Container container,
    Lifestyle lifestyle) {
    var registration = lifestyle.CreateRegistration<TImplementation>(container);
    foreach (Type interfaceType in typeof(TImplementation).GetInterfaces()) {
        container.AddRegistration(interfaceType, registration);
    }
}
```
