### ISSUE TITLE
Windows Froms Docs Don't Work

### ISSUE THREAD

**Issue by matt-lethargic** [simpleinjector/SimpleInjector#723]
**Describe the bug**
When following the Windows Forms Integration Guide I get lifestyle exception

**Expected behavior**
It just works

**Actual behavior**
Exception thrown on .Verify

The configuration is invalid. The following diagnostic warnings were reported:
-[Disposable Transient Component] MainForm is registered as transient, but implements IDisposable.
See the Error property for detailed information about the warnings. Please see https://simpleinjector.org/diagnostics how to fix problems and how to suppress individual warnings.

**To Reproduce**
Follow [integration guide to the letter](https://simpleinjector.readthedocs.io/en/latest/windowsformsintegration.html)

leaving out 

    container.Register<IUserRepository, SqlUserRepository>(Lifestyle.Singleton);
    container.Register<IUserContext, WinFormsUserContext>();

**Comment by dotnetjunkie** [comment]
You can follow [this guide](https://stackoverflow.com/questions/38417654/winforms-how-to-register-forms-with-ioc-container/38421425#38421425) and ignore the warning as follows:

``` c#
container.RegisterForm<Form1>();
container.RegisterForm<Form2>();
container.RegisterForm<Form3>();

// Where RegisterForm is the following extension method:
public static void RegisterForm<TForm>(this Container container) where TForm : Form
{
    var registration = Lifestyle.Transient.CreateRegistration<TForm>(container);
    container.AddRegistration(typeof(TForm), registration);
    registration.SuppressDiagnosticWarning(DiagnosticType.DisposableTransientComponent);
}
```
