### ISSUE TITLE
Allow resolving types with unregistered optional dependencies

### ISSUE THREAD

**Issue by chivandikwa** [simpleinjector/SimpleInjector#724]
I just discovered that Simple Injector cannot resolve dependencies that have an unregistered optional dependency in it's ctor. For example:

``` c#
internal interface ISample { }

internal class Sample : ISample
{
    public Sample(Dictionary<string, string> junk = null) { }
}

class Program
{
    static void Main(string[] args)
    {
        var container = new Container();

        container.Register<ISample, Sample>();

        container.Verify();
    }
}
```

Here because the container is not aware of the type `Dictionary<string, string>` it fails on verify. However because the dependency is nullable should Simple Injector not be able to resolve this? Naturally I expected this would be handled but wondering if this clashes with some design decisions of Simple Injector.

**Comment by dotnetjunkie** [comment]
> However because the dependency is nullable should SimpleInjector not be able to resolve this

This is a very explicit design decision. A constructor declares a component's required dependencies. It therefore doesn't make sense to make a required dependency optional. Instead of making dependencies optional, a better solution is to apply the Null Object pattern.
