### ISSUE TITLE
Integrating Simple injector with polly policies  

### ISSUE THREAD

**Issue by DanielLebon** [simpleinjector/SimpleInjector#729]
Hi, 
I have a question about the good way to use [Polly](https://github.com/App-vNext/Polly) with Simple Injector.

I was thinking of doing it in the following way:

**a) create all my Polly policies in a simple class like so:**

``` c#
public class Policies
{
    public readonly RetryPolicy<HttpResponseMessage> InternalServerErrorPolicy;
    public readonly RetryPolicy<HttpResponseMessage> RequestTimeoutPolicy;
    public Policies()
    {
        InternalServerErrorPolicy = Policy.HandleResult<HttpResponseMessage>(
           r => r.StatusCode == HttpStatusCode.InternalServerError)
           .WaitAndRetryAsync(3, retryAttempt => TimeSpan.FromSeconds(retryAttempt));
        RequestTimeoutPolicy = Policy.HandleResult<HttpResponseMessage>(
            r => r.StatusCode == HttpStatusCode.RequestTimeout)
            .WaitAndRetryAsync(3, retryAttempt => TimeSpan.FromSeconds(Math.Pow(0.2, retryAttempt)));
    }
}
```

**b) Register policies in simpleinjector with something like this :**

``` c#
container.Register< Policies>();
```

**c) Use Policies as a constructor parameter**

``` c#
public class MyService
{
    private readonly Policies _policies;
    public MyService(Policies policies)
    {
        _policies = policies;
    }
```

Is this a good way to do it, can this work?

Thank you for your help.

**Comment by dotnetjunkie** [comment]
Can you explain why you want to *inject* the `Policies` class into Simple Injector? Why not do the following:

``` c#
public static class Policies
{
    public static readonly RetryPolicy<HttpResponseMessage> InternalServerErrorPolicy =
        Policy.HandleResult<HttpResponseMessage>(
           r => r.StatusCode == HttpStatusCode.InternalServerError)
           .WaitAndRetryAsync(3, retryAttempt => TimeSpan.FromSeconds(retryAttempt));

    public static readonly RetryPolicy<HttpResponseMessage> RequestTimeoutPolicy =
        Policy.HandleResult<HttpResponseMessage>(
            r => r.StatusCode == HttpStatusCode.RequestTimeout)
            .WaitAndRetryAsync(3, retryAttempt => TimeSpan.FromSeconds(Math.Pow(0.2, retryAttempt)));
}

public class MyService
{
    private readonly IOtherDependency dep;
    public MyService(IOtherDependency dep)
    {
        _dep = dep;
    }

    public void DoSomethingUsefull()
    {
        // Use policy
        Policies.InternalServerErrorPolicy.
    }
}
```

What is it that want you to inject the policy into your service's constructor?

**Comment by DanielLebon** [comment]
Hi dotnetjunkie
Thank you for your reply.
Yes in Static indeed it will certainly work.
Just for my understanding, if the static mode can be used to do the dependency injection,  is it recommended to do it without going through the container as Simpleinjector  ?

**Comment by dotnetjunkie** [comment]
> if the static mode can be used to do the dependency injection

The use of statics is *not* an application of Dependency Injection. You don't have to use Dependency Injection in every occassion. Dependency Injection is especially useful as technique on Volatile Dependencies. A Volatile Dependency is a dependency that you wish to be able to replace, mock, or Intercept, without having to change the original source code.

In your case, however, `MyService` was already *tightly coupled* with both the `Policies` class and the Polly classes. Injecting it would not help you much. That wouldn't reduce the amount of tight coupling.

Another option is to inject an `RetryPolicy<HttpResponseMessage>` directly into `MyService`'s constructor, although I'm not sure this is a sensible thing to do with Polly (I'm not that familiar with the library). It still causes tight coupling to Polly, but would allow you to change the policy from inside your [Composition Root](https://mng.bz/K1qZ) without having to touch (or even recompile) the other modules in your application. This can be especially useful when you load the exact policy from a configuration file, as you only want the final application (i.e. the Composition Root) to take a dependency on the configuration file.

Injecting an `RetryPolicy<HttpResponseMessage>`, however, would complicate Simple Injector's configuration as you will likely have multiple services depending on the exact same type, but do require different policies on each of them. In Simple Injector, this can be achieved by using `RegisterConditional`.

**Comment by DanielLebon** [comment]
Hi dotnetjunkie,
Thank you for this very clear and enriching analysis
