### ISSUE TITLE
Alternative given in ObsoleteAttribute of RegisterMvcControllers wrong

### ISSUE THREAD

**Issue by bender2k14** [simpleinjector/SimpleInjector#730]
**Describe the bug**
I think I found a mistake in the documentation.

The code in [this `ObsoleteAttribute`](https://github.com/simpleinjector/SimpleInjector/blob/master/src/SimpleInjector.Integration.AspNetCore.Mvc.Core/SimpleInjectorAspNetCoreMvcIntegrationExtensions.cs#L31) is supposed to tell you the preferred alternative.  It also links to [this page](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html) that contains more details.

**Expected behavior**
The linked page shows that the correct code should be
```
services.AddSimpleInjector(container, options =>
    options.AddAspNetCore().AddControllerActivation());
```

which compiles for me.  I expected the text in the `ObsoleteAttribute` to correctly tell me this preferred alternative.

**Actual behavior**
The `ObsoleteAttribute` suggests this alternative
```
services.AddSimpleInjector(container, options =>
    options.AddControllerActivation());
```

but this doesn't compile for me.

**Comment by bender2k14** [comment]
I think the other two `ObsoleteAttribute`s in that file have the same problem.

I can create a PR to resolve this issue.

**Comment by dotnetjunkie** [comment]
Created [bug-730 branch](https://github.com/simpleinjector/SimpleInjector/tree/bug-730).

**Comment by dotnetjunkie** [comment]
Hi @bender2k14,

Thank you for reporting this and thank you for suggesting sending a PR. A PR won't be needed though, as I already pushed a fix. This fix will be release to the next patch or minor release (what comes first).

Thanks again for taking the time to report this.
