### ISSUE TITLE
TypeFactoryContext.Consumer changed from null to System.Object in v4.5.1 and later versions

### ISSUE THREAD

**Issue by mpickers** [simpleinjector/SimpleInjector#734]
In v4.4.3, when using `RegisterConditional` the `TypeFactoryContext.Consumer` could be null when there was no consumer, however, versions of Simple Injector after v4.4.3 seem to contain an ImplementationType of System.Object with Target.Name of 'Chars' which doesn't seem correct.

I've checked the existing bug reports and release notes but there doesn't seem to be a mention of a reported issue or expected change in behavior.

Example to reproduce:
Create a new console app with the below code. Run with v4.4.3 and then v4.6.0 of SimpleInjector nuget.

``` c#
   class Program
   {
      static void Main(string[] args)
      {
         var con = new Container();

         con.RegisterConditional(
            typeof(ILogger),
            // As of v4.5.2 c.Consumer is never null and instead the 
            // ImplementationType contains System.Object
            c => typeof(MyLogAdapter<>).MakeGenericType(
               c.Consumer == null 
               ? typeof(Program) 
               : c.Consumer.ImplementationType),
         Lifestyle.Singleton,
         c => true);

         var noConsumerLogger = con.GetInstance<ILogger>();

         noConsumerLogger.Info("No Consumer.");

         var consumer = con.GetInstance<MyConsumer>();

         consumer.WriteToLog("I have a consumer");
      }
   }

   public interface ILogger
   {
      void Info(string msg);
   }

   public class MyLogger : ILogger
   {
      private readonly Type _type;

      public MyLogger(Type type)
      {
         _type = type;
      }

      public void Info(string msg)
      {
         Debug.WriteLine($"{_type.Name}: {msg}");
      }
   }

   public class MyLogAdapter<T> : ILogger
   {
      private readonly MyLogger _adaptee = new MyLogger(typeof(T));

      public void Info(string msg)
      {
         _adaptee.Info(msg);
      }
   }

   public class MyConsumer
   {
      private ILogger _logger;

      public MyConsumer(ILogger logger)
      {
         _logger = logger;
      }

      public void WriteToLog(string msg)
      {
         _logger.Info(msg);
      }
   }

```

Output for v4.4.3 of SimpleInjector
_**Program**_: No Consumer.
MyConsumer: I have a consumer

Output for v4.6.0 of SimpleInjector
_**Object**_: No Consumer.
MyConsumer: I have a consumer

**Comment by dotnetjunkie** [comment]
Thank you for reporting this. I can confirm your findings. This seems to be a bug introduced in v4.5.2. I will investigate the cause of this, and create v4.5.3 and v4.6.1 patch releases to fix this.

In the meantime, you can use v4.5.1.

I'm sorrry this bugs slipped through the cracks. There seems to be a unit test missing in this regard.

**Comment by dotnetjunkie** [comment]
I just release v4.5.3 and v4.6.1. Both versions fix the bug.

**Comment by mpickers** [comment]
No Problem and thanks for the quick turnaround!
