### ISSUE TITLE
Mark Obsolete messages as error in v4.7

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#736]
There are several classes and members that are marked with an `ObsoleteAttribute`. Some of them are marked with `error: false` while describing they will be set as `error: true` from version v4.7 and up.

**Comment by dotnetjunkie** [comment]
[feature-736](https://github.com/simpleinjector/SimpleInjector/tree/feature-736) branch created.

**Comment by dotnetjunkie** [comment]
Also fix the messages of the following members:

* `AdvancedExtensions.GetItem`
* `BehaviorDeprecationExtensions.BuildExpression`

They miss a space in their message.

**Comment by singh-manvinder** [comment]
Hi,
Should the unit tests of these obsolete methods also be removed as they causing build error because of error = true?

**Comment by dotnetjunkie** [comment]
@singh-manvinder

It depends. There are basically two option:

* Error=true on functionality that is still implemented.
* Error=true on removed functionality, e.g. throwing a InvalidOperationException.

Sometimes, features keep implemented, even though we let the C# compiler give a compile error. This allows older integration libraries (built by others) that depend on that feature to keep working, while you allow new development to stop using that feature. This is a strategy I don't often use btw.

But as long as the feature is implemented, unit tests are warranted, although, since the feature is ready to be removed, unit tests could theoretically be removed, although that risks introducing breaking changes on code that might still be used by other libraries.

In case the feature is no longer implemented, the solution is simple: remove the unit tests.
