### ISSUE TITLE
MSDN links in ReferenceLibrary are broken, point to msdn2.microsoft.com

### ISSUE THREAD

**Issue by abatishchev** [simpleinjector/SimpleInjector#738]
**Describe the bug**

Links to the built-in types, such as `System.Predicate`, point to MSDN and are broken. msdn2 was shutdown years ago.

**Expected behavior**

Links point to modern docs.microsoft.com, such as https://docs.microsoft.com/en-us/dotnet/api/system.predicate-1

**Actual behavior**

>The connection has timed out
>The server at msdn2.microsoft.com is taking too long to respond.

**To Reproduce**

Go to https://simpleinjector.org/ReferenceLibrary/html/M_SimpleInjector_Container_RegisterDecorator.htm and click on link http://msdn2.microsoft.com/en-us/library/bfcke1bz

**Comment by dotnetjunkie** [comment]
Reference documentation is generated with Sandcastle and @ewsoftware's pretty amazing SHFB (Sandcastle Help File Builder). During a build of the documentation, SHFB contacts a Microsoft API to request a documentation URL for a given type. It seems that Microsoft's API still returns links to msdn2.microsoft.com, while that site is deprecated, as you rightfully noticed.

Unfortunately, I have no idea how to fix this.

**Comment by EWSoftware** [comment]
msdn2.microsoft.com was working and just redirected to the new site.  If you drop the "2" and just use msdn.microsoft.com in the URLs, it still works and redirects.  The MTPS content service used to look up the IDs was down a couple of weeks ago but is back up again so this may be a temporary issue unless they really have shut it down for good.  

I do plan on updating it to [use the new docs site](https://github.com/EWSoftware/SHFB/issues/707), but no firm release date for such a feature update.

**Comment by dotnetjunkie** [comment]
Hi Eric,

Thanks for chiming in. Much appreciated and happy to hear you're still improving SHFB.

**Comment by abatishchev** [comment]
If you'll need help with MTPS or Docs, I'm happy to try to find internal contacts and get traction/prioritization.

**Comment by EWSoftware** [comment]
I see that msdn2.microsoft.com came back up again earlier this week.  I've been working on replacing the current URL resolver with one that uses the new one for docs.microsoft.com and it'll be in the next release.  I'll probably release it in a week or so.

**Comment by dotnetjunkie** [comment]
That's awesome. Thanks for your hard work.

**Comment by EWSoftware** [comment]
The new SHFB release is available.

**Comment by dotnetjunkie** [comment]
@abatishchev, I will upload updated of the reference library with the next minor release of Simple Injector.
