### ISSUE TITLE
How to register DynamicProxy as decorator?

### ISSUE THREAD

**Issue by abatishchev** [simpleinjector/SimpleInjector#739]
Hello,
This is a proposal to take another look on the idea discussed and rejected several years ago at #61.

Here's my scenario. Right now I'm having the following chain of decorators:

```c#
container.Register<IDeploymentService, DeploymentService>();
container.RegisterDecorator<IDeploymentService, MultiTenantDeploymentServiceDecorator>();
container.RegisterDecorator<IDeploymentService, LoggingDeploymentServiceDecorator>();
```

General case: I'd like to do is to insert to the chain a decorator which type is _not known at the registration time_, can't be specified as generic type parameter. My particular case: the decorator/its type would be a proxy generated by [Castle DynamicProxy](https://github.com/castleproject/Core/blob/master/docs/dynamicproxy.md) in the runtime:

```c#
// registrations are same as before

container.RegisterDynamicDecorator<IDeploymentService>(Lifestyle.Singleton);

// registrations are same as before
```

The implementation of the extension method from above:

```c#
public static void RegisterDynamicDecorator<TService>(
    this Container container, Lifestyle lifestyle)
{
    Type interfaceType = typeof(TService);
    TService target = ???;
    var proxyGenerator = new ProxyGenerator();
    var proxy = proxyGenerator.CreateInterfaceProxyWithTarget(
        interfaceType,
        target,
        new ProxyGenerationOptions(),
        new ContainerInstanceInterceptor<TService>(_container));
    var decoratorType = proxy.GetType();
    container.RegisterDecorator(typeof(TService), decoratorType, lifestyle);
}
```

But it doesn't work, throws an exception: target cannot be null.

The generator from above would generate a decorator almost perfectly suiting the Simple Injector needs/requirements (the code is mine, based on my understanding what's getting generated):

```c#
class DeploymentServiceDynamicProxy : IDeploymentService
{
    public DeploymentServiceDynamicProxy (
        IEnumerable<IInterceptor> interceptors, IDeploymentService target)
        _target => target;

    public StartDeploymentResponse StartDeployment(StartDeploymentRequest request) =>
        _target.StartDeployment(request);
}
```

If only I could provide `target` in the registration time. But currently there is no overload such as:
- `RegisterDecorator<TService>(Func<TService, TService> decoratorSelector)`
- or rather `RegisterDecorator<TService>(Func<TService, Type> decoratorTypeSelector)`.

If that's not technically feasible still today, another option might be supporting `Expression<Func<TService, Type>>`. I'm not familiar with the exact Simple Injector internals but I see that already there is the [overload](https://simpleinjector.org/ReferenceLibrary/html/M_SimpleInjector_Container_RegisterDecorator.htm) having `Func(DecoratorPredicateContext, Type)` which parameter `DecoratorPredicateContext` has `Expression`.

But today it's read-only and, as I understand, is used to make the decision whether to return true or false from this method. Would be great if I could compose it myself and return for the container's consumption.

**Comment by dotnetjunkie** [comment]
Would it change for you to change the call from `CreateInterfaceProxyWithTarget` to `CreateInterfaceProxyWithTargetInterface`? As in:

``` c#
public static void RegisterDynamicDecorator<TService>(
    this Container container, Lifestyle lifestyle)
{
    var proxyGenerator = new ProxyGenerator();
    var proxy = proxyGenerator.CreateInterfaceProxyWithTargetInterface(
        typeof(TService),
        default(TService),
        new ProxyGenerationOptions(),
        new ContainerInstanceInterceptor<TService>(_container));
    var decoratorType = proxy.GetType();
    container.RegisterDecorator(typeof(TService), decoratorType, lifestyle);
}
```

`CreateInterfaceProxyWithTargetInterface` accepts the supplied `target` to be `null`, while generating a type with the following constructor: `ctor(IInterceptor[], TService)`.

Does this solve your needs?

**Comment by dotnetjunkie** [comment]
One warning about your code though. Please be aware that `ProxyGenerator` should typically be created once per AppDomain. Creating it once for every method call might lead to performance problems.

**Comment by dotnetjunkie** [comment]
What I'm wondering, though, is why you are trying to use the decorator sub system to apply dynamic interception? When using [this guidance](https://stackoverflow.com/questions/24513530/using-simple-injector-with-castle-proxy-interceptor), you can simply do the following:

``` c#
container.InterceptWith<ContainerInstanceInterceptor<TService>>(
    type => /* some condition */);
```

**Comment by dotnetjunkie** [comment]
And that said, in the situation where `RegisterDecorator` is too limited, you can fall back to `ExpressionBuilt`, as shown in [this example](https://stackoverflow.com/questions/24513530/using-simple-injector-with-castle-proxy-interceptor) that adds interception abilities.

**Comment by abatishchev** [comment]
>Would it change for you to change the call from CreateInterfaceProxyWithTarget to CreateInterfaceProxyWithTargetInterface?

Thanks a lot! That's exactly what has resolved the issue I was facing.

> When using [this guidance](https://stackoverflow.com/questions/24513530/using-simple-injector-with-castle-proxy-interceptor), you can simply do the following

This is eve better!

> And that said, in the situation where RegisterDecorator is too limited

Nonetheless, what do you think about extending the RegisterDecorator API? I was google and found a number of time an ask to add something like  `RegisterDecorator<TService>(Func<TService, Type> decoratorTypeSelector)` and/or `RegisterDecorator<TService>(Func<TService, TService> decoratorSelector)`

**Comment by dotnetjunkie** [comment]
> Nonetheless, what do you think about extending the RegisterDecorator API?

This is a direction I very deliberately steered Simple Injector away from in the last few major releases. Where in the beginning the API mostly allowed delegate registrations, in later releases, old delegate APIs where slowly removed and new features not always include `Func<T>` registration APIs. Delegate-based APIs blind Simple Injector's ability to verify the user's object graphs, which is the most prominent reason why I tend to exclude them.

This holds for the decorator sub system as well. I won't be including them.

This, of course, sometimes means that you have to change the way you approach things, but generally it's for the better. I haven't come across a scenario that couldn't be refactored to actually work on Simple Injector's API.
