### ISSUE TITLE
Integrating with ASMX web services in ASP web forms application

### ISSUE THREAD

**Issue by simmohall** [simpleinjector/SimpleInjector#74]
Hi guys,
First up, fantastic product, been using for a while in some projects with great success.

Just a question, as i'm trying to integrate some of the features into an older webforms application. I've followed the ASP.NET Web Forms Integration Guide successfully and works great with the web pages, but haven't been able to wire up the script asmx webservices in the same way. Just wondering if it's possible at all? I allowed the "System.Web.Extensions" in the Init module but gave me an exception below.

"Additional information: No registration for type ScriptHandlerFactory.HandlerWrapperWithSession could be found and an implicit registration could not be made. 
For the container to be able to create ScriptHandlerFactory.HandlerWrapperWithSession, it should contain exactly one public constructor, but it has 0."

Thanks,
Simon

**Comment by dotnetjunkie** [comment]
Hi Simon,

ASAK, you can't easily do this with asmx web services. Best thing is to make your web service a [Humble Object](http://xunitpatterns.com/Humble%20Object.html) by extracting all the logic and it dependencies into a different component and registering this new component in the container. After that, there should only be two lines of code left in your web service, i.e.
- A call to the container to resolve that new component.
- A call to the method of that resolved component that will handle the request.

**Comment by simmohall** [comment]
Ok thanks. Makes sense.
