### ISSUE TITLE
Breaking change between 4.6.2 and 4.7.0

### ISSUE THREAD

**Issue by fanc-mso** [simpleinjector/SimpleInjector#746]
After updating the different SimpleInjector libraries from 4.6.2 to 4.7.0, this code no longer works in Startup.cs of a ASP.NET MVC Application (.NET Framework 4.7.2):

`container.RegisterMvcControllers(Assembly.GetExecutingAssembly());`

It throws error 

> System.ArgumentNullException: 'assemblies
> Parameter name: The supplied elements in the array can't be null.'

I've tested Assembly.GetExecutingAssembly() and it's obviously not null so not sure what's causing this.

If I revert back to SimpleInjector 4.6.2 it works again.

Many thanks for looking into this or for providing me with an alternate solution to register my MVC Controllers.

**Comment by dotnetjunkie** [comment]
Thank you for reporting this. This is indeed a regression that unfortunately happened while adding C# 8 support.

**Comment by dotnetjunkie** [comment]
I pushed patch release v4.7.1 to NuGet. It should be available for you to download within the next hour.

**Comment by fanc-mso** [comment]
Many thanks for the quick fix


Mathieu SOUPHY
Applications Administrator

Federaal Agentschap voor Nucleaire Controle
Ravensteinstraat 36 - 1000 Brussel
T +32 2 289 20 67
M +32 486 53 07 66
E Mathieu.Souphy@fanc.fgov.be<mailto:Mathieu.Souphy@fanc.fgov.be>
www.fanc.fgov.be

**Comment by fanc-mso** [comment]
Many thanks for the quick fix
