### ISSUE TITLE
Injecting ILogger<T> in Azure Functions throws an Exception

### ISSUE THREAD

**Issue by ahocquet** [simpleinjector/SimpleInjector#749]
In an Azure Function, an instance of `ILogger` is injected in the functions themselves. But I would like to inject an instance of `ILogger` / `ILogger<T>` / `ILoggerFactory` in my components registered with SimpleInjector. Doing so results in the following exception:

> 
System.Private.CoreLib: Exception while executing function: TestGenericLogger. 
SimpleInjector: The registered delegate for type ILogger<GenericSpeaker> threw an exception. 
Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IFileLoggingStatusManager' while attempting to activate 'Microsoft.Azure.WebJobs.Script.Diagnostics.HostFileLoggerProvider'. 
Microsoft.Extensions.DependencyInjection: Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IFileLoggingStatusManager' while attempting to activate 'Microsoft.Azure.WebJobs.Script.Diagnostics.HostFileLoggerProvider'.

The full example can be found on this repo: https://github.com/ahocquet/simple-injectore-af-logging

Here's a sample of my code:
```csharp
[FunctionName("TestGenericLogger")]
public static IActionResult TestGenericLogger(
	[HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]
	HttpRequest req,
	ILogger log)
{
	DIConfig.Container.GetInstance<GenericSpeaker>().SayHello();

	return new OkResult();
}
```

The registration process looks like this:
```csharp
public static class DIConfig
{
	public static readonly Container Container = new Container();

	public static void Init(IServiceCollection serviceCollection)
	{
		serviceCollection.AddSimpleInjector(Container);

		Container.Register<Speaker>();
		Container.Register<GenericSpeaker>();
		Container.Register<FactorySpeaker>();

		serviceCollection.BuildServiceProvider()
						 .UseSimpleInjector(Container);
	}
}
```

The dependency injection using `IServiceCollection` works great for `ILogger<T>` and `ILoggerFactory`. Therefore, there *must* be a way to crosswire the `ILoggerFactory` / `ILogger<T>`.

I could apply a composition root pattern and use an entry point in all my functions that will set the `ILogger` instance within a `LoggingWrapper` service. That would work, but that would let me unsatisfied. 🤔

**Comment by dotnetjunkie** [comment]
Be careful with the static `Logger` property in `AzureFunctionLogger`. Are you sure the application is single threaded? Otherwise you must, for the very least, change it to use `AsyncLocal<ILogger>` instead.

**Comment by ahocquet** [comment]
My application is not single-threaded as it's an Azure Function. But I thought that ILogger/ILogger<> were threadsafe because they're registered as a singleton in [MS DI AddLogging() extension method](https://github.com/aspnet/Extensions/blob/f162f1006bf8954f0102af8ff98c04077cf21b04/src/Logging/Logging/src/LoggingServiceCollectionExtensions.cs):
```csharp
services.TryAdd(ServiceDescriptor.Singleton(typeof(ILogger<>), typeof(Logger<>)));
```

But probably I'm all wrong and a static field isn't thread/context safe? In this case, I would appreciate if you can share some details about why it's wrong 🧐

**Comment by dotnetjunkie** [comment]
Supposedly, every function gets its own contextual logger instance. I would expect this, because what you're doing would otherwise make little sense. I  that case you should just register a single logger and inject that directly into all consumers.

So assuming that the function's logger is contextual,when you store that in a static field, you might be accidentally providing the logger of one request/function to another. Yes, loggers will be thread safe, so this will not break with weird exceptions. However, you will from time to time likely see log messages be written as if they come from a different request/function. This is unlikely what you want.

**Comment by ahocquet** [comment]
Oh, I see! That makes sense.

Anyway, even though I was able to register an `ILogger` instance within SimpleInjector Container, I now have another issue to resolve an `IHttpClientFactory`. This one also has a dependency on `IFileLoggingStatusManager`. I guess this one is going to be much harder to solve, and maybe it's time to let go Simple Injector with Azure Functions for the moment. :(

Anyway, thanks for your help!  🎉

**Comment by dotnetjunkie** [comment]
I created a new [Azure Functions Integration](https://simpleinjector.org/azurefunctions) page. This demonstrates how to integrate Simple Injector with  Azure Functions v3.

**Comment by OzBob** [comment]
@ahocquet v3 AzFn has more DI support, here is an example of using a HttpCLient
https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#use-injected-dependencies

The [AzFn Docs ILogger advice](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#iloggert-and-iloggerfactory) is: 

```
 private readonly ILogger<HttpTrigger> _log;

        public HttpTrigger(ILogger<HttpTrigger> log)
        {
            _log = log;
        }

        [FunctionName("HttpTrigger")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req)
        {
            _log.LogInformation("C# HTTP trigger function processed a request.");

            // ...
```
and the notes say to add a logging section to the host.json
