### ISSUE TITLE
Improve the error message when ExecutionContextScopeLifestyle should be used

### ISSUE THREAD

**Issue by qujck** [simpleinjector/SimpleInjector#75]
Current:

> Additional information: It is not safe to use a LifetimeScope instance across threads. Make sure the complete operation that the lifetime scope surrounds gets executed within the same thread and make sure that the LifetimeScope instance gets disposed on the same thread as it gets created. Dispose was called on thread with ManagedThreadId 27, but was created on thread with id 21.

Suggested:

> Additional information: It is not safe to use a LifetimeScope instance across threads. The LifetimeScope instance was Disposed on thread id 27 but was created on thread id 21. Consider switching to ExecutionContextScopeLifestyle (https://simpleinjector.readthedocs.org/en/latest/lifetimes.html#per-execution-context-scope-async-await).

**Comment by dotnetjunkie** [comment]
Good suggestion. 

I would suggest the following:

> It is not safe to use a LifetimeScope instance across threads. The LifetimeScope instance was Disposed on thread id 27 but was created on thread id 21. Make sure the complete operation that the lifetime scope surrounds gets executed within the same thread and make sure that the LifetimeScope instance gets disposed on the same thread as it gets created. In case your intention is to create a scope that flows with the logical flow of control of asynchronous methods, please switch to the ExecutionContextScopeLifestyle (https://simpleinjector.org/await).
