### ISSUE TITLE
Learning Simple-Injector

### ISSUE THREAD

**Issue by bkea** [simpleinjector/SimpleInjector#752]
Question:  I'm learning more about DI and I've choose simple-injector as my library of choice.  I've also been tasked with comparing it to another DI library for use in our office.

I've written my first application that uses DI and simple-injector.  I was wanting to know if I coded this correctly.  Hence, do I have a good understanding of using the tool.

[My First.zip](https://github.com/simpleinjector/SimpleInjector/files/3648692/My.First.zip)

**Comment by dotnetjunkie** [comment]
Hi bkea,

Great to hear you choose Simple Injector as your DI library of choice. Unfortunately, as it currently stands, your question is too broad. Please read [the documentation](https://simpleinjector.org/wiki). If you have any *specific* questions after reading the documentation, feel free to ask here. In that case, make sure you follow the question issue template, and add the minimum, but complete code examples, and prevent uploading complete project examples or or linking to external sources. Your question as-is should be able to stand on its own.

Good luck.
