### ISSUE TITLE
SimpleInjector 4.7.2 was not published to NuGet

### ISSUE THREAD

**Issue by mattzink** [simpleinjector/SimpleInjector#753]
Looking at https://www.nuget.org/packages/SimpleInjector/ and the latest release (4.7.2) does not seem to be available.

**Comment by mattzink** [comment]
Not sure why this got labeled as a question

**Comment by dotnetjunkie** [comment]
4.7.2 only contqins changes to the SimpleInjector.Integration.AspNetCore.Mvc package so that's the only one that got a version bump. That package depends on core library 4.7.1.

**Comment by dotnetjunkie** [comment]
But considering the extra amount of work it takes to release a single package opposed to *all* packages, this is likely the last time you see this happening. For future v4.x releases you'll likely see all packages being updated, even when only a single package gets changed.

For v5 we are changing this and instead let all packages have an independent minor version number that only changes when that specific package changes.

**Comment by dotnetjunkie** [comment]
For more information on this, see: 
https://github.com/simpleinjector/SimpleInjector/issues/543
