### ISSUE TITLE
Services added with AddHostedService are unable to resolve registrations in ASP.NET Core 3

### ISSUE THREAD

**Issue by sychare** [simpleinjector/SimpleInjector#754]
## Description of the bug
Adding a service with `AddHostedService<T>()` is unable to resolve types registered with Simple Injector in ASP.NET Core 3. The same code worked in 2.2.

Trying to step through the code it appears that services added with `AddHostedService()` are being started (and subsequently resolved) earlier in Core 3 than in 2.2, causing registrations to not yet have been added. The `Startup.Configure()` method is not hit at the time the exception is raised.

Moving the registrations to occur at the end of `ConfigureServices()` doesn't help, as despite it fixing the missing registrations it is not possible to then call `app.UseSimpleInjector()` in `Configure()` as the hosted service being resolved before `Configure()` is called locks the container:

> The container can't be changed after the first call to GetInstance, GetAllInstances, Verify, and some calls of GetRegistration. Please see https://simpleinjector.org/locked to understand why the container is locked. The following stack trace describes the location where the container was locked:

```
at SimpleInjector.Container.GetInstance[TService]()
at SimpleInjector.SimpleInjectorGenericHostExtensions.<>c__DisplayClass0_0`1.<AddHostedService>b__0(IServiceProvider _)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
at Test.Web.Program.Main(String[] args) in E:\projects\test\src\backend\Test.Web\Program.cs:line 14
```

## Expected behavior
Type of `HostedService` is resolved.

## Actual behavior

Exception:

> The container can't be changed after the first call to GetInstance, GetAllInstances, Verify, and some calls of GetRegistration. Please see https://simpleinjector.org/locked to understand why the container is locked. The following stack trace describes the location where the container was locked:

## To Reproduce

Replace the default `Startup` with the following:
 
```csharp
public class HostedService : IHostedService
{
    public Task StartAsync(CancellationToken cancellationToken) => Task.CompletedTask;
    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}

public class Startup
{
    private readonly Container container = new Container();

    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllersWithViews();

        services.AddSimpleInjector(this.container, options =>
        {
            options.AddHostedService<HostedService>();
        });
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.ApplicationServices.UseSimpleInjector(this.container);

        app.UseStaticFiles();

        app.UseRouting();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllerRoute(
                name: "default",
                pattern: "{controller=Home}/{action=Index}/{id?}");
        });
    }
}
```

## Additional context

* Simple Injector 4.7.1
* .NET Core 3

**Comment by dotnetjunkie** [comment]
Crap. Yet another unfortunate breaking change in ASP.NET Core v3. I will investigate this and report back to you when I found a workaround or have a fix available. Might take a few days for me to get to this point though.

**Comment by dotnetjunkie** [comment]
This problem is caused by the behavioral change of the new `Host` class compared to the previous `WebHost` class. I [filed a bug](https://github.com/aspnet/AspNetCore/issues/14585).

As workaround, switch back to using `WebHost` in your `Program.cs` instead of the new `Host`, which is used in the default Visual Studio template. When creating a new ASP.NET Core 3.0 application, the `Program.cs` looks like this:

``` c#
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });
}
```

You should change it to the following:

``` c#
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>();
}
```
The reason this works is because `Host` starts creating hosted services too early in the pipeline, which causes problems for containers like Simple Injector, Castle Windsor, and Ninject, that can't conform to the presented Microsoft container abstraction.

As it currently stands, there is no way for Simple Injector to work around this issue, as this behavior is embedded deeply into the `Host` class.

**Comment by dotnetjunkie** [comment]
I published beta1 release of v4.8 to NuGet that aims to fix this problem. The package marked some methods obsolete and guides you towards the right methods. Do note that the obsolete messages reference the documentation, but the documentation has not yet been updated.

I appreciate any feedback on this.

**Comment by dotnetjunkie** [comment]
[feature-754-v2](https://github.com/simpleinjector/SimpleInjector/tree/feature-754-v2) branch.

**Comment by dotnetjunkie** [comment]
Awesome. Great to hear. Thank you for your input @sychare.

**Comment by dotnetjunkie** [comment]
We just release [Simple Injector v4.8](https://github.com/simpleinjector/SimpleInjector/releases/tag/v4.8), which fixed this.

**Comment by paolopiaggio** [comment]
Hello @dotnetjunkie 
This issue was really helpful as to understand what was happening and why the HostedService registered with:
`services.AddSimpleInjector(this.container, options =>
        {
            options.AddHostedService<HostedService>();
        });`

was driving the HosterService.StartAsync() to be called before the AspNet Core `Configure(IApplicationBuilder app)`, causing then errors on any further container registration because it had already resolved dependencies.

I see this issue has been closed but just wanted to notify that the issue still stands using AspNetCore 3.1 (only using Host, with WebHost it works).

Would it also make sense to add a note in the HostedService Simple injector documentation? It might help other people facing the same issue in the future :)

**Comment by dotnetjunkie** [comment]
Hi @paolopiaggio,

I'm unable to reproduce this using ASP.NET Core v3.1. I'm very interested in learning more about the issue you are having, so I can act accordingly. Would you mind creating a new issue with a minimal reproducible example that demonstrates the bug?

Thanks in advance.

**Comment by paolopiaggio** [comment]
Hi @dotnetjunkie.
thanks for your previous prompt reply 🙂

While I was quickly cooking up a sample application that would have had to reproduce the issue, I realized what was my original mistake: there were some explicit SimpleInjector Container Registration inside the `Configure(IApplicationBuilder app, IWebHostEnvironment env)`.

There's an interesting behavior that I'd like to share though:
```csharp
        // With this => the HostedService is started after Configure Services but before Configure App
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });

        // With this => the HostedService is started after both Configure Services and Configure App
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
```
I am not sure if this is of any interest for anybody :)

Here the app if you want to have a look at it:
https://github.com/paolopiaggio/AspNet31.SimpleInjector.HostedService/tree/master/SampleApp

**Comment by dotnetjunkie** [comment]
Hi @paolopiaggio,

That difference in behavior between `Host` and `WebHost` is the core incombatibility that this issue describes (and explained in [this post](https://github.com/simpleinjector/SimpleInjector/issues/754#issuecomment-536731536)), that I [reported](https://github.com/dotnet/aspnetcore/issues/14585) to Microsoft, and that [Simple Injector v4.8](https://github.com/simpleinjector/SimpleInjector/releases/tag/v4.8) has a fix/workaround for.

In the Simple Injector v4.8 ASP.NET integration, the integration gets notified when ASP.NET starts to resolve from the container before the `Configure` method is called. This allows the integration to do its required last-minute registrations. This allows the integration to succeed, but it doesn't prevent the container from being locked. This is something that can't be prevented. 

I hope this makes sense.

**Comment by paolopiaggio** [comment]
Ohh I see! I had bumped into the issue you filed to Microsoft but I didn't read all the details. 
Now everything is crystal clear :) thanks @dotnetjunkie  for taking time to help me understand this!

Really appreciate it!

**Comment by dotnetjunkie** [comment]
We might be able to improve the error message you are getting when trying to register stuff in Configure, while the container is already locked. But TBH, this can be quite tricky, because that message should only be given when the cause really is that the container is locked because of resolving Hosted Services, while you're inside the `Configure` stage.

**Comment by thirstyape** [comment]
In case others are still having issues after reading this. I used a modified version of the suggestion by @dotnetjunkie from Sep 30, 2019.

    public static void Main(string[] args)
    {
        CreateHostBuilder(args)
            .UseDefaultServiceProvider(options => { })
            .Build()
            .Run();
    }

    public static IWebHostBuilder CreateHostBuilder(string[] args) => WebHost.CreateDefaultBuilder(args).UseStartup<Startup>();

Note the addition of `.UseDefaultServiceProvider(options => { })` in the `Main()` method. Not sure why, but in my .NET Core 3.1.8 web API this was the only way I could find to get `AddHostedService()` to work without throwing an exception.
