### ISSUE TITLE
Provided SignalR integration no longer works with Core 3.0

### ISSUE THREAD

**Issue by CRidge** [simpleinjector/SimpleInjector#757]
Not posting this as a bug, as it isn't a problem with Simple Injector as such.

The problem is related to #631 (how to integrate with SignalR Core - which is closed for external comment), which has served me well for some time now. Unfortunately, the provided code no longer works with 3.0 of the framework:

The classes `HubDispatcher` and `DefaultHubDispatcher` are now internal, and from what I can see, they are no longer used via DI. So, even if I were able to inject a custom implementation, it wouldn't be used. 

There is an issue on the SignalR Core repo: https://github.com/aspnet/AspNetCore/issues/14247 - but I'm not holding my breath, as it talks about a fix in version 5.0 😮 

I can't see a way to work around this easily, but at least the original issue should be updated with information about it no longer working for 3.0 😞

**Comment by dotnetjunkie** [comment]
Hi @CRidge,

I updated the [SignalR Core integration page](https://github.com/simpleinjector/SimpleInjector/issues/631). This should (mostly) do the trick for integrating SignalR core.

There might be some corner cases where this integration is too simplistic, and might not work, such as:

* Registering your `Hub` derivates with the `Transient` lifestyle. `Hub` implements `IDisposable`, which causes Simple Injector to warn about [disposable transient components](https://simpleinjector.org/diadt). You should either suppress the warning, or register your hub as `Scoped`.
* As David [pointed out](https://github.com/aspnet/AspNetCore/issues/14247#issuecomment-561495767) on the ASP.NET Core forum, "long polling and non-http SignalR" scenarios might not work with this simplistic activator.

In the future I will add an SignalR Core integration package that fixes these limitations.

**Comment by dotnetjunkie** [comment]
The introduction of Simple Injector v4.9 simplified the integration with SignalR Core. I updated the [SignalR Core integration page](https://github.com/simpleinjector/SimpleInjector/issues/631) accordingly.

**Comment by patrickdoodyIRL** [comment]
Hi,

The example on [https://github.com/simpleinjector/SimpleInjector/issues/631]#631 does not compile with the latest SimpleInjector - 4.9.1. The there is no overload on the Container.Register method that accepts a Type and Lifestyle.

The nearest overloads all require an instanceCreator delegate which is not provided in the example.

**Comment by dotnetjunkie** [comment]
Hi Patrick, thank you for reporting is. I updated the code.
