### ISSUE TITLE
IHttpClientFactory and custom HttpClientHandler with dependencies registered in SI

### ISSUE THREAD

**Issue by matt-lethargic** [simpleinjector/SimpleInjector#758]
Hi I'd like some advice before I go down the wrong path with this.

I'm using `IHttpClientFactory` and the .Net Core DI to create HttpClients, this has worked fine, but now I need to use a certificate for authentication, my solution was to create a `SecureHttpClientHandler` that inherits `HttpClientHandler`. The problem I'm getting is that I'm registering a settings class with Simple Injector and the `SecureHttpClientHandler` with .Net DI and now .Net DI obviously can't find the `SecureClientSettings` class. I don't really want to register the settings class with .Net DI as it'll mean a refactor in a direction I'm not 100% happy with, I was wondering if there's any other way that I'm not aware of?

HttpClientHandler

    public class SecureHttpClientHandler : HttpClientHandler
    {
        public SecureHttpClientHandler(SecureClientSettings settings)
        {
            if (settings == null) throw new ArgumentNullException(nameof(settings));

            var clientCertificatePath = $"Certs/{settings.CertificatePath}";
            var fc = File.ReadAllBytes(clientCertificatePath);

            var clientCert = new X509Certificate2(fc, settings.CertificatePassword);
            ClientCertificates.Add(clientCert);
        }
    }

Settings

    public class SecureClientSettings {
         public string CertificatePath { get; set;}
         public string CertificatePassword { get; set; }
    }

Registering

    services.AddTransient<SecureHttpClientHandler>();
                    services.AddHttpClient("MySecureClient")
                        .ConfigurePrimaryHttpMessageHandler(s => s.GetRequiredService<SecureHttpClientHandler>());

Registering Settings

    _container.RegisterInstance(settings);

Crosswiring

     .UseSimpleInjector(container, options =>
                {
                    options.UseLogging();
                    options.CrossWire<IHttpClientFactory>();
                });

**Comment by dotnetjunkie** [comment]
Since the settings class is a simple DTO with no dependencies of its own, I see no risk in, and no reason in not registering it in the MS.DI configuration system. It needs it.

**Comment by matt-lethargic** [comment]
Yeah I've just done that and found a way to refactor my app that isn't horrible so all this was a little pointless, but thanks for your time.

(And good luck with .Net Core 3 ;-) )
