### ISSUE TITLE
RegisterAll / RegisterCollection with Lifestyles

### ISSUE THREAD

**Issue by AlthalusDGr8** [simpleinjector/SimpleInjector#76]
Is it currently possible to use Container.RegisterAll and pass a lifetime long with these objects or are these always assumed to be transient?

Thanks

**Comment by dotnetjunkie** [comment]
There are multiple ways of configuring the lifestyle of elements of a collection. The two most common (and usually best) ways of doing this are given below.

**Method 1: Register the concrete type explicitly.**
Here two logger implementations are registered. The `SqlLogger` will be resolved as singleton:

``` c#
container.Register<SqlLogger>(Lifestyle.Singleton);
container.RegisterAll<ILogger>(new[] { typeof(SqlLogger), typeof(MailLogger) });
```

**Method 2: Register *Registration* instances.**
Here the `Singleton` lifestyle is asked to create `Registration` instances and those instances are supplied to the `RegisterAll<ILogger>` method.

``` c#
var types = new[] { typeof(SqlLogger), typeof(MailLogger) };
container.RegisterAll<ILogger>(
    from type in types
    select Lifestyle.Singleton.CreateRegistration(type, container));
```

**Comment by joshcobalt** [comment]
Does this still work with new the RegisterCollection() overload and a generic open type?

**Comment by dotnetjunkie** [comment]
Yes it does.
