### ISSUE TITLE
Need support for performance analysis

### ISSUE THREAD

**Issue by ChristianHoe** [simpleinjector/SimpleInjector#760]
Hi,

at work we got complains, that our application is too slow. Therefore I used the Visual Studio Diagnostic Tools. What got me really surprised is, that at startup the bootstrapping caused roughly 25% of the CPU cycles. Which split up in container.Verify() ~5% and service registration ~20%. What completely left me stunned is one service registration causing ~15% of the CPU cycles.
I did some testing. I could reduce the class to something like (from my mind):

``` c#
using Spire.PDF;

public interface ITest
{
  void Method(PdfPageSetupAngle angle);
}
public class Test : ITest
{
  public void Method(PdfPageSetupAngle angle) {};
}
```
With using/removing an enum(!) from the referenced dll as method parameter I could change the costs from 15% to 0% and via versa. Using some other classes from the named dlls did not do anything.
I am completely clueless whats going on and I would like to understand why/what is so costly in this special case . Any help is appreciated.

Regards
Christian

**Comment by dotnetjunkie** [comment]
Please run your test again:

* While compiled in Release mode
* Without a debugger attached.

Debugger and VS can have enourmous negative impact on your test.

For the rest, there is there's not much I can do at this point. I need a specific repro that points to Simple Injector being the problem. If you can supply me with such a specific repro, I can do an analysis to track down the problem.
