### ISSUE TITLE
AddTagHelperActivation incorrectly uses DefaultScopedLifestyle for tag helpers instead of Transient

### ISSUE THREAD

**Issue by ofirgeller** [simpleinjector/SimpleInjector#761]
I have a tag helper that **inherits from a Microsoft tag helper**. before using:
`options.AddTagHelperActivation` inside of  the `AddSimpleInjector` configuration method i would get an instance of the helper per appearance of the tag in the cshtml document. now it seems I am getting the same instance. 

## Expected behavior
Would expect simple injector to behave like the dotnet core framework DI and create an instance per appearance of a tag. or give an option of specifying that it should.

## Actual behavior
The tag helper is registered as a singleton/per request or something similar.

## To Reproduce

``` c#
[HtmlTargetElement(tag: "simple-tag")]
public class SimpleTag : AnchorTagHelper
{
    public override int Order => int.MaxValue;

    public SimpleTag(IHtmlGenerator generator) : base(generator) { }

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        base.Process(context, output);
        output.TagName = "a";
        output.Attributes.SetAttribute("href", $"/something" + output.Attributes["href"].Value);
    }
}
```

If you use the tag helper multiply times, sometimes with an href attribute  and sometimes with an action attribute you will get an exception since you can't have both attributes on the same tag, and since the tag helper will be the same instance if the rendering is in this order:

1) tag with action attribute 
2) tag with href attribute 

you will get an exception when you get to the second tag.

Context:
Container has these settings:

``` c#
container.Options.DefaultLifestyle = Lifestyle.Scoped;
container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
```

Which is the wrong option for the tag helpers, but there is no way to override the lifestyle of the tag helpers that I could find.

**Comment by dotnetjunkie** [comment]
I can confirm this is a bug. I added it to the v4.8 milestone. In the meantime, as a workaround, you can [override the lifetime selection behavior](https://simpleinjector.org/extensibility#overriding-selection-behavior) to ensure that tag helpers always get a transient lifestyle.

**Comment by dotnetjunkie** [comment]
[bug-761](https://github.com/simpleinjector/SimpleInjector/tree/bug-761) branch created.

**Comment by dotnetjunkie** [comment]
We just release [Simple Injector v4.8](https://github.com/simpleinjector/SimpleInjector/releases/tag/v4.8), which fixed this bug.
