### ISSUE TITLE
Custom Lifestyle To Handle Multi Tenant Architecture

### ISSUE THREAD

**Issue by devteamexpress** [simpleinjector/SimpleInjector#764]
Hello!

We are running asp.net with a single code base supporting many clients.
A request comes into the API with a given API Key and based on that we know who the calling client is for that request.

Let's say we need a dependency which is cached as a "singleton" per client, so not a single instance for all clients, and not per request either. What would be the recommended advice as to how to achieve this through IOC? Would a custom lifestyle be a good fit here?

Here is an example class:

public class Service A {
  private HttpClient _client
  public ServiceA(ClientSettings settings){
    _client = new HttpClient();
   _client.AddHeaders("Authorization",settings.APIKey);
  }

}

**Comment by dotnetjunkie** [comment]
Hi Daniel,

As you closed the question, I assume you're no longer interested in any response from our side. If that's not the case, let me know.
