### ISSUE TITLE
Support Grpc.AspNetCore integration

### ISSUE THREAD

**Issue by enif-lee** [simpleinjector/SimpleInjector#776]
Hello there,

Could you have any plan to support with ASP.Net Core gRPC library? 
When start with grpc template, it seems be not working.

References 
- https://docs.microsoft.com/ko-kr/aspnet/core/grpc/?view=aspnetcore-3.0
- https://github.com/grpc/grpc-dotnet

Thank you.
Best Regards,

**Comment by dotnetjunkie** [comment]
>  it seems be not working.

Could you provide me with more details?  For instance:

> * Provide a Minimal, Complete, and Verifiable example that reproduces the problem, illustrates your question, or shows the feature you are missing. (see: https://stackoverflow.com/help/mcve)
> * Show a simplified, but realistic, representation of your application. We are not interested to see a large amount of source code, but DI-related questions are typically design questions and it is impossible to feedback on your design when you reduce your interfaces and classes to e.g. `IFoo`, `Flux` and `Baz`.
> * Include complete stack trace including all exception details of the exception and all inner exceptions in case an exception is thrown.
> * Do ensure that code listing don't have a line width that exceeds 100 characters, as that would cause horizontal scrollbars, which make it harder to view the code.
> * Do not include screen shots of exceptions, but paste the actual exception details (see: https://idownvotedbecau.se/imageofanexception/)
> * Make sure that code and exception details are formatted correctly and ideally include the programming language (typically `c#`). This way GitHub will highlight the code automatically. (see: https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

> (from [the issue template](https://github.com/simpleinjector/SimpleInjector/issues/new?assignees=&labels=question&template=question-and-feature-request.md&title=))

**Comment by enif-lee** [comment]
> Could you provide me with more details? For instance:

I'm sorry that I does not provide details. I attached sample project as below and you can run test code after running api project.

![image](https://user-images.githubusercontent.com/9916002/69689122-71378d80-110b-11ea-993c-8785b748c393.png)
```
System.InvalidOperationException: Unable to resolve service for type 'Grpc.SimpleInjector.Sample.Api.Repository.ISampleRepository' while attempting to activate 'Grpc.SimpleInjector.Sample.Api.GreeterService'.
```

[Grpc.SimpleInjector.Sample.zip](https://github.com/simpleinjector/SimpleInjector/files/3894868/Grpc.SimpleInjector.Sample.zip)

As separately, In my investigation, There seem to be no replaceable point IoC container, Grpc.AspNetCore project is using `ServiceCollection` directly in there internal.

Could you check [Grpc.AspNetCore](https://github.com/grpc/grpc-dotnet/tree/master/src/Grpc.AspNetCore.Server) package?

**Comment by dotnetjunkie** [comment]
At the moment, grpc-dotnet does not contain the required interception points for Simple Injector, or any other non-conforming Container, to hook into. I just reported an [feature request](https://github.com/grpc/grpc-dotnet/issues/671) with the grpc-dotnet team.

In the mean time, only feasible the way around this issue is by viewing and implementing gRPC services as [Humble Objects](http://xunitpatterns.com/Humble%20Object.html). This means that you view gRPC services as part of your [Composition Root](https://freecontent.manning.com/dependency-injection-in-net-2nd-edition-understanding-the-composition-root/) and move all logic out of them, into new services. Then inside the gRPC service, you simply resolve that new service and forward the call to that service. You can do this by injecting the Simple Injector container into the gRPC service's constructor.

For instance:

``` c#
// GreeterGrpcService  as Humble Object depending on Simple Injector
public class GreeterGrpcService : Greeter.GreeterBase
{
    private readonly Container _container;

    public GreeterGrpcService(Container container) => _container = container;

    // Simply resolve and forward the call
    public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context) =>
        _container.GetInstance<IGreeterService>().SayHello(request);
}

// A real application service
public interface IGreeterService
{
    Task<HelloReply> SayHello(HelloRequest request);
}

// An application component with multiple dependencies and business logic
public class GreeterService : IGreeterService
{
    private readonly ILogger _logger;
    private readonly ISampleRepository _repo;

    public GreeterService(ILogger logger, ISampleRepository repo)
    {
        _logger = logger;
        _repo = repo;
    }

    public async Task<HelloReply> SayHello(HelloRequest request)
    {
        _logger.LogInformation("Saying hello to {Name}", request.Name);

        return new HelloReply { Message = "Hello " + request.Name };
    }
}
```

**Comment by JamesNK** [comment]
An activator is now public, and it made it into the next release - 2.26.0 - https://www.nuget.org/packages/Grpc.AspNetCore.Server/2.26.0-pre1

It would be create if you could test that it works (both for services and interceptors) before the non-prerelease 2.26.0 is published in a week or so.

**Comment by dotnetjunkie** [comment]
I can confirm that interception of both gRPC services and interceptors works with the new externion point.

**Comment by dotnetjunkie** [comment]
@enif-lee, I added new documentation on how to integrate Simple Injector with Grpc.AspNetCore. You can read it [here](https://github.com/simpleinjector/SimpleInjector/issues/785).

**Comment by enif-lee** [comment]
@dotnetjunkie Thank you for tracking this issue. I'm really appreciate it! I will check out documentation for integrating grpc with simple injector.
