### ISSUE TITLE
Add IAsyncDisposable integration for ASP.NET Core 3

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#778]
The documentation [describes](https://simpleinjector.readthedocs.io/en/latest/lifetimes.html#retrieving-list-of-container-created-disposables) how to implement async disposal with Simple Injector.

.NET Core 3 now contains an [IAsyncDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.iasyncdisposable?view=dotnet-plat-ext-3.0) interface. It would be nice if Simple Injector's ASP.NET Core packages could automatically asynchronously dispose its created scoped instances.

Downside, however, is that Simple Injector's integration packages require ASP.NET Core 2.0 or higher, while `IAsyncDisposable` is only available in .NET Core 3. There are 3 paths to walk here:

1. Upgrade the integration packages to require ASP.NET Core 3
2. Add an extra integration package specifically for working with `IAsyncDisposable`. 
3. Use duck typing.

About the options:

1. is not an attractive solution, because it blocks ASP.NET Core 2 users from using newer packages and features.
2. is not an attractive solution, because it makes it much harder for users to find this feature.
3. downside is internal complexity to achieve this while allowing great performance.

**Comment by mbett7** [comment]
or
4. Use [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/) for ASP.NET Core 2.0

**Comment by dotnetjunkie** [comment]
Hi @mbett7,

Thank you for this valuable tip. I ran some tests with this and it indeed does the trick. The package uses type forwarding, which allows the runtime to use the `IAsyncDisposable` from the package in case the application is .NET Standard < 2.1 and automatically uses the built-in type for .NET Standard 2.1. This is the ideal solution and I'll go with that option.

**Comment by dotnetjunkie** [comment]
[feature-778](https://github.com/simpleinjector/SimpleInjector/tree/feature-778) branch created.

**Comment by dotnetjunkie** [comment]
The use of `Microsoft.Bcl.AsyncInterfaces` proved to be an absolute PITA. Therefore, in v5.2, we're removing this dependency again from the core library and instead apply duck typing in order to apply asynchronous disposal. For more information, see #867.
