### ISSUE TITLE
How to properly integrate with ASP.NET Core 3.1 Web API app?

### ISSUE THREAD

**Issue by ralphhendriks** [simpleinjector/SimpleInjector#788]
I am trying to integrate Simple Injector with an ASP.NET Core 3.1 Web API app. Unfortunately, the documentation is not entirely clear on how to do that. Especially, it is unclear what is the correct way the various methods in the `Startup`-class should be adapted for integrating with Simple Injector.

First, I am uncertain what is the correct integration package for this use case. Is `SimpleInjector.Integration.AspNetCore` sufficient? This package apparently does not contain an adapter for `IControllerActivator`. The following setup works, though:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
    services.AddSimpleInjector(_container, options =>
    {
        options.AddAspNetCore();
    });
    InitializeContainer();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseSimpleInjector(_container);
    app.UseRouting();
    app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
    _container.Verify();
}
```

To my understanding this setup results in using the built-in DI system (`IServicesCollection`) to resolve the controllers, which in turn will use Simple Injector to wire up their dependencies.

If I want Simple Injector to provide the controller activation, I should probably use the integration package `SimpleInjector.Integration.AspNetCore.Mvc.Core`. The relevant parts of the `Startup` class then become:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
    services.AddSimpleInjector(_container, options =>
    {
        options
            .AddAspNetCore()
            .AddControllerActivation();
    });
    InitializeContainer();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseSimpleInjector(_container);
    app.UseRouting();
    app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
    _container.Verify();
}
```

This does compile but does not start, failing with: _System.InvalidOperationException: 'A registration for the Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager is missing from the ASP.NET Core configuration system. This is most likely caused by a missing call to services.AddMvcCore() or services.AddMvc() as part of the ConfigureServices(IServiceCollection) method of the Startup class. A call to one of those methods will ensure the registration of the ApplicationPartManager.'_ I feel hesitant to follow this suggestion, as the `.AddMvcCore()` or `.AddMvc()` extensions also register services relating to views, which is not necessary for a Web API app.

Would using SimpleInjectors `.AddControllerActivation()` replace the need for including `services.AddControllers()`, or does the latter more than just providing an implementation for `IControllerActivator` and hence remains necessary.

Also, the `SimpleInjector.Integration.AspNetCore.Mvc.Core` adds (dormant) references to view-related parts of ASP.NET Core. This relates to #587 

Should Simple Injector be used to provide an implementation for `IControllerActivator` at all? Or is the default ASP.NET Core DI adapter sufficient?

I would appreciate some hints in the right direction. When resolved, I am willing to contribute to improving the docs in this respect. Please let me know if that would be helpful.

**Comment by dotnetjunkie** [comment]
> Is SimpleInjector.Integration.AspNetCore sufficient?

No, it isn't. The `SimpleInjector.Integration.AspNetCore` contains provides integration with the ASP.NET Core framework—not with its sub frameworks, such as MVC and Web API. The required integration methods for Web API are located in the `SimpleInjector.Integration.AspNetCore.Mvc.Core` integration package. Among other things, that package contains:

* An `IControllerActivator` implementation for Simple Injector.
* An `IViewModelActivator` implementation for Simple Injector.
* Extension methods that hook those activators into the MVC pipeline and register controllers and view models in Simple Injector

> To my understanding this setup results in using the built-in DI system (IServicesCollection) to resolve the controllers, which in turn will use Simple Injector to wire up their dependencies.

No, this won't happen. Without the custom `IControllerActivator`, Simple Injector will not be invoked at all. The built-in `IControllerActivator` will create controllers itself and will resolve any controllers' dependencies from the `IServiceCollection` (i.e. from MS.DI).

> If I want Simple Injector to provide the controller activation, I should probably use the integration package SimpleInjector.Integration.AspNetCore.Mvc.Core. 

Correct.

> This does compile but does not start, failing with: System.InvalidOperationException:

I am unable to reproduce this error. I'm running your exact code on an ASP.NET Core 3.1 app, but the `AddControllerActivation` call succeeds. Do note that the `.AddControllers()` extension method internally [calls](https://github.com/aspnet/AspNetCore/blob/0303c9e90b5b48b309a78c2ec9911db1812e6bf3/src/Mvc/Mvc/src/MvcServiceCollectionExtensions.cs#L145) `.AddMvcCore()`. This means that the `ApplicationPartManager` should be registered when you call `.AddController()`. I'm not sure what's going on in your case.

> Would using SimpleInjectors .AddControllerActivation() replace the need for including services.AddControllers(), or does the latter more than just providing an implementation for IControllerActivator and hence remains necessary.

You need both. `.AddControllerActivation()` just does two things: it adds the `SimpleInjectorControllerActivator` to the `IServiceCollection`, and it registers all controllers in Simple Injector. MVC's `.AddController()` initializes the complete MVC sub system on top of ASP.NET Core.

> Should Simple Injector be used to provide an implementation for IControllerActivator at all? Or is the default ASP.NET Core DI adapter sufficient?

I'm not sure what you're asking here. You might want to rephrase this.

**Comment by ralphhendriks** [comment]
Thank you for your swift and elaborate answer. This definitely shines light on the less obvious parts.

> I am unable to reproduce this error. I'm running your exact code on an ASP.NET Core 3.1 app, but the `AddControllerActivation` call succeeds. Do note that the `.AddControllers()` extension method internally calls `.AddMvcCore()`. This means that the `ApplicationPartManager` should be registered when you call `.AddController()`. I'm not sure what's going on in your case.

I tried a second time, and then the error was gone. After playing around a bit more, it appears that this exception is thrown when the `ConfigureServices(...)` method does not call `AddControllers()` but does call `AddControllerActivation()` on the Simple Injector setup action. I guess I had an unsaved edit when I run the project initially. My apologies for the confusion.

> I'm not sure what you're asking here. You might want to rephrase this.

I guess that was just a clumsy rephrasing of the question that you already answered (i.e. Simple Injector provided `IControllerActivator` should be used). All is clear now.

Summarizing, to integrate Simple Injector into an ASP.NET Core Web Api app the integration package `SimpleInjector.Integration.AspNetCore.Mvc.Core` has to be used, and the minimal setup code should look like my second example.
