### ISSUE TITLE
Cross-wired scoped services don't support nested scoping?

### ISSUE THREAD

**Issue by darjanbogdan** [simpleinjector/SimpleInjector#796]
I've encountered a situation in which cross-wired scoped service (e.g. `DbContext`) needs to be isolated in a nested scope via SimpleInjector's nested scoping capabilities.

I thought it is supported out-of-the-box, as SimpleInjector preserves the scope from NetCore's cross-wired service. It is also preserved in my case as each _HTTP request_ ends up having a new instance of it, for example. However, it's not acting like a _scoped_ instance when trying to do some work inside the nested scope created via `AsyncScopedLifestyle.BeginScope` method. In that case, the same service acts as a "singleton" as I'm getting the same instance of the service. 

I couldn't find more thorough documentation about SimpleInjector nested scoping in conjunction with cross-wired scoped service (from `IServiceCollection`). So, would it be possible to give more insights into internal specifics or point me somewhere else, as it feels/sounds like a bug at this moment, although I guess it's not the case. 

Here is the setup:

```
public interface IScopedService { }
public class ScopedService : IScopedService { }

public class Startup
{
    private readonly Container _container = new Container();

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllers();
        services.AddScoped<IScopedService, ScopedService>();

        services.AddSimpleInjector(_container, opts =>
        {
            opts.AddAspNetCore().AddControllerActivation();
        });
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseSimpleInjector(_container);

        app.UseRouting();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
    }
}
```

As I found that when building API, here is a test controller used to show the behavior:
```
[ApiController]
[Route("")]
public class TestController : ControllerBase
{
    private readonly Container _container;

    public TestController(Container container)
    {
        _container = container;
    }

    [HttpGet]
    public async Task<bool> Get()
    {
        Debug.WriteLine($"Service : {_container.GetInstance<IScopedService>().GetHashCode()}");

        using (AsyncScopedLifestyle.BeginScope(_container))
        {
            Debug.WriteLine($"Service Scope 1: {_container.GetInstance<IScopedService>().GetHashCode()}");

            using (AsyncScopedLifestyle.BeginScope(_container))
            {
                Debug.WriteLine($"Service Scope 1.1: {_container.GetInstance<IScopedService>().GetHashCode()}");
            }
        }

        using (AsyncScopedLifestyle.BeginScope(_container))
        {
            Debug.WriteLine($"Service Scope2: {_container.GetInstance<IScopedService>().GetHashCode()}");
        }

        using (var scope = AsyncScopedLifestyle.BeginScope(_container))
        {
            Debug.WriteLine($"Service Scope 3: {scope.GetInstance<IScopedService>().GetHashCode()}");
        }

        return true;
    }
}
```
This is the output which I get:

> Service : 47441805
Service Scope 1: 47441805
Service Scope 1.1: 47441805
Service Scope2: 47441805
Service Scope 3: 47441805

However, if I register the same service with `Lifestyle.Scoped` in SimpleInjector, I get the expected behavior and the following output:

> Service : 6044116
Service Scope 1: 59817589
Service Scope 1.1: 48209832
Service Scope2: 5773521
Service Scope 3: 54135081

Usually, I'd just relocate registration to SimpleInjector, however what if we can't do that easily, let's say I want to take advantage of `AddDbContext` extension method to register `DbContext`. So, is there a way to configure/integrate those containers differently to allow nesting of cross-wired scoped service?

I'm using latest ASP.Net Core (3.1) and SimpleInjector (4.9)

**Comment by dotnetjunkie** [comment]
The documentation is a bit scarce in this regard, I agree.

The behavior you are seeing is "by design." Within a HTTP request, Simple Injector will reuse .NET Core's request scope. This is a conscious design decision. This was chosen because even though developers  would start a new Simple Injector scope, they would often like to reuse request data provided by .NET Core. I think overall this is the simplest for kost developers, although it can also be less obvious.

Outside the context of a .NET Web Request, however, the behavior is exactly is you'd expect. Every Simple Injector scope automatically creates its own .NET Core scope.

But either way, it would be good to make this behavior configurable; currently it is fixed.

**Comment by darjanbogdan** [comment]
Thank you very much for the explanation. I assumed something like that could be the case, as it is preferred behavior when working with `IHttpContextAccessor' instance, for example. 

Also, thanks for the confirmation about the behavior outside of a .NET Web Request, as it was working correctly when I delegated work to the background (e.g. scoped inside `IHostedService`), but I wasn't completely sure is it working by accident or by design.

**Comment by dotnetjunkie** [comment]
Hi @darjanbogdan,

I didn't realize this before, but (as I just mentioned [here](https://github.com/simpleinjector/SimpleInjector/issues/831)) there is actually a way to configure this, which is as follows:

``` c#
services.AddSimpleInjector(container, options =>
{
    IServiceProviderAccessor defaultAccessor = options.ServiceProviderAccessor;
    options.AddAspNetCore();

    // Restore the default ServiceProviderAccessor; this prevents the IServiceScope
    // from being reused within the same web request. Creating a new Simple Injector
    // Scope will ensure the creation of a new IServiceScope as well.
    options.ServiceProviderAccessor = defaultAccessor;   
});
```

For more details on what this does, and how it works, read [this](https://github.com/simpleinjector/SimpleInjector/issues/831#issuecomment-659658645).

**Comment by darjanbogdan** [comment]
Hi @dotnetjunkie ,

Thank you for the explanation, it's nice to see there is a way to configure it!

Does it make sense to expand `AddAspNetCore` method with additional parameter used to configure if `IServiceScope` should be reused within the same request?

**Comment by dotnetjunkie** [comment]
That absolutely makes sense and was already considering such construct.

**Comment by dotnetjunkie** [comment]
I released [SimpleInjector.Integration.AspNetCore v5.1](https://www.nuget.org/packages/SimpleInjector.Integration.AspNetCore/5.1.0) which now contains an `AddAspNetCore` overload that accepts an `ServiceScopeReuseBehavior` enum that allows you to override the behavior.

For instance:

``` c#
services.AddSimpleInjector(options =>
{
    options.AddAspNetCore(ServiceScopeReuseBehavior.OnePerNestedScope);
});
```

There are three options:

* `OnePerRequest`: This gets the same behavior as calling the parameterless `AddAspNetCore()` method.
* `OnePerNestedScope`: This reuses the the request's `IServiceScope` for Simple Injector's root (request) scope, but creates new (isolated) `IServiceScope` instances for any created nested scope. This means, for instance, that every nested scoped will get its own cross-wired `DbContext` instance.
* `Unchanged`: This uses the behavior you would get without calling `AddAspNetCore()`, which means that even the root (request) scope gets its own (new) `IServiceScope`. This means that Simple Injector-resolved services run in their own bubble, and get their own set of cross-wired scoped services.

**Comment by darjanbogdan** [comment]
This is amazing, with such overload in place all the confusion (I had) around cross-wiring and scoping is gone, thank you again for all the effort!

**Comment by tim-626** [comment]
Excellent, thanks so much.  It makes configuration much cleaner and easier to understand with built-in support!
