### ISSUE TITLE
How to use with Xamarin Forms?

### ISSUE THREAD

**Issue by RyanGaudion** [simpleinjector/SimpleInjector#797]
I'm  very new to this and am probably making a simple mistake but how to I use SimpleInjector with Xamarin Forms. There are no docs on the website for Xamarin. Here is my App Class:

```
public partial class App : Application
    {
        public App()
        {
            InitializeComponent();
            SetUpContainer();
            MainPage = new MainPage();
        }

        private void SetUpContainer()
        {
            var container = new Container();
            container.Register<IPerson, Human>(Lifestyle.Transient);
            container.Verify();
        }
    }
```

And here is my MainPage:

```
public partial class MainPage : ContentPage
    {
        private IPerson _person;
        public MainPage(IPerson person)
        {
            _person = person;
            InitializeComponent();
        }
    }
```
When I compile my code I get the error, there is no argument given that corresponds to the required formal parameter 'person'.

Please advise on how to fix this issue. It's probably really simple.

**Comment by RyanGaudion** [comment]
Issue Resolved

**Comment by dotnetjunkie** [comment]
Would you mind sharing your solution with others?

**Comment by RyanGaudion** [comment]
Thought I had resolved the issue but another issue arose. Please see:
https://stackoverflow.com/questions/60061003/how-to-use-simple-injector-with-xamarin-forms-and-entity-framework-core
