### ISSUE TITLE
Is there support for ServiceProviderFactory?

### ISSUE THREAD

**Issue by SeanFeldman** [simpleinjector/SimpleInjector#798]
I couldn't find an issue covering support for `IServiceProviderFactory` to support Microsoft DI.
Looking through the code it doesn't seem to be available (no implementation of `IServiceProviderFactory`). Is this planned or my search is incorrect? Thank you.

**Comment by dotnetjunkie** [comment]
> Is there support for ServiceProviderFactory?

Nope.

Just follow the integration guide and you'll be fine.

**Comment by andreasohlund** [comment]
Still early days but our current plan to allow the users to pass the containers `ServiceProviderFactory` to us using

https://github.com/Particular/NServiceBus.Extensions.Hosting/pull/37/files#diff-cca5dcd6eafb15bb4f7bdcd8839ccafdR19

so to support simple injector we would need to provide an overload where a `ServiceCollection` is passed where the user can have enabled SimpleInjector using https://github.com/simpleinjector/SimpleInjector/blob/master/src/SimpleInjector.Integration.ServiceCollection/SimpleInjectorServiceCollectionExtensions.cs#L44, would that be accurate?

**Comment by dotnetjunkie** [comment]
That won't work with Simple Injector. If you choose to use MS.DI as your default container for NServiceBus, Simple Injector users can't replace your "built-in" container with Simple Injector. Instead they should leave MS.DI in to resolve framework components and use Simple Injector side by side to resolve application components such as message handlers. This might feel weird to you, but this is actually how Simple Injector users in the past would have used NServiceBus whilenyou were using Autofac. Simple Injector is incompatible with the abstractions provided by Microsoft, just as it was with the container abstractions that NServiceBus provided.

You, as NSB designers, should make sure you expose the proper abstractions that allow Simple Injector users (and users of other so-called "non-conforming containers") to intercept the creation of root types such as message handlers.

If you look closely, this is exactly the advice we give to our users when dealing with ASP.NET Core and other feameworks.

Note that even outside the context of Simple Injector, framework designers should always expose the required extension points that allow users to intercept the creation of framework types, typically using factory abstractions or the like.

I hope this makes sense.

**Comment by andreasohlund** [comment]
Thanks for the thorough answer Steven, exposing those factory extension points have been on our radar for some time already. I'll bring your input to our internal discussions 👍

**Comment by SeanFeldman** [comment]
Thank you, @dotnetjunkie.
