### ISSUE TITLE
Resolving HttpContext Identity in Hangfire Background tasks 

### ISSUE THREAD

**Issue by nhaberl** [simpleinjector/SimpleInjector#800]
I am really struggling...I abstracted a usercontext in IClient and added factory which gets all relevant user data from httpcontext

This IClient is injected into my services everywhere as constructor injection.
Everything wirks fine innthe web request pipeline but I would like to inject my services also in Hangfire background tasks but the HttpContext is not available there.

So my question is if there is any chance to "forward" IClient so all my services can get resolved.

Or is there a way to resolve the graph based on any runtime info stored anywhere?!
...or do I have to reject IClient from all services and add it as runtime info?

I hope you understand what I mean ?

**Comment by dotnetjunkie** [comment]
There are many ways to solve this, but it depends on your needs.

One option is to use two isolated container instances: one for your web requests, and another for Hangfire. This allows you to configure the hangire container with a different IClient implementation. Of course you can (and should) reuse as much of your configuration as possible. Downside of this approach is that having two container instances will cause each container to have its own singleton (so singletons are not shared). On the plus side, it makes both application parts isolated, and this later on, makes it easier to move the Hangfire jobs to another process, if required.

Another option is to make the IClient implementation mutable, and set a fixed value for client in your Hangfire infrastructure, directly after you created a scope, and resolved the graph, but before the hangfire job is invoked. I'm not that familiar with Hangfire myself, so I can't show you an example.

These are two ideas that crossed my mind.

I hope this helps.

**Comment by nhaberl** [comment]
Thanks a lot, it's all clear for my but how can I "forward" the IClient info to the container before the Job is started ... 
In my CommandHandler instance I store the IClient info (which exists in the webrequest context) and from there I need to add IClient to the container ... so when the job starts which is async and out of scope of the webrequest the job can resolve IClient ...

I know it's maybe a bit weird but any help is kindly appreciated

**Comment by dotnetjunkie** [comment]
To achieve this, you need a bit of infrastructure. It might look like this:

``` c#
using (AsyncScopedLifestyle.BeginScope(container))
{
    var client = container.GetInstance<ClientImpl>();
    client.Id = */ some id */; // set the runtime data for the client

    var handler = container.GetInstance<ICommandHandler<TCommand>>();
    handler.Handle(command);
}
```

Here `ClientImpl` is an implementation of `IClient` which allows its data to be set. Registration might be done as follows:

``` c#
container.Register<IClient, ClientImpl>(Lifestyle.Scoped);
container.Register<ClientImpl>(Lifestyle.Scoped);
```

I hope this makes sense.
