### ISSUE TITLE
UseLoosenedLifestyleMismatchBehavior and container.Verify()

### ISSUE THREAD

**Issue by AceVentura** [simpleinjector/SimpleInjector#801]
Hello,

While using V4.9 with `UseLoosenedLifestyleMismatchBehavior = true` I noticed that `Verify` does not take this property into account.

Is this an expected behaviour? For now I'm not using verify as a "workaround".

**Comment by dotnetjunkie** [comment]
Hi @AceVentura,

I tried to reproduce the issue, but I do see `UseLoosenedLifestyleMismatchBehavior` to have an effect when calling `Verify()`. Perhaps what you are seeing is a special case. Can you post a repro of your issue?

**Comment by AceVentura** [comment]
Of course!
For the repro, I created a project with ASP.NET Core (3.1.1), API Settings.
Added SimpleInjector and SimpleInjector.Integration.AspNetCore.Mvc.Core (4.9.0).

Replaced the Startup.cs code with the following:
`using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using SimpleInjector;

namespace SimpleInjectorBug
{
    public class Startup
    {
        private Container _container = new Container();
        public Startup(IConfiguration configuration)
        {
            // Set to false. This will be the default in v5.x and going forward.
            _container.Options.ResolveUnregisteredConcreteTypes = false;
            _container.Options.SuppressLifestyleMismatchVerification = true;
            _container.Options.UseLoosenedLifestyleMismatchBehavior = true;
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddSimpleInjector(_container, options =>
            {
                // AddAspNetCore() wraps web requests in a Simple Injector scope and
                // allows request-scoped framework services to be resolved.
                options.AddAspNetCore()

                    // Ensure activation of a specific framework type to be created by
                    // Simple Injector instead of the built-in configuration system.
                    // All calls are optional. You can enable what you need. For instance,
                    // PageModels and TagHelpers are not needed when you build a Web API.
                    .AddControllerActivation();
            });
            _container.Register<IamSingleton>(Lifestyle.Singleton);
            _container.Register<IamScoped>(Lifestyle.Scoped);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseSimpleInjector(_container);
            _container.Verify();
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }

    public class IamSingleton
    {
        private IamScoped _scoped;
        public IamSingleton(IamScoped scoped)
        {
            _scoped = scoped;
        }
    }

    public class IamScoped
    {
        public IamScoped()
        {
        }
    }
}
`

If you comment the disabled and add the following to the WeatherForecastController, the container works as expected.
`        private readonly ILogger<WeatherForecastController> _logger;
        private readonly IamSingleton _singleton;
        private readonly IamScoped _scoped;
        public WeatherForecastController(ILogger<WeatherForecastController> logger, IamSingleton singleton, IamScoped scoped)
        {
            _logger = logger;
            _singleton = singleton;
            _scoped = scoped;
        }`

**Comment by dotnetjunkie** [comment]
I assume you are trying to prevent verification of the injection of a Scoped into a Singleton, but that's not what  
`UseLoosenedLifestyleMismatchBehavior` doesand that's by design. You should hardly ever suppress the injection of Scoped insrances into Singletons, because that would lead to lots of trouble.

`UseLoosenedLifestyleMismatchBehavior` only suppresses detection of injecting Transients into Scoped components, because that will, in many cases, not be a problem.

**Comment by dotnetjunkie** [comment]
Out of interest, why are you using the `SuppressLifestyleMismatchVerification` option?
