### ISSUE TITLE
Problem registering assembly with a type from another namespace

### ISSUE THREAD

**Issue by jdahan91** [simpleinjector/SimpleInjector#806]
OK, so i'm trying to register an assembly that uses the SAME type definition as the base module but the type is in another namespace (external file [sdk]).

For example, I have 20 modules that implement `IModule` from a specific file and an external module that implements `IModule` from an sdk .cs file.

The container picks up 20 modules instead of 21.

What can I do in this situation?

**Comment by dotnetjunkie** [comment]
Minimal Reproducible Example please. Show me the codez.

**Comment by jdahan91** [comment]
`var modulesType = IocContainer.GetTypesToRegister<IModule>(assemblies);`

assemblies is an IEnumberable<Assembly> which is a local variable returned from a local function that enumerates all files in .\Plugins folder and looks for all .dlls which are "*Plugin.dll" (end with Plugin)

I don't see the external module loaded.

**Comment by dotnetjunkie** [comment]
Can you post a complete, verifiable example? Reproduce the problem using a new, empty console project,and share the complete code for that console here.

**Comment by jdahan91** [comment]
> Can you post a complete, verifiable example? Reproduce the problem using a new, empty console project,and share the complete code for that console here.

Take a look [here](https://github.com/jdahan91/Telebot/blob/master/Telebot/Program.cs#L86)

This specific line is resolving only modules from solution and not from another solution. I really don't know if it's the solution the cause or the namespace of the `IModule` definition.

**Comment by jdahan91** [comment]
OK, I've just ran a test and yes, it needs to use the type definition in the same assembly as the one used in the .exe. 

What can be done in this situation?

**Comment by jdahan91** [comment]
So in the bottom line, i'd have to extract all sdk definitions into a usable module that would be shared across application and sub modules.

Awaiting for your reply to see what can be done.

**Comment by jdahan91** [comment]
OK, this case can be closed. I managed to export a .dll that acts as a broker for the main module (App) and the external modules (Plugins) and now it works fine. Even though I encourage the author of SI to find a "fix" for this.
