### ISSUE TITLE
SimpleInjector 2.8.1 upgrade breaks Code Analysis (CA0058) of projects with SimpleInjector.Extensions.ExecutionContextScoping

### ISSUE THREAD

**Issue by medianick** [simpleinjector/SimpleInjector#81]
After upgrading to SimpleInjector 2.8.1, builds with MSBuild 2013 (on our Jenkins server) started breaking with errors along these lines:

    MSBUILD : error : CA0058 : The referenced assembly 'SimpleInjector, Version=2.8.0.0, 
    Culture=neutral, PublicKeyToken=984cb50dea722e99' could not be found. This assembly is 
    required for analysis and was referenced by: C:\MyProject\bin\MyProject.dll, 
    C:\MyProject\packages\SimpleInjector.Extensions.ExecutionContextScoping.2.8.0\lib\net45\
    SimpleInjector.Extensions.ExecutionContextScoping.dll.

The workaround (not unreasonable, but we hadn't had to do it before) was to add &lt;CodeAnalysisAdditionalOptions&gt;/assemblyCompareMode:StrongNameIgnoringVersion&lt;/CodeAnalysisAdditionalOptions&gt; to the relevant PropertyGroup (for the Debug build configuration) in the csproj files for the relevant projects. I imagine that this is because SimpleInjector is strong-named and a 2.8.1 version of the SimpleInjector.Extensions.ExecutionContextScoping library is not available on NuGet (yet), so although it builds properly, since the dependency versioning only requires >=2.8.0, Code Analysis by default matches by strong name and version.

So, this might just be a request to release 2.8.1 of SimpleInjector.Extensions.ExecutionContextScoping, unless there's some other way we should be handling this. :)

**Comment by dotnetjunkie** [comment]
Binding redirect are typically the way to solbe this and this is something that NuGet usually sets. But this goes wrong.quite often and that's why I usually roll out new versions of depending assemblies (such as the ExecutionContextScoping) as well. I didn't do that this time, and you can immediately see where this brings us.

I will push a 2.8.1 version of the other packages as well to NuGet tomorrow.

Thanks for reporting this

**Comment by medianick** [comment]
NuGet did add all the binding redirects correctly, as far as I can see, but my understanding is that Code Analysis doesn't honor them (http://stackoverflow.com/a/5493320/466874). A 2.8.1 version for the other packages should do the trick. Thanks for the quick response!

**Comment by dotnetjunkie** [comment]
I just increased the patch number of the core library and all other libraries to 2.8.3 and pushed them to NuGet. They should be available for download shortly.
