### ISSUE TITLE
Make 'loosened lifestyle mismatch behavior' the default

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#816]
See #793

**Comment by dotnetjunkie** [comment]
[feature-816](https://github.com/simpleinjector/SimpleInjector/tree/feature-816) branch created.

**Comment by qujck** [comment]
The name of this option is not simple  I suggest something else like `StrictLifestyleMismatchBehavior`.

**Comment by dotnetjunkie** [comment]
That's a good suggestion. It does force making `UseLoosenedLifestyleMismatchBehavior` obsolete and forward its getter and setter to the new property. Because of consistency with all other properties on`ContainerOptions`, however, I rather go with `UseStrictLifestyleMismatchBehavior`.

**Comment by dotnetjunkie** [comment]
Design notes:

* `ContainerOptions.UseStrictLifestyleMismatchBehavior` property added
* `ContainerOptions.UseLoosenedLifestyleMismatchBehavior` marked obsolete.
