### ISSUE TITLE
OWIN + Simpleinjector = ObjectDisposedException

### ISSUE THREAD

**Issue by daniel-tiziani-tzn** [simpleinjector/SimpleInjector#82]
I'm trying to use SimpleInjector with OWIN, but I can't get it working correctly. Can you please help me? It's a normal Web API project to be hosted on IIS. 

On the first request, the following exception occurs:
System.ObjectDisposedException: 'System.Web.Http.HttpServer'.

Here's the code for startup.cs

``` c#
public void Configuration(IAppBuilder app)
{
    var config = new HttpConfiguration();
    var container = new Container();
    container.RegisterWebApiRequest<LocationService, LocationService>();
    this.ConfigureAuth(app, container);
    config.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(container);
    WebApiConfig.Register(config);
    app.UseWebApi(config);   
}

public void ConfigureAuth(IAppBuilder app, Container container)
{
    // Enables COORS
    app.Use(async (context, next) =>
    {
        using (var scope = container.BeginExecutionContextScope())
        {
            await next();
        }
    });
}
```

And here's the stacktrace for error: 

[ObjectDisposedException: Não é possível acessar um objeto descartado.
Nome do objeto: 'System.Web.Http.HttpServer'.]
   System.Net.Http.DelegatingHandler.CheckDisposed() +333788
   System.Net.Http.DelegatingHandler.CheckDisposedOrStarted() +13
   System.Net.Http.DelegatingHandler.set_InnerHandler(HttpMessageHandler value) +23
   System.Web.Http.HttpServer.Initialize() +107
   System.Web.Http.HttpServer.<EnsureInitialized>b__b() +31
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func'1 valueFactory) +115
   System.Threading.LazyInitializer.EnsureInitialized(T& target, Boolean& initialized, Object& syncLock, Func'1 valueFactory) +72
   System.Web.Http.HttpServer.EnsureInitialized() +119
   System.Web.Http.<SendAsync>d__0.MoveNext() +276
...
 Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +287
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +11846300
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +53
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +272
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   Microsoft.Owin.Host.SystemWeb.Infrastructure.ErrorState.Rethrow() +33
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +150
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +42
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +415
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by dotnetjunkie** [comment]
I just created an empty ASP.NET 4.5 Web API application and pasted in the code you posted above, but I'm unable to reproduce this issue. Can you please post more code so I can reproduce this?

**Comment by daniel-tiziani-tzn** [comment]
Sure I can. But I found out that there is 2 context's running, which is strange. I'm running WebApi + OWIN, but when executing in debug, if I put a breakpoint in Global.asasx/Application_start, for EACH request this breakpoint gets a hit, and then the Owin startup class all over again, and no exceptions thrown. What can I be messing with? :-(

**Comment by dotnetjunkie** [comment]
Which version of Simple Injector are you using? We did change some behavior in the `SimpleInjectorWebApiDependencyResolver` of v2.8. Prior to 2.8 the `SimpleInjectorWebApiDependencyResolver` would always ensure that a controller would run in its own execution scope, but this is changed with 2.8. Now the resolver checks if there is already an active execution context scope and if that's the case it will run inside that scope without creating a new one.

Are you using a Simple Injector version below 2.8?

**Comment by daniel-tiziani-tzn** [comment]
I have the following in my project:
<package id="SimpleInjector" version="2.8.0" targetFramework="net46" />
  <package id="SimpleInjector.Extensions.ExecutionContextScoping" version="2.8.0" targetFramework="net46" />
  <package id="SimpleInjector.Integration.WebApi" version="2.8.1" targetFramework="net46" />
  <package id="SimpleInjector.Integration.WebApi.WebHost.QuickStart" version="2.8.1" targetFramework="net46" />

Isn't it strange that the context seems to be dying?! :(

**Comment by dotnetjunkie** [comment]
Are you sure this is actually one single request? You can watch the `HttpContext.Current.Request.Url` in the debugger to get an indication if there is a second request going on.

**Comment by daniel-tiziani-tzn** [comment]
Yes, pretty sure. The scenario I have is the following:
1) Starting debug, it goes to Application_start and then to the owin Configure
2) Making the first request, it goes to the scope of app.use (correctly) and responds ok
3) Next request it takes a long time and then goes over Application_start and owin config...

Do you have any tips of how to debug that? I say the context is dying, but I don't know what is causing it to re-run all the configuration.

**Comment by daniel-tiziani-tzn** [comment]
Apparently I found the guilty one: Nlog
When I disabled it, the OWIN stopped working. I think it has some issues with SimpleInjector when injecting Logger on controllers that has other parameters to inject, unfortunatelly :(

**Comment by daniel-tiziani-tzn** [comment]
I'm closing this issue. Couldn't find a solution for the issue, but it's not related to SimpleInjector at all. Hope someone with the same issue (NLOG + OWIN) finds it here to know they're not alone :-)

Thanks for the support, kudos for the awesome project!
