### ISSUE TITLE
I used your suggestion for Signalr, but it produces errors

### ISSUE THREAD

**Issue by JeromeKen** [simpleinjector/SimpleInjector#821]
To be able to use the Lifestyle.Scoped property, please ensure that the container is configured with a default scoped lifestyle by setting the Container.Options.DefaultScopedLifestyle property with the required scoped lifestyle for your type of application

**Comment by dotnetjunkie** [comment]
Hi Jerome,

Is this a question or a suggestion? Which SignalR example are you referring to? 
Considering the exception message, did you try to follow the exception's advice to fix the problem? Did that fix thw problem?

**Comment by JeromeKen** [comment]
My Startup class looks like this
`          private Container container = new Container();
        public Startup(IConfiguration configuration)
        {
            container.Options.UseLoosenedLifestyleMismatchBehavior = true;
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            services.AddCors(options => options.AddPolicy("CorsPolicy",
                builder =>
                {
                    builder.AllowAnyMethod().AllowAnyHeader()
                           .AllowCredentials();
                }));

            foreach (Type type in container.GetTypesToRegister<Hub>(typeof(ServerHub).Assembly))
                container.Register(type, type, Lifestyle.Scoped);

            services.AddScoped(typeof(IHubActivator<>), typeof(SimpleInjectorHubActivator<>));

            services.AddSignalR(hubOptions =>
            {
                hubOptions.ClientTimeoutInterval = TimeSpan.FromSeconds(30);

            }).AddMessagePackProtocol(options =>
            {
                //options.FormatterResolvers = new List<MessagePack.IFormatterResolver>()
                //{
                //     MessagePack.Resolvers.StandardResolver.Instance
                //};
            });
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = "JwtBearer";
                options.DefaultChallengeScheme = "JwtBearer";
            })
            .AddJwtBearer("JwtBearer", jwtBearerOptions =>
            {
                // Set the context on an event to use the `token` query parameter for the bearer token
                jwtBearerOptions.Events = new JwtBearerEvents();
                jwtBearerOptions.Events.OnMessageReceived = context =>
                {
                    context.Token = context.HttpContext.Request.Query["token"];
                    return Task.CompletedTask;
                };
                var key = Configuration.GetValue<string>("JWTKey");
                jwtBearerOptions.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key)),
                    ValidateIssuer = false,
                    //ValidIssuer = "The name of the issuer",
                    //ValidAudience = "The name of the audience",
                    ValidateAudience = false,
                    ValidateLifetime = true, //validate the expiration and not before values in the token
                    ClockSkew = TimeSpan.FromMinutes(5) //5 minute tolerance for the expiration date
                };
            });
            services.AddControllers(options =>
            {
            });

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseCors("CorsPolicy");
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<ServerHub>("/SignalR", options =>
                {
                    options.Transports = HttpTransportType.WebSockets;
 
                });
                endpoints.MapControllerRoute(
                   name: "default",
                   pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }`

**Comment by JeromeKen** [comment]
Signalr Croe , https://github.com/simpleinjector/SimpleInjector/issues/631

**Comment by JeromeKen** [comment]
When the connection is opened, I use the client to send a message to the server
I now have a new error
Unable to resolve service for type'SimpleInjector.Container' while attempting to activate

**Comment by JeromeKen** [comment]
when I injected the container,I have solved my problem, thank you for your reply,

**Comment by dotnetjunkie** [comment]
Hi Jerome,

After reviewing your code I noticed that you aren't calling `services.AddSimpleInjector()` before registering the hubs. Integration with ASP.NET Core was implied in the documentation, but this was very implicit. I updated the documentation and extended the code sample to make it easier to use in the situation where you start with a blank project without ASP.NET Core integration already applied.

For your case, you should add the following code before registering your hubs:

``` c#
services.AddSimpleInjector(container, options =>
{
});
```

`AddSimpleInjector` does two things for you that are important here:
* It adds the Simple Injector `Container` to the `ServiceCollection`. This is required because `SimpleInjectorHubActivator<T>` depends on the `Container`.
* It adds the `AsyncScopedLifestyle` as `DefaultScopedLifestyle`. This is required because both the hubs and the `SimpleInjectorHubActivator<T>`  are registered as scoped.

Both additions of `AddSimpleInjector` can be applied manually, but it's easier to just call `AddSimpleInjector`.

I hope this helps.

**Comment by JeromeKen** [comment]
yes,That's right, when I tested the effect, I found that I couldn't meet the demand. I need to write to db before and after another Signalr Croe access method,It looks like I cannot achieve this requirement before signalr core version 5,In short, thank you for your reply
