### ISSUE TITLE
Simple Injector asks to register an MVC controller since v5

### ISSUE THREAD

**Issue by ShareTEC** [simpleinjector/SimpleInjector#828]
Since upgrading to v5 I always get an error that I should register my Controller with Simple Injector.

I have a quick and simple example:

I created an interface:

```
public interface IUserRepository
{
   string Get();
}
```
Implemented that interface:

```
public class UserRepository : IUserRepository
{
   public string Get()
   {
      return "Test";
   }
}
```

Registered with Simple Injector:

```
public Container GetContainer() 
{
     var container = new Container();
     container.Register<IUserRepository, UserRepository>();
     return container;
 }
```

In the Global.asax.cs

```
protected void Application_Start()
{
    DependencyResolver.SetResolver(new SimpleInjectorDependencyResolver(GetContainer()));
}
```

A very Simple ASP.NET MVC Controller (no, not ASP.NET Core)

```
public class HomeController : Controller
{
    private readonly IUserRepository _userRepository;

    public HomeController(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }

    public ActionResult Index()
    {
        ViewBag.Name = _userRepository.Get();
        return View();
    }
}
```

Running this code:

> No registration for type HomeController could be found. Make sure HomeController is registered, for instance by calling 'Container.Register<HomeController>();' during the registration phase. An implicit registration could not be made because Container.Options.ResolveUnregisteredConcreteTypes is set to 'false', which is now the default setting in v5. This disallows the container to construct this unregistered concrete type. For more information on why resolving unregistered concrete types is now disallowed by default, and what possible fixes you can apply, see https://simpleinjector.org/ructd.

The documentation is not really helping me. I'm doing exactly as they suggest. Any other suggestions?

**Comment by dotnetjunkie** [comment]
The message is stating that you didn't register HomeController. The solution is to register HomeController. There is a RegisterMvcControllers extension method for you to batch-register all your controllers.

**Comment by ShareTEC** [comment]
> 
> 
> The message is stating that you didn't register HomeController. The solution is to register HomeController. There is a RegisterMvcControllers extension method for you to batch-register all your controllers.

@dotnetjunkie Thanks, this helped. Is that since v5? I never used it before. In the ASP.NET MVC Integration document they mention it. [https://simpleinjector.readthedocs.io/en/latest/mvcintegration.html](https://simpleinjector.readthedocs.io/en/latest/mvcintegration.html). Didn't find it before.

**Comment by dotnetjunkie** [comment]
> Is that since v5? I never used it before.

That RegisterMvcControllers has been there for years and we have always advised to call this because of the arguments given in https://simpleinjector.org/ructd.
