### ISSUE TITLE
Blazor Server: AsyncScopedLifestyle Nested Scoping and DbContext Issue

### ISSUE THREAD

**Issue by tim-626** [simpleinjector/SimpleInjector#831]
This question is an extension of https://github.com/simpleinjector/SimpleInjector/issues/796 (*Cross-wired scoped services don't support nested scoping?*) regarding Blazor and service lifetime issues.

Blazor Server side has a unique default lifetime (long-lived), which in my scenario has made it difficult to find a good pattern to use that also still accommodates traditional Razor Pages DI patterns—in particular the DbContext's Scoped lifetime, which works great for Razor Pages, but is not suitable for Blazor Server where the DbContext lives for as long as the user is on the page with the Blazor Component (i.e., as long as the SignalR connection is open).

The TL;DR; is that I use a Mediator pattern (I have an `IMyMediator` and `ExecuteRequest(...)` method...currently implemented using MediatR) to route all Commands/Queries through handlers to keep business logic out of the web project.  But currently the same DbContext instance is being used with Blazor Server for all requests to the mediator and request handlers, which causes issues like concurrency exceptions when clicking on a button rapidly.  My plan was to add a new `IMyMediator.ExecuteRequestInNewScope(...)` where `AsyncScopedLifestyle.BeginScope(_container)` is called to provide a new scope while executing.  I would use this method for all Blazor-based command/query requests.  But I'm running into the same problem as the above-mentioned GitHub issue, as I'm still getting the same DbContext instance even in a new scope.  If this behavior was configurable in some way, perhaps my solution could work; or perhaps there's a better way to go about it.  I'm not sure, and so looking for some help on this.

For more details on this topic and my issue, please see below (and the attached VS Solution to demo):

To work around this issue of DbContext lifetime, MS Docs (https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1#use-of-entity-framework-dbcontext-from-di) suggests:
1. *Have Razor Components inherit from OwningComponentBase, which will at least isolate DbContext per Razor Component instances.*
**[RESPONSE]** This isn't bullet-proof because the DbContext can still be reused concurrently within the same Razor Component.
2. *New up your own DbContext instances as needed*
**[RESPONSE]** Not at all a good idea IMO.  This is a DI responsibility and manually new'ing up services is problematic in all sorts of ways (including mine which uses, among other things, MediatR and Command/Query objects and handlers, which depend on DbContext being ctr-injected).
3. *Register DbContext with a Transient lifetime*
**[RESPONSE]** Won't work well because it breaks the Unit-of-Work pattern where multiple services might need the same DbContext instance.

As mentioned above, I'm using a mediator pattern where oftentimes a DbContext instance and other services are ctr-injected into the `IRequestHandler`'s for these Commands/Queries.  Below is the mediator interface I currently use...

```csharp
public interface IMyMediator
{
    Task<TResponse> ExecuteRequest<TResponse>(IRequest<TResponse> request);
}

class MyMediator : IMyMediator
{
    private readonly IMediator _mediator;
    public MyMediator(IMediator mediator)
    {
        _mediator = mediator;
    }
    public Task<TResponse> ExecuteRequest<TResponse>(IRequest<TResponse> request)
    {
        return _mediator.Send(request);
    }
}
```
...which allows for requests and handlers such as...
```csharp
    public class GetPeopleRequest : IRequest<List<Person>> { }

    public class GetPeopleRequestHandler : IRequestHandler<GetPeopleRequest, List<Person>>
    {
        private readonly MyDbContext _context;

        public GetPeopleRequestHandler(MyDbContext context)
        {
            _context = context;
        }

        public async Task<List<Person>> Handle(GetPeopleRequest request, CancellationToken cancellationToken)
        {
            // Simplified for brevity
            return await _context.People.ToListAsync();
        }
    }
```
I have hundreds of such Queries (and Commands) defined like the one above.  So my Razor Page action logic is generally very thin, such as...
```csharp
public async Task OnGet()
{
    People = await _mediator.ExecuteRequest(new GetPeopleRequest());
}
```

With the help of Simple Injector for my DI container, this approach has worked fantastically for a long while.  But now I'm starting to tinker around with Blazor Server and instantly hit some friction as far as how to handle service lifetimes, as my current implementation assumes there will be relatively short-lived page request scopes; whereas a Blazor Server app will maintain services for the duration of the SignalR connection.  This is most immediately an issue with EntityFrameworkCore's DbContext, where the same instance is being used for any command or query request via my mediator, but perhaps there could be a problem with other services.

My solution, and where I am running into trouble, was to add a new `ExecuteRequestInNewScope(...)` method to my `IMyMediator` interface which executes the request in a new scope, which I'd use from Blazor components.  However, I'm still getting the same DbContext instance.  This results in an error from EF Core about starting a second operation before the first one completed in certain scenarios (such as repeatedly and quickly pressing a button that executes a longer-running query).

The below code shows this:
```csharp
public interface IMyMediator
{
    Task<TResponse> ExecuteRequest<TResponse>(IRequest<TResponse> request);
    Task<TResponse> ExecuteRequestNewScope<TResponse>(IRequest<TResponse> request);
}
class MyMediator : IMyMediator
{
    private readonly IMediator _mediator;
    private Container _container;
    public MyMediator(IMediator mediator, Container container)
    {
        _mediator = mediator;
        _container = container;
    }


    // Normal path for standard Razor Pages created by web requests.
    public Task<TResponse> ExecuteRequest<TResponse>(IRequest<TResponse> request)
    {
        return _mediator.Send(request);
    }


    // For Blazor, I cannot use the above method because it would use the same MyDbContext 
    // instance over the entire lifetime of the Blazor app / SignalR connection.  So let's add
    // an option to execute the request in a new scope...except there's a problem...
    public async Task<TResponse> ExecuteRequestInNewScope<TResponse>(IRequest<TResponse> request)
    {
        TResponse response = default;

        // I thought creating a new scope would work...
        using (var scope = AsyncScopedLifestyle.BeginScope(_container))
        {
            var mediator = _container.GetInstance<IMediator>();
            response = await mediator.Send(request);
            // ...however, the MyDbContext ultimately used by this request causes a
            // concurrency exception, indicating I'm still getting the same DbContext instance.
        }

        //// Taking my MediatR out of the way, the below shows the same context is being used 
        //// regardless of scope.
        //using (var scope1 = AsyncScopedLifestyle.BeginScope(_container))
        //{
        //    var context1 = scope1.GetInstance<MyDbContext>();
        //    using (var scope2 = AsyncScopedLifestyle.BeginScope(_container))
        //    {
        //        var context2 = scope2.GetInstance<MyDbContext>();

        //        //Debug.Assert(context1.ContextId != context2.ContextId);
        //    }
        //}

        return response;
    }
}
```

And the Razor Component:
```
  @inject IMyMediator Mediator

  @* Click this button repeatedly very quickly and you'll get an EF Core exception *@
  <label>Click Me Rapidly!</label>
  <button @onclick="GetPeople">Search</button>

  <ul>
    <li>@counter</li>
    @foreach (var person in people)
    {
      <li>@person.FirstName</li>
    }
  </ul>

  @code {
      private int counter = 0;
      private List<Person> people = new List<Person>();

      private async Task GetPeople()
      {
        counter++;
        people = await Mediator.ExecuteRequestInNewScope(new GetPeopleRequest());
      }
  }
```

Attached is a sample VS Solution that fully demonstrates this.  The Index page is just a traditional Razor Page which uses my normal non-Blazor Server approach.  If you click on the "Blazor" link in the navbar, then click on the button rapidly enough, you'll see the error about concurrent use of DbContext.  In my actual use-case, I'm using an "auto-complete" editable select input, which provides possible matches as you type a name.  It's the relatively rapid checks to the DB which cause the concurrency issue.

Is it possible to introduce some sort of configuration option that would provide new nested scopes to allow this sort of scenario to work?  Or perhaps I am not going about this in the best way?  Hopefully whatever the solution is, it doesn't require major refactoring, since I have hundreds of commands/queries that could potentially be affected...

Any help or guidance anyone can provide is appreciated!

[SimpleInjectorTest.zip](https://github.com/simpleinjector/SimpleInjector/files/4927105/SimpleInjectorTest.zip)

**Comment by dotnetjunkie** [comment]
Let me start by admitting that I didn't read your post in its entirety, just scanned over it as it it's quite lengthy. So my apologies if I'm saying something that is completely off track. You are already applying CQRS-styled architecture using message handlers and this gives you the perfect interception point to apply scoping, i.e. apply scoping at the boundary of the message handler. You can do this using a decorator.

How such decorator exactly looks, depends on the shape of your message handler interface(s), but there is a [complete section in the documentation](https://simpleinjector.readthedocs.io/en/latest/aop.html#decorators-with-func-t-decoratee-factories) that describes how to do this.

I hope this helps.

**Comment by tim-626** [comment]
Hi Steven, thank you for the quick reply.  And if I may just briefly say, thank you not only for a great product but great support across many mediums (your site's doc, blog, StackOverflow, your book which I'm currently in the middle of, etc.).  It is clear that *educating* developers to write good code is just as important to you as developing and maintaining an excellent product like Simple Injector.  I'm certainly still in the learning phase, and probably always will be, so I appreciate the broad support base as I dig deeper into good DI and just general software architecture practices.

Sorry for the above lengthy message.  It's been a challenge to figure out the best way to distill our large project down to the most basic test-case but still provide (what I think might be) adequate context that is relevant.  FWIW, there is a minimally reproducible example attached to my original message that demo's this using the default Blazor Server VS Project.  I think that should make things more clear, but I'll summarize the above message with the following:

If I could boil my issue down as succinctly as possible I think there's 1) an important point as far as how Simple Injector handles cross-wired service lifetimes (our main blocker), and 2) potentially some relevant context as far as our app's architecture, which I hope doesn't need major rewriting :grimacing::

1. The DbContext service is cross-wired and so doesn't seem to play by the normal rules when creating nested scopes (i.e., https://github.com/simpleinjector/SimpleInjector/issues/796).  In the context of Blazor Server and a Razor Component, I can create a new scope for each command/query request (i.e., `AsyncScopedLifestyle.BeginScope(_container)`), but I still get the same DbContext instance across all requests.  Regardless of my use of a mediator or otherwise (such as an "isolated scope" decorator), this seems to be unavoidable, unless I'm still not fully understanding something.

2. For our app's design, practically the only thing injected into most Controllers, Razor Pages (and eventually Blazor Server Razor Components), etc., is our mediator service (`IMyMediator` in my code above), for which we use to execute `IRequest<>` objects.  The mediator is our *only* entry point for running any commands or queries, which keeps the web app code for such calls extremely clean and consistent.  Therefore it would seem that adding a new option to `IMyMediator` to execute `IRequest<>`s in a new scope (i.e., a new `ExecuteRequestInNewScope(request)` method as mentioned in my message above...or perhaps just adding a "useNewScope" bool parameter to the existing `ExecuteRequest(...)` method) to accommodate Blazor Server is the most straightforward solution.  I could then use the exact same `IRequest<>` for both Razor Pages and Blazor Server, with the only difference being the call to IMyMediator.

    I am looking into the possible use of an "isolated scope" decorator as described into the doc.  MediatR (which `IMyMediator` currently uses for its implementation has its own special "pipeline behavior" API, so I'll need to work out those details.  However, I think this approach might also require extending `IRequest<>` to something like `IScopedRequest<>`, as I need the option to execute any given command/query either the "normal" way (Razor Pages) or in an isolated scope (Blazor Server).

I hope all the above makes sense.  If there's a need to further clarify anything I'm happy to do so.  I am on "half days" as I'm on vacation currently, so my normal response time might be a bit slower than normal.

**Comment by dotnetjunkie** [comment]
Hi Tim,

Thank you for this detailed description and I'm sorry for not going through your detailed analysis directly. Fortunately, there is a quite easy (although a bit obscure) fix you can apply, which is the following:

``` c#
services.AddSimpleInjector(container, options =>
{
    IServiceProviderAccessor defaultAccessor = options.ServiceProviderAccessor;
    options.AddAspNetCore();

    // Restore the default ServiceProviderAccessor; this prevents the IServiceScope
    // from being reused within the same web request. Creating a new Simple Injector
    // Scope will ensure the creation of a new IServiceScope as well.
    options.ServiceProviderAccessor = defaultAccessor;   
});
```

This code might require some explaining. The Simple Injector .NET Core integration has the notion of an `IServiceProviderAccessor`. It:

> Allows access to the request's System.IServiceProvider instance. This interface is used by Simple Injector and allow it to resolve transient and scoped services from the framework's System.IServiceProvider through cross wiring.

When calling `.AddSimpleInjector()`, the `SimpleInjectorAddOptions.ServiceProviderAccessor` is configured with the internal `DefaultServiceProviderAccessor`. It resolves `IServiceScope` instances from Simple Injector, which is registered as `Scoped`. In other words, it has the behavior you need for Blazor.

When calling `.AddAspNetCore()`, however, the default accessor is overridden with the internal `AspNetCoreServiceProviderAccessor`. It depends on `IHttpContextAccessor` and always returns the `IServiceProvider` from the active HTTP request, and falls back to the default behavior when there is no HTTP request.

When working in ASP.NET Core applications you typically want this behavior... except perhaps when running in Blazor. The code sample replaces the ASP.NET Core accessor again with the default one that isn't aware of the existence of HTTP requests. Both accessors, however, are internal, which is why the code sample does this swapping.

I hope this helps.

**Comment by tim-626** [comment]
Great!  I just applied this to the test app and it appears to be working just as expected.  I still need to make this change into our main app and run our tests to make sure all works well.  I'll do so, likely early next week, and see how it goes and hopefully close this issue.

Thanks again for the prompt help on this, I greatly appreciate it!

**Comment by dotnetjunkie** [comment]
I released [SimpleInjector.Integration.AspNetCore v5.1](https://www.nuget.org/packages/SimpleInjector.Integration.AspNetCore/5.1.0) which now contains an `AddAspNetCore` overload that accepts an `ServiceScopeReuseBehavior` enum that allows you to override the behavior.

For instance:

``` c#
services.AddSimpleInjector(options =>
{
    options.AddAspNetCore(ServiceScopeReuseBehavior.OnePerNestedScope);
});
```

There are three options:

* `OnePerRequest`: This gets the same behavior as calling the parameterless `AddAspNetCore()` method.
* `OnePerNestedScope`: This reuses the the request's `IServiceScope` for Simple Injector's root (request) scope, but creates new (isolated) `IServiceScope` instances for any created nested scope. This means, for instance, that every nested scoped will get its own cross-wired `DbContext` instance.
* `Unchanged`: This uses the behavior you would get without calling `AddAspNetCore()`, which means that even the root (request) scope gets its own (new) `IServiceScope`. This means that Simple Injector-resolved services run in their own bubble, and get their own set of cross-wired scoped services.

**Comment by dotnetjunkie** [comment]
I updated [the documentation](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html#using-razor-pages) to reflect this new feature.

**Comment by dotnetjunkie** [comment]
More up-to-date integration examples for Blazor can be found [here](https://github.com/simpleinjector/SimpleInjector/issues/676#issuecomment-756940305).

**Comment by dotnetjunkie** [comment]
There is [Blazor Server App integration guide](https://simpleinjector.org/blazor) in the [Simple Injector documentation](https://simpleinjector.org/wiki).

**Comment by richardaubin** [comment]
> More up-to-date integration examples for Blazor can be found [here](simpleinjector/SimpleInjector.Integration.AspNetCore#28).

404 on link.

**Comment by dotnetjunkie** [comment]
The link should have pointed [here](https://github.com/simpleinjector/SimpleInjector.Integration.AspNetCore/issues/28). I removed my comment, because the [Blazor Server App integration guide](https://simpleinjector.org/blazor) in the [Simple Injector documentation](https://simpleinjector.org/wiki) contains the most up-to-date information.
