### ISSUE TITLE
Implement .NET Standard HealthChecks extension package

### ISSUE THREAD

**Issue by felixpp** [simpleinjector/SimpleInjector#832]
Hi guys!

I have implemented an HealthCheck extension package that allows a developer to add health checks to a .NET API. It is open source and available here : [https://github.com/felixpp/SimpleInjector.Extensions.HealthChecks](SimpleInject.Extensions.HealthChecks)

I wanted to push the nuget package on nuget.org, but it seems that the SimpleInjector.Extensions.* packages belong to this organization, which means I can't push it myself.

How can we proceed so that I can make this package available to the community?

Thanks!

**Comment by dotnetjunkie** [comment]
Hi @Felixpp,

Great to see you are building an extension package for Simple Injector. Me and the other Simple Injector contributors are chuffed to see that you are doing this. This can make Simple Injector even more awesome than we think it already is :-)

We are, however, very keen on keeping a very clear distinction between the packages that are officially supported by the Simple Injector Contributors, and all the other awesome packages built by Simple Injector users. This is why we, as organization, claimed the SimpleInjector.* package-id prefix from NuGet. This prevents anyone but us from uploading packages with that prefix. We think it prevents confusion from any of our users. The same holds for the logo. We like our logo to only be used by our official packages, to make the distinction clear between everything that is coming from us (and is supported by us) and other packages.

So to be clear, in no way we want to discourage you from writing the package or any other extension on top of Simple Injector. No! We love it, so please continue to do so. And we don't really care what ID you choose, and as long as you don't use our logo. You can pick any other package ID you like (as long as it doesn't have a claimed prefix). Here are some ideas:

* Felixpp.HealthChecks.SimpleInjector
* 4Each.SimpleInjector.HealthChecks
* PerreaultSoft.Extensions.SimpleInjectorHealthChecks

I hope this helps

**Comment by AdaskoTheBeAsT** [comment]
Hi, it would be good to have some aggregator (some page) of such 3rd party active extensions for simple injector :)

**Comment by dotnetjunkie** [comment]
There actually is [a page](https://simpleinjector.org/integration+other-technologies) for that. At the moment, however, it does not contain any links to third-party extensions. That's because we only want to add third-party tooling to the list that we (the Simple Injector contributors) were able to test and approve ourselves. Unfortunately our time is limited.

**Comment by AdaskoTheBeAsT** [comment]
I see - of course fully understood. Thanks for great lib.
