### ISSUE TITLE
How to achieve DI in Godot Engine

### ISSUE THREAD

**Issue by ksvslk** [simpleinjector/SimpleInjector#838]
I've now tried many DI packages for Godot Engine and failing to understand the reasons why they don't work.
Godot uses Mono - so that should be supported?

In the engine everything (almost) what you use in the game [is a Node](https://docs.godotengine.org/en/stable/getting_started/step_by_step/scenes_and_nodes.html).

I was able to register my interface -> class and use it right after it.

``` c#
var container = new Container();
container.Register<IAds, AndroidAds>();
container.Verify();
container.GetInstance<IAds>().CreateAndLoadBanner();
```

But running it later in the menu I did not get it to work. In Godot you cannot inject to constructor as you must have empty constructor for Nodes (`Control` is also a `Node`). So I did some workaround and created this wrapper just for testing:

``` C#
public class Test
{
    public IAds adsManager;
    public Test(IAds ads = null)
    {
        adsManager = ads;
    }
}
```

But it still did not work (at this point there could be other reasons for not working):

``` c#
public class MainMenu : Control
{
    public override void _Ready()
    {
        var test = new Test();
        test.adsManager.CreateAndLoadBanner();
    }
}
```

As you have read this far you know that I don't know much of what I'm writing about but maybe you do :)

**Comment by dotnetjunkie** [comment]
I have exactly got 0.0 experience with Godot, so I can't comment on that, but it seams that Godot is applying the Constraint Construction anti-pattern, which causes your trouble.

What you can try is moving all application logic out of your Controls and make them Humble Objects. Such Humble Object can then resolve an application component from the container or some other construct. Doing so might lead to the Service Locstor anti-pattern, but this probably unavoidable in your case. But in that case all application logic will be placed in code where you are allowed to use constructor injection, which allows that code to be tested more easily.

I hope this helps

**Comment by ksvslk** [comment]
Thanks for the explanation. Seems like it is not convenient at all in Godot :)

**Comment by dotnetjunkie** [comment]
> Godot uses Mono - so that should be supported?

Depending on which version of Simple Injector you use. In v5, Mono is supported through .NET Standard, while in older versions Mono was supported directly.

>  Test class is not Godot class - why is it not workin there?

In your example code, `Test` isn't resolved by Simple Injector. You are creating it manually. Could that be the problem?
