### ISSUE TITLE
Does using SimpleInjector in Azure functions using recommended approach prevent Singleton dependencies?

### ISSUE THREAD

**Issue by sonic1981** [simpleinjector/SimpleInjector#839]
I've just been reading this documentation issue ([Integrating Simple Injector in Azure Functions](https://github.com/simpleinjector/SimpleInjector/issues/536)).

It strikes me that there is a major drawback to this approach unless I'm missing something. Namely there is no way to register true singleton dependencies? If I'm reading this correctly it's saying essentially re-register all dependencies on startup, as the DI is just an object that's instanciated when the function is called. But If I do this I seem to miss out on being able to use true service lifetimes. I'm a big fan of SI and would usually prefer it to the MS implementation. The MS implementation in this instance seems to have a big  advantage though, namely:

> Singleton: The singleton service lifetime matches the host lifetime **and is reused across function executions** on that instance. Singleton lifetime services are recommended for connections and clients, for example DocumentClient or HttpClient instances.

My questions are:

1. Am I correct in saying that the above approach will re-register all dependencies on function run?
2. This then means there is no (true) singleton instance possible using SI in an Azure function when using this approach?
3. Is it possible to integrate SI into the Azure function registration as you do [for Asp.Net Core](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html), what is the recommended configuration for this?

It's worth nothing that given that startup times are critical to Azure function performance I'm thinking this could have a major impact in the functions speed.

**Comment by dotnetjunkie** [comment]
What part in the guidance causes to make you think that Singletons are not supported?

**Comment by sonic1981** [comment]
Ah hold on, I've just noticed that `DIConfig` is `static` and has a `static` property `public static readonly Container Container;`. right so the class isn't instanciated every time. :no_mouth:

**Comment by CasperWSchmidt** [comment]
I know I'm a little late to the party BUT. Azure functions are no longer required to be static and recently version 1.1.0 of Microsoft.Azure.Functions.Extensions came out with support for getting the context/configuration object from the IFunctionsHostBuilder. This means that you can leverage the MS dependency injection framework to inject an instance of Container into the function and then use it. Even when your configuration depends on IConfiguration (we have a lot of XXXSettings classes that are injected into handlers and services a like).

```
[assembly: FunctionsStartup(typeof(Startup))]
namespace YourFunction.DI
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var configuration = builder.GetContext().Configuration;

            builder.Services.AddSingleton(Setup(configuration));
        }

        public static Container Setup(IConfiguration configuration) // Could be non-static
        {
        //This is where the container is set up and verified
        }
    }
}
```
This will then be used in a function like this:
```
public class YourFunction
{
    private readonly Container container;
        
    public YourFunction(Container container)
    {
        this.container = container;
    }

    [FunctionName("YourFunctionName")]
    public async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "v1/yourFunctionName")]
        HttpRequest req)
    {
        var handler= container.GetInstance<ISomeHandler>();
        handler.Handle();
    }
}
```

**Comment by dotnetjunkie** [comment]
I created a new [Azure Functions Integration](https://simpleinjector.org/azurefunctions) page. This demonstrates how to integrate Simple Injector with  Azure Functions v3.

**Comment by sonic1981** [comment]
Awesome I might spend Monday stripping out the ms di 🤗
