### ISSUE TITLE
Error while resolving registered concrete types

### ISSUE THREAD

**Issue by pgshanker** [simpleinjector/SimpleInjector#842]
Unable to resolve types from (Simple Injector 5.0.3) container which have a base abstract class and are registered with the `ResolveUnregisteredConcreteTypes` flag set to `false`. Error message given below:

> No registration for type USA could be found. Make sure USA is registered, for instance by calling 'Container.Register<USA>();' during the registration phase.

sample code:

``` c#
public class USA : Country
{
    public int SenateMembers { get; set; }
    public USA() { }
}

public abstract class Country
{
    public string Name { get; set; }
    public Country() { }
}


Assembly assm = typeof(Country).Assembly;
var types = container.GetTypesToRegister<Country>(assm);
foreach (Type t in types)
{
    container.Register(t.BaseType, t);
}

container.Options.ResolveUnregisteredConcreteTypes = false;
container.Verify();


using (AsyncScopedLifestyle.BeginScope(container))
{
    dynamic v = container.GetInstance<USA>();
    v.SenateMembers = 100;
}
```

_this throws error_

**Comment by dotnetjunkie** [comment]
You are using Auto-Registration (a.k.a. Batch Registration) to register your `Country` types. You are, however, registering those countries by their *base type*. If you (for the sake of argument) would rewrite this Auto-Registration code to explicit registrations, you would end up with the following:

``` c#
RDXDIContainer.Register(typeof(Country), typeof(USA));
...
RDXDIContainer.Register(typeof(Country), typeof(China));
RDXDIContainer.Register(typeof(Country), typeof(Venesuela));
RDXDIContainer.Register(typeof(Country), typeof(Russia));
```

But since you are registering those components *by their base type*, you can only *resolve* them by their base type. That means that, with your sample code, you would have to call `container.GetInstance<Country>()` to get `USA`.

Problem, however, is that this won't work if have multiple `Country` sub types, which is what you typically want if you use Auto-Registration.

How to change the code to work, however, highly depends on what you need. Assuming you don't need collections of countries and only refer to specific collections (e.g. `USA`) directly, you can change your registration to the following:

``` c#
foreach (Type t in types)
{
    RDXDIContainer.Register(t, t);
}
```

**Comment by pgshanker** [comment]
Works !
Thank you

**Comment by pgshanker** [comment]
One more question, is this the right way to register a generic

```
public abstract class Employee
    {
        public string Name { get; set; }
        public Employee() { }
    }


public class Accountant : Employee
    {
        public bool CertifiedAccountant { get; set; }
        public Accountant() { }
    }

public class Accountant_DataSet : DataSet<Accountant> { }


public class Engineer : Employee
    {
        public string EngineeringBranch { get; set; }
        public Engineer () { }
    }

public class Engineer_DataSet : DataSet<Engineer> { }

      
public class DataSet<T> where T : Employee
    {
          public List<T> EmpDataSet;

          public DataSet(){}
    }



            Assembly assm = typeof(Accountant_DataSet).Assembly;
            RDXDIContainer.Register(typeof(DataSet<>), asm);
            RDXGlobal.RDXDIContainer.Options.ResolveUnregisteredConcreteTypes = false;
            RDXGlobal.RDXDIContainer.Verify();


Main Program
            using (AsyncScopedLifestyle.BeginScope(RDXGlobal.RDXDIContainer))
            {
                dynamic v =
                    RDXGlobal.RDXDIContainer.GetInstance<Accountant_DataSet>();

            }

```
This throws error:
Says no registration could not be found - as in my previous post

**Comment by dotnetjunkie** [comment]
The call to `Register(Type, Assembly)` registers all found implementations in the assembly by a closed version of the supplied type. In your case it means under the covers the following registration is made:

``` C#
container.Register<DataSet<Engineer>, Engineer_DataSet>();
```
So this case is similar to your previous problem. You are trying to resolve the concrete type `Engineer_DataSet` while it hasn't been registered directly. Instead, you should resolve `DtaSet<Engineer>` as that is the service that's being registered.

**Comment by pgshanker** [comment]
Could you tell me how to resolve this if the concrete type, that is  Engineer or Accountant is known only at run time? Thanks

**Comment by dotnetjunkie** [comment]
Can you elaborate? I don't understand your question. What does it mean for a concrete type to be only known at runtime?

**Comment by pgshanker** [comment]
I am passing the Type Engineer_DataSet as a variable into the framework for resolution. One way to handle is to have Switch/Case statements , check the name and call the hard coded resolver. Since there is huge number of such DataSets I wanted to know if there is a Resolve statement which will accept this Type variable as a parameter.

**Comment by dotnetjunkie** [comment]
I'm afraid I still don't undersrand what you are trying to accomplish. Xan you demonstrate your problem with some code examples?

**Comment by pgshanker** [comment]
I want to pass the Engineer_DataSet as a Type parameter to the function below

```
public void CreateDataSet(Type dset)
{
       dynamic rds = container.GetInstance(dsType);
}
```

**Comment by dotnetjunkie** [comment]
And calling `CreateDataSet(typeof(Engineer_DataSet))` won't work in your case? I think I need more information to be of any help to you.

**Comment by pgshanker** [comment]
Will check - Thanks for all that info. 
While Simple Injector is very good, the ResolveUnregisteredConcreteTypes = false setting with the associated registration documentation can be more elaborate. Thanks again

**Comment by dotnetjunkie** [comment]
> the ResolveUnregisteredConcreteTypes = false setting with the associated registration documentation can be more elaborate. Thanks again

This is a complaint we had before, and I agree with this complaint. This change was introduced in v5 and we still need to update the documentation to reflect these changes.
