### ISSUE TITLE
Injecting HttpClient or IHttpClientFactory in ASP.NET Framework (non Core)

### ISSUE THREAD

**Issue by ajbeaven** [simpleinjector/SimpleInjector#843]
Injecting `IHttpClientFactory` in a .NET Core project appears trivial, but I'm struggling to do the same in .NET Framework. Could you please provide some direction in how to achieve this?

Assume the standard setup as per [the docs](https://simpleinjector.readthedocs.io/en/latest/mvcintegration.html) where `MyService` takes an `IHttpClientFactory`. 

``` c#
using System.Web.Mvc;
using SimpleInjector;
using SimpleInjector.Integration.Web;
using SimpleInjector.Integration.Web.Mvc;
using Microsoft.Extensions.DependencyInjection;

protected void Application_Start(object sender, EventArgs e)
{
    // Create the container as usual.
    var container = new Container();
    container.Options.DefaultScopedLifestyle = new WebRequestLifestyle();

    // Register your types, for instance:
    container.Register<IMyService, MyService>(Lifestyle.Scoped);
    container.Register<IHttpClientFactory, DefaultHttpClientFactory>(); // fails as inaccessible

    // This is an extension method from the integration package.
    container.RegisterMvcControllers(Assembly.GetExecutingAssembly());

    container.Verify();

    DependencyResolver.SetResolver(new SimpleInjectorDependencyResolver(container));
}

public class MyService : IMyService
{
    public MyService(IHttpClientFactory clientFactory) { }
}
```

I've installed the `Microsoft.Extensions.DependencyInjection` package so have reference to `IHttpClientFactory`, however the concrete implementations that I could use to manually register in SimpleInjector appear to be inaccessible. There is also the `IServicesCollection.AddHttpClient` extension method, but this doesn't appear to be useable in a .NET Framework environment.

_________

So I was just about to submit this when I came across [this github issue](https://github.com/dotnet/extensions/issues/1345) which lead to something that appears to work:
``` c#
var serviceProvider = new ServiceCollection().AddHttpClient().BuildServiceProvider();
container.RegisterSingleton<IHttpClientFactory>(() => serviceProvider.GetService<IHttpClientFactory>());
```
I thought I'd submit this in any case and wondered if you could please just confirm whether this approach is acceptable? I figure it might benefit others stuck using .NET Framework.

**Comment by dotnetjunkie** [comment]
Yes, your proposed solution seems to be the only way to do it. The new HttpClientFactory model is tightly coupled to the use of the `ServiceCollection` and, as you already noticed, `DefaultHttpClientFactory` is internal. 

Instead of using `RegisterSingleton` to register the factory, I would suggest using `RegisterInstance`. This code is a bit simpler, and prevents the service provider from being referenced for the duration of the application. The effect will be the same though:

``` c#
var serviceProvider = new ServiceCollection().AddHttpClient().BuildServiceProvider();
container.RegisterInstance<IHttpClientFactory>(serviceProvider.GetService<IHttpClientFactory>());
```

**Comment by ajbeaven** [comment]
Thanks for the confirmation and recommendation. Just linking to #654 too as at least one other there appeared to have had the same questions that I did.

**Comment by dotnetjunkie** [comment]
@ajbeaven, I updated the code example to include registration of the IServiceProvider for disposal.

**Comment by ajbeaven** [comment]
Alas, `container.ContainerScope` does not appear to exist in SimpleInjector on .NET Framework. Is there an alternative way to easily dispose of this instance?

**Comment by dotnetjunkie** [comment]
This has nothing to do with .NET Core. You are likely running and old Simple Injector version (<v4.5). You should upgrade.
