### ISSUE TITLE
Batch-register concrete generic types

### ISSUE THREAD

**Issue by meinsiedler** [simpleinjector/SimpleInjector#845]
Hi,

we implemented a command-query-separation architecture using SimpleInjector which is very similar to the [solidservices reference architecture application](https://github.com/dotnetjunkie/solidservices).

We use `ICommand` and `IQuery<TResult>` interfaces as well as `ICommandHandler<TCommand>` and `IQueryHandler<TQuery, TResult>` interfaces to handle queries and commands.

We also implemented a permission check logic by placing `[Permission(...)]` attributes on our commands and queries. Then, we have an `PermissionAttributeChecker<TCommandOrQuery>` class, which checks if the `[Permission(...)]` attribute is applied to the command or query in the static constructor and throws an exception if the attribute is missing. With that approach, developers cannot forget to apply a `[Permission(...)]` attribute, because otherwise the application would throw that exception on startup. We extract IDs of permissions which are passed to the `[Permission(...)]` attribute and check these permission IDs at runtime when executing the command or query using a decorator.

Here is the implemenation of our `PermissionAttributeChecker<TCommandOrQuery>`:

```csharp
public class PermissionAttributeChecker<TCommandOrQuery>
{
  private static readonly Guid[] PermissionIds;
  private readonly IPermissionsService permissionsService;

  /// <summary>
  /// Since the check for the [PermissionAttribute] is done in the static constructor, the InvalidOperationException is thrown on startup of the application
  /// when the decorators are initialized by SimpleInjector. This means, that the applications fails immediatly on startup if a developer forgot to add
  /// the [PermissionAttribute] on a query or command.
  /// </summary>
  static PermissionAttributeChecker()
  {
    var tCommandOrQuery = typeof(TCommandOrQuery);

    var permissionAttribute = tCommandOrQuery
      .GetCustomAttributes(typeof(PermissionAttribute), inherit: false)
      .OfType<PermissionAttribute>()
      .SingleOrDefault();

    if (permissionAttribute == null)
    {
      throw new InvalidOperationException($"The type {typeof(TCommandOrQuery).FullName} is not marked with the [{typeof(PermissionAttribute).Name}]. " +
                        $"Please define the permission the user needs to execute this query.");
    }

    PermissionIds = permissionAttribute?.PermissionIds ?? new Guid[0];
  }

  public PermissionAttributeChecker(IPermissionsService permissionsService)
  {
    this.permissionsService = permissionsService;
  }

  public Task CheckPermissionForCurrentUser()
  {
    return this.permissionsService.CheckPermissionAsync(PermissionIds);
  }
}
```

Prior to SimpleInjector v5 we didn't have to register the `PermissionAttributeChecker<TCommandOrQuery>` but now, with the new default option for `ResolveUnregisteredConcreteTypes` this doesn't work any more.

Is there a way in SimpleInjector v5 to register the `PermissionAttributeChecker<TCommandOrQuery>` for all concrete types of queries and commands?

**Comment by meinsiedler** [comment]
Oh, that was an easy one. I didn't think about just registering the open generic type like this.

Thank you for the super fast response and for this great package in general.

**Comment by dotnetjunkie** [comment]
You're welcome.
