### ISSUE TITLE
Question: Without using the anti-pattern "Service Locator", how to create an instance of a class in a factory that resolves the class' dependencies?

### ISSUE THREAD

**Issue by canuszczyk** [simpleinjector/SimpleInjector#848]
I have a class called `Station`
This class' constructor has dependencies including a collection (not singleton lifestyles)

I have a factory class called `StationFactory` with a method called `Create` that returns an instance of the `Station` class.

Without injecting the container into the station factory and calling `Resolve<Station>()`, what is the best way to approach this?

**Comment by dotnetjunkie** [comment]
I've not got much time to answer, so I'll have to refer you to these articles:

* [Composition Root](https://freecontent.manning.com/dependency-injection-in-net-2nd-edition-understanding-the-composition-root/)
* [Service Locator](https://freecontent.manning.com/the-service-locator-anti-pattern/)

After you read them, you'll understand that a Service Locator does not exist within the Composition Root, which means that you should place the factory implementation *inside* the Composition Root, but define its abstraction *outside* the Composition Root.

I hope this helps

**Comment by canuszczyk** [comment]
Oh very cool.  I have done that in the past but it felt, I don't know,
dirty. lol.  Basically, the composite root becomes the factory
implementation.

Thanks for your time and help.  It is much appreciated!

Carl
