### ISSUE TITLE
Unable to use the InterceptorExtensions in .NET Core

### ISSUE THREAD

**Issue by sandipghosh** [simpleinjector/SimpleInjector#849]
Hello Team,

We are migrating from .Net 4.5 to .Net Core 2.2. During this migration process, our existing code base fails because of the "InterceptorExtensions" we have used for the dynamic proxy interception. "System.Runtime.Remoting.Messaging" and "System.Runtime.Remoting.Proxies" assemblies does not exists in .Net Core 2.2. If any workable version of 'InterceptorExtensions" available and ready to use for .Net Core 2.2, will be highly appriciated.

Thanks

**Comment by dotnetjunkie** [comment]
You can use Castle Dynamic Proxy ([Castle.Core](https://www.nuget.org/packages/Castle.Core/)) instead, as described [here](https://stackoverflow.com/questions/24513530/using-simple-injector-with-castle-proxy-interceptor).

**Comment by sandipghosh** [comment]
Thanks, man, great help.
