### ISSUE TITLE
Allow conditional registrations to be made even if AllowOverridingRegistrations is set to true

### ISSUE THREAD

**Issue by AroglDarthu** [simpleinjector/SimpleInjector#850]
This question is related to this [question](https://stackoverflow.com/questions/63886380/how-to-swap-dependencies-in-simple-injector-for-integration-testing-when-conditi) on stackoverflow.

Consider we have a fully functional, verified set of registrations that include conditionals. Obviously, there is no overlap between the conditional registrations because otherwise the container would have thrown an exception. It feels very odd that the container immediately throws an exception with these exact same registrations and the option `AllowOverridingRegistrations` set to `true` from the get-go. There is, of course, a very easy workaround for this scenario: set the option after making these registrations.

Now consider the exact same scenario as above. The option has been set at the end (so no exceptions) and we can start overriding some registrations for integration test purposes. All is well, except if you need an additional conditional registration.
1. Even if it is a totally different abstraction, the registration will fail;
2. Even if there have been no overrides yet, the registration will fail.

Would it be possible to allow making conditional registrations if the option `AllowOverridingRegistrations` is `true` under the following circumstances: **No actual overrides have been made yet**. That would at least overcome issue (2) above.

Would be awesome if issue (1) can be remedied as well.

**Comment by dotnetjunkie** [comment]
Good point. I marked this request as 'feature' and added it to the v5.1 milestone.

**Comment by dotnetjunkie** [comment]
This has just been fixed in [v5.0.4](https://github.com/simpleinjector/SimpleInjector/releases/tag/5.0.4).
