### ISSUE TITLE
Auto verification cannot be turned off

### ISSUE THREAD

**Issue by gitcob** [simpleinjector/SimpleInjector#854]
The `EnableAutoVerification` option does not seem to do anything.

Here is an xUnit test case:

```csharp
public class MyClass { }

[Fact]
public void ResolveBeforeVerifyFailsWhenAutoVerificationIsDisabled()
{
    using var container = new Container { Options = { EnableAutoVerification = false } };
    container.Register<MyClass>();

    Assert.Throws<ActivationException>(() => container.GetInstance<MyClass>());
}
```

Found in nuget version 5.0.3.

**Comment by dotnetjunkie** [comment]
That's correct. When set to `true` (the default) EnableAutoVerification will ensure verification on first resolve. When set to false (as your example) nothing happens.

**Comment by gitcob** [comment]
I see, then I misunderstood the v5 release notes. I thought setting it to false would trigger the old behavior - if I recall correctly, it used to throw an exception if you tried to resolve before verifying.
