### ISSUE TITLE
Prevent Microsoft.Bcl.AsyncInterfaces dependency

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#867]
#823 and #825 demonstrate that the new Microsoft.Bcl.AsyncInterfaces dependency that the Simple Injector core library uses is problematic.

Instead, Simple Injector should try to do duck typing so the dependency on this NuGet package can be removed.

**Comment by dotnetjunkie** [comment]
Unfortunately, the dependency with both Microsoft.Bcl.AsyncInterfaces (`IAsyncDisposable`), and its System.Threading.Tasks.Extensions dependency (`ValueTask`) are to strong. Removing them would inevitably lead to breaking changes:

* `Container` and `Scope` now implement `IAsyncDisposable` in .NET 4.6.1 and up, and .NET Standard 2.0 and up. Removing the dependency on Microsoft.Bcl.AsyncInterfaces will force the removal of `IAsyncDisposable` from `Container` and `Scope` for all Simple Injector target builds except .NET Standard 2.1. This is a breaking change for anyone using a target < .NET Standard 2.1 who depends on those types implementing `IAsyncDisposable` (e.g. when developers use `async using`).
* To prevent the binding redirect hell we're in, System.Threading.Tasks.Extensions must be removed as well, but this means that no `ValueTask` can be returned. Although C# uses duck typing when calling `async using`, this means that the `DisposeAsync` methods will get a different signature, which will make different target builds incompatible and might code to break -either at compile time or at runtime- when an application starts using a different target. Especially at runtime this would lead to JIT `MethodNotFound` exceptions.

These breaking changes are too big. This means we're stuck with this situation until we can remove all targets prior to .NET Standard 2.1, meaning removing the:

* .NET 4.5
* .NET 4.6.1
* .NET Standard 1.0
* .NET Standard 1.3
* .NET Standard 2.0

Although targets .NET 4.5, .NET Standard 1.0, and .NET Standard 1.3 do not depend on Microsoft.Bcl.AsyncInterfaces, removing .NET 4.6.1 or .NET Standard 2.0, can cause an application to fall back on .NET 4.5 or .NET Standard 1.3, which should be considered a breaking change, because it would cause the `DisposeAsync` method to disappear from the API (or change in signature).

**Comment by dotnetjunkie** [comment]
[feature-867](https://github.com/simpleinjector/SimpleInjector/tree/feature-867) branch created.

**Comment by dotnetjunkie** [comment]
Developers keep hitting this issue, and I even got smacked in the face by this myself quite recently, while trying for quite some time to get the binding redirects fixed, without success. The pain is so enormous that I think this warrens a this breaking change.

What will change:

* The `Microsoft.Bcl.AsyncInterfaces` dependency will be removed from the Simple Injector core library (which also impacts the ASP.NET Core integration packages).
* The .NET Standard 2.1 build of Simple Injector will behave as is, because it can still depend on `IAsyncDisposable`, except for the following:
  * The `Scope.RegisterForDisposal(IAsyncDisposable)` method is replaced with `Scope.RegisterForDisposal(object)`
* For the .NET Standard 2.0 build and .NET 4.6.1 build of Simple Injector, the following will change:
  * `Container` and `Scope` no longer implement `IAsyncDisposable` (making it impossible to use C# 7.3 `async using (...)` any longer)
  * `Container` and `Scope` no longer contain an `ValueTask DisposeAsync()` method
  * `Container` and `Scope` use duck typing to still allow asynchronous disposal (of course in a highly optimized fashion)
  * `Container` contains a new `Task DisposeContainerAsync()` method for asynchronous disposal
  * `Scope` contains a new `Task DisposeScopeAsync()` method for asynchronous disposal
  * A new `object[] Scope.GetAllDisposables()` method is added to allow retrieving both `IDisposable` and `IAsyncDisposable` instances.
  * For registering `IAsyncDisposable` components in the container, you can either take a dependency on `Microsoft.Bcl.AsyncInterfaces`, or define your own `System.IAsyncDisposable` interface that contains an `Task DisposeAsync()` method (but please do not mix these two approaches).
  * The `Scope.RegisterForDisposal(IAsyncDisposable)` method is replaced with `Scope.RegisterForDisposal(object)`

This means that developers:

* using .NET Core 3 and .NET 5 can still make use of `async using` while disposing `Scope` instances.
* using .NET Core 2 and .NET 4 can call `await Container.DisposeContainerAsync()` and `await Scope.DisposeScopeAsync()` to do asynchronous disposal, while either taking a dependency on `Microsoft.Bcl.AsyncInterfaces` or define their own `System.IAsyncDisposable` interface to make components async disposable.
* using .NET 4.5, .NET Standard 1.0, and .NET Standard 1.3 versions of Simple Injector are now able to use asynchronous disposal as well; they are required, however, to define their own `System.IAsyncDisposable` interface.

**Comment by dotnetjunkie** [comment]
[5.2.0-alpha1 version of core library](https://www.nuget.org/packages/SimpleInjector/5.2.0-alpha1) has been pushed to NuGet.

**Comment by Tornhoof** [comment]
The amount of work you put into getting this to work is staggering. I'm not affected by this, but may I suggest that you include a short example (maybe in this issue and Docs) how you think devs should define their own ``System.IAsyncDisposable`` interface.

**Comment by davidroth** [comment]
Nice work. I admire your commitment to support  `.NET Standard < 2.1`. This issue shows that cross-targeting to support legacy frameworks adds a lot of maintenance overhead 🙈

One additional story regarding the "IAsyncDisposable" issue:

We recently created a reusable class library targeting .net5, which only referenced "SimpleInjector.Integration.GenericHost" at the beginning.
So in the initial draft, we did not explicitly reference "SimpleInjector", because that gets resolved as a transitive nuget dependency via the GenericHost package.

Later on when compiling, the error from this issue popped up:

`The type 'IAsyncDisposable' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51`

Because of the way transitive resolving works, our project implicitly referenced SimpleInjector Version="**5.0.0**". (SimpleInjector.Integration.GenericHost references SimpleInjector **5.0.0**).

The "5.0.0" package of SimpleInjector does not multi-target ".net standard 2.1". It only multi-targets ".net standard 2.0".
Since "IAsyncDisposable" isnt a thing in ".net standard 2.0", the "Microsoft.Bcl.AsyncInterfaces" package was requested by the compiler because that got exposed via the ".net standard 2.0" targeted SimpleInjector.

SimpleInjector >= "5.0.1", does multi-target for ".net standard 2.1". So no more Microsoft.Bcl.AsyncInterfaces needed beceause IAsyncDisposable is a thing in ".net standard 2.1".

The fix was easy:
We explicitly added a reference to SimpleInjector "5.1.0" and the error was gone.

Therefore I'd suggest publishing new versions of the Integration packages as well because they can lead to this issue due to transient references. The updated integration packages should at least reference SI **5.0.1**, because thats the point where SI started targeting ".net standard 2.1".

**Comment by dotnetjunkie** [comment]
@davidroth,

> Therefore I'd suggest publishing new versions of the Integration packages as well because they can cause this error when "older" transient references are used.

We used to do this prior to v5, but decided to stop doing this in v5. As you noticed, however, this proves to be very problematic due to the way NuGet works. There is a [longstanding issue](https://github.com/NuGet/Home/issues/1192) with the NuGet team, that just won't get fixed by them, and the problem only got worse with recent Visual Studio NuGet plugins. This is why I actually decided to partly go back to old situation, as described [here](https://github.com/simpleinjector/SimpleInjector/issues/872).

What this means is that the ASP.NET Core integration packages are considered one and will always be updated together. They will still reference the lowest Simple Injector core library version possible. Since there is a problem in core library v5.0.0, however, those integration packages shouldn't reference that library, and should have been updated. With the introduction of v5.2 we will update all NuGet packages, so hopefully the problem goes away completely.

**Comment by davidroth** [comment]
Thanks for sharing the links!
Yes, the current situation regarding transient nuget dependencies is indeed suboptimal.
Anyway, thanks for updating the packages 👍

**Comment by dotnetjunkie** [comment]
The breaking change in the 5.2.0 alpha release broke (all) the ASP.NET Core integration packages; which is something I expected. For the last days, I've been working on an alpha release of those as well. Those are now pushed to NuGet.

To everybody reading this, please try them out and provide me with feedback below. Interesting things to test:

* Do you get any exceptions, or experience any problems after upgrading your application to these latest alpha releases?
* If you got any exceptions, was the exception message clear enough for you to fix the problem?
* If you have any `IAsyncDisposable` registrations (scoped and/or singleton), are those disposed of?
* Does your application shutdown gracefully? (tip: this [post](https://stackoverflow.com/a/43844804/) explains how to trigger a shutdown)

**Comment by dotnetjunkie** [comment]
Hi @davidroth and others,

Simple Injector v5.2 has been released today with fixes the binding redirect issues.

@Tornhoof, documentation can be found [here](https://simpleinjector.org/lifestyles+asynchronous-disposal).
