### ISSUE TITLE
StackOverflow when resolving types

### ISSUE THREAD

**Issue by Reonekot** [simpleinjector/SimpleInjector#87]
_A bit of background info_
We have been running SimpleInjector for 3-4 months now in a large'ish legacy codebase. Unfortunately we are now running into serious problems we can't figure out – it's probably a registration problem, circular dependency or similar, but I haven't managed to figure out why yet. Also we are seeing some weird inconsistent behavior of SimpleInjector. (While it apparently works with Ninject, which we are running on some of the projects in the solution.)

The solution base consist of a few different service/repository assemblies, with a mix of both C# and VB (we are migrating to C#, which DI is a great help in archiving) and we have interfaces declared in the base assembly which is implemented by other assemblies etc.

----

The problem is that we are refactoring quite a bit and now I'm stuck with fx. the following throwing StackOverflowException (without Verify() as that will ofc. fail also):
_container.GetInstance< X.Elements.Webshop.Acquaintance.IOrderService>()_

What is weird to me though, is that if I resolve a specific type before the above:
_container.GetInstance< X.Elements.Repository.IOrderRepository>()_
Then the first (IOrderService) resolve will work…

The overflow exception is located in the OrderRepository on CompiledQuery.Compile(), so for some reason it seems like the static class initialization must be failing somehow when calling the first resolve listed, but not when the second has been run before.

This is in a "small" test project only including the service assemblies and a test website I have made. In the real project it behaves a bit differently, and the StackOverflowException is normally at the GetInstance() call and not down in the layers. In the real project I currently can't resolve IOrderService at all, though I can resolve all it's dependencies manually through SimpleInjector and new it up manually.

This happens with both 2.8.3 and 3.0 beta-3.

Also, this is with .NET 4.6 and LegacyJIT. Same happens in 4.5.x. With the new JIT in 4.6 I have seen different error though with it throwing a "Common Language Runtime detected an invalid program" instead…

I can't attach the test project publicly here, but if any maintainers will have a look I can send it privately. (Should run without problems in VS2013 & 2015.)

I would greatly appreciate if anyone could help out with a clue as to what might be wrong.

**Comment by dotnetjunkie** [comment]
You can send send the test project to "steven at cuttingedge dot it". I will look at i5 a.s.a.p.

**Comment by Reonekot** [comment]
Steven has contacted me by email and looked into this. Generally "we are f***ed" and our dependency chains is simple insane (I knew that) and we are running into problems compiling the expression for an new'ing an object with 19000 instantiations.

Thank you again Steven for looking into this.

**Comment by dotnetjunkie** [comment]
This issue was resolved with issue #91 and rolled out with Simple Injector v3. Simple Injector 3 and up are able to construct object graphs of any size. Really big graphs might obviously cause performance problems due to their size, but it won't cause a stackoverflow exception.
