### ISSUE TITLE
Decorate through a shared interface?

### ISSUE THREAD

**Issue by Ergamon** [simpleinjector/SimpleInjector#887]
I am quite aware that the design is not the best, but sadly it is an old application and refactoring is not really possible due to thousands of classes designed in the following way :(

There is a base interface looking (simplified) like this:

``` c#
  public interface IProgramTask
  {
    void Execute();
  }
```
The original developers added an inheritance layer like this:

``` c#
  public abstract class ProgramTask : IProgramTask
  {
    public abstract void Execute();
  }
```
Now we have some program tasks:

``` c#
  public class ProgramTaskA : ProgramTask
  {
    public override void Execute()
    {
      Console.WriteLine("A");
    }
  }

  public class ProgramTaskB : ProgramTask
  {
    public override void Execute()
    {
      Console.WriteLine("B");
    }
  }
```
What I am trying is adding a decorator to some of these program tasks:

``` c#
  public sealed class ProgramTaskDecorator : IProgramTask
  {
    private readonly IProgramTask _decoratee;

    public ProgramTaskDecorator(IProgramTask decoratee)
    {
      _decoratee = decoratee;
    }

    void IProgramTask.Execute()
    {
      Console.WriteLine("Message by decorator");

      _decoratee.Execute();
    }
  }
```
But the following code does not compile:

``` c#
      var container = new Container();
      container.Register<ProgramTaskA>();
      container.Register<ProgramTaskB>();
      container.RegisterDecorator<ProgramTaskA, ProgramTaskDecorator>();

      var a = container.GetInstance<ProgramTaskA>();
      a.Execute();

      var b = container.GetInstance<ProgramTaskB>();
      b.Execute();
```

Simple Injector demands that the `ProgramTaskDecorator` should be castable to `ProgramTaskA`, which is not the case.

Sadly, as written, I cannot change the original architecture. Is there any other way to achieve what I want?

**Comment by dotnetjunkie** [comment]
> Simple Injector demands that the ProgramTaskDecorator should be castable to ProgramTaskA, which is not the case.

That is correct. For `ProgramTaskDecorator` to be used as decorator in Simple Injector, it requires the class to have a constructor argument of the _exact_ type as is given as service. In other words, when you are calling `RegisterDecorator<ProgramTaskA, ProgramTaskDecorator>()`, Simple Injector depends `ProgramTaskDecorator` to have a constructor argument of type `ProgramTaskA`.

What this means is that you can't apply decorators conditionally in this way. Simple Injector contains a [different method](https://simpleinjector.org/aop+applying-decorators-conditionally) for applying decorators conditionally. This is done using an overload of `RegisterDecorator` that accepts a predicate. For instance:

``` c#
container.RegisterDecorator<IProgramTask, ProgramTaskDecorator>(c =>
    c.ImplementationType == typeof(ProgramTaskA) ||
    c.ImplementationType == typeof(ProgramTaskB));
```

**Comment by Ergamon** [comment]
Probably too early for me today. I should have waited before posting.

My own demo code is showing the problem when I call container.GetInstance<ProgramTaskA>().

For SimpleInjector this is of course a call to retrieve a ProgramTaskA instance. Of course it cannot work without the decorator castable to ProgramTaskA.

Seems I have to do a lot of refactoring cause the old application is heavily using the ServiceLocator anti-pattern.

So in the end in the legacy code we have at some point:
Type type = Type.GetType(someValueFromDatabase);
IProgramTask programTask = ServiceLocator.Get(type);

Meanwhile I have progressed so far that I changed a lot of areas to not use the ServiceLocator and where this is not possible I basically made ServiceLocater.Get use SimpleInjector´s Container.GetInstance

So my hope was to already earn some fruits at this intermediate stage of refactoring, but the more I think about it, basically the best I can do at the moment to add some kind of behavior is to add interception cause all methods where defined virtual.

Believe it or not, but I think your posted code still helped me a lot.

I think the way to go from seeing this is not registering the program tasks like they are now, instead to register them as collection of IProgramTask.

In the next step I can then replace the the ServiceLocator with a call to a fitting factory like you describe in your documentation. Am I heading in the right direction?

Thx for your help

**Comment by dotnetjunkie** [comment]
> In the next step I can then replace the the Service Locator with a call to a fitting factory like you describe in your documentation. Am I heading in the right direction?

I wished I could comment on this, but this requires a much better understanding of your design and application.

**Comment by Ergamon** [comment]
Basically you helped me in the right direction.

The rest is really application specific and has to be solved by myself.
