### ISSUE TITLE
Getting the error "The configuration is invalid. Creating the instance for type ILoggerFactory failed" when trying to use Simple Injector in an Azure function, what am I missing?

### ISSUE THREAD

**Issue by sonic1981** [simpleinjector/SimpleInjector#895]
I have the following Startup class:

```c#
[assembly: FunctionsStartup(typeof(Snapshot.List.Startup))]
namespace Snapshot.List
{
    public class Startup : FunctionsStartup
    {
        public static Container Container = new SimpleInjector.Container();

        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddLogging();

            builder.Services.AddSimpleInjector(Container, options => {
                options.AddLogging();

            });

            builder.Services
                .BuildServiceProvider(validateScopes: true)
                .UseSimpleInjector(Container);

            Container.Register<...>();

            Container.Verify();
        }
   }
}
```

But this fails on the verify method with the error:

> The configuration is invalid. Creating the instance for type ILoggerFactory failed. The registered delegate for type ILoggerFactory threw an exception. Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IFileLoggingStatusManager' while attempting to activate 'Microsoft.Azure.WebJobs.Script.Diagnostics.HostFileLoggerProvider'.'

What am I missing?

**Comment by dotnetjunkie** [comment]
You are doing several things the do not work:

* Calling `Services.AddSimpleInjector` does *not* replace the built-in DI Container, which means that in the end the built-in (MS.DI) container is still used; not Simple Injector.
* By calling `BuildServiceProvider().UseSimpleInjector()` you are creating an MS.DI container to which you connect Simple Injector, but that DI Container is never used by the framework. The framework will build its own MS.DI version. This can cause all sorts of trouble.

Instead, try the approach outlined [here](https://github.com/simpleinjector/SimpleInjector/issues/536).

Now about your specific exception, you probably forget to call one of Azure's `AddXXX` extension methods. This is, however, something I cannot help you with.

**Comment by sonic1981** [comment]
But `builder.Services.AddLogging();` works if I use the built in container?

I'll try the other approach

**Comment by sonic1981** [comment]
I've seen that linked post before and tried that, I's not clear to me what `AzureLogger` is. It does not seem to exist in the Azure SDK (possibly removed)?

**Comment by dotnetjunkie** [comment]
>  It's not clear to me what AzureLogger is.

Me neither

Please also see #894. @CasperWSchmidt seems to have the exact same issues. You might want to join that thread; might speed things up.

**Comment by sonic1981** [comment]
Will do, that does look similar. Azure functions do seem to evolve hap haphazardly many of the original classes are deprecated.

**Comment by dotnetjunkie** [comment]
> Azure functions do seem to evolve hap haphazardly

Yes, it does. And DI seems to be a complete afterthought.

**Comment by dotnetjunkie** [comment]
I created a new [Azure Functions Integration](https://simpleinjector.org/azurefunctions) page. This demonstrates how to integrate Simple Injector with  Azure Functions v3.
