### ISSUE TITLE
Disposing singletons

### ISSUE THREAD

**Issue by MichaelLogutov** [simpleinjector/SimpleInjector#90]
I have an issue with EasyNetQ library - basically I need to have a singleton service registration but with IDisposable pattern. The problem is it seems there is no way dispose the Conainter and so all singleton objects. Am I missing something?

**Comment by dotnetjunkie** [comment]
What you are missing is issue #5. The issue is described that in v3 the `Container` will implement `IDisposable` and the issue's comments describe how to add this behavior to the `Container` in v2.
