### ISSUE TITLE
Are there any plans to support blazor webassembly?

### ISSUE THREAD

**Issue by blmlmx** [simpleinjector/SimpleInjector#900]
Hi there :)

Are there any plans to support blazor webassembly with Simple Injector?
I played around with the integration guide for blazor server apps and managed to get a [rudimentary webassembly project](https://github.com/blmlmx/BlazorWasmSimpleInjector.git) (more or less the default template project) running with Simple Injector...

**Comment by dotnetjunkie** [comment]
Nope. No plans. And TBH, I'm not sure whether this is technically possible as this would mean the Simple Injector would run in the (very limited) sandbox of the browser. It would likely mean a complete rewrite of Simple Injector with stripped functionality.

**Comment by blmlmx** [comment]
Oh sorry... And I thought I linked an already working code example...

**Comment by dotnetjunkie** [comment]
I've been looking through your example. Perhaps I'm misunderstanding how this works, but it seems like not much is running on the client. Can you confirm that Simple Injector is *actually* compiled to webasm and is running *in* the browser?

**Comment by blmlmx** [comment]
What do you mean with "Simple Injector is actually compiled to webassembly and is running in the browser"? Where else should it be running? 

I just tried to use simple injector inside the project you get when running `dotnet new blazorwasm`. This was pretty easy using your Integration guide for blazor server app integration. I then modified the weatherforecast page replacing direct use of HttpClient by IQueryHandler<T>. And just for fun built a dirty version of a console logging decorator (because this is for sure something the standard dotnet injection framework can't do). Then registered all this stuff in Simple Injector's container and startet the application without any problems.

Then i published this whole stuff to a nginx running inside a systemd-nspawn Arch Linux container on a rasparry pi with definitely no dotnet installed anywhere and gave it another try. Works well browsing with Android Tablet and Mobile as well as with Chromium and Opera on my Linux desktop. There could be problems browsing with Windows but as I dont have any OS of Microsoft I won't test this out. I can't promise you that every single detail of Simple Injector is working well inside Blazor Webassembly, but as I don't need all of this I realy don't care.

And to be honest I won't invest more time arguing whether this is working inside Webassmbly or not because for my purposes all works fine (with Simple Injector inside the browser).
