### ISSUE TITLE
Container.GetRegistration<T>() returns null after calling container.Register<T>();

### ISSUE THREAD

**Issue by henriblMSFT** [simpleinjector/SimpleInjector#909]
## Describe the bug
calling `container.GetRegistration<T>()` immediately after calling `container.Register<T>()` returns null even though the registration is present

## Expected behavior
`container.GetRegistration<T>()` should return an instance producer for the regisation.

An instance producer can be found using:
```csharp
container.GetCurrentRegistrations().First(r => r.ServiceType == typeof(T));
```

## Actual behavior
 `container.GetRegistration<T>()` returns null;

## To Reproduce
```csharp
public class TestService {}
public void CanGetRegistrationAfterRegister()
{
    var container = new Container();
    container.Register<TestService>();
    var registration = container.GetRegistration<TestService>(); // returns null
    registration.Should().NotBeNull();
}
```

## Additional context
SimpleInjector Version 5.3.0

**Comment by dotnetjunkie** [comment]
I'm unable to reproduce this issue. I added the following test to the Simple Injector test suite, but it succeeds:

``` c#
public class TestService { }

[TestMethod]
public void CanGetRegistrationAfterRegister()
{
    var container = new Container();
    container.Register<TestService>();
    var registration = container.GetRegistration<TestService>();
    Assert.IsNotNull(registration);
}
```

When I debug through it, I see that the `registration` variable gets assigned with a valid registration; it is not `null`.

If the test you posted really returns `null`, something very weird is going on what I don't fully understand.

**Comment by henriblMSFT** [comment]
In an attempt to simplify the problem I removed the issue. The problem occurs if you can GetRegistration<T>() before calling register. In that case the next call to GetRegistration<T>() is presumably cached and returns null:

```csharp
public class TestService { }

[TestMethod]
public void CanGetRegistrationAfterRegister()
{
    var container = new Container();
    container.GetRegistration<TestService>();
    container.Register<TestService>();

    var registration = container.GetRegistration<TestService>();
    Assert.IsNotNull(registration); // Fails
}
```

**Comment by dotnetjunkie** [comment]
> In that case the next call to `GetRegistration<T>()` is presumably cached and returns null:

Shit.... that's quite a bug. Thanksnfor taking the time to write the unit test. I will try to fix this incthe next patch release.

**Comment by dotnetjunkie** [comment]
[bug-909](https://github.com/simpleinjector/SimpleInjector/tree/bug-909) branch created.

**Comment by dotnetjunkie** [comment]
Here's another failing test. Same problem, but this one is even worse:

``` c#
[TestMethod]
public void GetService_WithGetRegistrationCalledBeforeRegistration_ReturnsThatService()
{
    // Arrange
    var container = new Container();

    container.GetRegistration<TestService>();
    container.Register<TestService>();

    // Act
    var service = ((IServiceProvider)provider).GetService(typeof(TestService));

    // Assert
    Assert.IsNotNull(service);
}
```

**Comment by henriblMSFT** [comment]
While our team doesn't use this settings what should be the behavior when the container is configured to automatically resolves unregistered concrete type?

Should GetRegistration<T>() dynamically create the registration or should it return null?

**Comment by dotnetjunkie** [comment]
> Should `GetRegistration<T>()` dynamically create the registration or should it return null?

When the container is set with `ResolveUnregisteredConcreteTypes` to `true`, a call to `GetRegistration` for an unregistered concrete type will return its `InstanceProducer`—but only when all its dependencies are registered.

Example:

``` c#
var container = new Container();
container.Options.ResolveUnregisteredConcreteTypes = true;
var registration = container.GetRegistration<TestService>();
Assert.IsNotNull(registration);
```

**Comment by dotnetjunkie** [comment]
Simple Injector v5.3.1 was pushed to NuGet. This patch release fixes this issue.
