### ISSUE TITLE
Big ass object graphs cause stackoverflow exception.

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector#91]
Due to a limitation in the CLR, the compilation of expression trees is limited to a certain amount of size. In case the `Expression` graph gets too big (over a few thousand nodes) a stackoverflow can occur during a call to `LambdaExpression.Compile` or `LambdaExpression.CompileToMethod`. 

The stackoverflow is really painful, because it leaves users in the dark about what is going on, and the stackoverflow might occur only in production (where memory is more rare than on a dev box), or the addition of a single extra registration might cause the stackoverflow.

We are talking about object graphs that are huge; typically even bigger than yo mama (so that's really big). You'll typically see this happening in object graphs that consist of mainly transient objects (since object graphs of transients are currently compiled down to one single big delegate). The case I've been debugging recently had an object graph that constructed around 19,000 new transient instances during that resolve. The expression tree consisted of almost 50,000 nodes.

Do note that the application's design is usually the source of these problems, because application's that are designed around the SOLID principles tend to have object graph that are consist of fewer services. SOLID object graphs tend to be deeper, because of the use of decorators, and the total number of components in the configuration is bigger, but still in total size of individual object graphs much smaller.

The use of singleton object graphs would also help, but the use of singleton object graphs is usually only feasible in cases where the application is already designed around the SOLID principles. Without SOLID, you'll find it really cumbersome to apply common patterns that make it possible to make the graph a singleton.

So the usual note about SOLID is in place, but still the occurrence of a stackoverflow exception is rather painful, because it leaves developers in the dark, perhaps even forced to move away from using Simple Injector, which again can cause all kinds of other troubles, such as performance problems (with those big object graphs) and the lack of the ability to diagnose the configuration, again causing bugs.

To fix this, Simple Injector should detect big object graphs just before compilation and break the object graph into multiple smaller delegates. Not only does this prevent stackoverflow exceptions, it also allows the application's memory footprint to be lowered, because such single gigantic object graph usually consists of lots of duplicated code. Although in theory the JIT should be able to optimize is, you will typically see that the JIT compiler stops optimizing after a method gets a certain size. So breaking up the object graph even makes sense in cases where the stackoverflow doesn't happen.

Detection of duplicate parts of the object graph is rather simple, because an InstanceProducer caches the generated `Expression` instance, causing that same reference reoccur repeatedly within the same tree. These duplicate expressions (especially `NewExpression`s) can be detected and replaced with a compiled version of the delegate.

The difficult parts of these are:
 - Making sure that the performance of a typical configuration doesn't suffer, especially during a call to `container.Verify()`.
 - Finding the sweet spot when to start breaking object graphs.
 - Scoped instances are resolved only once per call to a compiled delegate. Breaking a graph into multiple smaller delegates might therefore cause scoped instances to be requested much more frequently. This will cost performance as well. The balance between those needs to be found, and a smart heuristic perhaps needs to be created, that can calculate the best place to break a graph.

**Comment by qujck** [comment]
does the problem become another validation such as `AboveCapacityObjectGraphValidationError` and a new Container option `bool DivideObjectGraphIntoManageableChunks`?

**Comment by dotnetjunkie** [comment]
I rather not warn about this. Instead it should 'just work' and Simple Injector should fix this transparently for the user. Even though we could add an diagnostic warning, chances are around 99.9% that there already quite a lot SRP-violation warnings in the user's configuration.

Having an `ObjectGraphDepthLimit` wouldn't be useful, because in the case I've been debugging, the object graph wasn't that deep at all. It is the size of the expression tree that is causing trouble. Having some kind of `ObjectGraphSizeLimit` would be useful, but for now I rather make it internal. I'm not sure that users would ever need to tweak that.
