### ISSUE TITLE
Compile-time Container Creation

### ISSUE THREAD

**Issue by vvolkgang** [simpleinjector/SimpleInjector#914]
Anyone tried using [Source Generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) to create a compile time Container to optimize the runtime registration process?

**Comment by dotnetjunkie** [comment]
I believe there are several prototypes that try to implement a container-like system that generates the graphs at compile-time. Not sure sure they use Slurce Generators, but there are likely some experiments done with Source Generators.

But to be honest, to me these compile-time DI systems have no advantage over using Pure DI. Besides using Simple Injector in the systemsI help build, I tend to use Pure DI side Simple Injector in different projects of the same solution. I use a DI Container for bigger applications that benefit Auto-Registration and Convention over Configuration, while sticking with Pure DI for projects that are smaller have certain constraints that don't allow a DI Container.

**Comment by vvolkgang** [comment]
All the compile time alternative I've seen so far lack what easily achieved with SimpleInjector so I think I'm looking for the best of both worlds, Auto-Registration + Convention Over Configuration + No runtime registration.

**Comment by dotnetjunkie** [comment]
You could take a look at [DIVEX](https://divex.dev/). DIVEX is a fairly new tool that ships as a Visual Studio plugin. I'm not familiar with it, but from what I understand, it supports compile-time composition of object graphs by generating code at compile-time. My assumption is, however, that it _does not_ support Auto-Registration nor Convention over Configuration features.

**Comment by dotnetjunkie** [comment]
I'm closing this question because it's not related to Simple Injector.
