### ISSUE TITLE
Using ActionFilterAttribute with Simple injector

### ISSUE THREAD

**Issue by sarabu07** [simpleinjector/SimpleInjector#919]
We are using fluent validation library and use ActionFilterAttribute for custom handling the validation events.
Please see our code below. Let me know how to integrate Simple Injector with this example.

``` c#
public class ValidateModelAttribute : ActionFilterAttribute
{
    private readonly IValidatorFactory _factory; //Using FluentValidation
    private readonly ILogger _logger; // using Serilog
 
    public ValidateModelAttribute(IValidatorFactory factory, ILogger logger)
    {
        _factory = factory;
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    public override void OnActionExecuting(ActionExecutingContext context)
    {
        var result = new ValidationResult();

        if (!context.ActionArguments.Any() && !context.ModelState.IsValid)
        {
           
            var failures = new List<ValidationFailure>();

            foreach (var key in context.ModelState.Keys)
            {
                failures.Add(new ValidationFailure(key,
                    "can't process the input data. please validate your input"));
            }

            result = new ValidationResult(failures);
        }

        if (context.ActionArguments.Any())
        {
            foreach (var arg in context.ActionArguments)
            {
                //skip null values
                if (arg.Value == null)
                    continue;

                var validator = _factory.GetValidator(arg.Value.GetType());

                //skip objects with no validators
                if (validator == null)
                    continue;

                //validate
                result = validator.Validate(arg.Value);
            }
        }
    }
}
```

**Comment by dotnetjunkie** [comment]
Does [this](https://stackoverflow.com/questions/9984144/what-is-the-correct-way-to-register-fluentvalidation-with-simpleinjector) help? If not, please provide me with more information on what it is you are trying to achieve, what you tried, and what you're stuck with.

**Comment by sarabu07** [comment]
@dotnetjunkie We are using Asp.Net core and .Net core 3.1. The above example seems to be for .Net framework. Is it still valid for .Net core 3.1?

**Comment by dotnetjunkie** [comment]
> Is it still valid for .Net core 3.1?

Don't know. Did you check?

**Comment by sarabu07** [comment]
@dotnetjunkie I get 'FluentValidationModelValidatorProvider' is inaccessible due to its protection level error. Also, I get 'System.InvalidOperationException: Unable to resolve service for type 'Serilog.ILogger' while attempting to activate' and didn't get any error for IValidatorFactory interface. We use below code to use Fluent Validation. 

 _ = services.AddMvc(options =>
                  {
                      _ = options.Filters.Add(typeof(ValidateModelAttribute));
                      options.EnableEndpointRouting = false;

                  })
                 .SetCompatibilityVersion(CompatibilityVersion.Version_3_0)
                 .AddXmlSerializerFormatters()
                 .AddFluentValidation(options =>
                 {
                     options.RegisterValidatorsFromAssemblyContaining<Startup>();
                     options.RunDefaultMvcValidationAfterFluentValidationExecutes = false; // Avoid MVC modelstate validation
                 });

**Comment by dotnetjunkie** [comment]
> Unable to resolve service for type 'Serilog.ILogger' while attempting to activate'

How is that related to the integration Fluent Validation? Does Fluent Validation depend on and use Serilog? Or do you usr Serilog in your application?

**Comment by sarabu07** [comment]
@dotnetjunkie we use Serilog in our ValidateModelAttribute class to log the errors. Please refer to my first post for code.

```
public ValidateModelAttribute(IValidatorFactory factory, ILogger logger)
    {
        _factory = factory;
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }
```

**Comment by sarabu07** [comment]
@dotnetjunkie We are using global action filter with the name 'ValidateModelAttribute' and if i remove Ilogger from construction the code is working.

```
public ValidateModelAttribute(IValidatorFactory factory)
        {
            _factory = factory;
            //_logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
```

In simple injector we could not pass any additional parameter to global filter constructor ? or Im missing something

**Comment by sarabu07** [comment]
@dotnetjunkie Thanks, When i implemented in my code i get 'Argument 1: cannot convert from 'T.SimpleInjectiorAsyncActionFilterProxy<FTDR.API.Dispatches.CustomValidator>' to 'System.Type''

```
_ = services.AddMvc(mvc =>
                  {
                      _ = mvc.Filters.Add(new SimpleInjectiorAsyncActionFilterProxy<ValidateModelAttribute >(container);
                      mvc.EnableEndpointRouting = false;
                  })
                 .SetCompatibilityVersion(CompatibilityVersion.Version_3_0)
                 .AddFluentValidation(options =>
                 {
                     options.RegisterValidatorsFromAssemblyContaining<Startup>();
                     options.RunDefaultMvcValidationAfterFluentValidationExecutes = false; // Avoid MVC modelstate validation
                 });
```

**Comment by dotnetjunkie** [comment]
Try this:

``` C#
mvc.Filters.Add(typeof(SimpleInjectiorAsyncActionFilterProxy<ValidateModelAttribute>));
```

**Comment by sarabu07** [comment]
@dotnetjunkie Thanks. Now the DI is injecting for Logger but getting '"The type 'D.SimpleInjectiorAsyncActionFilterProxy`1[[D.CustomValidator, D, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' must derive from 'Microsoft.AspNetCore.Mvc.Filters.IFilterMetadata'. (Parameter 'filterType')"'

Please see below my proxy class.

```
public sealed class SimpleInjectiorAsyncActionFilterProxy<TAsyncActionFilter> where TAsyncActionFilter : ActionFilterAttribute, IFilterMetadata
    {
        private readonly Container container;
        public SimpleInjectiorAsyncActionFilterProxy(Container container)
        {
            this.container = container;
        }

        public void OnActionExecuting(ActionExecutingContext c)
        {
            container.GetInstance<TAsyncActionFilter>().OnActionExecuting(c);
        }
    }
```

**Comment by dotnetjunkie** [comment]
Change the definitioncof your proxy to:

``` c#
public sealed class SimpleInjectiorAsyncActionFilterProxy<TAsyncActionFilter
    : IFilterMetadata
    where TAsyncActionFilter : ActionFilterAttribute, IFilterMetadata
```

**Comment by sarabu07** [comment]
@dotnetjunkie Thanks now no errors, I see DI injected but OnActionExecuting is not getting fired

**Comment by sarabu07** [comment]
```
public sealed class SimpleInjectiorAsyncActionFilterProxy<TAsyncActionFilter> : IFilterMetadata where TAsyncActionFilter : ActionFilterAttribute, IFilterMetadata
    {
        private readonly Container container;
        public SimpleInjectiorAsyncActionFilterProxy(Container container)
        {
            this.container = container;
        }

        public void OnActionExecuting(ActionExecutingContext context)
        {
            container.GetInstance<TAsyncActionFilter>().OnActionExecuting(context);
        }
    }
```

**Comment by dotnetjunkie** [comment]
I'm sorry, but I'm on holiday roght now, so am unable to help you any further at the moment. Hopefully you'll be able to figure out how to get this working. Ley me know if you figured it out.

Cheers

**Comment by sarabu07** [comment]
@dotnetjunkie Sorry to bother in your vacation. Happy vacation!.

**Comment by sarabu07** [comment]
@dotnetjunkie The below code for simple injector action proxy worked. Thanks for your help.

```
public sealed class SimpleInjectiorAsyncActionFilterProxy<T> : IFilterFactory where T : ActionFilterAttribute, IFilterMetadata
    {
        private readonly Container container;
        public SimpleInjectiorAsyncActionFilterProxy(Container container)
        {
            this.container = container;
        }

        bool IFilterFactory.IsReusable { get; }

        public void OnActionExecuting(ActionExecutingContext context)
        {
            container.GetInstance<T>().OnActionExecuting(context);
        }

        IFilterMetadata IFilterFactory.CreateInstance(IServiceProvider serviceProvider)
        {
            return container.GetInstance<T>();
        }
    }
```
