### ISSUE TITLE
How to disable resolving of un-registered types in simpleInjector

### ISSUE THREAD

**Issue by muralipoola** [simpleinjector/SimpleInjector#92]
I am trying to use SimpleInjector as DI Container for NServiceBus. While trying to do so, i ran into a problem caused with resolving of un-registered types. I need to make sure that un-registered types are not resolved by SimpleInjector.

I did try below code, however it didn't do any good.

_context.ResolveUnregisteredType += _context_ResolveUnregisteredType;

 void _context_ResolveUnregisteredType(object sender,                                          UnregisteredTypeEventArgs e)
    {
       e.Register(()=> null);
    }
Any ideas/suggestions welcome.

**Comment by dotnetjunkie** [comment]
Please don't ask the same question in [two places](https://stackoverflow.com/questions/32038617/how-to-disable-resolving-of-un-registered-types-in-simpleinjector). That isn't going to help getting your question answered quicker.
