### ISSUE TITLE
NuGet - Slight tweak to Github link from SimpleInjector.Packaging

### ISSUE THREAD

**Issue by tiesont** [simpleinjector/SimpleInjector#923]
The package for SimpleInjector.Packaging (https://www.nuget.org/packages/SimpleInjector.Packaging/) has a slight typo in the reference URL included in the _Release Notes_ section.

This:

```
https://github.com/simpleinjector/SimpleInjector/releases/tag/5.0.0
```

should be

```
https://github.com/simpleinjector/SimpleInjector/releases/tag/v5.0.0
```

Just an FYI.

**Comment by dotnetjunkie** [comment]
Thank you for reporting this. I'll have a look to see if I can update that link without having to update a complete new version.

**Comment by dotnetjunkie** [comment]
Not only packaging has this problem, other SimpleInjector.* packages have the same error. Unfortunately, a package's release notes can't be changed after publication. I updated the template. This means that newly published packages will get a fixed release notes link.
