### ISSUE TITLE
Allow retrieve `items` dictionary from Scope lifestyle. 

### ISSUE THREAD

**Issue by gtteamamxx** [simpleinjector/SimpleInjector#924]
Currently `Scope` class allows only to use: `GetItem` and `SetItem` to store scope custom data.

I think there's missing `GetAllItems()` method which returns `IReadOnlyDictionary` of `items` dictionary.

https://github.com/simpleinjector/SimpleInjector/blob/8602b096618b9684714de03b1681a2c956ad41d4/src/SimpleInjector/Scope.cs#L62

Use case:
Inherit dictionary to nested scope

some pseudocode
```cpp
using ... new MySuperScope() // stores some dict with "User1" key
{
   ....
   using(new MySuperScope()) // should inherit "User1" key from root scope
   {
      var user = Lifestyle.Scoped(container).GetItem("User1");
   }
}

**Comment by dotnetjunkie** [comment]
You are correct, there's currently no support for retrieving the complete list of items from the Scope. Can you elaborate on your use case? Understanding your use case might allow me to come up with workarounds for your case, or perhaps even an alternative improvement of the `Scope` API.

**Comment by gtteamamxx** [comment]
Yep, look at this code.

For example, i have a process which takes long time on begining (we accept that) and this same process which takes less time during working.

1. See method: `ExecuteAtProcessStart()`, it creates a scope with db context and sets scope info to use
context with timeout constructor (see `ContainerRegistration()`
 
It fires `InvokeDbOperation()` which creates another scope. This scope should inherit all root scope items dictionary, because it
would allow to use db context with timeout constructor.

2. After some time this process should make this operation using default timeout (see: `ExecuteDuringProcess()`).
First we create a scope without updating `items` dictionary so method `InvokeDbOperation` will inject `DbContext` without `timeout` constructor.



```c#
public void ContainerRegistration()
{
    var container = new Container();

    container.Register(() =>
        Lifestyle.Scoped.GetCurrentScope(container)?.GetItem("Timeout") is TimeSpan timeout
            ? new DbContext(timeout)
            : new DbContext(),
        Lifestyle.Scoped
    );

    ContainerHolder.SetContainer(container);
}

public void ExecuteAtProcessStart()
{
    ScopedHelper.ActionInScoped(container =>
    {
        InvokeDbOperation();
    },
    new Dictionary<object, object>()
    {
        ["Timeout"] = TimeSpan.FromMinutes(60)
    }); // passing dict performs
        // dict.ForEach((key, value) => Lifestyle.Scoped.GetCurrentScope(ContainerHolder.Container).SetItem(key, value);
        // before scope creation
}

public void ExecuteDuringProcess()
{
    ScopedHelper.ActionInScoped(container =>
    {
        InvokeDbOperation();
    }); // no extra scope info, use default DB Context timeout
}

public void InvokeDbOperation()
{
    // Another scope
    ScopedHelper.ActionInScoped(container =>
    {
        // should be an instance with 60 minutes or default timeout

        // it would be possible when this scope would inherit items dictionary
        ContainerHolder.GetInstance<DbContext>().PerformSomeOperation(); 
    }); 
}
```

**Comment by dotnetjunkie** [comment]
Instead of using the Scope's dictionary to store items, you can also create your individual dictionary and store that in the Scope. In that case you can pass through what you want, without being limited by the ability of `Scope`. Example:

``` c#
void InitializeScope(Scope scope)
{
   scope.Items["AppSettings"] = new Dictionary<string, object>()
    {
        ["Timeout"] = TimeSpan.FromMinutes(60)
    });
}
```

**Comment by gtteamamxx** [comment]
Yeah, i thought about that before making an example, but i think it would be great feature so i created the one to show the idea of inheriting
