### ISSUE TITLE
.NET 6

### ISSUE THREAD

**Issue by vlapoec** [simpleinjector/SimpleInjector#930]
I am wondering what's the state of Simple Injector regarding .NET 6 integrations.
Is the last version of Simple Injector directly compatible with .NET 6 and ASP.NET Core under .NET 6?

Thanks

**Comment by dotnetjunkie** [comment]
Although I haven't tested this, I have no reason to believe that there are breaking changes in .NET 6 and ASP.NET Core that would prevent you from using Simple Injector.

If you find any anomalies, please let me know.

**Comment by dotnetjunkie** [comment]
Hi @vlapoec , there was a minor issue (see #933) that complicated integration with ASP.NET Core 6.  The documentation has been updated; integration with .NET 6 should work as expected.
