### ISSUE TITLE
How to inject Azure Functions MessageReceiver, Message?

### ISSUE THREAD

**Issue by commonquail** [simpleinjector/SimpleInjector#936]
An Azure `ServiceBusTrigger` function can request a `MessageReceiver` parameter named `messageReceiver` and a `Message` parameter by any name. With those instances, the function can manage message completion and AFAIK that is the only way to do so.

Following the Azure Functions integration example, I have access to a functional `ILogger` (I had to explicitly set the log level in `local.settings.json` but I don't know if that's a difference caused by the Simple Injector integration or another dependency difference between two applications I'm comparing). Unfortunately I cannot seem to access neither `MessageReceiver` nor `Message` (or `EventContext` but I can live without that).

I've tried variations of

```csharp
services.AddSimpleInjector(Container, opts =>
{
    opts.EnableHostedServiceResolution = false;
    opts.AutoCrossWireFrameworkComponents = true;
    opts.AddLogging();
                                                                         
    opts.CrossWire<IHttpContextAccessor>(); // Necessary despite automatic cross-wiring?!

    opts.CrossWire<MessageReceiver>();
    opts.CrossWire<Message>();

    opts.Container.RegisterSingleton(() =>
        opts.ApplicationServices.GetRequiredService<MessageReceiver>());
    opts.Container.RegisterSingleton(() =>
        opts.ApplicationServices.GetRequiredService<Message>());
});
```

* Explicitly enabling automatic cross-wiring changes nothing (as expected).
    *  For some reason automatic cross-wiring is situationally insufficient. If this is surprising and you have any suggestions for investigating local configuration errors I'm willing to experiment but ultimately I don't care about this discrepancy now.
* If I make no references to the desired types I get the usual "type not registered" error.
* With explicit cross-wiring I get e.g.

        System.InvalidOperationException: The configuration is invalid.\
        Creating the instance for type HoldingsCreatedHandler failed.\
        Failed to resolve Message.\
        Message is a cross-wired service,\
        meaning that Simple Injector forwarded the request the framework's IServiceProvider\
        in order to get an instance.\
        The used Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedServiceProvider,\
        however, failed with the following message:\
        "No service for type 'Microsoft.Azure.ServiceBus.Message' has been registered.".\
        This error might indicate a misconfiguration of services in the framework's IServiceCollection.
* With `GetRequiredService`, SI fails due to the framework resolving a null value.

In practice I _do_ have access to `Message` but only because I have a dedicated `HandleAsync(Message)` implementation I use in `ServiceBusTrigger` functions, which then request the `Message` from the framework. I can, of course, extend that to include `MessageReceiver`, and ultimately that's an acceptable compromise; unlike `ILogger`, `MessageReceiver` is not likely to be used throughout the call tree so the parameter won't propagate far.

Is there a way to get this working? Evidently whatever is set up for `ILogger` doesn't just magically extend itself to all the framework-provided dependencies

**Comment by dotnetjunkie** [comment]
> An Azure ServiceBusTrigger function can request an IMessageReceiver parameter named messageReceiever and a Message parameter by any name. With those instances, the function can manage message completion and AFAIK that is the only way to do so.

Unfortunately, I'm not that experienced with Azure Functions. Can you point me to some (Microsoft) documentation that shows these concepts with some code examples? This hopefully gives me a better grasp of what you are trying to accomplish and how this would be implemented in an Azure Function.

That said, resolving a `Message` from the container seems like an odd thing to do. Doesn't the `Message` contain the runtime data that's coming in through the request (or loaded from a queue). Please correct me if I'm not making any sense, but isn't `Message` just a container of runtime data instead of something that provides a service? That would explain why `Message` can't be resolved from the `IServiceProvider` and, therefore, not from Simple Injector. Why are you resolving this `Message` from the container and where do you need it? Isn't it supplied to the Azure Function?

**Comment by commonquail** [comment]
Sorry, it's the concrete [`MessageReceiver`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagereceiver?view=azure-dotnet), not the `IMessageReceiver` interface. The framework fails to resolve the latter.

> Can you point me to some (Microsoft) documentation that shows these concepts with some code examples?

There is very little.

* [The official Service Bus supported bindings example](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp#example) does not show the `MessageReceiver` but does name it as a supported binding for these purposes.
* [This ticket reply](https://github.com/Azure/azure-webjobs-sdk/issues/1986#issuecomment-433960534) demonstrates the functionality I need, although my method is not static (not necessary as of V3).
* [This appears to be the framework implementation](https://github.com/Azure/azure-functions-servicebus-extension/blob/bd33615fa784598aec0385a6592964f3a801b7c3/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Listeners/ServiceBusListener.cs). It looks like `MessageReceiver` comes from a `MessagingProvider` but that's just passing the bucket. However, it may explain that injecting `MessageReceiver` directly is at least impossible.

**Comment by Sondergaard** [comment]
Hi @commonquail 

To my knowledge you don't need the `MessageReceiver` to ack. the message. If your function does not throw any exception while processing the message, then it gets marked as received/completed. If an exception is raised, then depending on your configuration, it will have a retry and eventually be moved to `dead-letter-queue`.

In the [usage section](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp#usage) on the documentation it states that `MessageReceiver` is needed if you have set autoComplete to false.

As I read the documentation you can add an input of `BrokeredMessage` to access the actual service bus message, without the need for `MessageReceiver`.

**Comment by commonquail** [comment]
> To my knowledge you don't need the `MessageReceiver` to ack. the message.

The actual point is that autocomplete is limited so I _want_ to disable it and use manual settlement. That costs very little extra boilerplate and grants much greater flexibility.

> [...] `BrokeredMessage` [...]

In v1. In v2+ that's `Message`. Neither obviates the need for `MessageReceiever`.

In any case, I will close this issue because everything indicates it's not a SimpleInjector responsibility.
