### ISSUE TITLE
Contravariance for nested generic type parameters?

### ISSUE THREAD

**Issue by J-Hauser** [simpleinjector/SimpleInjector#939]
Hello.

Is it possible to introduce contravariance for nested generic type parameters? (see test below)
Some of my models derive from a common base-class. I can reuse the same validations with a base-validator because of the contravariance type parameter (provided by fluentvalidation).
As these models also have some common functionality which could be handled in a base-requesthandler i tried to introduce contravariance here also. But they are not resolved. 
I tried to debug but got lost somewhere in the InstanceProducer.
Current "workaround" is to have a dummy-requesthandler for each derived type for each scenario. Which is cumbersome and i tend to forget some of them sometimes.
I was also thinking about composition (having the common properties on a child-object), but this would also require to have some dummy-validator/-requesthandler, which i wanted to get rid of.
So the best bet seems to have contravariance here for ease-of-use.

Is this even possible? 

```c#
// Copyright (c) Simple Injector Contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for license information.

using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SimpleInjector.Tests.Unit
{
    [TestClass]
    public class OpenGenericTypeWithOpenGenericTypeParametersTest
    {
        public abstract class Base { }
        public class Derived : Base { }

        public interface IValidator<in T> { }
        public abstract class AbstractValidator<T> : IValidator<T> { public List<IValidator<T>> Dependencies { get; } }
        public class ValidatorForBase : AbstractValidator<Base> { } 
        public class ValidatorForDerived : AbstractValidator<Derived> { }

        public interface IRequestHandler<T> { List<IRequestHandler<T>> Dependencies { get; } }
        public interface IRequest<in T> { }
        public class Request<T> : IRequest<T> { }
        public abstract class RequestHandlerBase<T> : IRequestHandler<T> { public List<IRequestHandler<T>> Dependencies { get; }} 
        public class RequestHandlerForBase : RequestHandlerBase<Request<Base>> { } 
        public class RequestHandlerForDerived : RequestHandlerBase<Request<Derived>> { }

        public class ValidatorComposite<T> : IValidator<T>
        {
            public ValidatorComposite(List<IValidator<T>> dependencies)
            {
                this.Dependencies = dependencies;
            }

            public List<IValidator<T>> Dependencies { get; }
        }

        public class RequestHandlerComposite<T> : IRequestHandler<T>
        {
            public RequestHandlerComposite(List<IRequestHandler<T>> dependencies)
            {
                this.Dependencies = dependencies;
            }

            public List<IRequestHandler<T>> Dependencies { get; }
        }

        [TestMethod]
        public void Should_Find_Base_Handlers_Also()
        {
            var container = ContainerFactory.New();
            container.Collection.Register(typeof(IValidator<>), this.GetType().Assembly);
            container.Collection.Register(typeof(IRequestHandler<>), this.GetType().Assembly);
            
            container.Register(typeof(IValidator<>), typeof(ValidatorComposite<>));
            container.Register(typeof(IRequestHandler<>), typeof(RequestHandlerComposite<>));

            var flatType = container.GetInstance<IValidator<Derived>>();
            var nestedType = container.GetInstance<IRequestHandler<Request<Derived>>>();

            Assert.IsTrue(((ValidatorComposite<Derived>)flatType).Dependencies.Count() == 2);
            Assert.IsTrue(nestedType.Dependencies.Count() == 2); //Throws
        }
    }
}

```

**Comment by dotnetjunkie** [comment]
When it comes to handling variant registrations, there is little limitations in Simple Injector. The reason this doesn't work for you is because you haven't registered `IRequestHandler<T>` as contravariant, thus: `IRequestHandler<in T>`.

To demonstrate this, add the following code to your project:

``` c#
new RequestHandlerComposite<Request<Derived>>(new List<IRequestHandler<Request<Derived>>>
{
    new RequestHandlerForDerived(),
    new RequestHandlerForBase()
});
```

This code does not compile, and reports the following error on the line containing `new RequestHandlerForBase()`:

> CS1503 Argument 1: cannot convert from 'RequestHandlerForBase' to 'IRequestHandler<Request<Derived>>'

If you, however, change `IRequestHandler<T>` to `IRequestHandler<in T>`, you'll see that the code starts compiling and that Simple Injector would inject the `RequestHandlerForBase` into the `RequestHandlerComposite`.

This does require, however, to remove the `List<IValidator<T>> Dependencies` property from the interface, as it prevents `T` to be marked using the `in` keyword.
