### ISSUE TITLE
Alternative for AsyncScopedLifestyle that flows the same way but doesn't rely on AsyncLocal?

### ISSUE THREAD

**Issue by ScarletKuro** [simpleinjector/SimpleInjector#946]
In most scenarios, AsyncScopedLifestyle works great, but there are moments when ExecutionContext gets broken.
For example:
https://github.com/dotnet/runtime/issues/47802
https://github.com/reactiveui/ReactiveUI/issues/3258

As a result, sometimes I need to manually restore the ExecutionContext (or i get `x is registered using the 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope. Please see https://simpleinjector.org/scoped for more information about how apply lifestyles and manage scopes.` exception).

I haven't tested it with Microsoft DI yet, but after a brief look in the source code I didn't find usage of AsynLocal in their scope lifestyle.
How does their scoped lifestyle work then, and can we bring something like that to SimpleInjector?

I just have a TCP request that I want to be scoped, because I don't want to pollute my code and add this TCP request info across all my classes / methods.
When I receive the TCP request an UI will appear, the UI is using ReactiveUI (that gives headache with the ExecutionContext), user clicks a button (lets say "pay") and this is forwarded to MediatR which in the end forms the TCP reply to that request.

So I'm pretty much just wondering if there is something that can be done on SimpleInjector side to avoid this AsyncLocal problems.

**Comment by dotnetjunkie** [comment]
> I haven't tested it with Microsoft DI yet, but after a brief look in the source code I didn't find usage of AsynLocal in their scope lifestyle.

That's true. The scoping implementation of MS.DI is very different from that of Simple Injector. The model Simple Injector chooses by default is similar to the [Ambient Composition Model](https://blogs.cuttingedge.it/steven/p/acm/), while MS.DI favors the [Closure Composition Model](https://blogs.cuttingedge.it/steven/p/ccm/).

Simple Injector contains a scoping implementation that behaves similar to that of MS.DI, meaning: it doesn't depend on `AsyncLocal<T>`, which is the "flowing scoped lifestyle". It can be enabled as follows:

``` c#
var container = new Container();
container.Options.DefaultScopedLifestyle = ScopedLifestyle.Flowing;
```

For a more-detailed explanation about this, please see [Object Lifetime Management - Flowing Scoped](https://simpleinjector.org/lifestyles#flowing-scopes).

**Comment by dotnetjunkie** [comment]
Big warning: the current ASP.NET Core integration for Simple Injector is built around the concept of `AyncScopedLifestyle`. Quite a few changes likely need to be made to support or plugin the 'flowing scope' into your ASP.NET Core applications, especially when using MVC or other specific ASP.NET Core parts. Currently you will likely need to partly re-implement part of the integration.

**Comment by ScarletKuro** [comment]
Thanks for the valuable info! Closing.
