### ISSUE TITLE
SimpleInjector.Integration.Web startup failed when use Microsoft.Web.Infrastructure 2.0.0

### ISSUE THREAD

**Issue by regionbbs** [simpleinjector/SimpleInjector#952]
Hello,

I use Simple Injector with  ASP.NET MVC project, and it's upgraded Microsoft.Web.Infrastructure assembly version to 2.0.0
But SimpleInjector.Integration.Web can't use 2.0.0 and reports error "Could not load file or assembly 'Microsoft.Web.Infrastructure, 
Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of 
its dependencies. The system cannot find the file specified".

Can you help to upgrade reference version of Microsoft.Web.Infrastructure to 2.0.0?

Thank you.

**Comment by dotnetjunkie** [comment]
The error indicates your application's config file is missing the proper binding redirect. Adding this to your config file will fix the problem.

**Comment by regionbbs** [comment]
I will try another approach to handle this error.
Thank you.

**Comment by leonardolb** [comment]
Hi! Im using proper biding redirect but precompile view does not work.

**Comment by dotnetjunkie** [comment]
I can't reproduce this locally, @leonardolb. Please create a new issue and add the the necessary information so I can reproduce this issue.
