### ISSUE TITLE
Need help understanding how to inject, and then to do stuff.

### ISSUE THREAD

**Issue by SnapSkullYT** [simpleinjector/SimpleInjector#961]
I just need help understanding how to inject, and then I want it to detect when a Lua function is fired, so then my C# code will run. I'm just really stupid and don't know how to understand it.

I already have an program with a GUI and stuff, so can someone tell me how to put a button on my GUI and when clicked it shows all running applications, so select one to inject into to detect when a function is fired.

**Comment by dotnetjunkie** [comment]
You reached the Simple Injector hotline,

Here you can ask all your questions related to Simple Injector. Simple Injector is a DI Container for .NET developers. Questions related other technologies, such as Lua are not suited for this hotline and should be asked somewhere else.

**Comment by dotnetjunkie** [comment]
Thank you for your understanding.
