### ISSUE TITLE
d__15 MoveNext Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.

### ISSUE THREAD

**Issue by accairlines** [simpleinjector/SimpleInjector#979]
I am completely stuck with this issue for a week now. It works on my developer environment but not on the Windows Server 2019, a virtual machine from Azure. 

I am developing a Windows Service to access Azure Service Bus in an application that uses the Azure Service Bus for implementing a near real-time business logic and write and read asynchronously from the queues.

The machine has net3.5 and net4.7.2 and I have:
amqmdnetstd.dll
amqmxmsstd.dll
Autofac.dll
Azure.Core.Amqp.dll
Azure.Core.dll
Azure.Messaging.ServiceBus.dll
BouncyCastle.Crypto.dll
EntityFramework.dll
EntityFramework.SqlServer.dll
Google.Protobuf.dll
Google.Protobuf.pdb
HubTMCommon.dll
HubTMCommon.dll.config
HubTMCommon.pdb
HubTMDBLibrary.dll
HubTMDBLibrary.dll.config
HubTMDBLibrary.pdb
HubTMEngineProcessing.dll
HubTMEngineProcessing.pdb
HubTMQueueProcessing.dll
HubTMQueueProcessing.dll.config
HubTMQueueProcessing.pdb
HubTMQueueSynchronization.dll
HubTMQueueSynchronization.dll.config
HubTMQueueSynchronization.pdb
HubTMServiceMgmt.exe
HubTMServiceMgmt.exe.config
HubTMServiceMgmt.pdb
K4os.Compression.LZ4.dll
K4os.Compression.LZ4.Streams.dll
K4os.Hash.xxHash.dll
Microsoft.Azure.Amqp.dll
Microsoft.Bcl.AsyncInterfaces.dll
MySql.Data.dll
MySql.Data.EntityFramework.dll
Newtonsoft.Json.dll
NLog.dll
NRules.dll
NRules.Fluent.dll
NRules.Fluent.pdb
NRules.pdb
NRules.RuleModel.dll
NRules.RuleModel.pdb
ProjectInstaller.cs
ProjectInstaller.Designer.cs
ProjectInstaller.resx

Don't understand if I need to add something, install something or remove something. Can anyone help? 

I can do a Teams meeting

**Comment by dotnetjunkie** [comment]
This is the Simple Injector forum, but from the list of used assemblies, it seems you're not using Simple Injector. This means that this issue is not related to Simple Injector, in which case this is not the right place to add.
