### ISSUE TITLE
GetAllInstances without any registration being made for type being asked for returns an empty collection

### ISSUE THREAD

**Issue by qujck** [simpleinjector/SimpleInjector#98]
I was surprised to find the following test fails and the container will happily resolve an empty collection when there has been no registration made for the type being requested.

```csharp
[Fact]
public void GetAllInstances_WithoutAnyRegistration_Throws()
{
    var container = new Container();

    Assert.Throws<ActivationException>(() => container.GetAllInstances<IService>());
}

public interface IService { }
```

IMO this is a violation of the design principle [never fail silently](http://simpleinjector.readthedocs.org/en/latest/principles.html#never-fail-silently)

> We all hate the hunt for bugs in our code. It can be made even worse when we discover a library or framework we have chosen to use is **hiding these bugs by ignoring them and failing to report them** to us.

**Comment by dotnetjunkie** [comment]
Use `container.Options.ResolveUnregisteredCollections = true` to fallback to old v1/v2 behavior.

**Comment by niemyjski** [comment]
I have 
```csharp
container.RegisterSingleton<IQueueBehavior<WorkItemData>>(() => new MetricsQueueBehavior<WorkItemData>(metricsClient));
```
And when the following `GetAllInstances` is called, I get this exception as well:

```csharp
container.RegisterSingleton<IQueue<WorkItemData>>(() => new InMemoryQueue<WorkItemData>(behaviours: container.GetAllInstances<IQueueBehavior<WorkItemData>>(), workItemTimeout: TimeSpan.FromHours(1)));
```

**Comment by dotnetjunkie** [comment]
@niemyjski, Simple Injector [differentiates between registration of collections and one-to-one mappings](https://simpleinjector.readthedocs.org/en/latest/decisions.html#separate-collections). You should therefore make the following registration instead:

``` c#
container.RegisterCollection(typeof(IQueueBehavior<WorkItemData>), new[] {
    Lifestyle.Singleton.CreateRegistration(
        () => new MetricsQueueBehavior<WorkItemData>(metricsClient), container)
});
```

**Comment by niemyjski** [comment]
Thanks!
