### ISSUE TITLE
Single constructor requirement incompatible with ASP.NET Core

### ISSUE THREAD

**Issue by AntMaster7** [simpleinjector/SimpleInjector#981]
I replaced the entire default service provider in my ASP.NET Core application with SimpleInjector because I need the dependency on IServiceProvider to resolve to the SimpleInjector container. Unfortunately SImpleInjector requires implementation types to have only one constructor which is an issue. When SimpleInjector tries to resolve IHostLifetime, which is implemented by the internal ConsoleLifetime class from Microsoft, it fails because this implementation type has two constructors. In my opinion SimpleInjector should be able to handle this by selecting the constructor with the most satisfiable dependencies. Or is there a way for me to implement this behavior on top of SimpleInjector?

**Comment by AntMaster7** [comment]
I found an option to solve this issue with container.Options.ConstructorResolutionBehavior.

**Comment by dotnetjunkie** [comment]
Simple Injector does not follow the MS.DI Conforming Container contract and can't does not allow the built-in container to be replaced with Simple Injector. Integration with ASP.NET Core works differently with Simple Injector. Please follow the [official integration guide](https://docs.simpleinjector.org/en/latest/aspnetintegration.html). This documentation describes how to integrate Simple Injector with ASP.NET Core.
