### ISSUE TITLE
What would happen in case of duplicate registrations?

### ISSUE THREAD

**Issue by amguilmet** [simpleinjector/SimpleInjector#989]
In case of duplicate registrations like 

```
services.AddScoped<IDbContextFactory<MyContext>, DbContextFactory<MyContext>>();
services.AddTransient<IDbContextFactory<MyContext>, DbContextFactory<MyContext>>();
```

There doesn't seem to be any run-time errors with this code when I try it. But what is the expected behavior of this?

**Comment by dotnetjunkie** [comment]
I'm confused by your question. You are asking a question on the Simple Injector forum, while the syntax you show is of a different DI Container, namely MS.DI. You need to give more context to this question before I'm able to answer it.
